import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,objective} from './helpers.js';
import {normalizeTokens,addTokens,ZERO} from '../src/domain/usage/tokens.js';
import {estimate,priceFor,PRICING_VERSION,usd} from '../src/domain/usage/pricing.js';
import {eligibleSubscription,executionPolicy,ACTIVITY_MAX} from '../src/domain/usage/policy.js';
const token=(input=24500,cached:number|null=20000,output=3200)=>({inputTokens:input,cachedInputTokens:cached,cacheWriteInputTokens:0,outputTokens:output,reasoningOutputTokens:Math.min(output,1200),totalTokens:input+output});
const price=priceFor('gpt-5.3-codex','openai')!;
for(const [label,usage,want] of [
 ['uncached',token(1000000,0,0),'1.750000000000'],['cached',token(1000000,1000000,0),'0.175000000000'],['output',token(0,0,1000000),'14.000000000000'],['combined fixture',token(),'0.056175000000'],['sub-cent',token(1,0,0),'0.000001750000'],
] as const)test(`exact pricing: ${label}`,()=>assert.equal(estimate(usage,price,'standard',true).usd,want));
test('cache and reasoning subsets are never added twice',()=>{const t=normalizeTokens(token());assert.equal(t.totalTokens,27700);assert.equal(estimate(t,price,'standard',true).usd,'0.056175000000');});
for(const [label,invalid] of Object.entries({negative:{...token(),inputTokens:-1},overflow:{...token(),inputTokens:Number.MAX_SAFE_INTEGER+1},fractional:{...token(),outputTokens:1.5},cached:{...token(),cachedInputTokens:30000},reasoning:{...token(),reasoningOutputTokens:4000},contradictory:{...token(),totalTokens:1}}))test(`reject ${label} telemetry`,()=>assert.throws(()=>normalizeTokens(invalid)));
test('addition overflow rejects instead of rounding',()=>assert.throws(()=>addTokens(normalizeTokens({inputTokens:Number.MAX_SAFE_INTEGER,outputTokens:0,totalTokens:Number.MAX_SAFE_INTEGER}),token(1,0,0))));
test('unknown model, alias and provider do not inherit price',()=>{for(const [m,p] of [['gpt-5.3','openai'],['GPT-5.3-Codex','openai'],['gpt-5.3-codex','unknown']])assert.equal(priceFor(m!,p!),null);assert.equal(estimate(token(),null,'standard',true).usd,null);});
test('missing cached tokens has explicitly conservative estimate',()=>{const e=estimate(token(100, null,10),price,'standard',true);assert.equal(e.state,'partial');assert.match(e.reasons.join(),/conservative/);});
test('unsupported service/cache dimensions cannot be complete cost',()=>{assert.equal(estimate(token(),price,null,true).state,'unavailable');assert.equal(estimate({...token(),cacheWriteInputTokens:10},price,'standard',true).state,'unavailable');assert.equal(estimate(token(),priceFor('gpt-6-astra','openai'),'standard',true).state,'partial');});
test('exact decimal aggregation handles totals beyond safe number arithmetic',()=>assert.equal(usd(9007199254740993000000000000n),'9007199254740993.000000000000'));
const account={account:{type:'chatgpt',planType:'pro'},requiresOpenaiAuth:true};
const limits={ordinaryUsageAllowed:true,rateLimits:{planType:'pro',credits:{hasCredits:false,unlimited:false,balance:null},spendControlReached:false,rateLimitReachedType:null}};
test('verified personal included subscription is eligible',()=>assert.equal(eligibleSubscription(account,limits).paidCredits,false));
for(const mode of ['apiKey','amazonBedrock','unknown'])test(`deny authentication ${mode}`,()=>assert.throws(()=>eligibleSubscription({...account,account:{...account.account,type:mode}},limits)));
for(const plan of ['unknown','ent26','business','self_serve_business_usage_based','free'])test(`deny ambiguous/metered plan ${plan}`,()=>assert.throws(()=>eligibleSubscription({...account,account:{...account.account,planType:plan}},limits)));
for(const patch of [{ordinaryUsageAllowed:null},{ordinaryUsageAllowed:false},{rateLimits:{...limits.rateLimits,credits:null}},{rateLimits:{...limits.rateLimits,credits:{hasCredits:true,unlimited:false,balance:'10'}}},{rateLimits:{...limits.rateLimits,spendControlReached:true}}])test(`deny missing/paid/reached subscription evidence ${JSON.stringify(patch)}`,()=>assert.throws(()=>eligibleSubscription(account,{...limits,...patch})));
test('legacy policy stays strict; higher caps require reviewed policy change',()=>{assert.equal(executionPolicy(undefined).mode,'strict_provider_enforced');for(const patch of [{maxRolling24h:9},{maxRun:25},{maxDurationMs:900001},{maxConcurrent:2},{uncertainRetries:1}])assert.throws(()=>executionPolicy({...ACTIVITY_MAX,...patch}));assert.deepEqual(executionPolicy({...ACTIVITY_MAX,maxRolling24h:3}),{...ACTIVITY_MAX,maxRolling24h:3});});
function usageFixture(){const f=fixture();let now=Date.parse('2026-10-10T20:00:00Z');f.company.mandates.clock={now:()=>now};f.company.assignObjective(objective);const c=f.company.claimNext()!,id=c.execution.execution_id,u=f.company.aiUsage;u.observe(id,{kind:'start',identity:{threadId:id,model:price.model,provider:'openai',serviceTier:'standard',freshThread:true}});u.observe(id,{kind:'turn',threadId:id,turnId:'turn-'+id});const observe=(responseId:string,value:unknown=token())=>u.observe(id,{kind:'response',threadId:id,turnId:'turn-'+id,responseId,usage:value});return {...f,c,id,u,observe,tick:(ms:number)=>{now+=ms;}};}
test('complete fixture is attributed, timed and priced using original version',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('response-1');f.tick(252000);f.u.finish(f.id,'completed',true);const r=f.u.report({executionId:f.id});assert.equal(r.executions[0]!.worker_id,f.c.worker.worker_id);assert.equal(r.executions[0]!.durationMs,252000);assert.equal(r.summary.estimatedUsd,'0.056175000000');assert.equal(r.executions[0]!.pricing_version,PRICING_VERSION);assert.equal(r.executions[0]!.actualSubscriptionCharges,'unavailable');assert.equal(r.summary.incompleteExecutionIds.length,0);});
test('multiple exact responses deduplicate with immutable observations',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.observe('a');f.observe('b',token(100,0,10));f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.tokens!.totalTokens,27810);assert.equal(f.store.all('SELECT * FROM ai_usage_responses').length,2);assert.throws(()=>f.store.run("UPDATE ai_usage_responses SET payload='null'"));});
test('repeated cumulative and last snapshots are not summed',async t=>{const f=usageFixture();t.after(()=>f.close());for(let i=0;i<3;i++)f.u.observe(f.id,{kind:'snapshot',threadId:f.id,turnId:'turn-'+f.id,total:token(),last:token(100,0,10)});f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.tokens!.totalTokens,27700);assert.equal(f.store.all('SELECT * FROM ai_usage_observations').length,1);assert.equal(f.u.records()[0]!.completeness,'incomplete');});
test('snapshot after exact response cannot overwrite authoritative counts',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.u.observe(f.id,{kind:'snapshot',threadId:f.id,turnId:'turn-'+f.id,total:token(30000,0,20000),last:token()});assert.equal(f.u.records()[0]!.tokens!.totalTokens,27700);});
test('missing final telemetry remains null; interrupted partial tokens survive',async t=>{const f=usageFixture();t.after(()=>f.close());f.u.finish(f.id,'interrupted',false);assert.equal(f.u.records()[0]!.estimate!.usd,null);f.observe('late');assert.equal(f.u.records()[0]!.tokens!.totalTokens,27700);assert.equal(f.u.records()[0]!.completeness,'incomplete');assert.equal(f.u.records()[0]!.status,'interrupted');});
test('malformed response retained as incomplete and never zero',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('bad',{...token(),inputTokens:-1});f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.tokens,null);assert.equal(f.u.records()[0]!.estimate!.usd,null);assert.match(f.u.records()[0]!.reasons.join(),/Rejected/);});
test('response with omitted usage prevents complete reporting',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.observe('b',null);f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.completeness,'incomplete');assert.equal(f.u.records()[0]!.estimate!.state,'partial');});
test('pricing registry update cannot overwrite an execution price',async t=>{const f=usageFixture();t.after(()=>f.close());const original=f.store.get<{price:string}>('SELECT price FROM ai_usage WHERE usage_id=?',f.id)!.price;f.store.run("UPDATE ai_usage SET pricing_version='historic-version' WHERE usage_id=?",f.id);f.u.observe(f.id,{kind:'start',identity:{threadId:f.id,model:price.model,provider:'openai',serviceTier:'standard',freshThread:true}});assert.equal(f.u.records()[0]!.pricing_version,'historic-version');assert.equal(JSON.stringify(f.u.records()[0]!.price),original);});
test('model rerouting invalidates price rather than guessing aliases',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.u.observe(f.id,{kind:'model_changed',threadId:f.id,turnId:'turn-'+f.id});f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.estimate!.usd,null);});
test('partial aggregates disclose exact excluded execution identities',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.u.finish(f.id,'completed',true);f.u.ensure(f.id,'broker','research_broker');f.u.finish(f.id,'failed',false,'broker');const r=f.u.report({workerId:f.c.worker.worker_id});assert.equal(r.summary.invocations,2);assert.equal(r.summary.estimatedUsd,'0.056175000000');assert.deepEqual(r.summary.unpricedExecutionIds,['broker']);assert.equal(r.summary.totalTokens,null);assert.equal(r.byActivity.research_broker!.incompleteExecutionIds.length,1);assert.equal(r.byDay['2026-10-10']!.invocations,2);assert.equal(r.actualProQuotaConsumed,'unavailable');});
test('restart recovery preserves duplicate response identity and unknown status',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a');f.u.recover();f.observe('a');assert.equal(f.u.records()[0]!.tokens!.totalTokens,27700);assert.equal(f.u.records()[0]!.status,'unknown');assert.equal(f.u.records()[0]!.completeness,'incomplete');});
test('zero is recorded only with explicit complete zero-token telemetry',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('a',ZERO);f.u.finish(f.id,'completed',true);assert.equal(f.u.records()[0]!.estimate!.usd,'0.000000000000');});

test('old duplicate snapshots after newer observations are idempotent',async t=>{const f=usageFixture();t.after(()=>f.close());const snapshot=(value:unknown)=>f.u.observe(f.id,{kind:'snapshot',threadId:f.id,turnId:'turn-'+f.id,total:value,last:token(1,0,0)});snapshot(token());snapshot(token(30000,20000,4000));snapshot(token());assert.equal(f.u.records()[0]!.tokens!.totalTokens,34000);assert.deepEqual(f.u.records()[0]!.reasons,[]);});
test('resumed thread does not charge historical cumulative usage to its new turn',async t=>{const f=usageFixture();t.after(()=>f.close());f.observe('first');f.u.observe(f.id,{kind:'snapshot',threadId:f.id,turnId:'turn-'+f.id,total:token(),last:token()});f.u.finish(f.id,'completed',true);f.u.observe(f.id,{kind:'start',identity:{threadId:f.id,model:price.model,provider:'openai',serviceTier:'standard',freshThread:false}},'resume');f.u.observe(f.id,{kind:'turn',threadId:f.id,turnId:'resumed-turn'},'resume');f.u.observe(f.id,{kind:'snapshot',threadId:f.id,turnId:'resumed-turn',total:token(24600,20000,3210),last:token(100,0,10)},'resume');f.u.finish(f.id,'completed',true,'resume');const r=f.u.records().find(r=>r.usage_id==='resume')!;assert.equal(r.tokens!.totalTokens,110);assert.equal(r.completeness,'incomplete');});
import {teamFixture} from './fixtures/investment-team/support.js';
test('mixed workers/models retain exact decimal totals and disclose the unpriced invocation',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a,b]=f.pair(),u=f.company.aiUsage;
 for(const [c,model,tokens] of [[a,'gpt-5.3-codex',token()],[b,'gpt-6-luna',token(1000000,500000,200000)]] as const){const id=c.execution.execution_id;u.observe(id,{kind:'start',identity:{threadId:id,model,provider:'openai',serviceTier:'standard',freshThread:true}});u.observe(id,{kind:'turn',threadId:id,turnId:id});u.observe(id,{kind:'response',threadId:id,turnId:id,responseId:id,usage:tokens});f.contribute(c);f.finish(c);}
 u.ensure(a.execution.execution_id,'unpriced');u.finish(a.execution.execution_id,'failed',false,'unpriced');const r=u.report({runId:f.config.runId});assert.equal(r.summary.estimatedUsd,'0.211175000000');assert.equal(r.byWorker[a.worker.worker_id]!.estimatedUsd,'0.056175000000');assert.equal(r.byWorker[b.worker.worker_id]!.estimatedUsd,'0.155000000000');assert.equal(r.summary.estimateStatus,'partial');assert.deepEqual(r.summary.unpricedExecutionIds,['unpriced']);assert.equal(r.summary.totalTokens,null);
});
