import {test} from 'node:test';
import assert from 'node:assert/strict';
import {rmSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {fixture,objective,until} from './helpers.js';
import {ownerAttention,ATTENTION_LIMIT} from '../src/control/attention.js';
import {task,computer,mandate,group,device,infrastructure,publication,databaseImage} from './attention-helpers.js';
import {setup as business} from './business-helpers.js';
const setup=(t:any)=>{const f=fixture();t.after(async()=>{await f.close();rmSync(f.dir,{recursive:true,force:true});});return f;};
const items=(f:ReturnType<typeof fixture>,time?:string)=>ownerAttention(f.store,time).items;

test('clean company is verified zero and reads leave every table unchanged',t=>{const f=setup(t),before=databaseImage(f);assert.equal(items(f).length,0);assert.deepEqual(databaseImage(f),before);assert.equal(f.runtime.calls.length,0);});
for(const state of ['blocked','failed','awaiting_approval'])test(`ordinary ${state} Task has one inspection item and authoritative cancellation removes it`,t=>{const f=setup(t),a=task(f,state);assert.equal(items(f).length,1);assert.equal(items(f)[0]!.source_id,a.task_id);f.company.cancel(a.task_id);assert.equal(items(f).length,0);});
for(const state of ['queued','working','completed','cancelled'])test(`${state} Task is not attention`,t=>{const f=setup(t);task(f,state);assert.equal(items(f).length,0);});
test('waiting_children is automated waiting, not attention',t=>{const f=setup(t);task(f,'blocked','waiting_children');assert.equal(items(f).length,0);});
test('failed execution under recovered Task does not accumulate badges',t=>{const f=setup(t);const a=f.company.assignObjective(objective),r=f.company.claimNext()!;f.company.finish(r.execution.execution_id,{status:'failed',settled:true,error:'PRIVATE error'});assert.equal(items(f).length,1);f.company.retry(a.task_id,true);const retry=f.company.claimNext()!;f.company.finish(retry.execution.execution_id,{status:'completed',settled:true,summary:'Recovered'});assert.equal(items(f).length,0);assert.equal(f.store.all("SELECT * FROM executions WHERE status='failed'").length,1);});
test('child failure already handed back to completed parent is retained history',t=>{const f=setup(t),parent=task(f,'completed'),child=task(f,'failed');f.store.run('UPDATE tasks SET parent_task_id=? WHERE task_id=?',parent.task_id,child.task_id);assert.equal(items(f).length,0);});
test('pending infrastructure approval suppresses related Task and execution; denial retains only unresolved coordination',t=>{const f=setup(t),a=infrastructure(f);assert.deepEqual(items(f).map(i=>i.kind),['infrastructure_approval']);f.company.infrastructure.decide({approval_id:a.op.approval_id,operation_id:a.op.operation_id,decision:'deny'});assert.deepEqual(items(f).map(i=>i.kind),['infrastructure_task']);f.company.cancel(a.t.task_id);assert.equal(items(f).length,0);});
test('expired historical infrastructure Task counts only while its desired binding is unresolved',t=>{const f=setup(t),a=infrastructure(f);f.store.run("UPDATE approvals SET status='expired' WHERE approval_id=?",a.op.approval_id);f.store.run("UPDATE protected_operations SET status='expired' WHERE operation_id=?",a.op.operation_id);f.store.run("UPDATE tasks SET status='blocked' WHERE task_id=?",a.t.task_id);assert.deepEqual(items(f).map(i=>i.kind),['infrastructure_task']);f.store.run("INSERT INTO worker_os_identities(worker_id,backend,state) VALUES (?,'development','ready')",a.scout.worker_id);assert.equal(items(f).length,0);});
test('interrupted consumed host operation is one uncertainty, normal running operation is not attention',t=>{const f=setup(t),a=infrastructure(f);f.store.run("UPDATE approvals SET status='approved',decided_by='human',decided_at='2026-10-06T00:00:00Z' WHERE approval_id=?",a.op.approval_id);f.store.run("UPDATE approvals SET status='consumed',consumed_at='2026-10-06T00:00:01Z' WHERE approval_id=?",a.op.approval_id);f.store.run("UPDATE protected_operations SET status='running' WHERE operation_id=?",a.op.operation_id);assert.equal(items(f).length,0);f.store.run("UPDATE protected_operations SET error='Needs reconciliation' WHERE operation_id=?",a.op.operation_id);assert.deepEqual(items(f).map(i=>i.kind),['infrastructure_reconciliation']);});
test('pending project approval is one item; real denial removes it',t=>{const f=setup(t),p=publication(f);assert.deepEqual(items(f).map(i=>i.kind),['project_approval']);f.company.remote.decide(p.approval,{approved:false});assert.equal(items(f).length,0);});
test('expired approval filtering writes no expiry or audit rows',t=>{const f=setup(t);f.company.initializeNix();publication(f);const before=databaseImage(f);assert.equal(items(f,'2099-01-01T00:00:00.000Z').length,0);assert.deepEqual(databaseImage(f),before);});
test('Computer proposed policy is one approval and existing deny removes it',t=>{const f=setup(t),s=computer(f);assert.deepEqual(items(f).map(i=>i.kind),['computer_approval']);f.company.computers.authorize({session_id:s.session_id,policy_hash:s.policy_hash,decision:'deny'});assert.equal(items(f).length,0);});
test('Computer exact pending intent, unknown, and resolved states supersede generic Task',t=>{const f=setup(t),s=computer(f);f.company.computers.authorize({session_id:s.session_id,policy_hash:s.policy_hash,decision:'approve'});const r=f.company.claimNext()!;f.store.run("INSERT INTO computer_intents(intent_id,session_id,worker_id,task_id,execution_id,generation,policy_hash,request,request_hash,page_hash,state,created_at,expires_at) VALUES(?,?,?,?,?,0,?,'PRIVATE_BROWSER_BODY','hash','page','pending',?,?)",'intent_fixture',s.session_id,s.worker_id,s.task_id,r.execution.execution_id,s.policy_hash,s.created_at,new Date(Date.now()+60000).toISOString());f.store.run("UPDATE computer_sessions SET state='awaiting_approval',active_execution_id=NULL WHERE session_id=?",s.session_id);assert.deepEqual(items(f).map(i=>i.kind),['computer_approval']);f.store.run("UPDATE computer_intents SET state='approved'");assert.equal(items(f).length,0);f.store.run("UPDATE computer_intents SET state='unknown'");f.store.run("UPDATE computer_sessions SET state='interrupted',shutdown_confirmed=1 WHERE session_id=?",s.session_id);assert.deepEqual(items(f).map(i=>i.kind),['computer_unknown']);f.store.run("UPDATE computer_intents SET state='completed'");assert.equal(items(f).length,0);});
for(const state of ['completed','denied','interrupted','expired','failed'])test(`confirmed historical Computer ${state} is not attention`,t=>{const f=setup(t),s=computer(f);f.store.run('UPDATE computer_sessions SET state=? WHERE session_id=?',state,s.session_id);assert.equal(items(f).length,0);});
test('terminal unconfirmed browser cleanup is actionable',t=>{const f=setup(t),s=computer(f);f.store.run("UPDATE computer_sessions SET state='failed',shutdown_confirmed=0 WHERE session_id=?",s.session_id);assert.deepEqual(items(f).map(i=>i.kind),['computer_cleanup']);});
test('business approval deduplicates waiting cycle and real denial removes item',async t=>{const f=await business();t.after(async()=>{await f.close();rmSync(f.dir,{recursive:true,force:true});});const a=f.propose();f.wait(a);assert.deepEqual(items(f).map(i=>i.kind),['business_approval']);f.company.business.decide({action_id:a.action_id,intent_hash:a.intent_hash,decision:'denied'});assert.equal(items(f).length,0);});
test('business unknown survives revoke/stop; confirmed reconciliation removes it',async t=>{const f=await business();t.after(async()=>{await f.close();rmSync(f.dir,{recursive:true,force:true});});const a=f.propose();f.wait(a);f.approve(a);f.adapter.unknown=true;f.company.business.progress();await until(()=>f.company.business.action(a.action_id).status==='outcome_unknown');assert.deepEqual(items(f).map(i=>i.kind),['business_unknown']);f.company.business.control({action_id:null,grant_id:f.grant.grant_id,operation:'revoke'});f.company.mandates.control({mandate_id:f.m.mandate_id,action:'stop'});assert.deepEqual(items(f).map(i=>i.kind),['business_unknown']);await f.company.business.reconcile({action_id:a.action_id});assert.equal(items(f).length,0);assert.equal(f.adapter.puts,1);});
for(const state of ['blocked','paused','stopped','completed','archived'])test(`working group ${state} classification`,t=>{const f=setup(t),g=group(f);f.store.run('UPDATE working_groups SET state=? WHERE group_id=?',state,g.group_id);assert.equal(items(f).length,state==='blocked'?1:0);});
test('blocked current cycle is one item; stopped mandate and retained occurrence are history',t=>{const f=setup(t),m=mandate(f);f.company.mandates.control({mandate_id:m.mandate_id,action:'activate'});f.store.run("UPDATE operating_cycles SET state='blocked'");assert.deepEqual(items(f).map(i=>i.kind),['mandate_blocked']);f.company.mandates.control({mandate_id:m.mandate_id,action:'stop'});assert.equal(items(f).length,0);});
test('waiting backoff and healthy future review do not require babysitting',t=>{const f=setup(t),m=mandate(f);f.company.mandates.control({mandate_id:m.mandate_id,action:'activate'});f.store.run("UPDATE operating_cycles SET state='waiting',failures=1,retry_at=?",new Date(Date.now()+60000).toISOString());f.company.mandates.saveOwnerSchedule({mandate_id:m.mandate_id,schedule_id:null,purpose:'Future review',initiative_id:null,due_at:new Date(Date.now()+120000).toISOString(),recurrence_kind:'once',interval_seconds:null,local_time:null,occurrence_limit:1,end_at:new Date(Date.now()+3600000).toISOString()});assert.equal(items(f).length,0);});
test('only claimed unexpired device identity requires owner attention; denial resolves it',t=>{const f=setup(t),d=device(f);assert.deepEqual(items(f).map(i=>i.kind),['device_confirmation']);const before=databaseImage(f);assert.equal(items(f,'2099-01-01T00:00:00.000Z').length,0);assert.deepEqual(databaseImage(f),before);d.trust.decide({device_id:d.d.device_id,decision:'deny'});assert.equal(items(f).length,0);});
test('active then revoked device and unclaimed pairing do not count',t=>{const f=setup(t),d=device(f);d.trust.decide({device_id:d.d.device_id,decision:'confirm'});assert.equal(items(f).length,0);d.trust.revoke({device_id:d.d.device_id});d.trust.createPairing({capabilities:['state:read']});assert.equal(items(f).length,0);});
test('direct failed request stays an obligation after newer success; cancel or archive resolves ordinary attention',t=>{const f=setup(t),w=f.company.initializeCEO(),c=f.company.conversations.open({worker_id:w.worker_id,purpose:'PRIVATE_CONVERSATION_BODY'});const r=f.company.conversations.send({conversation_id:c.conversation_id,body:'Private',request_reply:true,receipt_key:randomUUID()}).request!;const run=f.company.claimWorkNext()!;f.company.finish(run.execution.execution_id,{status:'failed',settled:true,error:'PRIVATE'});assert.equal(items(f).length,1);f.company.conversations.send({conversation_id:c.conversation_id,body:'New question',request_reply:true,receipt_key:randomUUID()});const next=f.company.claimWorkNext()!;f.company.finish(next.execution.execution_id,{status:'completed',settled:true,summary:'Answer'});assert.equal(items(f).length,1);f.company.conversations.cancel(r.request_id);assert.equal(items(f).length,0);});
test('normal active model intent is not attention; retained fence survives cancelled Task',t=>{const f=setup(t),a=f.company.assignObjective(objective),r=f.company.claimNext()!;f.store.run('INSERT INTO execution_runtime_attempts VALUES(?,1)',r.execution.execution_id);assert.equal(items(f).length,0);f.company.finish(r.execution.execution_id,{status:'failed',error:'Unknown'});assert.deepEqual(items(f).map(i=>i.category),['uncertain']);f.company.cancel(a.task_id);assert.deepEqual(items(f).map(i=>i.source_type),['execution']);});
test('metadata is sanitized, deterministically ordered and response bounded without lying about total',t=>{const f=setup(t);for(let i=0;i<ATTENTION_LIMIT+2;i++)task(f,i%2?'failed':'blocked','SECRET /private/file');f.company.initializeNix();const first=ownerAttention(f.store),again=ownerAttention(f.store,first.as_of);assert.deepEqual(first,again);assert.equal(first.total,ATTENTION_LIMIT+3);assert.equal(first.items.length,ATTENTION_LIMIT);assert.equal(first.truncated,true);assert.equal(first.items[0]!.category,'approval');assert.equal(Object.values(first.counts).reduce((a,b)=>a+b,0),first.total);assert.doesNotMatch(JSON.stringify(first),/SECRET|private\/file|objective|parameter_hash|credentials|PRIVATE/);});

test('shared conversation session uncertainty points only to latest unknown turn after archive',t=>{
 const f=setup(t),w=f.company.initializeCEO(),c=f.company.conversations.open({worker_id:w.worker_id,purpose:'Session ownership'});let last;
 for(let i=0;i<3;i++){f.company.conversations.send({conversation_id:c.conversation_id,body:'Question',request_reply:true,receipt_key:randomUUID()});const r=f.company.claimWorkNext()!;assert.equal(r.origin,'conversation');if(!f.company.conversations.binding(r.context))f.company.conversations.prepareBinding(r.context,{worker_id:w.worker_id,runtime_type:'fake',runtime_reference:randomUUID(),workspace_path:w.workspace_path,created_at:new Date().toISOString()});f.company.conversations.activateBinding(r.context);f.company.conversations.context(r.context);f.company.conversations.event(r.context,'runtime_turn_starting',{context_chars:100});f.company.finish(r.execution.execution_id,i<2?{status:'completed',settled:true,summary:'Settled reply'}:{status:'failed',error:'Lost provider result'});last=r.execution.execution_id;}
 assert.equal(items(f).length,1);assert.equal(items(f)[0]!.detail_record_id,last);f.company.conversations.control(c.conversation_id,'archived');assert.equal(items(f).length,1);assert.equal(items(f)[0]!.source_id,last);
});
for(const state of ['requested','ready'])test(`expired unstarted Computer ${state} requires cancellation or inspection`,t=>{const f=setup(t),s=computer(f);if(state==='ready')f.company.computers.authorize({session_id:s.session_id,policy_hash:s.policy_hash,decision:'approve'});assert.deepEqual(items(f,'2099-01-01T00:00:00.000Z').map(i=>i.kind),['computer_authorization_expired']);});
test('blocked current occurrence without a cycle is actionable; cancellation removes it',t=>{
 const f=setup(t),m=mandate(f);let time=Date.now();f.company.mandates.clock={now:()=>time};f.store.run("UPDATE mandates SET status='active' WHERE mandate_id=?",m.mandate_id);
 const s=f.company.mandates.saveOwnerSchedule({mandate_id:m.mandate_id,schedule_id:null,purpose:'Current review',initiative_id:null,due_at:new Date(time+60000).toISOString(),recurrence_kind:'once',interval_seconds:null,local_time:null,occurrence_limit:1,end_at:new Date(time+3600000).toISOString()});f.store.run('UPDATE workers SET enabled=0 WHERE worker_id=?',m.coordinator_id);time+=60001;f.company.mandates.tick();assert.deepEqual(items(f).map(i=>i.kind),['review_blocked']);f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});assert.equal(items(f).length,0);
});

test('generalized queued integration waiting is ordinary automated work',async t=>{
 const {readyGeneric,reviewGeneric}=await import('./projects-helpers.js');const {call,done}=await import('./engineering-helpers.js');
 const f=setup(t),e=readyGeneric(f),review=reviewGeneric(f,e.reviewer,'approved'),c=f.company.claimNext()!;
 call(f,c,'integrate_repository',{repository_id:e.repo.repository_id,review_id:review.review_id});done(f,c);
 assert.equal(f.company.task(c.task.task_id).blocking_reason,'waiting_integration');assert.equal(f.company.engineering.repositories()[0]!.workflow_task_id,null);assert.equal(items(f).length,0);
});
for(const origin of ['direct','group','mandate'])test(`unknown research owns blocked ${origin} attention and survives workflow closure`,async t=>{
 const {ResearchFailure}=await import('../src/domain/research.js');const f=setup(t),w=f.company.initializeCEO();
 f.company.research.provider={name:'ambiguous-fixture',async search(_q,_s,h){h.prepared(randomUUID());h.invoking();throw new ResearchFailure('provider_unknown','Lost acknowledgement');}};
 const grant=f.company.research.grant({worker_id:w.worker_id,preset:'public_research',document_paths:[],expires_at:null,allow_discussions:true});let conversation,groupId,mandateId;
 if(origin==='direct'){const c=f.company.conversations.open({worker_id:w.worker_id,purpose:'Fixture research'});conversation=c.conversation_id;f.company.conversations.send({conversation_id:conversation,body:'Question',request_reply:true,receipt_key:randomUUID()});}
 else if(origin==='group'){const g=group(f);groupId=g.group_id;conversation=g.conversation_id;f.company.discussions.control({group_id:g.group_id,action:'start',receipt_key:randomUUID()});}
 else {const m=mandate(f);mandateId=m.mandate_id;f.company.mandates.control({mandate_id:m.mandate_id,action:'activate'});}
 const run=f.company.claimWorkNext()!;assert.equal(run.origin,'conversation');f.company.conversations.context(run.context);
 // Group/mandate fault fixtures record the same durable broker-unknown state;
 // the direct case exercises the actual trusted Research adapter callback path.
 if(origin==='direct')await f.company.research.callTool(run.context,'search','research_search',{query:'public docs'},new AbortController().signal);
 else f.store.run("INSERT INTO research_operations(operation_id,execution_id,worker_id,origin,scope_id,grant_id,policy_version,call_id,request_hash,tool,request,state,created_at,unresolved) VALUES(?,?,?,?,?,?,?,'fixture','hash','research_search','PRIVATE_QUERY','unknown',?,1)",'research_'+randomUUID(),run.execution.execution_id,w.worker_id,origin==='group'?'discussion':'mandate',groupId??mandateId!,grant.grant_id,'fixture',new Date().toISOString());
 f.company.finish(run.execution.execution_id,{status:'failed',settled:true,error:'Unknown research'});
 if(groupId)f.store.run("UPDATE working_groups SET state='blocked' WHERE group_id=?",groupId);
 if(mandateId)f.store.run("UPDATE operating_cycles SET state='blocked' WHERE mandate_id=?",mandateId);
 assert.deepEqual(items(f).map(i=>i.kind),['research_unknown']);
 if(origin==='direct')f.company.conversations.control(conversation!,'archived');else if(groupId)f.company.discussions.control({group_id:groupId,action:'stop',receipt_key:randomUUID()});else f.company.mandates.control({mandate_id:mandateId!,action:'stop'});
 assert.deepEqual(items(f).map(i=>i.kind),['research_unknown']);
});

for(const condition of ['deadline','current_cycle','withdrawal'])test(`business approval read excludes stale ${condition} without changing its source`,async t=>{
 const f=await business();t.after(async()=>{await f.close();rmSync(f.dir,{recursive:true,force:true});});const a=f.propose();f.wait(a);assert.equal(items(f).filter(i=>i.kind==='business_approval').length,1);
 if(condition==='deadline')f.store.run("UPDATE operating_cycles SET deadline='2000-01-01T00:00:00.000Z' WHERE cycle_id=?",a.cycle_id);
 if(condition==='current_cycle')f.store.run('UPDATE mandates SET current_cycle_id=NULL WHERE mandate_id=?',a.mandate_id);
 if(condition==='withdrawal'){f.advance(1000);f.company.mandates.withdrawObservation({observation_id:f.evidence.evidence_id});}
 const before=databaseImage(f);assert.equal(items(f).filter(i=>i.kind==='business_approval').length,0);assert.deepEqual(databaseImage(f),before);assert.equal(f.adapter.puts,0);
});
for(const uncertainty of ['provider','research'])test(`mandate coordinator ${uncertainty} uncertainty in its internal group is one problem before and after stop`,async t=>{
 const {hire}=await import('./helpers.js');const f=setup(t),w=f.company.initializeCEO();f.company.assignObjective(objective);const hireRun=f.company.claimNext()!;
 const scout=f.company.callTool(hireRun.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(hireRun.execution.execution_id,{status:'completed',settled:true,summary:'Fixture roster'});
 // Choose the coordinator turn explicitly; roster UUID ordering may enqueue the specialist first.
 f.store.run("UPDATE workers SET execution_priority='high' WHERE worker_id=?",w.worker_id);
 const m=mandate(f);f.company.mandates.control({mandate_id:m.mandate_id,action:'activate'});const review=f.company.claimWorkNext()!;assert.equal(review.origin,'conversation');f.company.conversations.context(review.context);
 const g=f.company.mandates.callTool(review.context,'group','convene_working_group',{topic:'Bounded fixture',desired_output:'Compare alternatives',constraints:'No effect',participant_ids:[w.worker_id,scout.worker_id],facilitator_id:w.worker_id,synthesizer_id:scout.worker_id,observation_ids:[],allow_research:false}) as {group_id:string};
 f.company.mandates.callTool(review.context,'wait','wait_for_internal_work',{summary:'Wait for group'});f.company.finish(review.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});f.company.mandates.progress();
 const run=f.company.claimWorkNext()!;assert.equal(run.worker.worker_id,w.worker_id);assert.equal(run.origin,'conversation');f.company.conversations.context(run.context);
 if(uncertainty==='provider')f.store.run('INSERT INTO execution_runtime_attempts VALUES(?,1)',run.execution.execution_id);
 else {const grant=f.company.research.grant({worker_id:w.worker_id,preset:'public_research',document_paths:[],expires_at:null,allow_discussions:true});f.store.run("INSERT INTO research_operations(operation_id,execution_id,worker_id,origin,scope_id,grant_id,policy_version,call_id,request_hash,tool,request,state,created_at,unresolved) VALUES(?,?,?,?,?,?,?,'fixture','hash','research_search','PRIVATE_QUERY','unknown',?,1)",'research_'+randomUUID(),run.execution.execution_id,w.worker_id,'conversation',f.company.discussions.group(g.group_id).conversation_id,grant.grant_id,'fixture',new Date().toISOString());}
 f.company.finish(run.execution.execution_id,{status:'failed',settled:uncertainty==='research',error:'Unknown fixture'});f.company.discussions.progress();f.company.mandates.progress();
 assert.equal(f.company.discussions.group(g.group_id).state,'blocked');assert.equal(f.store.get<{state:string}>('SELECT state FROM operating_cycles WHERE mandate_id=?',m.mandate_id)!.state,'blocked');assert.deepEqual(items(f).map(i=>i.kind),[uncertainty+'_unknown']);
 f.company.mandates.control({mandate_id:m.mandate_id,action:'stop'});assert.deepEqual(items(f).map(i=>i.kind),[uncertainty+'_unknown']);
});
