import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {fixture,objective,hire} from '../dist/test/helpers.js';
import {createHttpServer} from '../dist/src/http/server.js';

test('browser direct conversations preserve drafts by recipient, show passive/queued replies, safe text, controls and lineage',async t=>{
  const f=fixture();const task=f.company.assignObjective(objective);const setup=f.company.claimNext();
  const scout=f.company.callTool(setup.context,'hire','hire_worker',hire);
  f.company.finish(setup.execution.execution_id,{status:'completed',summary:'Trusted test roster setup.'});
  f.company.pause(true);f.dispatcher.start();
  const http=createHttpServer(f.company,f.dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));
  const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100}});
  t.after(async()=>{await context.close();await browser.close();await http.close();await f.close();});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${http.server.address().port}`);await page.getByText('Connected to headquarters',{exact:true}).waitFor();
  await page.locator(`[data-worker="${scout.worker_id}"]`).first().click();await page.getByRole('button',{name:'Open conversations',exact:true}).click();
  await page.locator('#new-conversation').click();await page.locator('#chat-body').waitFor();
  const first=f.company.conversations.list().items[0].conversation_id;
  await page.locator('#chat-body').fill('PRIVATE_DRAFT_A');await page.locator('#new-conversation').click();
  await page.waitForFunction(()=>document.querySelector('#chat-body')?.value==='');
  const second=f.company.conversations.list().items[0].conversation_id;assert.notEqual(first,second);
  await page.locator('#chat-body').fill('<img src=x onerror="window.sentinel=1"> Passive context only');await page.locator('#chat-passive').click();
  await page.getByText('<img src=x onerror="window.sentinel=1"> Passive context only',{exact:true}).waitFor();
  assert.equal(await page.locator('.message-body img').count(),0);assert.equal(await page.evaluate(()=>window.sentinel),undefined);
  assert.equal(f.runtime.calls.length,0);assert.equal(f.company.snapshot().tasks.length,1);
  await page.locator(`[data-conversation="${first}"]`).click();await page.waitForFunction(()=>document.querySelector('#chat-body')?.value==='PRIVATE_DRAFT_A');
  await page.locator(`[data-conversation="${second}"]`).click();await page.waitForFunction(()=>document.querySelector('#chat-body')?.value==='');
  await page.locator('#chat-body').fill('Explain a concurrency tradeoff.');await page.getByRole('button',{name:'Send & request reply',exact:true}).click();
  await page.locator('.conversation-request .status.queued').waitFor();assert.equal(f.runtime.calls.length,0);
  assert.match(await page.locator('#view').innerText(),/dispatch is paused/);
  await page.locator('#pause').click();await page.locator('.conversation-request .status.completed').waitFor();
  assert.equal(f.runtime.calls.length,1);assert.equal(f.company.snapshot().tasks[0].task_id,task.task_id);
  await page.getByRole('button',{name:'Replace Scout’s context',exact:true}).click();
  await page.locator('#chat-body').fill('Continue this discussion after context replacement.');await page.getByRole('button',{name:'Send & request reply',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.conversation-request .status.completed').length===2);
  assert.match(await page.locator('#view').innerText(),/generation 2/);
  await page.getByRole('button',{name:'Mute reply dispatch',exact:true}).click();await page.getByRole('button',{name:'Resume conversation',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Send & request reply',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Archive',exact:true}).click();await page.locator('#chat-body').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Resume conversation',exact:true}).click();await page.locator('#chat-body').waitFor();
  const dir=join(process.cwd(),'.validation','prompt07-browser');mkdirSync(dir,{recursive:true});await page.screenshot({path:join(dir,'conversation.png'),fullPage:true});
  assert.deepEqual(errors,[]);
});

test('delayed history page cannot be appended to another selected conversation',async t=>{
  const f=fixture();const atlas=f.company.initializeCEO();f.company.pause(true);
  const a=f.company.conversations.open({worker_id:atlas.worker_id,purpose:'History A'});
  const b=f.company.conversations.open({worker_id:atlas.worker_id,purpose:'History B'});
  for(let i=0;i<31;i++)f.company.conversations.send({conversation_id:a.conversation_id,body:`PRIVATE_HISTORY_A_${i}`,request_reply:false,receipt_key:`history-page-a-${String(i).padStart(4,'0')}`});
  f.company.conversations.send({conversation_id:b.conversation_id,body:'VISIBLE_HISTORY_B',request_reply:false,receipt_key:'history-page-b-0000'});
  const http=createHttpServer(f.company,f.dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));
  const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();
  t.after(async()=>{await browser.close();await http.close();await f.close();});
  await page.goto(`http://127.0.0.1:${http.server.address().port}`);await page.getByText('Connected to headquarters',{exact:true}).waitFor();
  await page.locator(`[data-worker="${atlas.worker_id}"]`).first().click();await page.getByRole('button',{name:'Open conversations',exact:true}).click();
  await page.locator(`[data-conversation="${a.conversation_id}"]`).click();await page.locator('#older-chat').waitFor();
  let release;let entered;const intercepted=new Promise(r=>entered=r);const gate=new Promise(r=>release=r);
  await page.route(`**/api/conversations/${a.conversation_id}?before=*`,async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});
  await page.locator('#older-chat').click();await intercepted;
  await page.locator(`[data-conversation="${b.conversation_id}"]`).click();await page.getByText('VISIBLE_HISTORY_B',{exact:true}).waitFor();
  const arrived=page.waitForResponse(r=>r.url().includes(`${a.conversation_id}?before=`));release();await arrived;
  await new Promise(r=>setTimeout(r,200));assert.equal(await page.locator('.message-body').filter({hasText:'PRIVATE_HISTORY_A_'}).count(),0);
  assert.equal(await page.locator('.message-body').filter({hasText:'VISIBLE_HISTORY_B'}).count(),1);
});
