import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixture,objective,hire} from './helpers.js';
import type {Worker} from '../src/domain/model.js';
import {ClientDTOs} from '../src/client/dto.js';
import type {WorkingGroup} from '../src/domain/discussions.js';

type F=ReturnType<typeof fixture>;
function roster(f:F){f.company.assignObjective(objective);const setup=f.company.claimNext()!;const scout=f.company.callTool(setup.context,'hire','hire_worker',hire) as Worker;f.company.finish(setup.execution.execution_id,{status:'completed',summary:'Trusted roster fixture'});return {atlas:setup.worker,scout};}
function create(f:F,workers:Worker[],atlas=false){return f.company.discussions.create({topic:'Compare onboarding alternatives',desired_output:'Evidence-backed recommendation with trade-offs',constraints:'Hypothetical, no implementation. Offline first, accessible, one engineer-week.',participant_ids:atlas?[]:workers.map(w=>w.worker_id),facilitator_id:workers[0]!.worker_id,synthesizer_id:workers[0]!.worker_id,organize_with_atlas:atlas,allow_incomplete:true,allow_research:true,receipt_key:randomUUID()});}
function control(f:F,g:WorkingGroup,action:string){return f.company.discussions.control({group_id:g.group_id,action,receipt_key:randomUUID()});}
function claim(f:F){const c=f.company.claimWorkNext();assert.ok(c&&c.origin==='conversation');f.company.conversations.prepareBinding(c.context,f.company.conversations.binding(c.context)??{worker_id:c.worker.worker_id,runtime_type:c.worker.runtime_type,workspace_path:c.worker.workspace_path,runtime_reference:randomUUID(),created_at:new Date().toISOString()});f.company.conversations.activateBinding(c.context);f.company.conversations.context(c.context);return c;}
function contribution(f:F,c:ReturnType<typeof claim>,body='An interactive local sample reduces privacy and setup friction.',refs:string[]=[]){return f.company.conversations.callTool(c.context,randomUUID(),'submit_contribution',{body,contribution_ids:refs,evidence_ids:[],questions:[],answers:[]}) as {message_id:string};}
function finish(f:F,c:ReturnType<typeof claim>){f.company.finish(c.execution.execution_id,{status:'completed',summary:'Contribution committed.'});}
function synthesis(f:F,c:ReturnType<typeof claim>,ref:string){return f.company.conversations.callTool(c.context,randomUUID(),'submit_synthesis',{recommendation:'Use a local interactive example',alternatives:'Guided setup imposes up-front work; contextual help is cheap but may miss first-use friction.',supporting_findings:'Supplied hypothetical constraints favor offline demonstration; no observed adoption data.',challenges_addressed:'Privacy concern answered by keeping all example data local.',dissent_and_risks:'Accessibility remains untested. User research is missing.',missing_evidence_and_confidence:'Provisional recommendation; no actual usability evidence.',next_actions_and_approvals:'Owner may separately authorize an internal evaluation; no implementation authority.',contribution_ids:[ref],evidence_ids:[]}) as {synthesis_id:string};}

test('group drafts/passive material never dispatch; direct routes cannot start group work',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);const tasks=f.company.snapshot().tasks.length;
  f.company.discussions.note({group_id:g.group_id,body:'Private owner constraint for this audience',kind:'constraint',receipt_key:randomUUID()});
  f.company.discussions.share({group_id:g.group_id,kind:'owner_material',title:'Brief',content:'Hypothetical fixture material',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:JSON.parse(g.eligible_workers),receipt_key:randomUUID()});
  assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.snapshot().tasks.length,tasks);assert.equal(f.company.conversations.list().items.length,0);
  assert.throws(()=>f.company.conversations.send({conversation_id:g.conversation_id,body:'Start',request_reply:true,receipt_key:randomUUID()}),/working-group/);
  assert.throws(()=>f.company.conversations.control(g.conversation_id,'active'),/working-group/);
  assert.throws(()=>f.company.conversations.inspect(g.conversation_id),/working-group/);
  control(f,g,'start');const c=claim(f);assert.equal(c.execution.task_id,null);assert.ok(f.company.conversations.tools(c.context).some(t=>t.name==='submit_contribution'));
  for(const name of ['assign_task','hire_worker','ask_peer','submit_reply','read_company_document'])assert.throws(()=>f.company.conversations.callTool(c.context,name,name,{}),/authority/);
});

test('causal group progression, immutable synthesis review/final, no Task until explicit assignment',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);const taskCount=f.company.snapshot().tasks.length;control(f,g,'start');
  const first=claim(f),second=claim(f);assert.equal(f.company.claimWorkNext(),undefined);const a=contribution(f,first);contribution(f,second);finish(f,first);finish(f,second);
  const facilitator=claim(f);assert.equal(f.company.discussions.turn(facilitator.request.request_id)!.kind,'facilitate');
  f.company.conversations.callTool(facilitator.context,'plan','facilitate_discussion',{body:'Clarify the accessibility cost before deciding.',action:'discuss',turns:[{worker_id:scout.worker_id,prompt:'Challenge the first proposal on accessibility and privacy. Respond to its concrete claim.',contribution_ids:[a.message_id],evidence_ids:[]}]});
  assert.equal(f.company.claimWorkNext(),undefined);finish(f,facilitator);const response=claim(f);contribution(f,response,'An offline sample is reasonable, but keyboard flow needs validation. Retain the choice conditionally.',[a.message_id]);finish(f,response);
  const decision=claim(f);f.company.conversations.callTool(decision.context,'plan','facilitate_discussion',{body:'The accessibility risk remains explicit; evidence supports a provisional recommendation.',action:'synthesize',turns:[]});finish(f,decision);
  const draft=claim(f);const saved=synthesis(f,draft,a.message_id);finish(f,draft);assert.equal(f.company.discussions.synthesis(saved.synthesis_id).state,'draft');
  const review=claim(f);contribution(f,review,'Preserve that no user research or accessibility testing has happened.',[a.message_id]);finish(f,review);
  const final=claim(f);const result=synthesis(f,final,a.message_id);finish(f,final);assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.group(g.group_id).state,'completed');assert.equal(f.company.snapshot().tasks.length,taskCount);
  assert.throws(()=>f.store.run("UPDATE group_syntheses SET content='changed'"),/immutable/);assert.equal(f.company.discussions.inspect(g.group_id).syntheses.length,2);
  f.company.discussions.note({group_id:g.group_id,body:'Late passive question',kind:'question',receipt_key:randomUUID()});assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.synthesis(result.synthesis_id).transcript_revision<f.company.discussions.group(g.group_id).revision,true);
  const preview=f.company.discussions.assignmentPreview(result.synthesis_id);const input={synthesis_id:result.synthesis_id,objective:preview.objective,acceptance_criteria:preview.acceptance_criteria,constraints:preview.constraints,receipt_key:randomUUID()};
  const task=f.company.discussions.submitAssignment(input);assert.equal(f.company.snapshot().tasks.length,taskCount+1);assert.equal(f.company.discussions.submitAssignment(input).task_id,task.task_id);assert.equal(task.requester,'human');assert.equal(task.assignee_worker_id,atlas.worker_id);
});

test('pause permits active commitment, stops future dispatch, stop never creates a synthesis',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const c=claim(f);control(f,g,'pause');contribution(f,c);finish(f,c);assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.group(g.group_id).state,'paused');control(f,g,'resume');const second=claim(f);control(f,g,'stop');assert.throws(()=>contribution(f,second),/held or stopped/);finish(f,second);assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.inspect(g.group_id).syntheses.length,0);});

test('Atlas organization is explicit, freezes selected eligible members after real turn settlement',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout],true);assert.equal(f.company.claimWorkNext(),undefined);control(f,g,'start');const c=claim(f);assert.equal(f.company.discussions.members(g).length,1);
  f.company.conversations.callTool(c.context,'organize','organize_discussion',{participant_ids:[atlas.worker_id,scout.worker_id],synthesizer_id:atlas.worker_id,body:'Use research and coordination perspectives; architecture specialist is missing.'});assert.equal(f.company.discussions.members(g).length,1);finish(f,c);f.company.discussions.progress();assert.equal(f.company.discussions.members(g).length,2);assert.equal(f.company.discussions.group(g.group_id).scope_version,2);assert.equal(f.company.snapshot().tasks.length,1);});

test('new discussion research mode requires explicit owner grant; shared source excludes private history and preserves checkpoints',async t=>{
  const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);
  const grant=f.company.research.grant({worker_id:atlas.worker_id,preset:'public_research',expires_at:null,document_paths:[]});control(f,g,'start');const pair=[claim(f),claim(f)];const a=pair.find(c=>c.worker.worker_id===atlas.worker_id)!,b=pair.find(c=>c.worker.worker_id===scout.worker_id)!;
  assert.throws(()=>f.company.research.authorize(a.context,'public_research'),/work mode/);assert.throws(()=>f.company.research.authorize(b.context,'public_research'),/No active/);
  f.company.research.revoke({grant_id:grant.grant_id});f.company.research.grant({worker_id:atlas.worker_id,preset:'public_research',expires_at:null,document_paths:[],allow_discussions:true});
  let query='';f.company.research.provider={name:'fixture',async search(q,_signal,hooks){query=q;hooks.invoking();hooks.settled();return {provider:'fixture',outcome:'succeeded',sources:[{url:'https://example.com/docs',title:'Public fixture',content:'An exact public source excerpt.',kind:'search_snippet',retrieved_at:'2026-10-01T00:00:00.000Z',published_at:null,observed_at:null,freshness:'unknown',omissions:'Synthetic fixture, not real acceptance'}]};}};
  const lookup=await f.company.research.callTool(a.context,'lookup','research_search',{query:'public onboarding pattern'},new AbortController().signal) as {sources:{source_id:string}[]};assert.equal(query,'public onboarding pattern');
  const owner=f.company.discussions.share({group_id:g.group_id,kind:'owner_material',title:'New constraint',content:'OWNER_NEW_EVIDENCE',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:JSON.parse(g.eligible_workers),receipt_key:randomUUID()});
  const shared=f.company.discussions.callTool(a.context,'share','share_public_evidence',{source_id:lookup.sources[0]!.source_id,excerpt:'An exact public source excerpt.'}) as {evidence_id:string};
  assert.equal(f.company.discussions.turn(a.request.request_id)!.seen_evidence_revision,0);
  assert.throws(()=>f.company.discussions.callTool(a.context,'cite-unseen','submit_contribution',{body:'Claim',contribution_ids:[],evidence_ids:[owner.evidence_id],questions:[],answers:[]}),/delivered shared packet/);
  f.company.discussions.callTool(b.context,'refresh','read_discussion',{});const record=f.company.discussions.callTool(b.context,'read','read_group_record',{record_id:shared.evidence_id,offset:0});assert.match(JSON.stringify(record),/exact public source/);assert.doesNotMatch(JSON.stringify(record),/public onboarding pattern|operation_id|grant_id/);
  assert.throws(()=>f.company.research.callTool(b.context,'ungranted','research_search',{query:'New lookup'},new AbortController().signal),/No active/);
  assert.throws(()=>f.company.discussions.callTool(b.context,'steal','share_public_evidence',{source_id:lookup.sources[0]!.source_id,excerpt:'An exact public source excerpt.'}),/authority/);
  assert.throws(()=>f.company.research.authorize(a.context,'company_knowledge'),/group|Group/);
});

test('explicit incomplete finalization keeps failed participant fence without blocking a safe synthesizer',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const pair=[claim(f),claim(f)];const a=pair.find(c=>c.worker.worker_id===atlas.worker_id)!,b=pair.find(c=>c.worker.worker_id===scout.worker_id)!;const first=contribution(f,a);finish(f,a);f.company.conversations.event(b.context,'runtime_turn_starting',{context_chars:100});f.company.finish(b.execution.execution_id,{status:'failed',error:'Genuinely ambiguous fixture invocation',settled:false});f.company.discussions.progress();assert.equal(f.company.discussions.group(g.group_id).state,'blocked');assert.equal(f.company.providerUnresolved(scout.worker_id),true);
  control(f,g,'finish');const final=claim(f);assert.equal(final.worker.worker_id,atlas.worker_id);const saved=synthesis(f,final,first.message_id);finish(f,final);assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.group(g.group_id).state,'completed');assert.equal(f.company.providerUnresolved(scout.worker_id),true);assert.match(f.company.discussions.synthesis(saved.synthesis_id).content,/failed_participation/);
});

test('progression batch rolls back entirely on busy queue capacity; safe resume retains original plan',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const a=claim(f),b=claim(f);const original=contribution(f,a);contribution(f,b);finish(f,a);finish(f,b);const facilitator=claim(f);
  f.company.discussions.callTool(facilitator.context,'plan','facilitate_discussion',{body:'Both participants should examine the material issue.',action:'discuss',turns:[atlas,scout].map(w=>({worker_id:w.worker_id,prompt:'Respond to this proposal with an explicit tradeoff.',contribution_ids:[original.message_id],evidence_ids:[]}))});
  const direct=f.company.conversations.open({worker_id:scout.worker_id,purpose:'Unrelated queued work'});const requests=[];for(let i=0;i<8;i++)requests.push(f.company.conversations.send({conversation_id:direct.conversation_id,body:'Another authorized reply',request_reply:true,receipt_key:randomUUID()}).request!);
  finish(f,facilitator);const before=f.company.discussions.group(g.group_id).turns_used;f.company.discussions.progress();assert.equal(f.company.discussions.group(g.group_id).state,'blocked');assert.equal(f.company.discussions.group(g.group_id).turns_used,before);assert.equal(f.company.discussions.turn(facilitator.request.request_id)!.advanced,0);assert.equal(f.store.get<{n:number}>("SELECT count(*) n FROM discussion_turns WHERE group_id=? AND kind='response'",g.group_id)!.n,0);
  for(const r of requests)f.company.conversations.cancel(r.request_id);control(f,g,'resume');f.company.discussions.progress();assert.equal(f.company.discussions.group(g.group_id).state,'active');assert.equal(f.store.get<{n:number}>("SELECT count(*) n FROM discussion_turns WHERE group_id=? AND kind='response'",g.group_id)!.n,2);
});

test('committed final artifact is retained but unknown synthesizer outcome blocks group completion',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const a=claim(f),b=claim(f);const original=contribution(f,a);contribution(f,b);finish(f,a);finish(f,b);control(f,g,'finish');const final=claim(f);f.company.conversations.event(final.context,'runtime_turn_starting',{context_chars:100});const saved=synthesis(f,final,original.message_id);f.company.finish(final.execution.execution_id,{status:'failed',settled:false,error:'Lost final provider settlement fixture'});f.company.discussions.progress();assert.equal(f.company.providerUnresolved(atlas.worker_id),true);assert.equal(f.company.discussions.group(g.group_id).state,'blocked');assert.equal(f.company.discussions.synthesis(saved.synthesis_id).state,'final');assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.discussions.inspect(g.group_id).syntheses.length,1);});

test('private direct/task/document sentinels stay outside group context, grants and record retrieval',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const privateChat=f.company.conversations.open({worker_id:atlas.worker_id,purpose:'PRIVATE_CONVERSATION_TITLE'});const privateMessage=f.company.conversations.send({conversation_id:privateChat.conversation_id,body:'PRIVATE_CONVERSATION_SENTINEL',request_reply:false,receipt_key:randomUUID()});
  f.company.research.grant({worker_id:atlas.worker_id,preset:'company_knowledge',expires_at:null,document_paths:['README.md']});const other=create(f,[atlas,scout]);const privateEvidence=f.company.discussions.share({group_id:other.group_id,kind:'owner_material',title:'Private other group',content:'OTHER_GROUP_SENTINEL',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:other.scope_version,audience_worker_ids:JSON.parse(other.eligible_workers),receipt_key:randomUUID()});const g=create(f,[atlas,scout]);control(f,g,'start');const c=claim(f);const context=JSON.stringify(f.company.conversations.context(c.context));assert.doesNotMatch(context,/PRIVATE_CONVERSATION|OTHER_GROUP_SENTINEL|company_knowledge|README.md/);for(const record of [privateMessage.message.message_id,privateEvidence.evidence_id])assert.throws(()=>f.company.discussions.callTool(c.context,randomUUID(),'read_group_record',{record_id:record,offset:0}),/outside/);
  assert.throws(()=>f.company.discussions.share({group_id:g.group_id,kind:'document_excerpt',title:'Forged',content:'NOT_IN_APPROVED_DOCUMENT',source_id:null,document_path:'README.md',audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:JSON.parse(g.eligible_workers),receipt_key:randomUUID()}),/exact excerpt/);
  assert.throws(()=>f.company.discussions.share({group_id:g.group_id,kind:'owner_material',title:'Unconfirmed',content:'Body',source_id:null,document_path:null,audience_confirmed:false,receipt_key:randomUUID()}),/Confirm/);
});

test('membership revocation and evidence withdrawal invalidate cached group sessions and stale callbacks',t=>{for(const action of ['member','evidence']){const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);const shared=f.company.discussions.share({group_id:g.group_id,kind:'owner_material',title:'Shared snapshot',content:'SCOPED_MATERIAL',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:JSON.parse(g.eligible_workers),receipt_key:randomUUID()});control(f,g,'start');const c=claim(f);assert.match(JSON.stringify(f.company.conversations.context(c.context)),/Shared snapshot/);
  if(action==='member')f.company.discussions.revokeMember({group_id:g.group_id,worker_id:scout.worker_id});else f.company.discussions.withdrawEvidence({group_id:g.group_id,evidence_id:shared.evidence_id});
  assert.throws(()=>f.company.conversations.context(c.context),/scope changed|held or stopped/);assert.throws(()=>contribution(f,c),/scope changed|held or stopped/);finish(f,c);assert.equal(f.company.claimWorkNext(),undefined);assert.throws(()=>control(f,g,'resume'),/revoked|withdrawn/);assert.equal(f.company.discussions.inspect(g.group_id).evidence.length,1);
}});

test('owner interjection arriving during synthesis requires refreshed checkpoint before commitment',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const a=claim(f),b=claim(f);const ref=contribution(f,a);contribution(f,b);finish(f,a);finish(f,b);control(f,g,'finish');const final=claim(f);const seen=f.company.discussions.turn(final.request.request_id)!.seen_revision;
  f.company.discussions.note({group_id:g.group_id,body:'NEW_HUMAN_CONSTRAINT: all first-use actions must be keyboard accessible.',kind:'constraint',receipt_key:randomUUID()});assert.throws(()=>synthesis(f,final,ref.message_id),/New contributions/);const refreshed=f.company.discussions.callTool(final.context,'refresh','read_discussion',{});assert.match(JSON.stringify(refreshed),/NEW_HUMAN_CONSTRAINT/);const result=synthesis(f,final,ref.message_id);assert.ok(f.company.discussions.synthesis(result.synthesis_id).transcript_revision>seen!);
});

test('restart preserves completed turns and queued work; deterministic scoped generation replacement retains pending questions',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const first=claim(f);const original=f.company.discussions.callTool(first.context,'question','submit_contribution',{body:'An unresolved question about offline accessibility.',contribution_ids:[],evidence_ids:[],questions:[{question:'How does keyboard-only use work offline?',target_worker_id:null}],answers:[]}) as {message_id:string};finish(f,first);
  const priorCount=f.company.discussions.inspect(g.group_id).history.items.length;f.company.recover();assert.equal(f.company.discussions.inspect(g.group_id).history.items.length,priorCount);const second=claim(f);assert.notEqual(second.worker.worker_id,first.worker.worker_id);contribution(f,second);finish(f,second);
  const previous=f.store.get<{session_id:string}>('SELECT session_id FROM conversation_sessions WHERE conversation_id=? AND worker_id=?',g.conversation_id,atlas.worker_id)!;f.company.conversations.requestRollover(g.conversation_id,atlas.worker_id);const facilitator=claim(f);assert.ok(facilitator.execution.generation>=2);assert.notEqual(facilitator.execution.session_id,previous.session_id);const context=JSON.stringify(f.company.conversations.context(facilitator.context));assert.match(context,/How does keyboard-only use work offline/);assert.match(context,new RegExp(original.message_id));assert.throws(()=>contribution(f,first),/not authorized/);
});

test('durable deadlines, bounded owner extension and no consumed-limit reset',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);control(f,g,'start');const used=f.company.discussions.group(g.group_id).turns_used;control(f,g,'pause');f.store.run('UPDATE working_groups SET deadline=? WHERE group_id=?',new Date(Date.now()-1000).toISOString(),g.group_id);f.company.discussions.progress();assert.equal(f.company.discussions.group(g.group_id).state,'blocked');assert.equal(f.company.claimWorkNext(),undefined);assert.throws(()=>control(f,g,'resume'),/Deadline/);control(f,g,'extend');const extended=f.company.discussions.group(g.group_id);assert.equal(extended.turn_limit,g.turn_limit+8);assert.equal(extended.turns_used,used+1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM discussion_extensions WHERE group_id=?',g.group_id)!.n,1);control(f,g,'stop');control(f,g,'extend');control(f,g,'stop');assert.throws(()=>control(f,g,'extend'),/Maximum/);assert.equal(f.company.discussions.group(g.group_id).extensions_used,2);});

test('sharing pins the reviewed Atlas audience and scope during organization and after selection',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout],true);control(f,g,'start');const c=claim(f);const input={group_id:g.group_id,kind:'owner_material',title:'Reviewed export',content:'Scoped material',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:1,audience_worker_ids:[atlas.worker_id],receipt_key:randomUUID()};
  assert.throws(()=>f.company.discussions.share(input),/audience changed/);input.audience_worker_ids=[atlas.worker_id,scout.worker_id];f.company.discussions.share(input);f.company.discussions.callTool(c.context,'refresh','read_discussion',{});f.company.discussions.callTool(c.context,'organize','organize_discussion',{participant_ids:[atlas.worker_id,scout.worker_id],synthesizer_id:atlas.worker_id,body:'Use both existing perspectives.'});finish(f,c);f.company.discussions.progress();assert.throws(()=>f.company.discussions.share({...input,receipt_key:randomUUID()}),/audience changed/);
});

test('maximum charter and question inputs remain retrievable and allow a bounded final artifact',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=f.company.discussions.create({topic:'T'.repeat(300),desired_output:'O'.repeat(2000),constraints:'C'.repeat(4000),participant_ids:[atlas.worker_id,scout.worker_id],facilitator_id:atlas.worker_id,synthesizer_id:atlas.worker_id,organize_with_atlas:false,allow_incomplete:true,allow_research:false,receipt_key:randomUUID()});control(f,g,'start');const first=claim(f),second=claim(f);const refs=[];
  for(const c of [first,second]){refs.push((f.company.discussions.callTool(c.context,'max-questions','submit_contribution',{body:'B'.repeat(8000),contribution_ids:[],evidence_ids:[],questions:[{question:'Q'.repeat(600),target_worker_id:null},{question:'R'.repeat(600),target_worker_id:null}],answers:[]}) as {message_id:string}).message_id);finish(f,c);}
  for(let i=0;i<20;i++)f.store.run('INSERT INTO discussion_questions VALUES (?,?,?,?,NULL,NULL)',randomUUID(),g.group_id,refs[0]!,'U'.repeat(600));
  control(f,g,'finish');const final=claim(f);const question=f.store.get<{question_id:string}>('SELECT question_id FROM discussion_questions WHERE group_id=?',g.group_id)!;const original=f.company.discussions.callTool(final.context,'full-question','read_group_record',{record_id:question.question_id,offset:0}) as {content:string};assert.equal(original.content.length,600);const saved=synthesis(f,final,refs[0]!);const artifact=f.company.discussions.synthesis(saved.synthesis_id);assert.ok(artifact.content.length<=32000);assert.equal(JSON.parse(artifact.content).unanswered_questions.length,24);assert.equal(JSON.parse(artifact.content).constraints.length,4000);const preview=f.company.discussions.assignmentPreview(saved.synthesis_id);assert.ok(preview.constraints.length<=3000);assert.match(preview.selected_context,/CCCCCCCC/);
});

test('persistence rejects forged synthesis/checkpoint/evidence ownership independently of tools',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const a=create(f,[atlas,scout]),b=create(f,[atlas,scout]);control(f,a,'start');const c=claim(f);const turn=f.company.discussions.turn(c.request.request_id)!;
  assert.throws(()=>f.store.run('INSERT INTO group_syntheses VALUES (?,?,1,NULL,?,?,\'final\',?,0,1,\'{}\',\'hash\',?)',randomUUID(),b.group_id,c.execution.execution_id,scout.worker_id,1,new Date().toISOString()),/ownership/);
  assert.throws(()=>f.store.run('INSERT INTO discussion_checkpoints VALUES (?,?,?,?,?,?,?)',randomUUID(),turn.turn_id,c.execution.execution_id,99999,0,'hash',new Date().toISOString()),/ownership/);
  assert.throws(()=>f.store.run('INSERT INTO group_evidence VALUES (?,?,\'owner_material\',\'title\',\'content\',\'{}\',\'hash\',NULL,1,?,?,?)',randomUUID(),b.group_id,atlas.principal_id,c.execution.execution_id,new Date().toISOString()),/ownership/);
});

test('serialized charter admission and refresh/record accounting remain consistent',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);assert.throws(()=>f.company.discussions.create({topic:'"'.repeat(300),desired_output:'"'.repeat(2000),constraints:'"'.repeat(4000),participant_ids:[atlas.worker_id,scout.worker_id],facilitator_id:atlas.worker_id,synthesizer_id:atlas.worker_id,organize_with_atlas:false,allow_incomplete:true,allow_research:false,receipt_key:randomUUID()}),/serialized text budget/);const g=create(f,[atlas,scout]);control(f,g,'start');const c=claim(f);
  for(let i=0;i<3;i++)f.company.discussions.callTool(c.context,`refresh-${i}`,'read_discussion',{});const message=f.company.discussions.inspect(g.group_id).history.items[0]!;f.company.discussions.callTool(c.context,'record-after-refresh','read_group_record',{record_id:message.message_id,offset:0});assert.ok(f.store.get<{record_chars:number}>('SELECT record_chars FROM discussion_retrieval_usage WHERE execution_id=?',c.execution.execution_id)!.record_chars<1000);assert.throws(()=>f.company.discussions.callTool(c.context,'refresh-four','read_discussion',{}),/CHECK/);
  assert.throws(()=>f.company.conversations.event(c.context,'runtime_turn_starting',{context_chars:48001}),/accounting/);assert.equal(f.store.get('SELECT * FROM execution_runtime_attempts WHERE execution_id=?',c.execution.execution_id),undefined);f.company.conversations.event(c.context,'runtime_turn_starting',{context_chars:48000});assert.ok(f.store.get('SELECT * FROM execution_runtime_attempts WHERE execution_id=?',c.execution.execution_id));
});

test('many tiny owner constraints stop at admission before metadata can prevent context assembly',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const g=create(f,[atlas,scout]);for(let i=0;i<32;i++)f.company.discussions.note({group_id:g.group_id,body:'x',kind:'constraint',receipt_key:randomUUID()});assert.throws(()=>f.company.discussions.note({group_id:g.group_id,body:'x',kind:'constraint',receipt_key:randomUUID()}),/count budget/);control(f,g,'start');const c=claim(f);const context=f.company.discussions.context(c.context);assert.equal(context.owner_interjections.length,32);assert.ok(JSON.stringify(context).length<=48000);});

test('group device projections omit private executions, notes, evidence and event payloads',t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const before=f.store.all('SELECT * FROM client_events'),g=create(f,[atlas,scout]);f.company.discussions.note({group_id:g.group_id,kind:'constraint',body:'PRIVATE_GROUP_DEVICE_SENTINEL',receipt_key:randomUUID()});control(f,g,'start');const c=claim(f);const dto=new ClientDTOs(f.company,'test-hq');assert.throws(()=>dto.one('executions',c.execution.execution_id),/not found/i);assert.doesNotMatch(JSON.stringify(dto.page('executions',new URLSearchParams())),new RegExp(c.execution.execution_id));assert.doesNotMatch(JSON.stringify(dto.page('messages',new URLSearchParams())),/PRIVATE_GROUP_DEVICE_SENTINEL/);contribution(f,c);finish(f,c);assert.deepEqual(f.store.all('SELECT * FROM client_events'),before);});

test('delayed group research rechecks membership, evidence policy, stop and grant before delivery',async t=>{for(const change of ['membership','evidence','stop','grant']){const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);const grant=f.company.research.grant({worker_id:atlas.worker_id,preset:'public_research',expires_at:null,document_paths:[],allow_discussions:true}),g=create(f,[atlas,scout]);const shared=f.company.discussions.share({group_id:g.group_id,kind:'owner_material',title:'Shared',content:'Bounded material',source_id:null,document_path:null,audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:[atlas.worker_id,scout.worker_id],receipt_key:randomUUID()});control(f,g,'start');const c=claim(f);assert.equal(c.worker.worker_id,atlas.worker_id);let release!:()=>void;const gate=new Promise<void>(r=>release=r);f.company.research.provider={name:'delayed-fixture',async search(_q,_s,h){h.invoking();await gate;h.settled();return {provider:'fixture',outcome:'succeeded',sources:[{url:'https://example.com/',title:'Fixture only',content:'Never deliver after authority changes.',kind:'search_snippet',retrieved_at:new Date().toISOString(),published_at:null,observed_at:null,freshness:'unknown',omissions:'Deterministic fixture, not live evidence'}]};}};const pending=f.company.research.callTool(c.context,'delayed','research_search',{query:'public documentation'},new AbortController().signal) as Promise<{ok:boolean}>;
  if(change==='membership')f.company.discussions.revokeMember({group_id:g.group_id,worker_id:scout.worker_id});else if(change==='evidence')f.company.discussions.withdrawEvidence({group_id:g.group_id,evidence_id:shared.evidence_id});else if(change==='stop')control(f,g,'stop');else f.company.research.revoke({grant_id:grant.grant_id});release();assert.equal((await pending).ok,false);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_sources')!.n,0);assert.equal(f.company.providerUnresolved(atlas.worker_id),false);
}});

test('one group research budget applies to both granted participants and survives extension',async t=>{const f=fixture();t.after(()=>f.close());const {atlas,scout}=roster(f);for(const w of [atlas,scout])f.company.research.grant({worker_id:w.worker_id,preset:'public_research',expires_at:null,document_paths:[],allow_discussions:true});const g=create(f,[atlas,scout]);control(f,g,'start');const a=claim(f),b=claim(f);let calls=0;f.company.research.provider={name:'fixture',async search(){calls++;return {provider:'fixture',outcome:'succeeded',sources:[]};}};await f.company.research.callTool(a.context,'initial','research_search',{query:'public docs'},new AbortController().signal);const op=f.store.get<Record<string,string|number|null>>('SELECT * FROM research_operations')!;
  // Explicitly synthetic consumed history, never represented as actual source lookups.
  for(let i=1;i<32;i++){const v={...op,operation_id:randomUUID(),call_id:randomUUID(),runtime_reference:null,created_at:new Date(Date.now()-120000).toISOString()};f.store.run(`INSERT INTO research_operations (${Object.keys(v).join(',')}) VALUES (${Object.keys(v).map(()=>'?').join(',')})`,...Object.values(v));}
  assert.throws(()=>f.company.research.callTool(b.context,'new-worker','research_search',{query:'another public question'},new AbortController().signal),/Work research/);contribution(f,a);contribution(f,b);finish(f,a);finish(f,b);control(f,g,'extend');const next=claim(f);assert.throws(()=>f.company.research.callTool(next.context,'extended','research_search',{query:'public docs'},new AbortController().signal),/Work research/);assert.equal(calls,1);
});
