import test from 'node:test';
import assert from 'node:assert/strict';
import {teamFixture} from './fixtures/investment-team/support.js';
import type {PaperProposal,PaperReview} from '../src/domain/investment-team/types.js';
import type {Proposal} from '../src/domain/investment/types.js';
import {hash} from '../src/domain/investment/identity.js';
for(const maxOrders of [0,10])test(`typed BUY respects order budget ${maxOrders}, publication and fill health; SELL remains risk reducing`,async t=>{
 const f=teamFixture();t.after(()=>f.close());const target=f.config.calendar.sessions.find(s=>s.status==='open'&&Date.parse(s.open)>Date.parse(f.clock.now()))!;f.clock.set(new Date(Date.parse(target.open)-3600000).toISOString());f.envelope.maxOrders=maxOrders;const scope=f.grant();f.control('start');const [a,b]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const {proposal:p}=f.call(a,'paper_propose',{...f.proposal,action:'BUY',order:{instrumentId:'ACME',side:'BUY',quantity:'2',targetSession:target.date,priceGuard:'110'}}) as {proposal:PaperProposal};f.contribute(a);f.finish(a);f.call(b,'read_discussion',{});f.call(b,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});f.call(b,'paper_read_proposal',{proposalId:p.proposal_id});const review={proposalId:p.proposal_id,proposalHash:p.proposal_hash,disposition:'approve',rationale:'Fixture bounded position fits the frozen limits',dissent:['Possible adverse opening move'],evidenceIds:[]};assert.throws(()=>f.call(b,'paper_review',{...review,proposalHash:'0'.repeat(64)}),/exact|Exact/);const {review:r}=f.call(b,'paper_review',review) as {review:PaperReview};assert.throws(()=>f.call(b,'paper_review',review),/One authoritative/);f.contribute(b);f.finish(b);const submitter=f.claim();f.call(submitter,'paper_read_proposal',{proposalId:p.proposal_id});const input={proposalId:p.proposal_id,proposalHash:p.proposal_hash,reviewId:r.review_id};if(maxOrders===0){assert.throws(()=>f.call(submitter,'paper_submit',input),/order budget/);assert.equal(f.store.all('SELECT * FROM investment_team_submissions').length,0);return;}assert.throws(()=>f.call(submitter,'paper_submit',input),/Publication health/);assert.equal(f.store.all('SELECT * FROM investment_team_submissions').length,0);f.approvePublication();const submitted=f.call(submitter,'paper_submit',input);assert.equal(submitted.outcome.status,'pending');const orderId=submitted.outcome.orderId;const team=f.company.investmentTeam,market=team.market(team.scope(scope.scopeId));f.clock.set(new Date(Date.parse(target.open)+1000).toISOString());f.price('ACME',target.date,'regular_open','100');assert.throws(()=>market.execute(f.config.runId,{type:'fill',orderId},'opening'),/Publication health/);assert.equal(f.sim.inspect(f.config.runId).orders[orderId]!.status,'pending');f.company.publication.capture({channelId:f.channelId});assert.equal(market.execute(f.config.runId,{type:'fill',orderId},'opening').outcome.status,'filled');f.company.publication.control({channelId:f.channelId,action:'revoke',keyId:null,generation:null});assert.equal(market.execute(f.config.runId,{type:'fill',orderId},'opening').outcome.status,'filled');
 const next=f.config.calendar.sessions.find(s=>s.status==='open'&&s.date>target.date)!,proposal:Proposal={decisionId:'trusted-sell-guard-fixture',revision:1,author:f.atlas.worker_id,action:'SELL',evidenceCutoff:f.clock.now(),evidence:[],rationale:'Explicit fixture risk reduction',orders:[{instrumentId:'ACME',side:'SELL',quantity:'1',priceGuard:'90',targetSession:next.date}]};market.execute(f.config.runId,{type:'decision',proposal},'sell-decision');market.execute(f.config.runId,{type:'review',review:{id:'sell-review',decisionId:proposal.decisionId,revision:1,proposalHash:hash(proposal),reviewer:f.scout.worker_id,disposition:'approve',reviewedAt:f.clock.now()}},'sell-review');assert.equal(market.execute(f.config.runId,{type:'submit',decisionId:proposal.decisionId,revision:1,orderIndex:0,reviewId:'sell-review',expectedVersion:f.sim.inspect(f.config.runId).ledgerVersion},'sell-submit').outcome.status,'pending');
});
