import test from 'node:test';
import assert from 'node:assert/strict';
import {teamFixture} from './fixtures/investment-team/support.js';
import {Dispatcher} from '../src/control/dispatcher.js';
import {until,objective} from './helpers.js';
import type {RuntimeAdapter} from '../src/runtime/adapter.js';
import type {TurnLimits} from '../src/domain/investment-team/types.js';
for(const action of ['pause','revoke','expiry'] as const)test(`shared bounded dispatcher retains uncertainty and quotas after ${action}`,async t=>{
 const f=teamFixture(),signals:AbortSignal[]=[],limits:TurnLimits[]=[];f.store.run("UPDATE workers SET mission='PRIVATE_RUNTIME_MISSION' WHERE worker_id=?",f.atlas.worker_id);if(action==='expiry')f.envelope.expiresAt=new Date(Date.now()+1200).toISOString();const p=f.grant();f.runtime.gate=async(input,signal)=>{input.event('runtime_turn_starting',{context_chars:1});signals.push(signal);await new Promise<void>(resolve=>{if(signal.aborted)resolve();else signal.addEventListener('abort',()=>resolve(),{once:true});});return {status:'interrupted',settled:false,error:'Explicit fixture unresolved provider result'};};const adapter:RuntimeAdapter={...f.bounded,runBoundedInvestment:async(input,signal,bounds)=>{limits.push(bounds);return f.runtime.run(input,signal);}},dispatcher=new Dispatcher(f.company,adapter);t.after(async()=>{await dispatcher.stop();await f.close();});f.control('start');dispatcher.start();await until(()=>signals.length===2);assert.equal(dispatcher.activeCount,2);assert.deepEqual(limits,[f.envelope.turnLimits,f.envelope.turnLimits]);assert.doesNotMatch(JSON.stringify(f.runtime.calls.map(c=>({worker:c.worker.mission,context:c.context}))),/PRIVATE_RUNTIME_MISSION/);f.company.assignObjective(objective);await new Promise<void>(r=>setImmediate(r));assert.equal(f.runtime.calls.length,2);if(action!=='expiry')f.company.investmentTeam.control({scopeId:p.scopeId,action});await until(()=>signals.every(s=>s.aborted));await until(()=>dispatcher.activeCount===0);assert.equal(f.store.all('SELECT * FROM investment_team_executions').length,2);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),true);assert.equal(f.company.providerUnresolved(f.scout.worker_id),true);assert.equal(f.runtime.calls.length,2);
});
