import test from 'node:test';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {teamFixture} from './fixtures/investment-team/support.js';
import type {PaperProposal,PaperReview} from '../src/domain/investment-team/types.js';
test('scoped draft and consent preserve identities, remain passive and require exact owner digest',async t=>{
 const f=teamFixture();t.after(()=>f.close());const workers=f.company.workers(),p=f.preview();assert.equal(f.company.claimWorkNext(),undefined);assert.throws(()=>f.company.investmentTeam.consent({scopeId:p.scopeId,digest:'wrong'}),/digest/);f.company.investmentTeam.consent({scopeId:p.scopeId,digest:p.digest});assert.deepEqual(f.company.workers(),workers);assert.equal(f.company.claimWorkNext(),undefined);f.company.investmentTeam.control({scopeId:p.scopeId,action:'revoke'});assert.equal(f.company.investmentTeam.consent({scopeId:p.scopeId,digest:p.digest}).state,'revoked');
});
test('investment dispatch never falls back to an unbounded runtime and never loses its revoked binding',async t=>{
 const f=teamFixture();t.after(()=>f.close());const p=f.grant();f.company.investmentTeam.runtime=f.runtime;f.control('start');assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.runtime.calls.length,0);assert.ok(f.store.all<{error:string}>('SELECT error FROM conversation_requests WHERE conversation_id=?',f.group.conversation_id).some(x=>/Bounded investment/.test(x.error)));
 f.company.investmentTeam.control({scopeId:p.scopeId,action:'revoke'});assert.equal(f.company.investmentTeam.schema(f.group.conversation_id),'investment-discussion-v1');assert.equal(f.company.claimWorkNext(),undefined);
});
test('fresh investment context and handoff use reviewed responsibility without private mission or history',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.store.run("UPDATE workers SET mission='PRIVATE_MISSION_CANARY' WHERE worker_id=?",f.atlas.worker_id);f.grant();f.control('start');const [a]=f.pair();const context=JSON.stringify(f.company.conversations.context(a.context));const session=f.company.conversations.session(a.execution.session_id);assert.doesNotMatch(context,/PRIVATE_MISSION_CANARY/);assert.doesNotMatch(session.handoff,/PRIVATE_MISSION_CANARY/);assert.equal(session.tool_schema,'investment-discussion-v1');assert.ok(f.company.conversations.tools(a.context).some(t=>t.name==='paper_propose'));
});
test('exact independent HOLD review and submission require delivered evidence and settled upstream turns',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.envelope.maxOrders=0;f.grant();f.control('start');const [a,b]=f.pair();assert.equal(a.worker.worker_id,f.atlas.worker_id);assert.throws(()=>f.call(a,'paper_propose',f.proposal),/complete exact source/);f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const saved=f.call(a,'paper_propose',f.proposal) as {proposal:PaperProposal};assert.throws(()=>f.call(a,'paper_review',{proposalId:saved.proposal.proposal_id,proposalHash:saved.proposal.proposal_hash,disposition:'approve',rationale:'Self',dissent:[],evidenceIds:[]}),/Independent/);
 f.call(b,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});f.call(b,'paper_read_proposal',{proposalId:saved.proposal.proposal_id});const reviewInput={proposalId:saved.proposal.proposal_id,proposalHash:saved.proposal.proposal_hash,disposition:'approve',rationale:'Waiting is consistent with the stated uncertainty; retain opportunity-cost risk',dissent:[],evidenceIds:[]};assert.throws(()=>f.call(b,'paper_review',reviewInput),/not settled/);f.contribute(a);f.finish(a);f.call(b,'read_discussion',{});const reviewed=f.call(b,'paper_review',reviewInput) as {review:PaperReview};f.contribute(b);f.finish(b);
 const final=f.claim();f.call(final,'paper_read_proposal',{proposalId:saved.proposal.proposal_id});f.company.conversations.event(final.context,'runtime_turn_starting',{context_chars:1});const result=f.call(final,'paper_submit',{proposalId:saved.proposal.proposal_id,reviewId:reviewed.review.review_id,proposalHash:saved.proposal.proposal_hash});assert.equal(result.outcome.status,'hold');assert.equal(f.sim.inspect(f.config.runId).ordersUsed,0);assert.equal(f.store.all('SELECT * FROM investment_team_submissions').length,1);
});
test('owner preview binds the reviewed evidence checkpoint and the run cannot acquire a second scope',async t=>{
 const f=teamFixture();t.after(()=>f.close());const p=f.preview();f.company.discussions.note({group_id:f.group.group_id,kind:'note',body:'A newly added constraint',receipt_key:randomUUID()});assert.throws(()=>f.company.investmentTeam.consent({scopeId:p.scopeId,digest:p.digest}),/context changed/);const renewed=f.preview();assert.notEqual(renewed.digest,p.digest);assert.throws(()=>f.company.investmentTeam.consent({scopeId:p.scopeId,digest:p.digest}),/digest/);f.company.investmentTeam.consent({scopeId:renewed.scopeId,digest:renewed.digest});assert.throws(()=>f.preview(),/immutable investment scope/);
});
test('paper tool actor spoofing, different reviewer role and revoked callbacks are denied',async t=>{
 const f=teamFixture();t.after(()=>f.close());const p=f.grant();f.control('start');const [a,b]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});assert.throws(()=>f.call(a,'paper_propose',{...f.proposal,author:f.scout.worker_id}));assert.throws(()=>f.call(b,'paper_propose',f.proposal),/cannot propose/);f.company.investmentTeam.control({scopeId:p.scopeId,action:'revoke'});assert.throws(()=>f.call(a,'paper_propose',f.proposal),/inactive/);assert.equal(f.store.all('SELECT * FROM investment_team_proposals').length,0);
});
test('all pages of a long committed contribution are required and a current turn does not taint settled predecessor',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a,b]=f.pair();const body='Fixture detailed explanation. '.repeat(245);const contributed=f.contribute(b,body);f.finish(b);f.call(a,'read_discussion',{});const recordId=contributed.message_id as string;assert.ok(recordId);f.call(a,'read_group_record',{record_id:recordId,offset:0});const proposal={...f.proposal,evidenceIds:[],contributionIds:[recordId]};assert.throws(()=>f.call(a,'paper_propose',proposal),/complete exact source/);f.call(a,'read_group_record',{record_id:recordId,offset:6000});const saved=f.call(a,'paper_propose',proposal);assert.equal(saved.proposal.worker_id,f.atlas.worker_id);
});
test('proposal semantic retry is stable across time and conflicting terms roll back',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const first=f.call(a,'paper_propose',f.proposal);f.clock.set(new Date(Date.parse(f.clock.now())+1000).toISOString());const repeated=f.call(a,'paper_propose',f.proposal);assert.deepEqual(repeated,first);assert.throws(()=>f.call(a,'paper_propose',{...f.proposal,rationale:'Changed exact terms'}),/conflicts/);assert.equal(f.store.all('SELECT * FROM investment_team_proposals').length,1);
});
test('proposal, simulator journal, public intent and delivery receipt roll back atomically',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const journal=f.sim.journal(f.config.runId).length,intents=f.store.all('SELECT * FROM investment_public_intents').length,receipts=f.store.all('SELECT * FROM tool_receipts').length;f.company.investmentTeam.fault=()=>{throw new Error('Injected crash before commit');};assert.throws(()=>f.call(a,'paper_propose',f.proposal),/Injected crash/);assert.equal(f.sim.journal(f.config.runId).length,journal);assert.equal(f.store.all('SELECT * FROM investment_public_intents').length,intents);assert.equal(f.store.all('SELECT * FROM tool_receipts').length,receipts);assert.equal(f.store.all('SELECT * FROM investment_team_proposals').length,0);f.company.investmentTeam.fault=undefined;assert.ok(f.call(a,'paper_propose',f.proposal).proposal);
});
test('uncertain restart retains the execution allowance and rejects stale paper callbacks',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.envelope.maxExecutions=2;f.grant();f.control('start');const [a]=f.pair();f.company.conversations.event(a.context,'runtime_turn_starting',{context_chars:1});f.company.recover();assert.equal(f.store.all('SELECT * FROM investment_team_executions').length,2);assert.equal(f.company.providerUnresolved(a.worker.worker_id),true);assert.throws(()=>f.call(a,'paper_propose',f.proposal));assert.equal(f.store.all('SELECT * FROM investment_team_proposals').length,0);
});
test('research search needs a separate bounded adapter and capability expiry blocks each callback',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a]=f.pair();assert.throws(()=>f.company.investmentTeam.research(a.context,'research_search'),/separately enforceable/);f.clock.set(f.envelope.expiresAt);assert.throws(()=>f.call(a,'paper_inspect',{}),/expired/);assert.equal(f.store.all('SELECT * FROM research_operations').length,0);
});
test('a newer proposal revision supersedes reviewed terms and the old review cannot approve it',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.grant();f.control('start');const [a,b]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const p=f.call(a,'paper_propose',f.proposal).proposal;f.contribute(a);f.finish(a);f.call(b,'read_discussion',{});f.call(b,'paper_read_proposal',{proposalId:p.proposal_id});const review={proposalId:p.proposal_id,proposalHash:p.proposal_hash,disposition:'approve',rationale:'Fixture original terms reviewed',dissent:[],evidenceIds:[]};assert.throws(()=>f.call(b,'paper_review',review),/complete exact source/);f.call(b,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const r=f.call(b,'paper_review',review).review;f.contribute(b);f.finish(b);const next=f.claim();f.call(next,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const revised=f.call(next,'paper_propose',{...f.proposal,revision:2,rationale:'Revised terms need their own independent review'}).proposal;f.call(next,'paper_read_proposal',{proposalId:p.proposal_id});assert.throws(()=>f.call(next,'paper_submit',{proposalId:p.proposal_id,proposalHash:p.proposal_hash,reviewId:r.review_id}),/superseded/);f.call(next,'paper_read_proposal',{proposalId:revised.proposal_id});assert.throws(()=>f.call(next,'paper_submit',{proposalId:revised.proposal_id,proposalHash:revised.proposal_hash,reviewId:r.review_id}),/Exact approved/);assert.equal(f.store.all('SELECT * FROM investment_team_submissions').length,0);assert.equal(f.sim.inspect(f.config.runId).ordersUsed,0);
});
test('finite proposal allowance survives duplicate call IDs and excludes new revisions',async t=>{const f=teamFixture();t.after(()=>f.close());f.envelope.maxProposals=1;f.grant();f.control('start');const [a]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const callId=randomUUID(),first=f.call(a,'paper_propose',f.proposal,callId);assert.equal(JSON.stringify(f.call(a,'paper_propose',f.proposal,callId)),JSON.stringify(first));assert.throws(()=>f.call(a,'paper_propose',{...f.proposal,revision:2}),/budget exhausted/);assert.equal(f.store.all('SELECT * FROM investment_team_proposals').length,1);});
