import test from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {loopFixture} from './fixtures/investment-loop/support.js';
import {ownerAttention} from '../src/control/attention.js';
import {Store} from '../src/persistence/store.js';
import {removeEmptyLoopMigration} from './fixtures/investment/schema.js';

test('calendar preview is passive, replaceable before exact start, and preserves immutable consent',t=>{
 const f=loopFixture();t.after(f.close);const first=f.preview();assert.equal(f.runtime.calls.length,0);assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);assert.throws(()=>f.control(first.loopId,'start','forged'),/consent/);f.input.maxStageAttempts=2;const p=f.preview();assert.notEqual(p.digest,first.digest);assert.throws(()=>f.control(first.loopId,'start',first.digest),/consent/);f.control(p.loopId,'start',p.digest);assert.equal(f.loop.get(p.loopId).state,'active');assert.equal(f.loop.nextWake(),f.occurrences(p.loopId).filter(o=>o.state==='pending')[0]!.due_at);assert.throws(()=>f.control(p.loopId,'start',p.digest),/draft/);assert.throws(()=>f.control(p.loopId,'resume'),/held/);assert.equal(f.control(p.loopId,'cancel_order',undefined,'other-run-order').result.outcome.reason,'missing_order');assert.throws(()=>f.control(p.loopId,'start',p.digest),/draft/);assert.throws(()=>f.store.run("UPDATE investment_loops SET envelope='{}' WHERE loop_id=?",p.loopId),/immutable/);assert.throws(()=>f.company.discussions.control({group_id:f.group.group_id,action:'start',receipt_key:randomUUID()}),/Investment run/);
});
test('future calendar cycles do not poll models; complete first cycle waits overnight without quota reset',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),research=f.occurrences(p.loopId).filter(o=>o.stage==='research');for(let n=0;n<10;n++)f.company.mandates.tick();assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);f.at(research[0]!);f.company.mandates.tick();const old=f.openings();f.waitCycle();assert.equal(f.loop.occurrences(f.loop.get(p.loopId)).find(o=>o.occurrence_id===research[0]!.occurrence_id)?.state,'complete');assert.equal(f.company.discussions.group(f.group.group_id).state,'paused');assert.equal(f.company.discussions.group(f.group.group_id).deadline,null);const used=f.company.discussions.group(f.group.group_id).turns_used;f.at(research[1]!);f.company.mandates.tick();assert.equal(f.company.discussions.group(f.group.group_id).turns_used,used+1);const current=f.claim();assert.throws(()=>f.call(old[0],'paper_inspect',{}),/current|running|scope|execution/i);const context=f.loop.context(f.scope.scopeId)!;assert.equal(context.currentOccurrence?.session,research[1]!.session);assert.ok(context.outcomes.ledgerVersion);assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,4);f.company.finish(current.execution.execution_id,{status:'interrupted',settled:true,investmentUsage:{inputTokens:0,outputTokens:0,costMicros:0}});
});
test('missed research windows are retained without catch-up or backdating',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),research=f.occurrences(p.loopId).filter(o=>o.stage==='research');f.clock.set(new Date(Date.parse(research[1]!.expires_at)+1).toISOString());f.loop.tick();assert.ok(f.occurrences(p.loopId).filter(o=>o.stage==='research').every(o=>o.state==='missed'));assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);assert.equal(f.runtime.calls.length,0);
});
test('late queued claims and callbacks remain bound to the expired occurrence',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const c=f.claim();f.clock.set(o.expires_at);assert.throws(()=>f.call(c,'paper_inspect',{}),/window|deadline/);assert.equal(f.company.claimWorkNext(),undefined);f.loop.tick();assert.equal(f.occurrences(p.loopId).find(x=>x.occurrence_id===o.occurrence_id)?.state,'missed');assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,1);
});
for(const field of ['executions','tokens','money'] as const)test(`hard ${field} limits reserve before claim and never refund`,t=>{
 const f=loopFixture();t.after(f.close);if(field==='executions')f.input.maxCycleExecutions=2;if(field==='tokens')f.input.dailyLimits.inputTokens=16000;if(field==='money'){// Zero approved cost is a real bound, never inferred from missing usage.
  f.input.dailyLimits.maxCostMicros=0;f.input.runLimits.maxCostMicros=0;
 }
 const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const claims=f.pair();for(const c of claims){f.contribute(c);if(field==='money')f.company.finish(c.execution.execution_id,{status:'completed',investmentUsage:{inputTokens:1,outputTokens:1,costMicros:1}});else f.measured(c);}f.company.discussions.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,2);if(field==='money')assert.ok(f.store.all<{state:string}>('SELECT * FROM investment_loop_usage').every(u=>u.state==='exceeded'));
});
test('missing usage blocks future admission and remains unknown after reopen',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const c=f.claim();f.contribute(c);f.finish(c);f.loop.tick();assert.equal(f.loop.get(p.loopId).state,'blocked');assert.equal(f.store.get<{state:string}>('SELECT state FROM investment_loop_usage')!.state,'unknown');assert.equal(f.company.claimWorkNext(),undefined);assert.ok(ownerAttention(f.store).items.some(i=>i.source_type==='investment_loop'));const db=new Store(join(f.dir,'company.sqlite'));assert.equal(db.get<{state:string}>('SELECT state FROM investment_loop_usage')!.state,'unknown');assert.equal(db.get<{state:string}>('SELECT state FROM investment_loops WHERE loop_id=?',p.loopId)!.state,'blocked');assert.equal(db.all('SELECT * FROM investment_loop_executions').length,1);db.close();
});
test('crash before usage settlement rolls both back and restart retains unknown execution reservation',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const c=f.claim();f.contribute(c);f.loop.fault=point=>{if(point==='usage_before_settlement')throw Error('fixture power loss');};assert.throws(()=>f.measured(c),/power loss/);assert.equal(f.company.execution(c.execution.execution_id).status,'running');assert.equal(f.store.all('SELECT * FROM investment_loop_usage').length,0);f.loop.fault=undefined;f.company.recover();f.loop.tick();assert.equal(f.loop.get(p.loopId).state,'blocked');assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,1);assert.equal(f.company.claimWorkNext(),undefined);
});
test('occurrence and enqueue roll back together; restart and repeated tick produce one opening set',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.fault=point=>{if(point==='enqueue_before_occurrence_commit')throw Error('fixture crash');};assert.throws(()=>f.loop.tick(),/crash/);assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);assert.equal(f.occurrences(p.loopId).find(x=>x.occurrence_id===o.occurrence_id)?.state,'pending');f.loop.fault=undefined;f.loop.tick();f.company.recover();f.loop.tick();assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,2);assert.equal(f.company.discussions.group(f.group.group_id).turns_used,2);
});
test('source waits use bounded distinct attempts, terminal stages do not spin',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='open')!;f.approvePublication();f.at(o);for(let n=0;n<3;n++){f.loop.tick();f.clock.set(new Date(Date.parse(f.clock.now())+30000).toISOString());}const updated=f.occurrences(p.loopId).find(x=>x.occurrence_id===o.occurrence_id)!;assert.equal(updated.state,'blocked');assert.equal(updated.attempts,3);const attempts=f.store.all('SELECT * FROM investment_loop_attempts WHERE occurrence_id=?',o.occurrence_id);assert.equal(attempts.length,3);for(let i=0;i<10;i++)f.loop.tick();assert.equal(f.store.all('SELECT * FROM investment_loop_attempts WHERE occurrence_id=?',o.occurrence_id).length,3);assert.ok(f.loop.nextWake()!>f.clock.now());
});
test('pause and stop are atomic, receipt exact, and a global model pause is distinct',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start();f.company.pause(true);assert.equal(f.sim.inspect(f.config.runId).lifecycle,'active');const input={loopId:p.loopId,action:'pause',digest:null,receiptId:randomUUID(),orderId:null};const before=f.sim.inspect(f.config.runId).version;f.loop.fault=point=>{if(point==='control_before_commit')throw Error('fixture crash');};assert.throws(()=>f.loop.control(input),/crash/);assert.equal(f.sim.inspect(f.config.runId).version,before);assert.equal(f.loop.get(p.loopId).state,'active');f.loop.fault=undefined;const reply=f.loop.control(input);assert.equal(f.sim.inspect(f.config.runId).lifecycle,'paused');assert.equal(JSON.stringify(f.loop.control(input)),JSON.stringify(reply));assert.throws(()=>f.loop.control({...input,action:'stop'}),/mismatch/);f.control(p.loopId,'stop');assert.equal(f.sim.inspect(f.config.runId).lifecycle,'ended');assert.equal(f.loop.nextWake(),undefined);assert.throws(()=>f.control(p.loopId,'resume'),/held/);
});
test('populated schema18 preserves original rows across passive19 migration and restart',t=>{
 const f=loopFixture();t.after(f.close);removeEmptyLoopMigration(f.store);const tables=f.store.all<{name:string}>("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").map(r=>r.name),before=Object.fromEntries(tables.map(name=>[name,f.store.all(`SELECT rowid original_rowid,* FROM ${name} ORDER BY rowid`)]));for(let i=0;i<3;i++){const upgraded=new Store(join(f.dir,'company.sqlite'));try{for(const name of tables)assert.deepEqual(upgraded.all(`SELECT rowid original_rowid,* FROM ${name}${name==='schema_migrations'?' WHERE version<=18':''} ORDER BY rowid`),before[name],name);assert.equal(upgraded.all('SELECT * FROM investment_loops').length,0);assert.equal(upgraded.all('SELECT * FROM investment_loop_usage').length,0);assert.deepEqual(upgraded.all('PRAGMA foreign_key_check'),[]);}finally{upgraded.close();}}
});

test('replaced preview uses the approved opening predecessor while its retry window spans close',t=>{
 const f=loopFixture();t.after(f.close);const first=f.preview();f.input.retrySeconds=3600;const p=f.start();assert.notEqual(p.digest,first.digest);const mark=f.occurrences(p.loopId).find(o=>o.stage==='mark')!,opening=f.occurrences(p.loopId).find(o=>o.stage==='open')!;assert.ok(opening.expires_at>mark.due_at);f.approvePublication();f.at(mark,1000);f.loop.tick();assert.equal(f.occurrences(p.loopId).find(o=>o.occurrence_id===opening.occurrence_id)!.state,'pending');assert.equal(f.sim.inspect(f.config.runId).valuations.length,0);assert.match(f.occurrences(p.loopId).find(o=>o.occurrence_id===mark.occurrence_id)!.reason!,/Opening stage/);
});
test('exhausted blocked loop cannot resume an active simulator with no remaining eligible work',t=>{
 const f=loopFixture();t.after(f.close);f.input.sessions=f.input.sessions.slice(0,1);f.input.maxStageAttempts=1;const p=f.start();f.approvePublication();for(const o of f.occurrences(p.loopId).filter(o=>['open','mark','expire'].includes(o.stage))){f.at(o,1000);f.loop.tick();}assert.equal(f.loop.get(p.loopId).state,'blocked');assert.equal(f.sim.inspect(f.config.runId).lifecycle,'paused');assert.throws(()=>f.control(p.loopId,'resume'),/No eligible future/);assert.equal(f.sim.inspect(f.config.runId).lifecycle,'paused');
});
test('global model pause waits for cutoff or an explicit change, without recurring retry wakeups',t=>{
 const f=loopFixture();t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.company.pause(true);f.at(o);f.loop.tick();assert.equal(f.loop.nextWake(),o.expires_at);assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);f.company.pause(false);f.loop.tick();assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,2);
});
test('preview rejects omission of the frozen initial benchmark session',t=>{
 const f=loopFixture();t.after(f.close);f.input.sessions=f.input.sessions.slice(1);assert.throws(()=>f.preview(),/frozen benchmark/);assert.equal(f.store.all('SELECT * FROM investment_loops').length,0);
});

test('draft A to B to A retains separate plan revisions and permits exact restored consent',t=>{
 const f=loopFixture();t.after(f.close);const a=f.preview();f.input.retrySeconds=60;const b=f.preview();f.input.retrySeconds=30;const restored=f.preview();assert.equal(restored.digest,a.digest);assert.notEqual(restored.digest,b.digest);assert.equal(f.store.all('SELECT * FROM investment_loop_occurrences').length,30);assert.equal(f.occurrences(restored.loopId).length,10);assert.ok(f.occurrences(restored.loopId).every(o=>o.state==='pending'&&o.plan_revision===3));f.control(restored.loopId,'start',restored.digest);assert.equal(f.loop.get(restored.loopId).state,'active');
});

test('whole-run token reservations survive the next New York day without refund or reset',t=>{
 const f=loopFixture();t.after(f.close);f.input.dailyLimits.inputTokens=32000;f.input.runLimits.inputTokens=32000;const p=f.start(),cycles=f.occurrences(p.loopId).filter(o=>o.stage==='research');f.at(cycles[0]!);f.loop.tick();f.openings();f.waitCycle();f.at(cycles[1]!);f.loop.tick();const c=f.claim();f.call(c,'facilitate_discussion',{body:'Preserve original observations and produce a bounded final assessment.',action:'synthesize',turns:[]});f.measured(c);f.company.discussions.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,4);assert.equal(f.loop.context(f.scope.scopeId)!.usageReservations.inputTokens,32000);assert.equal(new Set(f.store.all<{day:string}>('SELECT day FROM investment_loop_executions').map(r=>r.day)).size,2);
});

test('activity loop retains cycle/run usage through owner pause/resume without using unknown dollar receipts as a budget',t=>{
 const f=loopFixture({activity:true});t.after(f.close);const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const c=f.claim();f.contribute(c);f.finish(c);
 assert.equal(f.store.get<{state:string}>('SELECT state FROM investment_loop_usage')!.state,'unknown');assert.equal(f.loop.get(p.loopId).state,'active');f.control(p.loopId,'pause');assert.equal(f.loop.get(p.loopId).state,'paused');f.approvePublication();f.control(p.loopId,'resume');assert.equal(f.loop.get(p.loopId).state,'active');assert.equal(f.company.investmentActivity.counts(f.config.runId).run,1);
 const report=f.company.aiUsage.report({runId:f.config.runId});assert.equal(report.summary.invocations,1);assert.equal(report.byCycle[o.occurrence_id]!.invocations,1);assert.equal(report.byWorker[c.worker.worker_id]!.invocations,1);assert.equal(report.rolling24h.invocations,1);assert.equal(report.summary.estimatedUsd,null);
});
