import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {teamFixture} from '../dist/test/fixtures/investment-team/support.js';
import {Dispatcher} from '../dist/src/control/dispatcher.js';
import {createHttpServer} from '../dist/src/http/server.js';
for(const width of [390,1440])test(`passive exact owner team consent, stale response and revocation (${width}px)`,async t=>{
 const f=teamFixture(),dispatcher=new Dispatcher(f.company,f.bounded),http=createHttpServer(f.company,dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:process.env.BOTSQUAD_BROWSER_CHANNEL??'chrome',headless:true}),page=await browser.newPage({viewport:{width,height:1000},timezoneId:'UTC'}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await http.close();await dispatcher.stop();await f.close();assert.deepEqual(errors,[]);});await page.goto(`http://127.0.0.1:${http.server.address().port}/investment-team`);await page.waitForFunction(()=>document.querySelector('[name=runId]').options.length>1);for(const field of ['runId','groupId','publicationChannelId'])await page.locator(`[name=${field}]`).selectOption(f.envelope[field]);
 for(const participant of f.envelope.participants){const section=page.locator(`[data-worker="${participant.workerId}"]`);await section.locator('[data-field=name]').fill(participant.name);await section.locator('[data-field=responsibility]').fill(participant.responsibility);for(const cap of ['proposers','reviewers','submitters'])if(f.envelope[cap].includes(participant.workerId))await section.locator(`[data-capability=${cap}]`).check();}await page.locator('[name=expiresAt]').fill('2026-11-01T00:00');for(const [key,value] of Object.entries({...f.envelope,...f.envelope.turnLimits}))if(typeof value==='number')await page.locator(`[name=${key}]`).fill(String(value));
 let entered,release;const seen=new Promise(r=>entered=r),ready=new Promise(r=>release=r);await page.route('**/api/investment-team/preview',async route=>{const response=await route.fetch();entered();await ready;await route.fulfill({response});},{times:1});await page.locator('#preview-button').click();await seen;await page.locator('[name=maxExecutions]').fill('23');release();await page.waitForResponse(r=>r.url().endsWith('/preview'));assert.equal(await page.locator('#preview-panel').isVisible(),false);await page.locator('#preview-button').click();await page.locator('#preview-panel').waitFor({state:'visible'});assert.equal(f.store.all('SELECT * FROM investment_team_executions').length,0);assert.equal(f.runtime.calls.length,0);assert.ok((await page.locator('#preview-json').textContent()).includes(f.evidence.content));await page.locator('#confirm').check();await page.locator('#consent').click();await page.getByText('Exact team consent saved. Start the working group separately.',{exact:true}).waitFor();await page.getByRole('button',{name:'Pause team',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#scopes').textContent.includes('paused ·'));await page.getByRole('button',{name:'Revoke team',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#scopes').textContent.includes('revoked ·'));assert.equal(f.runtime.calls.length,0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));mkdirSync('/private/tmp/botsquad-inv08-browser',{recursive:true});await page.screenshot({path:`/private/tmp/botsquad-inv08-browser/owner-${width}.png`,fullPage:true});
});
