import test from 'node:test';
import assert from 'node:assert/strict';
import {loopFixture} from './fixtures/investment-loop/support.js';
import type {PaperProposal,PaperReview} from '../src/domain/investment-team/types.js';
function pending(f:ReturnType<typeof loopFixture>,count=1,guarded=false,keepResearch=false){
 const p=f.start(),o=f.occurrences(p.loopId).find(o=>o.stage==='research')!;f.at(o);f.loop.tick();const [a,b]=f.pair(),proposals:PaperProposal[]=[],reviews:PaperReview[]=[];
 f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});for(let i=0;i<count;i++)proposals.push(f.call(a,'paper_propose',{...f.proposal,decisionId:`decision-${i}`,action:'BUY',order:{instrumentId:'ACME',side:'BUY',quantity:'2',targetSession:o.session,priceGuard:guarded&&i===0?'90':'110'}}).proposal);const contribution=f.contribute(a);f.measured(a);
 f.call(b,'read_discussion',{});f.call(b,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});for(const proposal of proposals){f.call(b,'paper_read_proposal',{proposalId:proposal.proposal_id});reviews.push(f.call(b,'paper_review',{proposalId:proposal.proposal_id,proposalHash:proposal.proposal_hash,disposition:'approve',rationale:'Explicit synthetic independent fixture review',dissent:['Unknown demand remains'],evidenceIds:[]}).review);}f.contribute(b);f.measured(b);
 const submitter=f.claim();f.approvePublication();const orders=[];for(let i=0;i<count;i++){const proposal=proposals[i]!,review=reviews[i]!;f.call(submitter,'paper_read_proposal',{proposalId:proposal.proposal_id});f.company.publication.capture({channelId:f.channelId});const result=f.call(submitter,'paper_submit',{proposalId:proposal.proposal_id,proposalHash:proposal.proposal_hash,reviewId:review.review_id});assert.equal(result.outcome.status,'pending');orders.push(result.outcome.orderId as string);}
 f.call(submitter,'facilitate_discussion',{body:'Synthetic fixture retains the guarded proposals and waits for original observations.',action:keepResearch?'discuss':'synthesize',turns:keepResearch?[{worker_id:f.scout.worker_id,prompt:'Challenge the locked order while preserving its exact receipt.',contribution_ids:[contribution.message_id],evidence_ids:[]}]:[]});f.measured(submitter);f.company.discussions.progress();return {p,o,orders};
}
for(const count of [1,2])test(`scheduled opening fills ${count} reviewed BUY orders once, values and retains terminal receipts`,t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f,count),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===opening.occurrence_id)?.state,'complete');for(const id of orders)assert.equal(f.sim.inspect(f.config.runId).orders[id]!.status,'filled');assert.equal(f.sim.inspect(f.config.runId).benchmarkExecutions.length,1);const version=f.sim.inspect(f.config.runId).version;f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).version,version);
 const mark=f.occurrences(p.loopId).find(n=>n.stage==='mark'&&n.session===o.session)!;f.at(mark,1000);f.price('ACME',o.session,'regular_close','101');f.price(f.config.benchmark.instrument.id,o.session,'regular_close','51');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).valuations.length,1);assert.equal(f.sim.inspect(f.config.runId).valuations[0]!.snapshot.quality,'complete');const marked=f.sim.inspect(f.config.runId).version;f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).version,marked);f.control(p.loopId,'pause');assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'filled');assert.equal(f.control(p.loopId,'cancel_order',undefined,orders[0]!).result.outcome.reason,'already_terminal');
});
test('opening with missing data retries a new safe attempt after evidence arrives',t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'pending');f.clock.set(new Date(Date.parse(f.clock.now())+31000).toISOString());f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'filled');assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===opening.occurrence_id)?.attempts,2);
});
test('pause commits cancellation before fill and resume never resurrects orders or missed research',t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f);f.control(p.loopId,'pause');assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'cancelled');const opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.company.publication.capture({channelId:f.channelId});f.control(p.loopId,'resume');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'cancelled');assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===opening.occurrence_id)?.state,'missed');
});
test('expiry cleanup works after team and publication revoke and source authorization horizon',t=>{
 const f=loopFixture();t.after(f.close);const {p,orders}=pending(f);f.company.investmentTeam.control({scopeId:f.scope.scopeId,action:'revoke'});f.company.publication.control({channelId:f.channelId,action:'revoke',keyId:null,generation:null});f.clock.set('2026-11-02T00:00:00.000Z');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'expired');assert.equal(f.sim.inspect(f.config.runId).portfolio.reservedCash,'0.000000');const attempts=f.store.all('SELECT * FROM investment_loop_attempts').length;f.loop.tick();assert.equal(f.store.all('SELECT * FROM investment_loop_attempts').length,attempts);assert.equal(f.loop.get(p.loopId).state,'blocked');
});
test('journal and stage failure roll back together before a new bounded attempt',t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');const version=f.sim.inspect(f.config.runId).version;f.loop.fault=point=>{if(point==='journal_before_stage')throw Error('fixture stage crash');};f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'pending');assert.equal(f.sim.inspect(f.config.runId).version,version);f.loop.fault=undefined;f.clock.set(new Date(Date.parse(f.clock.now())+31000).toISOString());f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'filled');assert.equal(f.sim.inspect(f.config.runId).benchmarkExecutions.length,1);
});
test('missing close marks produce one retained partial valuation, never repeated value at the same time',t=>{
 const f=loopFixture();t.after(f.close);const {p,o}=pending(f),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();const mark=f.occurrences(p.loopId).find(n=>n.stage==='mark'&&n.session===o.session)!;f.at(mark,1000);for(let i=0;i<3;i++){f.loop.tick();f.clock.set(new Date(Date.parse(f.clock.now())+31000).toISOString());}assert.equal(f.sim.inspect(f.config.runId).valuations.length,1);for(let i=0;i<5;i++)f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).valuations.length,1);assert.notEqual(f.sim.inspect(f.config.runId).valuations[0]!.snapshot.quality,'complete');
});

test('opening preserves a price-guard rejection while another independent order fills',t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f,2,true),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();const state=f.sim.inspect(f.config.runId);assert.equal(state.orders[orders[0]!]!.status,'rejected');assert.equal(state.orders[orders[0]!]!.reason,'price_guard');assert.equal(state.orders[orders[1]!]!.status,'filled');assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===opening.occurrence_id)?.state,'complete');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).version,state.version);
});
for(const claimFirst of [true,false])test(`${claimFirst?'claim':'scheduler'}-first cutoff preserves locked orders with active research and a queued continuation`,t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f,1,false,true);assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===o.occurrence_id)!.state,'running');assert.ok(f.company.discussions.group(f.group.group_id).deadline);assert.ok(f.store.get("SELECT 1 FROM conversation_requests WHERE status='queued'"));f.clock.set(o.expires_at);if(claimFirst){f.company.discussions.progress();assert.equal(f.company.claimWorkNext(),undefined);}f.loop.tick();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.sim.inspect(f.config.runId).lifecycle,'active');assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'pending');assert.equal(f.loop.get(p.loopId).state,'active');assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===o.occurrence_id)!.state,'missed');
});
test('scheduled committed team requires fresh prose consent before standing financial capture and filling',t=>{
 const f=loopFixture({committed:true});t.after(f.close);const {p,o,orders}=pending(f),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;
 // The settled facilitator adds prose after the earlier exact proposal/review consent.
 assert.throws(()=>f.company.publication.capture({channelId:f.channelId}),/new_derivative/);f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'pending');f.approvePublication();const jobs=f.store.all('SELECT * FROM investment_public_jobs').length;f.clock.set(new Date(Date.parse(f.clock.now())+31000).toISOString());f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'filled');assert.ok(f.store.all('SELECT * FROM investment_public_jobs').length>jobs);assert.equal(f.company.publication.health(f.channelId).unstaged,0);
});

test('failed automatic capture rolls back partial jobs, identities, sequences and capture high-water',t=>{
 const f=loopFixture();t.after(f.close);const {p}=pending(f);f.company.publication.capture({channelId:f.channelId});f.publicationEnvelope.maxQueueBytes=f.company.publication.health(f.channelId).bytes+1;f.approvePublication();
 const tables=['jobs','identities','sequences','captures'],snapshot=()=>tables.map(n=>f.store.all(`SELECT * FROM investment_public_${n} ORDER BY rowid`));f.sim.execute(f.config.runId,{type:'control',state:'paused'},'capture-quota-fixture');const before=snapshot();
 const failure=f.store.transaction(()=>f.loop['capture'](f.loop.get(p.loopId)));assert.match(failure!,/publication_backlog_budget/);assert.deepEqual(snapshot(),before);assert.ok(f.company.publication.health(f.channelId).unstaged>0);assert.equal(f.company.publication.health(f.channelId).newRiskBlocked,true);
});

test('publication-blocked second-cycle BUY does not erase an admitted risk-reducing SELL',t=>{
 const f=loopFixture();t.after(f.close);const {p,o}=pending(f),opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();const mark=f.occurrences(p.loopId).find(n=>n.stage==='mark'&&n.session===o.session)!;f.at(mark,1000);f.price('ACME',o.session,'regular_close','101');f.price(f.config.benchmark.instrument.id,o.session,'regular_close','51');f.loop.tick();
 const second=f.occurrences(p.loopId).filter(n=>n.stage==='research')[1]!;f.at(second);f.loop.tick();const author=f.claim(),proposals:PaperProposal[]=[],reviews:PaperReview[]=[];f.call(author,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});for(const side of ['SELL','BUY'] as const)proposals.push(f.call(author,'paper_propose',{...f.proposal,decisionId:`second-${side}`,action:side,order:{instrumentId:'ACME',side,quantity:'1',targetSession:second.session,priceGuard:side==='BUY'?'110':'90'}}).proposal);
 const prior=f.store.get<{message_id:string}>("SELECT message_id FROM discussion_contributions WHERE group_id=? AND kind='opening' ORDER BY revision LIMIT 1",f.group.group_id)!.message_id;f.call(author,'facilitate_discussion',{body:'Review the new risk and risk-reducing alternatives against the retained first-cycle result.',action:'discuss',turns:[{worker_id:f.scout.worker_id,prompt:'Review each exact second-cycle proposal independently.',contribution_ids:[prior],evidence_ids:[]}]});f.measured(author);f.company.discussions.progress();const reviewer=f.claim();f.call(reviewer,'read_discussion',{});f.call(reviewer,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});for(const proposal of proposals){f.call(reviewer,'paper_read_proposal',{proposalId:proposal.proposal_id});reviews.push(f.call(reviewer,'paper_review',{proposalId:proposal.proposal_id,proposalHash:proposal.proposal_hash,disposition:'approve',rationale:'Explicit synthetic independent second-cycle review',dissent:[],evidenceIds:[]}).review);}f.contribute(reviewer,'Explicit fixture response to the earlier proposal and original observations.',[prior]);f.measured(reviewer);f.company.discussions.progress();const submitter=f.claim();f.approvePublication();const ids:string[]=[];for(let i=0;i<proposals.length;i++){const proposal=proposals[i]!;f.call(submitter,'paper_read_proposal',{proposalId:proposal.proposal_id});f.company.publication.capture({channelId:f.channelId});ids.push(f.call(submitter,'paper_submit',{proposalId:proposal.proposal_id,proposalHash:proposal.proposal_hash,reviewId:reviews[i]!.review_id}).outcome.orderId);}f.call(submitter,'facilitate_discussion',{body:'Retain both independently reviewed outcomes.',action:'synthesize',turns:[]});f.measured(submitter);f.company.discussions.progress();
 f.company.publication.control({channelId:f.channelId,action:'revoke',keyId:null,generation:null});const nextOpen=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===second.session)!;f.at(nextOpen,1000);f.price('ACME',second.session,'regular_open','100');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[ids[0]!]!.status,'filled');assert.equal(f.sim.inspect(f.config.runId).orders[ids[1]!]!.status,'pending');assert.equal(f.occurrences(p.loopId).find(n=>n.occurrence_id===nextOpen.occurrence_id)!.state,'pending');
});

test('injected benchmark reducer rejection retains its journal and the independent successful fill',t=>{
 const f=loopFixture();t.after(f.close);const {p,o,orders}=pending(f),market=f.company.investmentTeam.market(f.company.investmentTeam.scope(f.scope.scopeId)),execute=market.execute.bind(market);t.mock.method(market,'execute',(...[run,command,request]:Parameters<typeof market.execute>)=>command.type==='benchmark_open'?f.sim.execute(run,{...command,session:f.input.sessions[1]!},request):execute(run,command,request));t.mock.method(f.company.investmentTeam,'market',()=>market);
 const opening=f.occurrences(p.loopId).find(n=>n.stage==='open'&&n.session===o.session)!;f.at(opening,1000);f.price('ACME',o.session,'regular_open','100');f.price(f.config.benchmark.instrument.id,o.session,'regular_open','50');f.loop.tick();assert.equal(f.sim.inspect(f.config.runId).orders[orders[0]!]!.status,'filled');const stage=f.occurrences(p.loopId).find(n=>n.occurrence_id===opening.occurrence_id)!;assert.equal(stage.state,'pending');assert.match(stage.result!,/benchmark_not_due/);assert.equal(f.sim.inspect(f.config.runId).benchmarkExecutions.length,0);
});
