import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {loopFixture} from '../dist/test/fixtures/investment-loop/support.js';
import {Dispatcher} from '../dist/src/control/dispatcher.js';
import {createHttpServer} from '../dist/src/http/server.js';
for(const width of [390,1440])test(`exact finite run preview, stale response and owner pause/stop (${width}px)`,async t=>{
 const f=loopFixture(),dispatcher=new Dispatcher(f.company,f.bounded),http=createHttpServer(f.company,dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:process.env.BOTSQUAD_BROWSER_CHANNEL??'chrome',headless:true}),page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await http.close();await dispatcher.stop();await f.close();assert.deepEqual(errors,[]);});await page.goto(`http://127.0.0.1:${http.server.address().port}/investment-run`);await page.waitForFunction(()=>document.querySelector('[name=scopeId]').options.length>1);await page.locator('[name=scopeId]').selectOption(f.scope.scopeId);await page.locator('[name=sessions]').fill(f.input.sessions.join(', '));for(const [key,value] of Object.entries(f.input)){if(typeof value==='number')await page.locator(`[name=${key}]`).fill(String(value));if(['dailyLimits','runLimits'].includes(key))for(const [k,v] of Object.entries(value))await page.locator(`[name=${key}_${k}]`).fill(String(k==='maxCostMicros'?v/1000000:v));}
 let entered,release;const seen=new Promise(r=>entered=r),ready=new Promise(r=>release=r);await page.route('**/api/investment-run/preview',async route=>{const response=await route.fetch();entered();await ready;await route.fulfill({response});},{times:1});await page.locator('#preview-button').click();await seen;await page.locator('[name=maxStageAttempts]').fill('2');release();await page.waitForResponse(r=>r.url().endsWith('/preview'));assert.equal(await page.locator('#preview-panel').isVisible(),false);await page.locator('#preview-button').click();await page.locator('#preview-panel').waitFor({state:'visible'});assert.equal(f.store.all('SELECT * FROM investment_loop_requests').length,0);await page.locator('#confirm').check();await page.locator('#start').click();await page.getByText('Exact run started. Work remains bounded by the displayed calendar and current authority.',{exact:true}).waitFor();await page.getByRole('button',{name:'Pause investment run',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#runs h2').textContent.startsWith('paused'));await page.getByRole('button',{name:'Stop investment run',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#runs h2').textContent.startsWith('stopped'));assert.equal(f.runtime.calls.length,0);assert.equal(f.store.all('SELECT * FROM investment_loop_executions').length,0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));mkdirSync('/private/tmp/botsquad-inv09-browser',{recursive:true});await page.screenshot({path:`/private/tmp/botsquad-inv09-browser/owner-${width}.png`,fullPage:true});
});
