import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {teamFixture} from './fixtures/investment-team/support.js';
import {CommittedTeamPublicationSource,type TeamPublicationSelection} from '../src/control/publication/team-source.js';
import {PublicationService} from '../src/control/publication/service.js';
import type {PaperProposal,PaperReview} from '../src/domain/investment-team/types.js';
function source(f:ReturnType<typeof teamFixture>,runtimeEvidence:TeamPublicationSelection['runtimeEvidence']='fake_runtime_fixture'){
 f.clock.set(new Date(Math.max(Date.now()+1000,Date.parse(f.clock.now()))).toISOString());const description=structuredClone(f.description);for(const p of f.envelope.participants){description.workers[p.workerId]={name:p.name,role:'Investment participant',responsibilities:[p.responsibility],status:'unavailable'};}
 const selection:TeamPublicationSelection={groupId:f.group.group_id,runtimeEvidence,evidenceRights:{[f.evidence.evidence_id]:'owner_authored'}};
 const source=new CommittedTeamPublicationSource('committed-team','Committed synthetic trial',f.store,f.clock,'fixture-owner',f.config.runId,description,selection);
 const service=new PublicationService(f.store,{sources:[source],destinations:[{id:'committed-destination',title:'Isolated fixture',origin:'http://127.0.0.1:9999',fixtureLoopback:true,publisherId:'fixture',generation:'1',keyId:'no-key'}],clock:f.clock});
 return {source,service,selection,envelope:{...f.publicationEnvelope,sourceId:source.id,destinationId:'committed-destination',participants:source.participants,eventTypes:[...f.publicationEnvelope.eventTypes,'discussion.opened','discussion.contribution','discussion.closed'] as typeof f.publicationEnvelope.eventTypes}};
}
function deliberation(f:ReturnType<typeof teamFixture>){f.grant();f.control('start');const [a,b]=f.pair();f.call(a,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});const {proposal:p}=f.call(a,'paper_propose',f.proposal) as {proposal:PaperProposal};const contribution=f.contribute(a,'Fixture author: wait for evidence before risking capital.');f.finish(a);f.call(b,'read_discussion',{});f.call(b,'read_group_record',{record_id:f.evidence.evidence_id,offset:0});f.call(b,'paper_read_proposal',{proposalId:p.proposal_id});const {review:r}=f.call(b,'paper_review',{proposalId:p.proposal_id,proposalHash:p.proposal_hash,disposition:'approve',rationale:'Fixture independent review preserves opportunity-cost dissent.',dissent:['Waiting could miss a recovery.'],evidenceIds:[]}) as {review:PaperReview};f.contribute(b,'Fixture reviewer: waiting has opportunity cost.',[contribution.message_id]);f.finish(b);return {p,r,contributionId:contribution.message_id as string};}
test('committed public records preserve exact author, independent review, reply and opaque source attribution',async t=>{
 const f=teamFixture();t.after(()=>f.close());const {p,r}=deliberation(f),s=source(f),preview=s.service.preview(s.envelope),events=preview.material.events.map(x=>x.event),decision=events.find(e=>e.type==='decision.published');assert.ok(decision?.type==='decision.published');assert.equal(decision.payload.proposal.rationale,JSON.parse(p.narrative).rationale);assert.equal(decision.payload.review.rationale,r.rationale);const contributions=events.filter(e=>e.type==='discussion.contribution');assert.deepEqual(contributions.map(e=>e.payload.ordinal),['1','2']);assert.equal(contributions[1]!.payload.replyTo,contributions[0]!.payload.contributionId);assert.notEqual(decision.actor.kind==='worker'?decision.actor.workerId:null,decision.payload.review.reviewerId);assert.equal(preview.material.contents.length,1);assert.equal(Buffer.from(preview.material.contents[0]!.base64,'base64').toString(),f.evidence.content);const publicBytes=JSON.stringify(events);for(const value of [f.atlas.worker_id,f.scout.worker_id,f.group.group_id,p.execution_id,r.execution_id])assert.ok(!publicBytes.includes(value));assert.match(publicBytes,/fake runtime records/);s.service.consent({previewId:preview.id,digest:preview.digest});assert.ok(f.store.all('SELECT * FROM investment_public_jobs').length>0);
});
test('a fake runtime cannot be relabelled as actual employee evidence',async t=>{const f=teamFixture();t.after(()=>f.close());deliberation(f);const s=source(f,'recorded_employee');assert.throws(()=>s.service.preview(s.envelope),/fixture_employee_claim/);});
test('publication requires explicit selected evidence rights and fresh group sharing at delivery',async t=>{
 const f=teamFixture();t.after(()=>f.close());deliberation(f);const s=source(f);delete s.selection.evidenceRights[f.evidence.evidence_id];assert.throws(()=>s.service.preview(s.envelope),/evidence_rights_required/);s.selection.evidenceRights[f.evidence.evidence_id]='owner_authored';const p=s.service.preview(s.envelope);s.service.consent({previewId:p.id,digest:p.digest});f.company.discussions.withdrawEvidence({group_id:f.group.group_id,evidence_id:f.evidence.evidence_id});assert.throws(()=>s.source.checkRights({sourceHash:p.sourceHash,events:p.material.events,contents:p.material.contents.map(c=>({...c,bytes:Buffer.from(c.base64,'base64')}))},f.clock.now()),/sharing_withdrawn/);assert.equal(f.store.all('SELECT * FROM investment_public_attempts').length,0);
});
test('later owner notes do not create gaps or renumber already previewed public contributions',async t=>{const f=teamFixture();t.after(()=>f.close());deliberation(f);const s=source(f),first=s.service.preview(s.envelope);f.company.discussions.note({group_id:f.group.group_id,kind:'note',body:'Owner note is not an employee contribution',receipt_key:randomUUID()});f.clock.set(new Date(Math.max(Date.now()+1000,Date.parse(f.clock.now()))).toISOString());const later=s.service.preview(s.envelope);assert.deepEqual(later.material.events.filter(e=>e.event.type==='discussion.contribution'),first.material.events.filter(e=>e.event.type==='discussion.contribution'));});
import {generateKeyPairSync} from 'node:crypto';
import {mkdtempSync,chmodSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {ServiceKeyRing,FixedPublicationTransport} from '../src/control/publication/transport.js';
const receiverRoot=process.env.INV07_RECEIVER_ROOT;
for(const scenario of ['openings','withdrawal','full','replacement'] as const)test(`actual isolated receiver: committed team ${scenario}`,{skip:!receiverRoot},async t=>{
 const f=teamFixture();t.after(()=>f.close());if(scenario==='full'||scenario==='replacement')fullGroup(f,scenario==='replacement');else deliberation(f);const projection=source(f);const {config}=await import(pathToFileURL(join(receiverRoot!,'dist/src/config.js')).href),{createReceiver}=await import(pathToFileURL(join(receiverRoot!,'dist/src/http.js')).href);const dir=mkdtempSync(join(tmpdir(),'botsquad-inv08-receiver-'));chmodSync(dir,0o700);const cfg=config({enabled:true,dataDir:dir,authority:'127.0.0.1',port:0,minFreeBytes:1048576}),receiver=await createReceiver(cfg,{now:()=>Math.floor(Date.parse(f.clock.now())/1000)});t.after(async()=>{await receiver.close();rmSync(dir,{recursive:true,force:true});});cfg.authority=`127.0.0.1:${receiver.server.address().port}`;
 const key=generateKeyPairSync('ed25519'),keys=new ServiceKeyRing(new Map([['fixture-key',{key:key.privateKey,notBefore:0,notAfter:2000000000,enabled:true}]])),destination={id:'committed-destination',title:'Disposable receiver',origin:`http://${cfg.authority}`,fixtureLoopback:true,publisherId:'fixture-publisher',generation:'1',keyId:'fixture-key'};let sends=0;const wire=new FixedPublicationTransport(),service=new PublicationService(f.store,{sources:[projection.source],destinations:[destination],keys,transport:{send:async(d,m)=>{sends++;return wire.send(d,m);}},clock:f.clock});const preview=service.preview(projection.envelope),{channelId}=service.consent({previewId:preview.id,digest:preview.digest}),run=preview.material.events[0]!.event;receiver.db.authorize({publisherId:destination.publisherId,keyId:destination.keyId,experimentId:run.experimentId,runId:run.runId,eventTypes:projection.envelope.eventTypes,contentTypes:projection.envelope.contentTypes,publicationPolicyVersion:run.publicationPolicyVersion,expiresAt:projection.envelope.expiresAt,enabled:true,generation:'1',writesPerMinute:60,bytesPerDay:1048576},{publicKey:key.publicKey.export({type:'spki',format:'pem'}).toString(),notBefore:0,notAfter:2000000000},f.clock.now());
 if(scenario==='withdrawal'){f.company.discussions.withdrawEvidence({group_id:f.group.group_id,evidence_id:f.evidence.evidence_id});await assert.rejects(service.deliver({channelId}),/sharing_withdrawn/);assert.equal(sends,0);assert.equal(f.store.all('SELECT * FROM investment_public_attempts').length,0);return;}
 for(let n=0;n<20&&service.health(channelId).pending;n++)await service.deliver({channelId});assert.equal(service.health(channelId).pending,0,JSON.stringify(service.health(channelId)));const response=await fetch(`${destination.origin}/api/experiments/v1/experiments/${run.experimentId}/runs/${run.runId}/status`);assert.equal(response.status,200);assert.ok(sends>0);
});
function fullGroup(f:ReturnType<typeof teamFixture>,replaceAuthor=false){const d=deliberation(f),facilitator=f.claim();f.call(facilitator,'facilitate_discussion',{body:'Fixture discussion has enough evidence to synthesize.',action:'synthesize',turns:[]});f.finish(facilitator);const synthesis=f.claim();const body={recommendation:'Fixture HOLD while evidence is incomplete.',alternatives:'A small guarded paper buy.',supporting_findings:'Owner-supplied synthetic premise only.',challenges_addressed:'The opportunity cost remains possible.',dissent_and_risks:'Waiting can miss a recovery.',missing_evidence_and_confidence:'No observed market data; limited confidence.',next_actions_and_approvals:'Separate exact public consent remains required.',contribution_ids:[d.contributionId],evidence_ids:[]};const draft=f.call(synthesis,'submit_synthesis',body);f.finish(synthesis);const reviewer=f.claim();let reviewed:string|undefined;if(replaceAuthor){f.company.finish(reviewer.execution.execution_id,{status:'failed',settled:true,error:'Fixture independent review unavailable; source preserves failure'});f.company.discussions.progress();f.company.discussions.control({group_id:f.group.group_id,action:'finish',receipt_key:randomUUID(),synthesizer_id:f.scout.worker_id});}else{f.call(reviewer,'read_group_record',{record_id:draft.message_id,offset:0});reviewed=f.contribute(reviewer,'Fixture review addresses the actual draft and retains uncertainty.',[draft.message_id]).message_id;f.finish(reviewer);}const finalizer=f.claim();f.call(finalizer,'read_group_record',{record_id:draft.message_id,offset:0});f.call(finalizer,'submit_synthesis',{...body,contribution_ids:[draft.message_id,...reviewed?[reviewed]:[]]});f.finish(finalizer);f.company.discussions.progress();return {draft,finalizer};}
for(const replacement of [false,true])test(`full group projects draft review and final synthesis with ${replacement?'replacement':'same'} author and exact predecessor links`,async t=>{
 const f=teamFixture();t.after(()=>f.close());fullGroup(f,replacement);const s=source(f),p=s.service.preview(s.envelope),events=p.material.events.map(x=>x.event),artifacts=events.filter(e=>e.type==='artifact.published').filter(e=>e.payload.title.includes('recommendation')),closure=events.find(e=>e.type==='discussion.closed');assert.equal(artifacts.length,2);assert.ok(closure?.type==='discussion.closed');if(replacement){assert.notEqual(artifacts[0]!.payload.artifactId,artifacts[1]!.payload.artifactId);assert.ok(artifacts[1]!.payload.relationships.some(r=>r.id===artifacts[0]!.payload.artifactId&&r.relation==='supersedes'));}else{assert.equal(artifacts[1]!.payload.version,2);assert.equal(artifacts[1]!.payload.supersedes?.id,artifacts[0]!.payload.artifactId);assert.ok(events.some(e=>e.type==='discussion.contribution'&&e.payload.evidence.some(r=>r.id===artifacts[0]!.payload.artifactId)));}const publicContent=p.material.contents.map(c=>Buffer.from(c.base64,'base64').toString()).join('\n');for(const w of [f.atlas.worker_id,f.scout.worker_id])assert.ok(!publicContent.includes(w));f.control('stop');assert.throws(()=>f.control('extend'),/cannot reopen/);assert.throws(()=>f.control('finish'),/cannot reopen/);
});
test('standalone admitted market evidence has no invented public mapping in pinned v1',async t=>{const f=teamFixture();t.after(()=>f.close());const target=f.config.calendar.sessions.find(s=>Date.parse(s.open)>Date.parse(f.clock.now()))!;f.clock.set(new Date(Date.parse(target.open)+1000).toISOString());const evidence=f.price('ACME',target.date,'regular_open','100');f.proposal.marketObservationIds.push(evidence.id as never);deliberation(f);const s=source(f);assert.throws(()=>s.service.preview(s.envelope),/standalone_price_evidence_unsupported_v1/);});
import {hire,objective} from './helpers.js';
import {Company} from '../src/control/company.js';
import type {Worker} from '../src/domain/model.js';
test('a scoped research-only participant can publish without widening frozen author or reviewer authority',async t=>{
 const f=teamFixture();t.after(()=>f.close());f.company.assignObjective(objective);const task=f.company.claimNext()!,third=f.company.callTool(task.context,randomUUID(),'hire_worker',{...hire,display_name:'Sage',title:'Product Manager',mission:'Fixture optional research'}) as Worker;f.company.finish(task.execution.execution_id,{status:'completed',summary:'Synthetic fixture roster only'});const participants=[...f.envelope.participants,{workerId:third.worker_id,name:'Fixture researcher',responsibility:'Read scoped evidence without paper authority'}];const group=f.company.discussions.create({topic:'Three-person fixture',desired_output:'Independent review and optional research',constraints:'No real execution or price claims',participant_ids:participants.map(p=>p.workerId),facilitator_id:f.atlas.worker_id,synthesizer_id:f.atlas.worker_id,organize_with_atlas:false,allow_incomplete:true,allow_research:true,receipt_key:randomUUID()});const scoped={...f,group,envelope:{...f.envelope,groupId:group.group_id,participants}},s=source(scoped);s.selection.evidenceRights={};const first=s.service.preview(s.envelope);const identities=s.source.participants;assert.equal(identities.length,3);assert.equal(f.config.authorization.authors.includes(third.worker_id),false);assert.equal(f.config.authorization.reviewers.includes(third.worker_id),false);
 const company=new Company(f.store,f.dir,process.cwd(),'fake',undefined,undefined,{sources:[s.source],clock:f.clock});company.mandates.clock={now:()=>Date.parse(f.clock.now())};const grant=company.investmentTeam.preview({...scoped.envelope,publicationChannelId:first.channelId});company.investmentTeam.consent({scopeId:grant.scopeId,digest:grant.digest});assert.ok(s.service.preview(s.envelope).material.events.some(e=>e.event.type==='discussion.opened'));
 assert.ok(first.material.events.some(e=>e.event.type==='team.published'&&e.event.payload.workers.length===3));
});
