import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {fixture} from '../dist/test/helpers.js';
import {createHttpServer} from '../dist/src/http/server.js';
test('owner browser creates passive mandate, admits visibly simulated evidence and controls schedules',async t=>{
  const f=fixture();f.company.initializeCEO();f.company.pause(true);f.dispatcher.start();const http=createHttpServer(f.company,f.dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await http.close();await f.close();assert.deepEqual(errors,[]);});const dir=join(process.cwd(),'.validation/prompt09/browser');mkdirSync(dir,{recursive:true});await page.goto(`http://127.0.0.1:${http.server.address().port}`);await page.getByText('Connected to headquarters',{exact:true}).waitFor();await page.locator('[data-tab=mandates]').click();await page.locator('#new-mandate').click();await page.locator('#mandate-form [name=title]').fill('Internal product strategy');await page.locator('#mandate-form [name=objective]').fill('Compare safe internal quality and adoption work.');await page.getByRole('button',{name:'Save passive draft',exact:true}).click();await page.locator('[data-mandate-action=activate]').waitFor();assert.equal(f.runtime.calls.length,0);assert.equal(f.company.snapshot().tasks.length,0);
  await page.locator('#add-observation').click();await page.locator('#observation-form [name=mode]').selectOption('simulated_fixture');for(const [key,value] of Object.entries({name:'SIMULATED baseline',source:'fixture://browser/test',provenance:'Owner-entered synthetic test',body:'<img src=x onerror="window.injected=1"> SIMULATED: no real revenue result.',limitations:'Not live metrics',missingness:'Business outcome unknown'}))await page.locator(`#observation-form [name=${key}]`).fill(value);await page.getByRole('button',{name:'Admit labelled observation',exact:true}).click();await page.locator('.evidence-mode.simulated').waitFor();assert.equal(await page.locator('#view img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);await page.screenshot({path:join(dir,'labelled-observation.png')});
  await page.locator('[data-mandate-action=activate]').click();await page.locator('[data-mandate-action=pause]').waitFor();assert.equal(f.runtime.calls.length,0);await page.locator('#new-review').click();await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.locator('[data-edit-review]').waitFor();assert.equal(f.company.store.get('SELECT count(*) n FROM review_schedules').n,1);await page.locator('[data-edit-review]').click();await page.locator('#review-form [name=purpose]').fill('Changed future purpose');await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.getByRole('heading',{name:'Changed future purpose active'}).waitFor();assert.equal(f.company.store.get('SELECT version FROM review_schedules').version,2);
  await page.locator('[data-review-control=pause]').click();await page.locator('[data-review-control=resume]').waitFor();await page.locator('[data-review-control=cancel]').click();await page.getByRole('heading',{name:'Changed future purpose cancelled'}).waitFor();await page.locator('[data-mandate-action=stop]').click();await page.getByRole('heading',{name:'Internal product strategy stopped'}).waitFor();await page.screenshot({path:join(dir,'stopped-history.png')});assert.equal(f.runtime.calls.length,0);
});
