import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,until,hire,objective} from './helpers.js';
import {Company} from '../src/control/company.js';
import {Store} from '../src/persistence/store.js';
import {wallClockInstant,nextReviewInstant} from '../src/control/company-clock.js';
import type {Mandate,ReviewOccurrence,OperatingCycle} from '../src/domain/mandates.js';
import type {ExecutionContext} from '../src/control/company.js';
import {join} from 'node:path';

function setup(envelope:Record<string,unknown>={}){const f=fixture(),atlas=f.company.initializeCEO();let time=Date.parse('2026-10-05T18:00:00Z');f.company.mandates.clock={now:()=>time};
  const m=f.company.mandates.create({title:'A useful company',objective:'Improve sustainable success',success_criteria:'Evidence-backed internal choices',stop_criteria:'Stop on limits or lack of permission',constraints:'No external action',resources:'Internal analysis only',coordinator_id:atlas.worker_id,envelope:{min_interval_seconds:30,...envelope}});
  return {...f,m,atlas,advance(ms:number){time+=ms;},time:()=>time};}
const observe=(f:ReturnType<typeof setup>,overrides:Record<string,unknown>={})=>f.company.mandates.admitObservation({mandate_id:f.m.mandate_id,cycle_id:null,initiative_id:null,mode:'simulated_fixture',name:'SIMULATED retention',value:'30',unit:'percent',observed_at:new Date(f.time()-60000).toISOString(),period:'A simulated prior week',source:'fixture://acceptance/baseline',provenance:'Trusted explicitly simulated test input',limitations:'Not production; no observed real improvement',missingness:'Costs unknown',body:'SIMULATED: retention is 30 percent; acquisition and quality are alternative hypotheses.',...overrides});
const schedule=(f:ReturnType<typeof setup>,overrides:Record<string,unknown>={})=>f.company.mandates.saveOwnerSchedule({mandate_id:f.m.mandate_id,schedule_id:null,purpose:'Review attributable evidence',initiative_id:null,due_at:new Date(f.time()+60000).toISOString(),recurrence_kind:'once',interval_seconds:null,local_time:null,occurrence_limit:1,end_at:new Date(f.time()+3600000).toISOString(),...overrides});
function activate(f:ReturnType<typeof setup>){f.company.mandates.control({mandate_id:f.m.mandate_id,action:'activate'});return f.company.mandates.mandate(f.m.mandate_id);}
function claim(f:ReturnType<typeof setup>){const x=f.company.claimWorkNext();assert.ok(x&&x.origin==='conversation');f.company.conversations.context(x.context);return x;}
function decision(f:ReturnType<typeof setup>,context:ExecutionContext,refs:string[]=[],overrides:Record<string,unknown>={}){return f.company.mandates.callTool(context,`decision-${Math.random()}`,'record_strategic_decision',{initiative_id:null,disposition:'continue',recommendation:'Investigate quality and retention',rationale:'Compare outcomes with missing costs',alternatives:'Quality improvements versus acquisition analysis',evidence_ids:refs,contrary_evidence:'Small sample and uncertain attribution',unknowns:'Actual business performance',missing_evidence:refs.length?null:'No admitted evidence yet; this is a hypothesis',...overrides}) as {decision_id:string};}
function closeCycle(f:ReturnType<typeof setup>,stop=false){const x=claim(f);decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Bounded assessment; evidence unknown.',stop});f.company.finish(x.execution.execution_id,{status:'completed',settled:true,summary:'Committed'});f.company.mandates.progress();return x;}
function occurrences(f:ReturnType<typeof setup>){return f.store.all<ReviewOccurrence>('SELECT * FROM review_occurrences ORDER BY rowid');}

test('mandate draft is passive, activation explicit, review ownership differs from direct replies and tasks',async()=>{const f=setup();try{
  assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);activate(f);const x=claim(f);
  assert.equal(x.execution.task_id,null);assert.equal(f.company.conversations.session(x.execution.session_id).tool_schema,'mandate-review-v1');assert.equal(f.company.conversations.list().items.length,0);
  assert.throws(()=>f.company.conversations.send({conversation_id:x.request.conversation_id,body:'Fake reply trigger',request_reply:true,receipt_key:'abcdefghijklmnop'}),/dedicated mandate/);
  for(const name of ['assign_task','hire_worker','research_search','grant_research','submit_reply','create_repository'])assert.throws(()=>f.company.mandates.callTool(x.context,name,name,{}),/outside mandate/);
  assert.throws(()=>f.store.run("UPDATE mandates SET envelope='{}' WHERE mandate_id=?",f.m.mandate_id),/authority/);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,0);
}finally{await f.close();}});

test('grounding requires full same-execution originals, denies invented/cross-mandate/future/withdrawn evidence',async()=>{const f=setup();try{const o=observe(f);assert.throws(()=>observe(f,{observed_at:new Date(f.time()+1).toISOString()}),/Future/);activate(f);const x=claim(f);
  assert.throws(()=>decision(f,x.context,[o.observation_id]),/complete current original/);assert.throws(()=>decision(f,x.context,['observation_invented']),/outside/);
  const read=f.company.mandates.callTool(x.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0}) as {fully_delivered:boolean;content:string};assert.equal(read.fully_delivered,true);assert.match(read.content,/simulated_fixture/);assert.match(read.content,/observed_at/);decision(f,x.context,[o.observation_id]);
  const other=f.company.mandates.create({title:'Other',objective:'Private',success_criteria:'Private',stop_criteria:'Stop',constraints:'Private',resources:'Internal',coordinator_id:f.atlas.worker_id,envelope:{}});const foreign=observe(f,{mandate_id:other.mandate_id});assert.throws(()=>f.company.mandates.callTool(x.context,'foreign','read_mandate_record',{record_id:foreign.observation_id,offset:0}),/outside/);
  f.company.mandates.withdrawObservation({observation_id:o.observation_id});assert.throws(()=>decision(f,x.context,[o.observation_id]),/withdrawn/);assert.throws(()=>f.store.run("UPDATE mandate_observations SET mode='real_read_only' WHERE observation_id=?",o.observation_id),/immutable/);
}finally{await f.close();}});

test('decisions are append-only, missing evidence explicit, committed outcome idempotent',async()=>{const f=setup();try{activate(f);const x=claim(f);assert.throws(()=>decision(f,x.context,[],{missing_evidence:null}),/explicitly/);const d=decision(f,x.context);assert.throws(()=>f.store.run("UPDATE strategic_decisions SET rationale='rewrite' WHERE decision_id=?",d.decision_id),/immutable/);
  const payload={summary:'Stop without evidence, within owner stop criteria',stop:true};const result=f.company.mandates.callTool(x.context,'finish','complete_cycle',payload);assert.deepEqual(f.company.mandates.callTool(x.context,'finish','complete_cycle',payload),result);assert.throws(()=>f.company.mandates.callTool(x.context,'after','propose_initiative',{title:'more'}),/committed/);
  f.company.finish(x.execution.execution_id,{status:'completed',summary:'Finished'});f.company.mandates.progress();assert.equal(f.company.mandates.mandate(f.m.mandate_id).status,'stopped');
}finally{await f.close();}});

test('one-time clock: before/exactly/after due, overlap hold-one, stable occurrence and no duplicate callback',async()=>{const f=setup();try{activate(f);schedule(f);f.company.mandates.tick();assert.equal(occurrences(f).length,0);f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'held');closeCycle(f);assert.equal(occurrences(f)[0]!.state,'queued');f.company.mandates.tick();f.advance(1);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);
}finally{await f.close();}});

test('recurring clock coalesces missed times without a model burst and ends at occurrence count',async()=>{const f=setup();try{activate(f);schedule(f,{recurrence_kind:'interval',interval_seconds:60,occurrence_limit:4});f.advance(180000);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(occurrences(f)[0]!.missed_count,2);assert.equal(occurrences(f)[0]!.state,'held');f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.missed_count,3);assert.equal(f.store.get<{status:string}>('SELECT status FROM review_schedules')!.status,'exhausted');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);
}finally{await f.close();}});

test('schedule edits retain versions, invalidate old due callbacks, cancellation is terminal',async()=>{const f=setup();try{activate(f);const s=schedule(f);f.advance(60000);f.company.mandates.tick();const changed=schedule(f,{schedule_id:s.schedule_id,due_at:new Date(f.time()+120000).toISOString(),recurrence_kind:'interval',interval_seconds:60,occurrence_limit:3});assert.equal(changed.version,2);assert.equal(occurrences(f)[0]!.state,'superseded');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM review_schedule_versions')!.n,2);f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});assert.throws(()=>f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'resume'}),/resurrected/);f.advance(300000);f.company.mandates.tick();assert.equal(occurrences(f).length,1);
}finally{await f.close();}});

test('global, mandate and schedule pause retain due work and resume without duplication',async()=>{for(const kind of ['global','mandate','schedule']){const f=setup();try{activate(f);const s=schedule(f);closeCycle(f);if(kind==='global')f.company.pause(true);if(kind==='mandate')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'pause'});if(kind==='schedule')f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'pause'});f.advance(60000);f.company.mandates.tick();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);
  if(kind==='global')f.company.pause(false);if(kind==='mandate')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'resume'});if(kind==='schedule')f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'resume'});f.company.mandates.tick();f.company.mandates.tick();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(occurrences(f).length,1);
}finally{await f.close();}}});

test('disabled coordinator, revoked communication, cycle limit and unknown provider fence deny due review',async()=>{for(const kind of ['disabled','capability','limit','unknown']){const f=setup(kind==='limit'?{max_cycles:1}:{});try{activate(f);schedule(f);closeCycle(f);if(kind==='disabled')f.store.run('UPDATE workers SET enabled=0 WHERE worker_id=?',f.atlas.worker_id);if(kind==='capability')f.store.run("UPDATE workers SET capability_profile='[]' WHERE worker_id=?",f.atlas.worker_id);if(kind==='unknown'){const prior=f.store.get<{execution_id:string}>('SELECT execution_id FROM executions')!;f.store.run('INSERT INTO execution_runtime_attempts VALUES (?,1)',prior.execution_id);}f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'blocked');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);
}finally{await f.close();}}});

test('stop prevents queued work and stale timers from reviving a mandate',async()=>{const f=setup();try{activate(f);schedule(f);f.company.mandates.control({mandate_id:f.m.mandate_id,action:'stop'});f.advance(120000);f.company.mandates.tick();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{status:string}>('SELECT status FROM review_schedules')!.status,'cancelled');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);
}finally{await f.close();}});

test('Vancouver DST uses first repeated minute and first valid post-gap minute; interval uses elapsed seconds',()=>{
  assert.equal(new Date(wallClockInstant('2026-03-08','02:30','America/Vancouver')).toISOString(),'2026-03-08T10:00:00.000Z');
  assert.equal(new Date(wallClockInstant('2026-11-01','01:30','America/Vancouver')).toISOString(),'2026-11-01T08:30:00.000Z');
  assert.equal(new Date(nextReviewInstant(Date.parse('2026-03-07T10:30:00Z'),{kind:'daily',local_time:'02:30'},'America/Vancouver')!).toISOString(),'2026-03-08T10:00:00.000Z');
  assert.equal(nextReviewInstant(1000,{kind:'interval',seconds:60},'America/Vancouver'),61000);
});

test('crash after occurrence commit, before claim: reopening safely queues exactly one review',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.fault=point=>{if(point==='after_occurrence_before_claim')throw new Error('injected crash');};assert.throws(()=>f.company.mandates.tick(),/injected/);assert.equal(occurrences(f)[0]!.state,'due');f.store.close();const store=new Store(join(f.dir,'company.sqlite')),company=new Company(store,f.dir,process.cwd(),'fake');company.mandates.clock={now:f.time};company.recover();company.mandates.progress();company.mandates.progress();assert.equal(store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(store.get<{state:string}>('SELECT state FROM review_occurrences')!.state,'queued');assert.deepEqual(store.all('PRAGMA foreign_key_check'),[]);store.close();}finally{await f.dispatcher.stop();}});

test('fault before next-time commit rolls back occurrence and consumption atomically',async()=>{const f=setup();try{activate(f);schedule(f);f.advance(60000);f.company.mandates.fault=point=>{if(point==='after_next_calculation_before_commit')throw new Error('injected');};assert.throws(()=>f.company.mandates.tick(),/injected/);assert.equal(occurrences(f).length,0);assert.equal(f.store.get<{consumed:number}>('SELECT consumed FROM review_schedules')!.consumed,0);f.company.mandates.fault=undefined;f.company.mandates.tick();assert.equal(occurrences(f).length,1);}finally{await f.close();}});

test('known review failure backs off boundedly; ambiguous invocation blocks without retry',async()=>{for(const unknown of [false,true]){const f=setup();try{activate(f);const x=claim(f);if(unknown)f.company.conversations.event(x.context,'runtime_turn_starting',{context_chars:100});f.company.finish(x.execution.execution_id,{status:'failed',settled:!unknown,error:'Injected known/unknown failure'});f.company.mandates.progress();const c=f.store.get<OperatingCycle>('SELECT * FROM operating_cycles')!;assert.equal(c.state,unknown?'blocked':'waiting');assert.equal(c.failures,unknown?0:1);f.advance(30000);f.company.mandates.progress();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM mandate_turns')!.n,unknown?1:2);}finally{await f.close();}}});

test('real dispatcher substrate executes two simulated-runtime cycles, second initiated only by persisted clock',async()=>{const f=setup();try{let completed=0;f.runtime.gate=async input=>{if(input.mode!=='conversation')throw new Error('Unexpected Task');const ctx=input.context as {mode:string;mandate:Mandate};assert.equal(ctx.mode,'mandate_review');decision(f,{executionId:input.execution.execution_id,workerId:input.worker.worker_id,workspacePath:input.worker.workspace_path});if(!completed)schedule(f);await input.callTool('close','complete_cycle',{summary:'Bounded simulated-runtime review',stop:completed++>0});return {status:'completed',summary:'Committed',settled:true};};activate(f);f.dispatcher.start();await until(()=>f.store.get<{n:number}>("SELECT count(*) n FROM operating_cycles WHERE state='closed'")!.n===1);assert.equal(f.runtime.calls.length,1);f.advance(60000);f.dispatcher.kick();await until(()=>f.company.mandates.mandate(f.m.mandate_id).status==='stopped');assert.equal(f.runtime.calls.length,2);assert.equal(occurrences(f)[0]!.state,'completed');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,0);}finally{await f.close();}});

test('idle company clock causes no model or research work',async()=>{const f=setup();try{f.dispatcher.start();for(let i=0;i<10;i++){f.advance(60000);f.dispatcher.kick();await new Promise(r=>setTimeout(r,5));}assert.equal(f.runtime.calls.length,0);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_operations')!.n,0);}finally{await f.close();}});

test('mandate internal Task enforces reporting hierarchy and separate decision link',async()=>{const f=setup();try{const parent=f.company.assignObjective(objective),t=f.company.claimNext()!;const scout=f.company.callTool(t.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(t.execution.execution_id,{status:'completed',summary:'Roster setup'});assert.equal(f.company.task(parent.task_id).status,'completed');activate(f);const x=claim(f),d=decision(f,x.context);assert.throws(()=>f.company.mandates.callTool(x.context,'bad','assign_internal_task',{decision_id:d.decision_id,worker_id:f.atlas.worker_id,objective:'Internal',acceptance_criteria:'Report',constraints:'No external action'}),/direct reports/);const assigned=f.company.mandates.callTool(x.context,'task','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Compare internal quality strategies',acceptance_criteria:'A source-labelled report',constraints:'No external action'}) as {task_id:string};assert.ok(assigned.task_id);assert.equal(f.company.task(assigned.task_id).parent_task_id,null);assert.equal(f.company.task(assigned.task_id).created_execution_id,x.execution.execution_id);assert.throws(()=>f.company.mandates.callTool(x.context,'premature','complete_cycle',{summary:'Finished',stop:true}),/not settled/);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM client_events WHERE task_id=?',assigned.task_id)!.n,0);}finally{await f.close();}});

test('cancel after due queue but before dispatch cancels its review without invocation',async()=>{const f=setup();try{activate(f);const s=schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'queued');f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});assert.equal(f.company.claimWorkNext(),undefined);assert.equal(occurrences(f)[0]!.state,'cancelled');}finally{await f.close();}});

test('mandate-selected group has actual coordinator provenance, explicit observation export and no hidden Task',async()=>{const f=setup();try{
  f.company.mandates.clock={now:()=>Date.now()};const parent=f.company.assignObjective(objective),t=f.company.claimNext()!;const scout=f.company.callTool(t.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(t.execution.execution_id,{status:'completed',summary:'Roster ready'});assert.equal(f.company.task(parent.task_id).status,'completed');const o=observe(f);activate(f);const x=claim(f);f.company.mandates.callTool(x.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0});
  const g=f.company.mandates.callTool(x.context,'group','convene_working_group',{topic:'Which internal hypothesis merits investigation?',desired_output:'Compare two alternatives and uncertainty',constraints:'Use only SIMULATED supplied material',participant_ids:[f.atlas.worker_id,scout.worker_id],facilitator_id:f.atlas.worker_id,synthesizer_id:scout.worker_id,observation_ids:[o.observation_id],allow_research:false}) as {group_id:string};
  const group=f.company.discussions.group(g.group_id);assert.equal(group.created_by,f.atlas.principal_id);assert.equal(group.initiating_operation,'mandate_coordinator');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,1);assert.equal(f.store.get<{executions_reserved:number}>('SELECT executions_reserved FROM operating_cycles')!.executions_reserved,25);
  assert.match(f.store.get<{content:string}>('SELECT content FROM group_evidence WHERE group_id=?',g.group_id)!.content,/simulated_fixture/);assert.throws(()=>f.company.discussions.control({group_id:g.group_id,action:'extend',receipt_key:'cannot_extend_mandate_group'}),/reserved envelope/);
  f.company.mandates.control({mandate_id:f.m.mandate_id,action:'pause'});assert.equal(f.company.claimWorkNext(),undefined);f.company.mandates.control({mandate_id:f.m.mandate_id,action:'resume'});const member=f.company.claimWorkNext();assert.ok(member&&member.worker.worker_id===scout.worker_id);
}finally{await f.close();}});

test('v1 DTOs and notification hints exclude strategic Tasks, reports, messages and review executions',async()=>{const {ClientDTOs}=await import('../src/client/dto.js');const f=setup();try{
  const parent=f.company.assignObjective(objective),setupClaim=f.company.claimNext()!,scout=f.company.callTool(setupClaim.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(setupClaim.execution.execution_id,{status:'completed',summary:'Roster fixture'});activate(f);const coordinator=claim(f),d=decision(f,coordinator.context);
  const task=f.company.mandates.callTool(coordinator.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'PRIVATE_STRATEGY_SENTINEL',acceptance_criteria:'Preserve modes',constraints:'Internal only'}) as {task_id:string};
  const worker=f.company.claimWorkNext()!;assert.equal(worker.origin,'task');const artifact=f.company.callTool(worker.context,'report','submit_artifact',{description:'PRIVATE_STRATEGY_SENTINEL',content:'SIMULATED internal interpretation only'}) as {artifact_id:string};f.company.finish(worker.execution.execution_id,{status:'completed',summary:'PRIVATE_STRATEGY_SENTINEL'});
  const dto=new ClientDTOs(f.company,'test-hq');for(const [resource,id] of [['tasks',task.task_id],['executions',worker.execution.execution_id],['executions',coordinator.execution.execution_id],['artifacts',artifact.artifact_id]] as const)assert.throws(()=>dto.one(resource,id),/not found/);
  for(const resource of ['tasks','executions','artifacts','messages'] as const)assert.doesNotMatch(JSON.stringify(dto.page(resource,new URLSearchParams())),/PRIVATE_STRATEGY_SENTINEL|mandate_/);
  assert.ok(dto.one('tasks',parent.task_id));assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM client_events WHERE task_id=? OR execution_id=? OR execution_id=?',task.task_id,coordinator.execution.execution_id,worker.execution.execution_id)!.n,0);
}finally{await f.close();}});

test('crash after claim before invocation retains effects, retries only known uninvoked attempt',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const first=claim(f);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);f.company.recover();f.company.mandates.progress();assert.equal(f.company.execution(first.execution.execution_id).status,'interrupted');assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);f.advance(30000);f.company.mandates.progress();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.ok(f.company.claimWorkNext());}finally{await f.close();}});

test('unknown provider outcome after a committed decision retains decision and blocks occurrence',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const x=claim(f);f.company.conversations.event(x.context,'runtime_turn_starting',{context_chars:100});const d=decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Committed but provider unknown',stop:true});f.company.recover();f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'blocked');assert.ok(f.store.get('SELECT 1 FROM strategic_decisions WHERE decision_id=?',d.decision_id));f.advance(120000);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),true);}finally{await f.close();}});

test('confirmed completion before occurrence completion reconciles on restart with no new model turn',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const x=claim(f);decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Review complete',stop:true});f.company.finish(x.execution.execution_id,{status:'completed',settled:true,summary:'Committed'});f.company.mandates.fault=point=>{if(point==='after_confirmed_decision_before_occurrence_completion')throw new Error('controlled crash');};assert.throws(()=>f.company.mandates.progress(),/controlled/);const before=f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n;f.company.mandates.fault=undefined;f.company.recover();f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'completed');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,before);assert.throws(()=>f.store.run("UPDATE review_occurrences SET reason='rewrite'"),/immutable/);}finally{await f.close();}});
