import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,until,hire,objective} from './helpers.js';
import {Company} from '../src/control/company.js';
import {Store} from '../src/persistence/store.js';
import {wallClockInstant,nextReviewInstant} from '../src/control/company-clock.js';
import type {Mandate,ReviewOccurrence,OperatingCycle} from '../src/domain/mandates.js';
import type {ExecutionContext} from '../src/control/company.js';
import {join} from 'node:path';
import {companyTools,researchTools} from '../src/runtime/adapter.js';
import type {Worker} from '../src/domain/model.js';

function setup(envelope:Record<string,unknown>={}){const f=fixture(),atlas=f.company.initializeCEO();let time=Date.parse('2026-10-05T18:00:00Z');f.company.mandates.clock={now:()=>time};
  const m=f.company.mandates.create({title:'A useful company',objective:'Improve sustainable success',success_criteria:'Evidence-backed internal choices',stop_criteria:'Stop on limits or lack of permission',constraints:'No external action',resources:'Internal analysis only',coordinator_id:atlas.worker_id,envelope:{min_interval_seconds:30,...envelope}});
  return {...f,m,atlas,advance(ms:number){time+=ms;},time:()=>time};}
const observe=(f:ReturnType<typeof setup>,overrides:Record<string,unknown>={})=>f.company.mandates.admitObservation({mandate_id:f.m.mandate_id,cycle_id:null,initiative_id:null,mode:'simulated_fixture',name:'SIMULATED retention',value:'30',unit:'percent',observed_at:new Date(f.time()-60000).toISOString(),period:'A simulated prior week',source:'fixture://acceptance/baseline',provenance:'Trusted explicitly simulated test input',limitations:'Not production; no observed real improvement',missingness:'Costs unknown',body:'SIMULATED: retention is 30 percent; acquisition and quality are alternative hypotheses.',...overrides});
const schedule=(f:ReturnType<typeof setup>,overrides:Record<string,unknown>={})=>f.company.mandates.saveOwnerSchedule({mandate_id:f.m.mandate_id,schedule_id:null,purpose:'Review attributable evidence',initiative_id:null,due_at:new Date(f.time()+60000).toISOString(),recurrence_kind:'once',interval_seconds:null,local_time:null,occurrence_limit:1,end_at:new Date(f.time()+3600000).toISOString(),...overrides});
function activate(f:ReturnType<typeof setup>){f.company.mandates.control({mandate_id:f.m.mandate_id,action:'activate'});return f.company.mandates.mandate(f.m.mandate_id);}
function claim(f:ReturnType<typeof setup>){const x=f.company.claimWorkNext();assert.ok(x&&x.origin==='conversation');f.company.conversations.context(x.context);return x;}
function decision(f:ReturnType<typeof setup>,context:ExecutionContext,refs:string[]=[],overrides:Record<string,unknown>={}){return f.company.mandates.callTool(context,`decision-${Math.random()}`,'record_strategic_decision',{initiative_id:null,disposition:'continue',recommendation:'Investigate quality and retention',rationale:'Compare outcomes with missing costs',alternatives:'Quality improvements versus acquisition analysis',evidence_ids:refs,contrary_evidence:'Small sample and uncertain attribution',unknowns:'Actual business performance',missing_evidence:refs.length?null:'No admitted evidence yet; this is a hypothesis',...overrides}) as {decision_id:string};}
function closeCycle(f:ReturnType<typeof setup>,stop=false){const x=claim(f);decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Bounded assessment; evidence unknown.',stop});f.company.finish(x.execution.execution_id,{status:'completed',settled:true,summary:'Committed'});f.company.mandates.progress();return x;}
function occurrences(f:ReturnType<typeof setup>){return f.store.all<ReviewOccurrence>('SELECT * FROM review_occurrences ORDER BY rowid');}

test('mandate draft is passive, activation explicit, review ownership differs from direct replies and tasks',async()=>{const f=setup();try{
  assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);activate(f);const x=claim(f);
  assert.equal(x.execution.task_id,null);assert.equal(f.company.conversations.session(x.execution.session_id).tool_schema,'mandate-review-v1');assert.equal(f.company.conversations.list().items.length,0);
  assert.throws(()=>f.company.conversations.send({conversation_id:x.request.conversation_id,body:'Fake reply trigger',request_reply:true,receipt_key:'abcdefghijklmnop'}),/dedicated mandate/);
  for(const name of ['assign_task','hire_worker','research_search','grant_research','submit_reply','create_repository'])assert.throws(()=>f.company.mandates.callTool(x.context,name,name,{}),/outside mandate/);
  assert.throws(()=>f.store.run("UPDATE mandates SET envelope='{}' WHERE mandate_id=?",f.m.mandate_id),/authority/);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,0);
}finally{await f.close();}});

test('grounding requires full same-execution originals, denies invented/cross-mandate/future/withdrawn evidence',async()=>{const f=setup();try{const o=observe(f);assert.throws(()=>observe(f,{observed_at:new Date(f.time()+1).toISOString()}),/Future/);activate(f);const x=claim(f);
  assert.throws(()=>decision(f,x.context,[o.observation_id]),/complete current original/);assert.throws(()=>decision(f,x.context,['observation_invented']),/outside/);
  const read=f.company.mandates.callTool(x.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0}) as {fully_delivered:boolean;content:string};assert.equal(read.fully_delivered,true);assert.match(read.content,/simulated_fixture/);assert.match(read.content,/observed_at/);decision(f,x.context,[o.observation_id]);
  const other=f.company.mandates.create({title:'Other',objective:'Private',success_criteria:'Private',stop_criteria:'Stop',constraints:'Private',resources:'Internal',coordinator_id:f.atlas.worker_id,envelope:{}});const foreign=observe(f,{mandate_id:other.mandate_id});assert.throws(()=>f.company.mandates.callTool(x.context,'foreign','read_mandate_record',{record_id:foreign.observation_id,offset:0}),/outside/);
  f.company.mandates.withdrawObservation({observation_id:o.observation_id});assert.throws(()=>decision(f,x.context,[o.observation_id]),/withdrawn|scope/i);assert.throws(()=>f.store.run("UPDATE mandate_observations SET mode='real_read_only' WHERE observation_id=?",o.observation_id),/immutable/);
}finally{await f.close();}});

test('decisions are append-only, missing evidence explicit, committed outcome idempotent',async()=>{const f=setup();try{activate(f);const x=claim(f);assert.throws(()=>decision(f,x.context,[],{missing_evidence:null}),/explicitly/);const d=decision(f,x.context);assert.throws(()=>f.store.run("UPDATE strategic_decisions SET rationale='rewrite' WHERE decision_id=?",d.decision_id),/immutable/);
  const payload={summary:'Stop without evidence, within owner stop criteria',stop:true};const result=f.company.mandates.callTool(x.context,'finish','complete_cycle',payload);assert.deepEqual(f.company.mandates.callTool(x.context,'finish','complete_cycle',payload),result);assert.throws(()=>f.company.mandates.callTool(x.context,'after','propose_initiative',{title:'more'}),/committed/);
  f.company.finish(x.execution.execution_id,{status:'completed',summary:'Finished'});f.company.mandates.progress();assert.equal(f.company.mandates.mandate(f.m.mandate_id).status,'stopped');
}finally{await f.close();}});

test('one-time clock: before/exactly/after due, overlap hold-one, stable occurrence and no duplicate callback',async()=>{const f=setup();try{activate(f);schedule(f);f.company.mandates.tick();assert.equal(occurrences(f).length,0);f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'held');closeCycle(f);assert.equal(occurrences(f)[0]!.state,'queued');f.company.mandates.tick();f.advance(1);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);
}finally{await f.close();}});

test('recurring clock coalesces missed times without a model burst and ends at occurrence count',async()=>{const f=setup();try{activate(f);schedule(f,{recurrence_kind:'interval',interval_seconds:60,occurrence_limit:4});f.advance(180000);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(occurrences(f)[0]!.missed_count,2);assert.equal(occurrences(f)[0]!.state,'held');f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.missed_count,3);assert.equal(f.store.get<{status:string}>('SELECT status FROM review_schedules')!.status,'exhausted');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);
}finally{await f.close();}});

test('editing a one-time review earlier invokes only the new version at its exact due instant',async()=>{const f=setup();try{
  activate(f);const old=schedule(f,{due_at:new Date(f.time()+180000).toISOString()});closeCycle(f);
  const edited=schedule(f,{schedule_id:old.schedule_id,due_at:new Date(f.time()+60000).toISOString()});assert.equal(edited.version,2);
  f.advance(59999);f.company.mandates.tick();assert.equal(occurrences(f).length,0);assert.equal(f.company.claimWorkNext(),undefined);
  f.advance(1);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(occurrences(f)[0]!.schedule_version,2);assert.equal(occurrences(f)[0]!.due_at,edited.next_due);
  closeCycle(f,true);assert.equal(occurrences(f)[0]!.state,'completed');f.advance(120000);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(f.company.claimWorkNext(),undefined);
  assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM review_schedule_versions')!.n,2);
}finally{await f.close();}});

test('recurring reviews execute successive completed cycles and stop at the end date before the count limit',async()=>{const f=setup();try{
  activate(f);const start=f.time();schedule(f,{recurrence_kind:'interval',interval_seconds:60,occurrence_limit:4,end_at:new Date(start+150000).toISOString()});closeCycle(f);
  f.advance(60000);f.company.mandates.tick();closeCycle(f);assert.equal(occurrences(f).length,1);assert.equal(occurrences(f)[0]!.state,'completed');assert.equal(f.store.get<{next_due:string}>('SELECT next_due FROM review_schedules')!.next_due,new Date(start+120000).toISOString());
  f.advance(59999);f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(f.company.claimWorkNext(),undefined);
  f.advance(1);f.company.mandates.tick();assert.equal(f.store.get<{status:string}>('SELECT status FROM review_schedules')!.status,'exhausted');closeCycle(f,true);const rows=occurrences(f);assert.equal(rows.length,2);assert.ok(rows.every(o=>o.state==='completed'&&o.missed_count===0));assert.notEqual(rows[0]!.cycle_id,rows[1]!.cycle_id);
  assert.deepEqual({...f.store.get<{consumed:number;status:string;next_due:string|null}>('SELECT consumed,status,next_due FROM review_schedules')},{consumed:2,status:'exhausted',next_due:null});
  f.advance(120000);f.company.mandates.tick();assert.equal(occurrences(f).length,2);assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,3);
}finally{await f.close();}});

test('schedule edits retain versions, invalidate old due callbacks, cancellation is terminal',async()=>{const f=setup();try{activate(f);const s=schedule(f);f.advance(60000);f.company.mandates.tick();const changed=schedule(f,{schedule_id:s.schedule_id,due_at:new Date(f.time()+120000).toISOString(),recurrence_kind:'interval',interval_seconds:60,occurrence_limit:3});assert.equal(changed.version,2);assert.equal(occurrences(f)[0]!.state,'superseded');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM review_schedule_versions')!.n,2);f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});assert.throws(()=>f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'resume'}),/resurrected/);f.advance(300000);f.company.mandates.tick();assert.equal(occurrences(f).length,1);
}finally{await f.close();}});

test('global, mandate and schedule pause retain due work and resume without duplication',async()=>{for(const kind of ['global','mandate','schedule']){const f=setup();try{activate(f);const s=schedule(f);closeCycle(f);if(kind==='global')f.company.pause(true);if(kind==='mandate')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'pause'});if(kind==='schedule')f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'pause'});f.advance(60000);f.company.mandates.tick();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);
  if(kind==='global')f.company.pause(false);if(kind==='mandate')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'resume'});if(kind==='schedule')f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'resume'});f.company.mandates.tick();f.company.mandates.tick();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(occurrences(f).length,1);
}finally{await f.close();}}});

test('disabled coordinator, revoked communication, cycle limit and unknown provider fence deny due review',async()=>{for(const kind of ['disabled','capability','limit','unknown']){const f=setup(kind==='limit'?{max_cycles:1}:{});try{activate(f);schedule(f);closeCycle(f);if(kind==='disabled')f.store.run('UPDATE workers SET enabled=0 WHERE worker_id=?',f.atlas.worker_id);if(kind==='capability')f.store.run("UPDATE workers SET capability_profile='[]' WHERE worker_id=?",f.atlas.worker_id);if(kind==='unknown'){const prior=f.store.get<{execution_id:string}>('SELECT execution_id FROM executions')!;f.store.run('INSERT INTO execution_runtime_attempts VALUES (?,1)',prior.execution_id);}f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'blocked');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);
}finally{await f.close();}}});

test('stop prevents queued work and stale timers from reviving a mandate',async()=>{const f=setup();try{activate(f);schedule(f);f.company.mandates.control({mandate_id:f.m.mandate_id,action:'stop'});f.advance(120000);f.company.mandates.tick();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{status:string}>('SELECT status FROM review_schedules')!.status,'cancelled');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,0);
}finally{await f.close();}});

test('Vancouver DST uses first repeated minute and first valid post-gap minute; interval uses elapsed seconds',()=>{
  assert.equal(new Date(wallClockInstant('2026-03-08','02:30','America/Vancouver')).toISOString(),'2026-03-08T10:00:00.000Z');
  assert.equal(new Date(wallClockInstant('2026-11-01','01:30','America/Vancouver')).toISOString(),'2026-11-01T08:30:00.000Z');
  assert.equal(new Date(nextReviewInstant(Date.parse('2026-03-07T10:30:00Z'),{kind:'daily',local_time:'02:30'},'America/Vancouver')!).toISOString(),'2026-03-08T10:00:00.000Z');
  assert.equal(nextReviewInstant(1000,{kind:'interval',seconds:60},'America/Vancouver'),61000);
});

test('crash after occurrence commit, before claim: reopening safely queues exactly one review',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.fault=point=>{if(point==='after_occurrence_before_claim')throw new Error('injected crash');};assert.throws(()=>f.company.mandates.tick(),/injected/);assert.equal(occurrences(f)[0]!.state,'due');f.store.close();const store=new Store(join(f.dir,'company.sqlite')),company=new Company(store,f.dir,process.cwd(),'fake');company.mandates.clock={now:f.time};company.recover();company.mandates.progress();company.mandates.progress();assert.equal(store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(store.get<{state:string}>('SELECT state FROM review_occurrences')!.state,'queued');assert.deepEqual(store.all('PRAGMA foreign_key_check'),[]);store.close();}finally{await f.dispatcher.stop();}});

test('fault before next-time commit rolls back occurrence and consumption atomically',async()=>{const f=setup();try{activate(f);schedule(f);f.advance(60000);f.company.mandates.fault=point=>{if(point==='after_next_calculation_before_commit')throw new Error('injected');};assert.throws(()=>f.company.mandates.tick(),/injected/);assert.equal(occurrences(f).length,0);assert.equal(f.store.get<{consumed:number}>('SELECT consumed FROM review_schedules')!.consumed,0);f.company.mandates.fault=undefined;f.company.mandates.tick();assert.equal(occurrences(f).length,1);}finally{await f.close();}});

test('known review failure backs off boundedly; ambiguous invocation blocks without retry',async()=>{for(const unknown of [false,true]){const f=setup();try{activate(f);const x=claim(f);if(unknown)f.company.conversations.event(x.context,'runtime_turn_starting',{context_chars:100});f.company.finish(x.execution.execution_id,{status:'failed',settled:!unknown,error:'Injected known/unknown failure'});f.company.mandates.progress();const c=f.store.get<OperatingCycle>('SELECT * FROM operating_cycles')!;assert.equal(c.state,unknown?'blocked':'waiting');assert.equal(c.failures,unknown?0:1);f.advance(30000);f.company.mandates.progress();assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM mandate_turns')!.n,unknown?1:2);}finally{await f.close();}}});

test('real dispatcher substrate executes two simulated-runtime cycles, second initiated only by persisted clock',async()=>{const f=setup();try{let completed=0;f.runtime.gate=async input=>{if(input.mode!=='conversation')throw new Error('Unexpected Task');const ctx=input.context as {mode:string;mandate:Mandate};assert.equal(ctx.mode,'mandate_review');decision(f,{executionId:input.execution.execution_id,workerId:input.worker.worker_id,workspacePath:input.worker.workspace_path});if(!completed)schedule(f);await input.callTool('close','complete_cycle',{summary:'Bounded simulated-runtime review',stop:completed++>0});return {status:'completed',summary:'Committed',settled:true};};activate(f);f.dispatcher.start();await until(()=>f.store.get<{n:number}>("SELECT count(*) n FROM operating_cycles WHERE state='closed'")!.n===1);assert.equal(f.runtime.calls.length,1);f.advance(60000);f.dispatcher.kick();await until(()=>f.company.mandates.mandate(f.m.mandate_id).status==='stopped');assert.equal(f.runtime.calls.length,2);assert.equal(occurrences(f)[0]!.state,'completed');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,0);}finally{await f.close();}});

test('idle company clock causes no model or research work',async()=>{const f=setup();try{f.dispatcher.start();for(let i=0;i<10;i++){f.advance(60000);f.dispatcher.kick();await new Promise(r=>setTimeout(r,5));}assert.equal(f.runtime.calls.length,0);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_operations')!.n,0);}finally{await f.close();}});

test('mandate internal Task enforces reporting hierarchy and separate decision link',async()=>{const f=setup();try{const parent=f.company.assignObjective(objective),t=f.company.claimNext()!;const scout=f.company.callTool(t.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(t.execution.execution_id,{status:'completed',summary:'Roster setup'});assert.equal(f.company.task(parent.task_id).status,'completed');activate(f);const x=claim(f),d=decision(f,x.context);assert.throws(()=>f.company.mandates.callTool(x.context,'bad','assign_internal_task',{decision_id:d.decision_id,worker_id:f.atlas.worker_id,objective:'Internal',acceptance_criteria:'Report',constraints:'No external action'}),/direct reports/);const assigned=f.company.mandates.callTool(x.context,'task','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Compare internal quality strategies',acceptance_criteria:'A source-labelled report',constraints:'No external action'}) as {task_id:string};assert.ok(assigned.task_id);assert.equal(f.company.task(assigned.task_id).parent_task_id,null);assert.equal(f.company.task(assigned.task_id).created_execution_id,x.execution.execution_id);assert.throws(()=>f.company.mandates.callTool(x.context,'premature','complete_cycle',{summary:'Finished',stop:true}),/not settled/);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM client_events WHERE task_id=?',assigned.task_id)!.n,0);}finally{await f.close();}});

test('cancel after due queue but before dispatch cancels its review without invocation',async()=>{const f=setup();try{activate(f);const s=schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'queued');f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});assert.equal(f.company.claimWorkNext(),undefined);assert.equal(occurrences(f)[0]!.state,'cancelled');}finally{await f.close();}});

test('mandate-selected group has actual coordinator provenance, explicit observation export and no hidden Task',async()=>{const f=setup();try{
  f.company.mandates.clock={now:()=>Date.now()};const parent=f.company.assignObjective(objective),t=f.company.claimNext()!;const scout=f.company.callTool(t.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(t.execution.execution_id,{status:'completed',summary:'Roster ready'});assert.equal(f.company.task(parent.task_id).status,'completed');const o=observe(f);activate(f);const x=claim(f);f.company.mandates.callTool(x.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0});
  const g=f.company.mandates.callTool(x.context,'group','convene_working_group',{topic:'Which internal hypothesis merits investigation?',desired_output:'Compare two alternatives and uncertainty',constraints:'Use only SIMULATED supplied material',participant_ids:[f.atlas.worker_id,scout.worker_id],facilitator_id:f.atlas.worker_id,synthesizer_id:scout.worker_id,observation_ids:[o.observation_id],allow_research:false}) as {group_id:string};
  const group=f.company.discussions.group(g.group_id);assert.equal(group.created_by,f.atlas.principal_id);assert.equal(group.initiating_operation,'mandate_coordinator');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tasks')!.n,1);assert.equal(f.store.get<{executions_reserved:number}>('SELECT executions_reserved FROM operating_cycles')!.executions_reserved,25);
  assert.match(f.store.get<{content:string}>('SELECT content FROM group_evidence WHERE group_id=?',g.group_id)!.content,/simulated_fixture/);assert.throws(()=>f.company.discussions.control({group_id:g.group_id,action:'extend',receipt_key:'cannot_extend_mandate_group'}),/reserved envelope/);
  f.company.mandates.control({mandate_id:f.m.mandate_id,action:'pause'});assert.equal(f.company.claimWorkNext(),undefined);f.company.mandates.control({mandate_id:f.m.mandate_id,action:'resume'});const member=f.company.claimWorkNext();assert.ok(member&&member.worker.worker_id===scout.worker_id);
}finally{await f.close();}});

test('v1 DTOs and notification hints exclude strategic Tasks, reports, messages and review executions',async()=>{const {ClientDTOs}=await import('../src/client/dto.js');const f=setup();try{
  const parent=f.company.assignObjective(objective),setupClaim=f.company.claimNext()!,scout=f.company.callTool(setupClaim.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(setupClaim.execution.execution_id,{status:'completed',summary:'Roster fixture'});activate(f);const coordinator=claim(f),d=decision(f,coordinator.context);
  const task=f.company.mandates.callTool(coordinator.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'PRIVATE_STRATEGY_SENTINEL',acceptance_criteria:'Preserve modes',constraints:'Internal only'}) as {task_id:string};
  const worker=f.company.claimWorkNext()!;assert.equal(worker.origin,'task');const artifact=f.company.callTool(worker.context,'report','submit_artifact',{description:'PRIVATE_STRATEGY_SENTINEL',content:'SIMULATED internal interpretation only'}) as {artifact_id:string};f.company.finish(worker.execution.execution_id,{status:'completed',summary:'PRIVATE_STRATEGY_SENTINEL'});
  const dto=new ClientDTOs(f.company,'test-hq');for(const [resource,id] of [['tasks',task.task_id],['executions',worker.execution.execution_id],['executions',coordinator.execution.execution_id],['artifacts',artifact.artifact_id]] as const)assert.throws(()=>dto.one(resource,id),/not found/);
  for(const resource of ['tasks','executions','artifacts','messages'] as const)assert.doesNotMatch(JSON.stringify(dto.page(resource,new URLSearchParams())),/PRIVATE_STRATEGY_SENTINEL|mandate_/);
  assert.ok(dto.one('tasks',parent.task_id));assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM client_events WHERE task_id=? OR execution_id=? OR execution_id=?',task.task_id,coordinator.execution.execution_id,worker.execution.execution_id)!.n,0);
}finally{await f.close();}});

test('crash after claim before invocation retains effects, retries only known uninvoked attempt',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const first=claim(f);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);f.company.recover();f.company.mandates.progress();assert.equal(f.company.execution(first.execution.execution_id).status,'interrupted');assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);f.advance(30000);f.company.mandates.progress();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.ok(f.company.claimWorkNext());}finally{await f.close();}});

test('unknown provider outcome after a committed decision retains decision and blocks occurrence',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const x=claim(f);f.company.conversations.event(x.context,'runtime_turn_starting',{context_chars:100});const d=decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Committed but provider unknown',stop:true});f.company.recover();f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'blocked');assert.ok(f.store.get('SELECT 1 FROM strategic_decisions WHERE decision_id=?',d.decision_id));f.advance(120000);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),true);}finally{await f.close();}});

test('confirmed completion before occurrence completion reconciles on restart with no new model turn',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const x=claim(f);decision(f,x.context);f.company.mandates.callTool(x.context,'close','complete_cycle',{summary:'Review complete',stop:true});f.company.finish(x.execution.execution_id,{status:'completed',settled:true,summary:'Committed'});f.company.mandates.fault=point=>{if(point==='after_confirmed_decision_before_occurrence_completion')throw new Error('controlled crash');};assert.throws(()=>f.company.mandates.progress(),/controlled/);const before=f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n;f.company.mandates.fault=undefined;f.company.recover();f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'completed');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,before);assert.throws(()=>f.store.run("UPDATE review_occurrences SET reason='rewrite'"),/immutable/);}finally{await f.close();}});

test('schedule pause and expiry are rechecked after durable queue, before first provider execution',async()=>{for(const action of ['pause','expire']){const f=setup();try{
  activate(f);const s=schedule(f,{end_at:new Date(f.time()+120000).toISOString()});closeCycle(f);f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'queued');
  if(action==='pause'){f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'pause'});assert.equal(f.company.claimWorkNext(),undefined);f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'resume'});assert.ok(f.company.claimWorkNext());assert.equal(occurrences(f).length,1);}
  else{f.advance(60001);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(occurrences(f)[0]!.state,'cancelled');}
}finally{await f.close();}}});

test('hypotheses and unsupported decisions cannot masquerade as supporting observation evidence',async()=>{const f=setup();try{activate(f);const x=claim(f);
  const i=f.company.mandates.callTool(x.context,'idea','propose_initiative',{title:'Unproven',mechanism:'Maybe useful',expected_outcome:'Unknown',assumptions:'No actual measurements'}) as {initiative_id:string};
  f.company.mandates.callTool(x.context,'read-i','read_mandate_record',{record_id:i.initiative_id,offset:0});assert.throws(()=>decision(f,x.context,[i.initiative_id]),/hypothesis/);
  const first=decision(f,x.context);f.company.mandates.callTool(x.context,'read-d','read_mandate_record',{record_id:first.decision_id,offset:0});assert.throws(()=>decision(f,x.context,[first.decision_id]),/prior decisions/);decision(f,x.context,[first.decision_id],{missing_evidence:'The earlier choice remains an untested hypothesis.'});
}finally{await f.close();}});

test('every distinct successful read consumes retrieval budget; idempotent replay does not',async()=>{const f=setup();try{const o=observe(f,{body:'S'.repeat(4000),limitations:'L'.repeat(1500),missingness:'M'.repeat(1000)});activate(f);const x=claim(f);
  const input={record_id:o.observation_id,offset:0};for(let n=0;n<8;n++)f.company.mandates.callTool(x.context,`read-${n}`,'read_mandate_record',input);
  assert.equal(f.store.get<{chars:number}>('SELECT chars FROM mandate_read_usage WHERE execution_id=?',x.execution.execution_id)!.chars,48000);
  f.company.mandates.callTool(x.context,'read-0','read_mandate_record',input);assert.throws(()=>f.company.mandates.callTool(x.context,'over','read_mandate_record',input),/retrieval budget/);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM mandate_evidence_delivery')!.n,0);
}finally{await f.close();}});

test('observation withdrawal revokes exported group scope and late evidence reads without deleting history',async()=>{const f=setup();try{
  f.company.mandates.clock={now:()=>Date.now()};f.company.assignObjective(objective);const setupClaim=f.company.claimNext()!,scout=f.company.callTool(setupClaim.context,'hire','hire_worker',hire) as {worker_id:string};f.company.finish(setupClaim.execution.execution_id,{status:'completed',summary:'Roster'});
  const o=observe(f);activate(f);const x=claim(f);f.company.mandates.callTool(x.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0});
  const g=f.company.mandates.callTool(x.context,'group','convene_working_group',{topic:'Evaluate evidence',desired_output:'Compare alternatives',constraints:'Simulated only',participant_ids:[f.atlas.worker_id,scout.worker_id],facilitator_id:f.atlas.worker_id,synthesizer_id:scout.worker_id,observation_ids:[o.observation_id],allow_research:false}) as {group_id:string};
  f.company.mandates.callTool(x.context,'wait','wait_for_internal_work',{summary:'Read the exported evidence'});f.company.finish(x.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});const member=claim(f),e=f.store.get<{evidence_id:string}>('SELECT evidence_id FROM group_evidence WHERE group_id=?',g.group_id)!;
  f.company.mandates.withdrawObservation({observation_id:o.observation_id});assert.equal(f.company.discussions.group(g.group_id).state,'blocked');
  assert.throws(()=>f.company.conversations.callTool(member.context,'late','read_group_record',{record_id:e.evidence_id,offset:0}),/withdrawn|withdrawal|active|scope|authorized/i);assert.ok(f.store.get('SELECT 1 FROM group_evidence WHERE evidence_id=?',e.evidence_id));assert.ok(f.store.get("SELECT 1 FROM audit_events WHERE type='discussion_sharing_withdrawn'"));
}finally{await f.close();}});

test('private analysis uses a Task-scoped provider context and preserves ordinary bindings in both directions',async()=>{for(const research of [false,true]){const f=setup();try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});
  if(research)f.company.research.grant({worker_id:scout.worker_id,preset:'public_research',expires_at:null,document_paths:[]});const tools=[...companyTools(scout),...(research?researchTools():[])];
  f.company.createTask('human',scout,{...objective,objective:'Ordinary visible analysis'},null,'research');const ordinary=f.company.claimNext()!;
  const old={worker_id:scout.worker_id,runtime_type:'fake',runtime_reference:'ordinary-reference',workspace_path:scout.workspace_path,created_at:new Date().toISOString()};
  const initialSession=f.company.research.taskSession(ordinary.context,tools);if(initialSession)f.company.research.prepareTaskBinding(ordinary.context,initialSession.session_id,old,true);else f.company.setBinding(ordinary.context,old);
  f.company.finish(ordinary.execution.execution_id,{status:'completed',settled:true,summary:'Ordinary result'});activate(f);const coordinator=claim(f),d=decision(f,coordinator.context);
  const assigned=f.company.mandates.callTool(coordinator.context,'private','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'PRIVATE_STRATEGY_SENTINEL. Compare internal alternatives.',acceptance_criteria:'Internal report',constraints:'Do not disclose outside mandate'}) as {task_id:string};
  f.company.mandates.callTool(coordinator.context,'wait','wait_for_internal_work',{summary:'Await private result'});f.company.finish(coordinator.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  const privateWork=f.company.claimNext()!;assert.equal(privateWork.task.task_id,assigned.task_id);const privateSession=f.company.mandates.taskSession(privateWork.context,tools)!;assert.ok(privateSession);assert.equal(f.company.mandates.taskBinding(privateSession),undefined);
  assert.throws(()=>f.company.mandates.prepareTaskBinding(privateWork.context,privateSession.session_id,old),/another work context/);assert.throws(()=>f.company.setBinding(privateWork.context,old),/scoped context/);
  const binding={...old,runtime_reference:'private-reference'};f.company.mandates.prepareTaskBinding(privateWork.context,privateSession.session_id,binding,true);f.company.finish(privateWork.execution.execution_id,{status:'completed',settled:true,summary:'Private result'});
  f.company.createTask('human',scout,{...objective,objective:'A later ordinary analysis'},null,'research');const later=f.company.claimNext()!;assert.equal(f.company.mandates.taskSession(later.context,tools),undefined);
  const laterSession=f.company.research.taskSession(later.context,tools);assert.equal((laterSession?f.company.research.taskBinding(laterSession):f.company.binding(scout.worker_id))?.runtime_reference,old.runtime_reference);assert.doesNotMatch(JSON.stringify(f.company.context(later.context)),/PRIVATE_STRATEGY_SENTINEL|Private result/);
  assert.throws(()=>laterSession?f.company.research.prepareTaskBinding(later.context,laterSession.session_id,binding):f.company.setBinding(later.context,binding),/private mandate context/);
}finally{await f.close();}}});

test('linked Task receives runtime abort at the enclosing cycle deadline',async()=>{const f=setup({max_cycle_minutes:1});try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});activate(f);const coordinator=claim(f),d=decision(f,coordinator.context);
  f.company.mandates.callTool(coordinator.context,'private','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Bounded slow analysis',acceptance_criteria:'A report',constraints:'Deadline applies'});f.company.mandates.callTool(coordinator.context,'wait','wait_for_internal_work',{summary:'Await bounded analysis'});f.company.finish(coordinator.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  f.advance(59900);let aborted=false;f.runtime.run=async(input,signal)=>{assert.equal(input.mode,'task');return new Promise(resolve=>{signal.addEventListener('abort',()=>{aborted=true;resolve({status:'interrupted',settled:true,error:'Acknowledged bounded interruption'});},{once:true});});};f.dispatcher.start();await until(()=>aborted);await until(()=>!f.store.get("SELECT 1 FROM executions WHERE status='running'"));assert.equal(f.company.providerUnresolved(scout.worker_id),false);
}finally{await f.close();}});

test('internal Task receives only explicitly selected evidence bodies and withdrawal denies late delivery',async()=>{const f=setup();try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});
  const selected=observe(f,{body:'SIMULATED_SELECTED_SOURCE: 45 percent create a first plan.'});observe(f,{body:'UNSELECTED_PRIVATE_SOURCE: unrelated strategic context'});activate(f);const c=claim(f);f.company.mandates.callTool(c.context,'read','read_mandate_record',{record_id:selected.observation_id,offset:0});const d=decision(f,c.context,[selected.observation_id]);
  f.company.mandates.callTool(c.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Analyze explicitly exported evidence',acceptance_criteria:'Source-linked report',constraints:'Internal only',evidence_ids:[selected.observation_id]});f.company.mandates.callTool(c.context,'wait','wait_for_internal_work',{summary:'Await result'});f.company.finish(c.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});const worker=f.company.claimNext()!,context=JSON.stringify(f.company.context(worker.context));assert.match(context,/SIMULATED_SELECTED_SOURCE/);assert.match(context,/simulated_fixture/);assert.doesNotMatch(context,/UNSELECTED_PRIVATE_SOURCE/);
  f.company.mandates.withdrawObservation({observation_id:selected.observation_id});assert.throws(()=>f.company.context(worker.context),/withdrawn|withdrawal/);
}finally{await f.close();}});

test('first-page reads allow omitted offset without relaxing scope, receipts or cumulative budgets',async()=>{const f=setup();try{const o=observe(f);activate(f);const c=claim(f);
  const first=f.company.mandates.callTool(c.context,'default','read_mandate_record',{record_id:o.observation_id}) as {offset:number;next_offset:null;next_action:string;content:string;fully_delivered:boolean};assert.equal(first.offset,0);assert.equal(first.next_offset,null);assert.equal(first.fully_delivered,true);assert.match(first.next_action,/Do not reread/);decision(f,c.context,[o.observation_id]);
  const second=f.company.mandates.callTool(c.context,'explicit','read_mandate_record',{record_id:o.observation_id,offset:0}) as {content:string};assert.equal(second.content,first.content);assert.equal(f.store.get<{chars:number}>('SELECT chars FROM mandate_read_usage')!.chars,first.content.length*2);
  for(const offset of [null,'0',-1,0.1,999999])assert.throws(()=>f.company.mandates.callTool(c.context,`invalid-${offset}`,'read_mandate_record',{record_id:o.observation_id,offset}),/offset must be/);assert.throws(()=>f.company.mandates.callTool(c.context,'foreign','read_mandate_record',{record_id:'observation_unavailable'}),/outside/);
}finally{await f.close();}});

test('withdrawal replaces coordinator provider generation and withholds earlier derived strategy and reports',async()=>{const f=setup();try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});
  const o=observe(f,{body:'WITHDRAWN_SENTINEL: simulated source'});activate(f);const first=claim(f);const binding={worker_id:f.atlas.worker_id,runtime_type:'fake',runtime_reference:'original-private-review',workspace_path:f.atlas.workspace_path,created_at:new Date().toISOString()};f.company.conversations.prepareBinding(first.context,binding);f.company.conversations.activateBinding(first.context);
  f.company.mandates.callTool(first.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0});const d=decision(f,first.context,[o.observation_id],{recommendation:'WITHDRAWN_SENTINEL: source-backed choice'});
  f.company.mandates.callTool(first.context,'task','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Analyze WITHDRAWN_SENTINEL',acceptance_criteria:'Report',constraints:'Internal',evidence_ids:[o.observation_id]});f.company.mandates.callTool(first.context,'wait','wait_for_internal_work',{summary:'WITHDRAWN_SENTINEL: awaiting result'});f.company.finish(first.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  const worker=f.company.claimNext()!,a=f.company.callTool(worker.context,'report','submit_artifact',{description:'Internal report',content:'WITHDRAWN_SENTINEL: derivative report'}) as {artifact_id:string};f.company.finish(worker.execution.execution_id,{status:'completed',settled:true,summary:'WITHDRAWN_SENTINEL: internal finding'});f.company.mandates.progress();const continued=claim(f);f.company.conversations.prepareBinding(continued.context,{...binding,runtime_reference:'continued-private-review'});f.company.conversations.activateBinding(continued.context);schedule(f);decision(f,continued.context);f.company.mandates.callTool(continued.context,'close','complete_cycle',{summary:'WITHDRAWN_SENTINEL: prior cycle summary',stop:false});f.company.finish(continued.execution.execution_id,{status:'completed',settled:true,summary:'Closed'});f.company.mandates.progress();
  f.advance(1);f.company.mandates.withdrawObservation({observation_id:o.observation_id});f.advance(1);f.company.mandates.control({mandate_id:f.m.mandate_id,action:'review_now'});const fresh=claim(f);assert.equal(fresh.execution.generation,continued.execution.generation+1);assert.equal(f.company.conversations.binding(fresh.context),undefined);assert.equal(f.company.conversations.session(fresh.execution.session_id).previous_session_id,continued.execution.session_id);
  assert.doesNotMatch(JSON.stringify(f.company.conversations.context(fresh.context)),/WITHDRAWN_SENTINEL/);for(const ref of [d.decision_id,a.artifact_id,worker.task.task_id])assert.throws(()=>f.company.mandates.callTool(fresh.context,ref,'read_mandate_record',{record_id:ref,offset:0}),/withdrawal|withdrawn/);
  assert.match(f.company.artifactContent(a.artifact_id),/WITHDRAWN_SENTINEL/);assert.match(JSON.stringify(f.company.mandates.inspect(f.m.mandate_id)),/WITHDRAWN_SENTINEL/);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);
}finally{await f.close();}});

test('withdrawal replaces a safely queued request without altering its immutable scope or duplicating cycles',async()=>{const f=setup();try{const o=observe(f);activate(f);const old=f.store.get<{request_id:string;scope_version:number}>('SELECT request_id,scope_version FROM conversation_requests')!;f.advance(1);f.company.mandates.withdrawObservation({observation_id:o.observation_id});const next=claim(f);assert.notEqual(next.request.request_id,old.request_id);assert.equal(next.request.scope_version,old.scope_version+1);assert.equal(f.company.conversations.request(old.request_id).scope_version,old.scope_version);assert.equal(f.company.conversations.request(old.request_id).status,'cancelled');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);
}finally{await f.close();}});

test('an unexecuted internal Task is inspectable but cannot alone satisfy decision grounding',async()=>{const f=setup();try{f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});activate(f);const c=claim(f),d=decision(f,c.context);const task=f.company.mandates.callTool(c.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Model-created objective only',acceptance_criteria:'Not yet a result',constraints:'Internal'}) as {task_id:string};f.company.mandates.callTool(c.context,'read-task','read_mandate_record',{record_id:task.task_id,offset:0});assert.throws(()=>decision(f,c.context,[task.task_id]),/unexecuted Task metadata/);decision(f,c.context,[task.task_id],{missing_evidence:'Task has not run and provides no actual evidence yet.'});
}finally{await f.close();}});

test('fault after atomic cycle/request claim rolls back without duplicate or orphaned scheduled work',async()=>{const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.fault=p=>{if(p==='after_claim_before_execution')throw Error('controlled claim crash');};assert.throws(()=>f.company.mandates.tick(),/controlled claim crash/);assert.equal(occurrences(f)[0]!.state,'due');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,1);f.company.mandates.fault=undefined;f.company.recover();f.company.mandates.progress();f.company.mandates.progress();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.equal(occurrences(f)[0]!.state,'queued');
}finally{await f.close();}});


test('each settled strategic turn uses a fresh checkpoint with retained cycle identity and fresh delivery receipts',async()=>{const f=setup();try{
  const o=observe(f);activate(f);const first=claim(f),cycle=f.company.mandates.mandate(f.m.mandate_id).current_cycle_id;
  const binding={worker_id:f.atlas.worker_id,runtime_type:'fake',runtime_reference:'strategic-first-provider',workspace_path:f.atlas.workspace_path,created_at:new Date().toISOString()};
  f.company.conversations.prepareBinding(first.context,binding);f.company.conversations.activateBinding(first.context);
  f.company.mandates.callTool(first.context,'read','read_mandate_record',{record_id:o.observation_id,offset:0});decision(f,first.context,[o.observation_id]);
  // A known settled turn without a terminal cycle disposition is boundedly retried.
  f.company.finish(first.execution.execution_id,{status:'completed',settled:true,summary:'PREVIOUS_PROVIDER_ONLY_SENTINEL'});f.company.mandates.progress();f.advance(30000);f.company.mandates.progress();
  const next=claim(f);assert.equal(next.execution.generation,first.execution.generation+1);assert.equal(f.company.mandates.mandate(f.m.mandate_id).current_cycle_id,cycle);
  assert.equal(next.request.conversation_id,first.request.conversation_id);assert.equal(f.company.conversations.session(next.execution.session_id).previous_session_id,first.execution.session_id);assert.equal(f.company.conversations.session(next.execution.session_id).reason,'strategic_turn_checkpoint');assert.equal(f.company.conversations.binding(next.context),undefined);
  assert.doesNotMatch(JSON.stringify(f.company.conversations.context(next.context)),/PREVIOUS_PROVIDER_ONLY_SENTINEL/);assert.throws(()=>decision(f,next.context,[o.observation_id]),/complete current original/);
  f.company.conversations.prepareBinding(next.context,{...binding,runtime_reference:'strategic-next-provider'});f.company.conversations.activateBinding(next.context);assert.equal(f.company.conversations.session(first.execution.session_id).state,'superseded');assert.equal(f.company.conversations.binding(next.context)?.runtime_reference,'strategic-next-provider');
  f.company.conversations.event(next.context,'runtime_turn_starting',{context_chars:100});f.company.finish(next.execution.execution_id,{status:'failed',settled:false,error:'Unknown provider outcome'});f.company.mandates.progress();f.advance(60000);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM conversation_sessions')!.n,2);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),true);
}finally{await f.close();}});

test('mandate research allowance is shared across separate internal Tasks and failed source attempts stay consumed',async()=>{const f=setup({public_research:true,max_research_operations:1});try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!;const workers=[f.company.callTool(roster.context,'hire1','hire_worker',hire),f.company.callTool(roster.context,'hire2','hire_worker',{...hire,display_name:'Orion'})] as Worker[];f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});
  for(const w of workers)f.company.research.grant({worker_id:w.worker_id,preset:'public_research',expires_at:null,document_paths:[]});activate(f);const c=claim(f),d=decision(f,c.context);
  for(const w of workers)f.company.mandates.callTool(c.context,w.worker_id,'assign_internal_task',{decision_id:d.decision_id,worker_id:w.worker_id,objective:'Compare public documentation',acceptance_criteria:'Source-linked internal report',constraints:'Public sources only',evidence_ids:[]});f.company.mandates.callTool(c.context,'wait','wait_for_internal_work',{summary:'Await reports'});f.company.finish(c.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  const {ResearchFailure}=await import('../src/domain/research.js');let calls=0;f.company.research.provider={name:'controlled-known-failure',async search(_q,_s,h){calls++;h.invoking();h.settled();throw new ResearchFailure('source_unavailable','Deterministic source outage');}};
  const first=f.company.claimNext()!,second=f.company.claimNext()!;const result=await f.company.research.callTool(first.context,'search','research_search',{query:'public software documentation'},new AbortController().signal) as {ok:boolean};assert.equal(result.ok,false);
  assert.throws(()=>f.company.research.callTool(second.context,'search','research_search',{query:'public software documentation'},new AbortController().signal),/Mandate research envelope exhausted/);assert.equal(calls,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_operations')!.n,1);assert.equal(f.company.providerUnresolved(first.worker.worker_id),false);assert.equal(f.company.mandates.mandate(f.m.mandate_id).status,'active');
}finally{await f.close();}});

for(const action of ['revoke','pause','withdraw'] as const)test(`mandate ${action} during Task research withholds late evidence and retains consumed budget`,async()=>{const f=setup({public_research:true});try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});const grant=f.company.research.grant({worker_id:scout.worker_id,preset:'public_research',expires_at:null,document_paths:[]});const o=observe(f);activate(f);const c=claim(f);f.company.mandates.callTool(c.context,'read','read_mandate_record',{record_id:o.observation_id});const d=decision(f,c.context,[o.observation_id]);
  f.company.mandates.callTool(c.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Compare public documentation',acceptance_criteria:'Report limitations',constraints:'Public sources only',evidence_ids:[o.observation_id]});f.company.mandates.callTool(c.context,'wait','wait_for_internal_work',{summary:'Await source'});f.company.finish(c.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});const task=f.company.claimNext()!;
  let release!:()=>void;f.company.research.provider={name:'controlled-gated-source',async search(_q,_s,h){h.invoking();await new Promise<void>(r=>release=r);h.settled();return {provider:'controlled',outcome:'succeeded',summary:'Controlled response',sources:[{url:'https://example.com/documentation',title:'Controlled source',content:'LATE_SOURCE_SENTINEL',kind:'search_snippet',retrieved_at:new Date().toISOString(),observed_at:null,published_at:null,freshness:'unknown',omissions:'Controlled fixture'}]};}};
  const pending=f.company.research.callTool(task.context,'search','research_search',{query:'public software documentation'},new AbortController().signal) as Promise<{ok:boolean}>;await Promise.resolve();if(action==='revoke')f.company.research.revoke({grant_id:grant.grant_id});else if(action==='pause')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'pause'});else{f.advance(1);f.company.mandates.withdrawObservation({observation_id:o.observation_id});}release();assert.equal((await pending).ok,false);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_sources')!.n,0);// Grant revocation aborts pending I/O; mandate scope changes reject the settled callback. Both retain a failed, consumed operation without sources.
  assert.equal(f.store.get<{state:string}>('SELECT state FROM research_operations')!.state,action==='revoke'?'withheld':'failed');assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM research_operations')!.n,1);assert.equal(f.company.providerUnresolved(scout.worker_id),false);
}finally{await f.close();}});

test('restart after provider reference persistence retains identity without replaying an ambiguous invocation',async()=>{for(const invoked of [false,true]){const f=setup();try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const c=claim(f);f.company.conversations.prepareBinding(c.context,{worker_id:f.atlas.worker_id,runtime_type:'fake',runtime_reference:'persisted-strategic-provider',workspace_path:f.atlas.workspace_path,created_at:new Date().toISOString()});if(invoked){f.company.conversations.activateBinding(c.context);f.company.conversations.event(c.context,'runtime_turn_starting',{context_chars:100});}f.company.recover();f.company.mandates.progress();assert.equal(f.company.conversations.session(c.execution.session_id).runtime_reference,'persisted-strategic-provider');assert.equal(f.company.conversations.session(c.execution.session_id).state,'blocked');assert.equal(f.company.providerUnresolved(f.atlas.worker_id),invoked);f.advance(30000);f.company.mandates.progress();assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);if(invoked){assert.equal(f.company.claimWorkNext(),undefined);assert.equal(occurrences(f)[0]!.state,'blocked');}else{assert.ok(f.company.claimWorkNext());}
}finally{await f.close();}}});

test('reopening before due preserves the future instant and produces no early or duplicate review',async()=>{const f=setup();let reopened:Store|undefined;try{activate(f);const s=schedule(f);closeCycle(f);const executions=f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n;await f.dispatcher.stop();f.store.close();reopened=new Store(join(f.dir,'company.sqlite'));const company=new Company(reopened,f.dir,process.cwd(),'fake');company.mandates.clock={now:f.time};company.recover();company.mandates.progress();assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM review_occurrences')!.n,0);assert.equal(company.mandates.schedule(s.schedule_id).next_due,s.next_due);assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM executions')!.n,executions);f.advance(59999);company.mandates.progress();assert.equal(company.claimWorkNext(),undefined);f.advance(1);company.mandates.progress();company.mandates.progress();assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM review_occurrences')!.n,1);assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);assert.ok(company.claimWorkNext());assert.equal(company.claimWorkNext(),undefined);
}finally{await f.dispatcher.stop();if(reopened)reopened.close();else f.store.close();}});

test('database reopen after persisted provider reference preserves invoked uncertainty and uninvoked recovery',async()=>{for(const invoked of [false,true]){const f=setup();let reopened:Store|undefined;try{activate(f);schedule(f);closeCycle(f);f.advance(60000);f.company.mandates.tick();const c=claim(f);f.company.conversations.prepareBinding(c.context,{worker_id:f.atlas.worker_id,runtime_type:'fake',runtime_reference:'persisted-before-process-loss',workspace_path:f.atlas.workspace_path,created_at:new Date().toISOString()});if(invoked){f.company.conversations.activateBinding(c.context);f.company.conversations.event(c.context,'runtime_turn_starting',{context_chars:100});}await f.dispatcher.stop();f.store.close();reopened=new Store(join(f.dir,'company.sqlite'));const company=new Company(reopened,f.dir,process.cwd(),'fake');company.mandates.clock={now:f.time};company.recover();company.mandates.progress();assert.equal(company.conversations.session(c.execution.session_id).runtime_reference,'persisted-before-process-loss');assert.equal(company.providerUnresolved(f.atlas.worker_id),invoked);f.advance(30000);company.mandates.progress();const next=company.claimWorkNext();if(invoked){assert.equal(next,undefined);assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM conversation_sessions')!.n,2);}else{assert.ok(next&&next.origin==='conversation');assert.notEqual(next.execution.session_id,c.execution.session_id);}assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM review_occurrences')!.n,1);assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM operating_cycles')!.n,2);
}finally{await f.dispatcher.stop();if(reopened)reopened.close();else f.store.close();}}});

test('known failures wait 30 then 60 seconds and exhaust the retry allowance without unbounded reviews',async()=>{const f=setup();try{activate(f);const first=claim(f);f.company.finish(first.execution.execution_id,{status:'failed',settled:true,error:'Controlled known failure one'});f.company.mandates.progress();f.advance(29999);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);f.advance(1);f.company.mandates.progress();const second=claim(f);f.company.finish(second.execution.execution_id,{status:'failed',settled:true,error:'Controlled known failure two'});f.company.mandates.progress();f.advance(59999);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);f.advance(1);f.company.mandates.progress();const third=claim(f);f.company.finish(third.execution.execution_id,{status:'failed',settled:true,error:'Controlled known failure three'});f.company.mandates.progress();assert.equal(f.store.get<{state:string}>('SELECT state FROM operating_cycles')!.state,'blocked');f.advance(3600000);f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM mandate_turns')!.n,3);assert.equal(f.company.providerUnresolved(f.atlas.worker_id),false);
}finally{await f.close();}});

test('cycle expiry cancels unstarted linked Tasks without erasing attempts or ordinary queued work',async()=>{const f=setup({max_cycle_minutes:1});try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});activate(f);const coordinator=claim(f),d=decision(f,coordinator.context);
  const linked=f.company.mandates.callTool(coordinator.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Bounded internal analysis',acceptance_criteria:'Report',constraints:'Internal only'}) as {task_id:string};
  f.company.mandates.callTool(coordinator.context,'wait','wait_for_internal_work',{summary:'Waiting for analysis'});f.company.finish(coordinator.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  const ordinary=f.company.createTask('human',scout,{...objective,objective:'Unrelated ordinary queued analysis'},null,'research');f.company.pause(true);const before=f.company.snapshot().executions.length;
  f.advance(60000);f.company.mandates.progress();f.company.mandates.progress();assert.equal(f.company.task(linked.task_id).status,'cancelled');assert.equal(f.company.task(ordinary.task_id).status,'queued');assert.ok(f.company.mandates.internalWork(linked.task_id));assert.ok(f.store.get("SELECT 1 FROM operating_cycles WHERE state='blocked' AND error LIKE 'Cycle wall-clock%'"));assert.equal(f.company.snapshot().executions.length,before);
  f.company.pause(false);assert.equal(f.company.claimNext()!.task.task_id,ordinary.task_id);
}finally{await f.close();}});

test('failed or interrupted mandate Tasks reject owner retry atomically and retain private sessions and fences',async()=>{for(const outcome of ['failed','interrupted'] as const){const f=setup();try{
  f.company.assignObjective(objective);const roster=f.company.claimNext()!,scout=f.company.callTool(roster.context,'hire','hire_worker',hire) as Worker;f.company.finish(roster.execution.execution_id,{status:'completed',summary:'Roster'});activate(f);const c=claim(f),d=decision(f,c.context);
  const task=f.company.mandates.callTool(c.context,'assign','assign_internal_task',{decision_id:d.decision_id,worker_id:scout.worker_id,objective:'Private internal analysis',acceptance_criteria:'Report',constraints:'Internal only'}) as {task_id:string};f.company.mandates.callTool(c.context,'wait','wait_for_internal_work',{summary:'Await result'});f.company.finish(c.execution.execution_id,{status:'completed',settled:true,summary:'Waiting'});
  const x=f.company.claimNext()!,session=f.company.mandates.taskSession(x.context,companyTools(scout))!;f.company.recordRuntimeEvent(x.context,'runtime_turn_starting',{context_chars:100});f.company.finish(x.execution.execution_id,{status:outcome,settled:outcome==='failed',error:'Controlled provider outcome'});
  const before=f.company.task(task.task_id),fenced=f.company.providerUnresolved(scout.worker_id);assert.equal(fenced,outcome==='interrupted');assert.throws(()=>f.company.retry(task.task_id,true),/single-attempt/);assert.deepEqual(f.company.task(task.task_id),before);assert.equal(f.company.providerUnresolved(scout.worker_id),fenced);assert.equal(f.store.get<{execution_id:string}>('SELECT execution_id FROM mandate_task_sessions WHERE session_id=?',session.session_id)!.execution_id,x.execution.execution_id);assert.equal(f.company.claimNext(),undefined);
}finally{await f.close();}}});

test('owner daily calendar dates resolve in mandate timezone, including spring gaps and autumn repeats',async()=>{for(const [now,date,time,expected] of [
  ['2026-10-05T18:00:00Z','2026-10-06','09:00','2026-10-06T16:00:00.000Z'],
  ['2026-03-07T18:00:00Z','2026-03-08','02:30','2026-03-08T10:00:00.000Z'],
  ['2026-10-31T18:00:00Z','2026-11-01','01:30','2026-11-01T08:30:00.000Z'],
]){const f=setup();try{f.advance(Date.parse(now!)-f.time());activate(f);const args={due_at:null,first_local_date:date,recurrence_kind:'daily',local_time:time,end_at:new Date(f.time()+3*86400000).toISOString(),occurrence_limit:2};const s=schedule(f,args);assert.equal(s.next_due,expected);assert.equal(s.timezone,'America/Vancouver');assert.equal(JSON.parse(s.recurrence).local_time,time);
  assert.throws(()=>schedule(f,{...args,schedule_id:s.schedule_id,due_at:expected}),/without an absolute due time/);assert.throws(()=>schedule(f,{...args,schedule_id:s.schedule_id,first_local_date:'2026-02-30'}),/does not exist/);assert.equal(f.company.mandates.schedule(s.schedule_id).version,1);
}finally{await f.close();}}});

// Personal Operator stabilization: explicit positive dispatch windows, no implicit grace.
for(const width of [-1,0,1,29999])test(`owner and worker reject ${width}ms dispatch window atomically and can correct it`,async()=>{
  const f=setup();try{activate(f);const x=claim(f),due=new Date(f.time()+60000).toISOString();
    const input={schedule_id:null,purpose:'One bounded internal review',initiative_id:null,due_at:due,recurrence_kind:'once',interval_seconds:null,local_time:null,occurrence_limit:1,end_at:new Date(Date.parse(due)+width).toISOString()};
    const before=f.store.get<{n:number}>('SELECT count(*) n FROM audit_events')!.n;
    assert.throws(()=>f.company.mandates.saveOwnerSchedule({mandate_id:f.m.mandate_id,...input}),/at least 30 seconds.*equal due\/end/);
    assert.throws(()=>f.company.mandates.callTool(x.context,'invalid-window','schedule_review',input),/at least 30 seconds/);
    for(const table of ['review_schedules','review_schedule_versions','review_occurrences'])assert.equal(f.store.get<{n:number}>(`SELECT count(*) n FROM ${table}`)!.n,0);
    assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM audit_events')!.n,before);
    assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tool_receipts WHERE execution_id=?',x.execution.execution_id)!.n,0);
    const corrected=f.company.mandates.callTool(x.context,'corrected-window','schedule_review',{...input,end_at:new Date(Date.parse(due)+30000).toISOString()}) as {next_due:string};
    assert.equal(corrected.next_due,due);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM tool_receipts WHERE execution_id=?',x.execution.execution_id)!.n,1);
  }finally{await f.close();}
});

for(const delay of [0,2,15000,30000])test(`one-time review dispatches once at due + ${delay}ms within its bounded window`,async()=>{
  const f=setup();try{activate(f);const s=schedule(f,{end_at:new Date(f.time()+90000).toISOString()});closeCycle(f);
    f.advance(59999);f.company.mandates.tick();assert.equal(occurrences(f).length,0);assert.equal(f.company.claimWorkNext(),undefined);
    f.advance(1+delay);f.company.mandates.tick();f.company.mandates.tick();assert.equal(occurrences(f).length,1);assert.equal(occurrences(f)[0]!.state,'queued');
    const x=closeCycle(f,true);assert.equal(occurrences(f)[0]!.state,'completed');
    const detail=JSON.parse(f.store.get<{detail:string}>("SELECT detail FROM audit_events WHERE type='mandate_review_dispatched' AND execution_id=?",x.execution.execution_id)!.detail);
    assert.equal(detail.nominal_due_at,s.next_due);assert.equal(detail.claimed_at,new Date(f.time()).toISOString());assert.equal(detail.lateness_ms,delay);assert.equal(detail.timing,delay===0?'on_time':'within_dispatch_window');
    f.advance(3600000);f.company.recover();f.company.mandates.progress();f.company.mandates.tick();assert.equal(f.company.claimWorkNext(),undefined);
    assert.equal(occurrences(f).length,1);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,2);assert.equal(f.runtime.calls.length,0);
  }finally{await f.close();}
});

for(const queued of [false,true])test(`hard end + 1ms expires ${queued?'queued':'undiscovered'} review without a model call`,async()=>{
  const f=setup();try{activate(f);schedule(f,{end_at:new Date(f.time()+90000).toISOString()});closeCycle(f);
    if(queued){f.advance(60000);f.company.mandates.tick();assert.equal(occurrences(f)[0]!.state,'queued');f.advance(30001);}else f.advance(90001);
    f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'cancelled');assert.match(occurrences(f)[0]!.reason!,/end.*(expired|before)/i);
    assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,1);assert.equal(f.runtime.calls.length,0);
  }finally{await f.close();}
});

for(const downtime of [59000,60002,90001])test(`restart at ${downtime}ms preserves one occurrence and bounded catch-up`,async()=>{
  const f=setup();let reopened:Store|undefined;try{activate(f);schedule(f,{end_at:new Date(f.time()+90000).toISOString()});closeCycle(f);f.store.close();f.advance(downtime);
    reopened=new Store(join(f.dir,'company.sqlite'));const company=new Company(reopened,f.dir,process.cwd(),'fake');company.mandates.clock={now:f.time};company.recover();company.mandates.progress();
    if(downtime<60000){assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM review_occurrences')!.n,0);f.advance(1002);company.mandates.progress();}
    company.mandates.progress();assert.equal(reopened.get<{n:number}>('SELECT count(*) n FROM review_occurrences')!.n,1);
    assert.equal(reopened.get<{state:string}>('SELECT state FROM review_occurrences')!.state,downtime>90000?'cancelled':'queued');
    const work=company.claimWorkNext();assert.equal(!!work,downtime<=90000);assert.equal(company.claimWorkNext(),undefined);
    assert.deepEqual(reopened.all('PRAGMA foreign_key_check'),[]);
  }finally{reopened?.close();await f.dispatcher.stop();}
});

test('invalid schedule edit preserves original version, consumed work, queued occurrence and audit',async()=>{
  const f=setup();try{activate(f);const s=schedule(f,{recurrence_kind:'interval',interval_seconds:60,occurrence_limit:3});closeCycle(f);f.advance(60000);f.company.mandates.tick();
    const snapshot=()=>['review_schedules','review_schedule_versions','review_occurrences','operating_cycles','conversation_requests','audit_events'].map(t=>f.store.all(`SELECT * FROM ${t}`));const before=snapshot();
    assert.throws(()=>schedule(f,{schedule_id:s.schedule_id,recurrence_kind:'interval',interval_seconds:60,occurrence_limit:3,end_at:new Date(f.time()+60000).toISOString()}),/at least 30 seconds/);assert.deepEqual(snapshot(),before);
    const edited=schedule(f,{schedule_id:s.schedule_id,recurrence_kind:'interval',interval_seconds:60,occurrence_limit:3,end_at:new Date(f.time()+90000).toISOString()});assert.equal(edited.version,2);assert.equal(edited.consumed,1);assert.equal(occurrences(f)[0]!.state,'superseded');
    f.advance(60002);f.company.mandates.tick();assert.equal(occurrences(f).filter(o=>o.state==='queued').length,1);assert.equal(occurrences(f)[1]!.schedule_version,2);assert.ok(f.company.claimWorkNext());assert.equal(f.company.claimWorkNext(),undefined);
  }finally{await f.close();}
});

test('legacy zero-width schedule is retained and expires without retroactive extension or replay',async()=>{
  const f=setup();try{activate(f);const s=schedule(f);closeCycle(f);
    // Reproduce an already-persisted pre-fix record, not an application save path.
    f.store.run('UPDATE review_schedules SET end_at=next_due WHERE schedule_id=?',s.schedule_id);const before=f.company.mandates.schedule(s.schedule_id);const versions=f.store.all('SELECT * FROM review_schedule_versions');
    f.advance(60002);f.company.recover();f.company.mandates.progress();assert.equal(occurrences(f)[0]!.state,'cancelled');assert.equal(f.company.mandates.schedule(s.schedule_id).end_at,before.end_at);assert.deepEqual(f.store.all('SELECT * FROM review_schedule_versions'),versions);assert.equal(f.company.claimWorkNext(),undefined);
  }finally{await f.close();}
});

for(const revoke of ['cancel_schedule','stop_mandate','disable_coordinator','revoke_participation'])test(`valid jitter window never bypasses ${revoke}`,async()=>{
  const f=setup();try{activate(f);const s=schedule(f,{end_at:new Date(f.time()+90000).toISOString()});closeCycle(f);f.advance(60002);f.company.mandates.tick();
    if(revoke==='cancel_schedule')f.company.mandates.controlSchedule({schedule_id:s.schedule_id,action:'cancel'});
    else if(revoke==='stop_mandate')f.company.mandates.control({mandate_id:f.m.mandate_id,action:'stop'});
    else if(revoke==='disable_coordinator')f.store.run('UPDATE workers SET enabled=0 WHERE worker_id=?',f.atlas.worker_id);
    else {const c=f.store.get<{conversation_id:string}>('SELECT conversation_id FROM mandate_conversations WHERE mandate_id=?',f.m.mandate_id)!;f.store.run('UPDATE conversation_participants SET active=0 WHERE conversation_id=? AND principal_id=?',c.conversation_id,f.atlas.principal_id);}
    f.company.mandates.progress();assert.equal(f.company.claimWorkNext(),undefined);assert.equal(f.store.get<{n:number}>('SELECT count(*) n FROM executions')!.n,1);assert.equal(f.runtime.calls.length,0);
  }finally{await f.close();}
});


test('first execution audit uses the authorization clock when claim recording crosses the hard end',async()=>{
  const f=setup();try{activate(f);schedule(f,{end_at:new Date(f.time()+90000).toISOString()});closeCycle(f);f.advance(90000);f.company.mandates.tick();
    const original=f.company.mandates.recordScheduleDispatch.bind(f.company.mandates);
    f.company.mandates.recordScheduleDispatch=(r,id,claimTime)=>{f.advance(1);original(r,id,claimTime);};
    const x=claim(f),detail=JSON.parse(f.store.get<{detail:string}>("SELECT detail FROM audit_events WHERE type='mandate_review_dispatched' AND execution_id=?",x.execution.execution_id)!.detail);
    assert.equal(detail.claimed_at,detail.end_at);assert.equal(Date.parse(detail.recorded_at),Date.parse(detail.end_at)+1);assert.equal(detail.timing,'within_dispatch_window');
    f.company.finish(x.execution.execution_id,{status:'failed',settled:true,error:'Known failure after first claim'});f.company.mandates.progress();f.advance(30000);f.company.mandates.progress();assert.ok(f.company.claimWorkNext());
    assert.equal(f.store.get<{n:number}>("SELECT count(*) n FROM audit_events WHERE type='mandate_review_dispatched'")!.n,1);
  }finally{await f.close();}
});
