import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {fixture} from '../dist/test/helpers.js';
import {createHttpServer} from '../dist/src/http/server.js';
test('owner browser creates passive mandate, admits visibly simulated evidence and controls schedules',async t=>{
  const f=fixture();f.company.initializeCEO();f.company.pause(true);f.dispatcher.start();const http=createHttpServer(f.company,f.dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await http.close();await f.close();assert.deepEqual(errors,[]);});const dir=join(process.cwd(),'.validation/prompt09/browser');mkdirSync(dir,{recursive:true});await page.goto(`http://127.0.0.1:${http.server.address().port}`);await page.getByText('Connected to headquarters',{exact:true}).waitFor();await page.locator('[data-tab=mandates]').click();await page.locator('#new-mandate').click();await page.locator('#mandate-form [name=title]').fill('Internal product strategy');await page.locator('#mandate-form [name=objective]').fill('Compare safe internal quality and adoption work.');await page.getByRole('button',{name:'Save passive draft',exact:true}).click();await page.locator('[data-mandate-action=activate]').waitFor();assert.equal(f.runtime.calls.length,0);assert.equal(f.company.snapshot().tasks.length,0);
  await page.locator('#add-observation').click();await page.locator('#observation-form [name=mode]').selectOption('simulated_fixture');for(const [key,value] of Object.entries({name:'SIMULATED baseline',source:'fixture://browser/test',provenance:'Owner-entered synthetic test',body:'<img src=x onerror="window.injected=1"> SIMULATED: no real revenue result.',limitations:'Not live metrics',missingness:'Business outcome unknown'}))await page.locator(`#observation-form [name=${key}]`).fill(value);await page.getByRole('button',{name:'Admit labelled observation',exact:true}).click();await page.locator('.evidence-mode.simulated').waitFor();assert.equal(await page.locator('#view img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);await page.screenshot({path:join(dir,'labelled-observation.png')});
  await page.locator('[data-mandate-action=activate]').click();await page.locator('[data-mandate-action=pause]').waitFor();assert.equal(f.runtime.calls.length,0);await page.locator('#new-review').click();
  const due=await page.locator('#review-form [name=due_at]').inputValue();
  for(const end of [due,new Date(Date.parse(due+'Z')-60000).toISOString().slice(0,16)]){
    await page.locator('#review-form [name=end_at]').fill(end);await page.getByRole('button',{name:'Save review schedule',exact:true}).click();
    assert.match(await page.locator('#review-window-error').textContent(),/at least 30 seconds/);assert.equal(f.company.store.get('SELECT count(*) n FROM review_schedules').n,0);
  }
  await page.locator('#review-form [name=end_at]').fill(new Date(Date.parse(due+'Z')+120000).toISOString().slice(0,16));
  assert.equal(await page.locator('#review-window-error').textContent(),'');await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.locator('[data-edit-review]').waitFor();assert.equal(f.company.store.get('SELECT count(*) n FROM review_schedules').n,1);await page.locator('[data-edit-review]').click();await page.locator('#review-form [name=purpose]').fill('Changed future purpose');await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.getByRole('heading',{name:'Changed future purpose active'}).waitFor();assert.equal(f.company.store.get('SELECT version FROM review_schedules').version,2);
  await page.locator('[data-review-control=pause]').click();await page.locator('[data-review-control=resume]').waitFor();await page.locator('[data-review-control=cancel]').click();await page.getByRole('heading',{name:'Changed future purpose cancelled'}).waitFor();await page.locator('[data-mandate-action=stop]').click();await page.getByRole('heading',{name:'Internal product strategy stopped'}).waitFor();await page.screenshot({path:join(dir,'stopped-history.png')});assert.equal(f.runtime.calls.length,0);
});

test('UTC browser creates and edits Vancouver daily reviews across normal and DST dates',async t=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());
  for(const [now,date,time,expected,nextDate,nextExpected] of [
    ['2026-10-05T18:00:00Z','2026-10-06','09:00','2026-10-06T16:00:00.000Z','2026-10-07','2026-10-07T16:00:00.000Z'],
    ['2026-03-07T18:00:00Z','2026-03-08','02:30','2026-03-08T10:00:00.000Z','2026-03-09','2026-03-09T09:30:00.000Z'],
    ['2026-10-31T18:00:00Z','2026-11-01','01:30','2026-11-01T08:30:00.000Z','2026-11-02','2026-11-02T09:30:00.000Z'],
  ]){
    const f=fixture(),atlas=f.company.initializeCEO();f.company.pause(true);f.company.mandates.clock={now:()=>Date.parse(now)};
    const m=f.company.mandates.create({title:'Vancouver daily review',objective:'Review internal evidence',success_criteria:'Grounded choices',stop_criteria:'Owner bounds',constraints:'Internal only',resources:'Bounded analysis',coordinator_id:atlas.worker_id,envelope:{timezone:'America/Vancouver'}});f.company.mandates.control({mandate_id:m.mandate_id,action:'activate'});
    const http=createHttpServer(f.company,f.dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));const page=await browser.newPage({timezoneId:'UTC'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    try{
      await page.goto(`http://127.0.0.1:${http.server.address().port}`);await page.getByText('Connected to headquarters',{exact:true}).waitFor();await page.locator('[data-tab=mandates]').click();await page.locator(`[data-mandate="${m.mandate_id}"]`).click();await page.locator('#new-review').click();await page.locator('#review-form [name=recurrence_kind]').selectOption('daily');assert.equal(await page.locator('#review-form [name=due_at]').isVisible(),false);
      await page.locator('#review-form [name=first_local_date]').fill(date);await page.locator('#review-form [name=local_time]').fill(time);await page.locator('#review-form [name=end_at]').fill(new Date(Date.parse(now)+3*86400000).toISOString().slice(0,16));await page.locator('#review-form [name=occurrence_limit]').fill('2');await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.locator('[data-edit-review]').waitFor();let s=f.company.store.get('SELECT * FROM review_schedules');assert.equal(s.next_due,expected);assert.equal(s.timezone,'America/Vancouver');
      await page.locator('[data-edit-review]').click();assert.equal(await page.locator('#review-form [name=first_local_date]').inputValue(),date);assert.equal(await page.locator('#review-form [name=local_time]').inputValue(),time);await page.locator('#review-form [name=first_local_date]').fill(nextDate);await page.getByRole('button',{name:'Save review schedule',exact:true}).click();await page.locator('#review-form').waitFor({state:'hidden'});s=f.company.store.get('SELECT * FROM review_schedules');assert.equal(s.next_due,nextExpected);assert.equal(s.version,2);assert.equal(f.runtime.calls.length,0);assert.deepEqual(errors,[]);
    }finally{await page.close();await http.close();await f.close();}
  }
});
