import {test} from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdirSync} from 'node:fs';
import {crc32,deflateSync} from 'node:zlib';
import {chromium} from 'playwright';
import {publicationFixture} from '../dist/test/fixtures/publication/support.js';
import {Company} from '../dist/src/control/company.js';
import {Dispatcher} from '../dist/src/control/dispatcher.js';
import {FakeRuntime} from '../dist/test/helpers.js';
import {sha256} from '../dist/scripts/investment-contracts/schema.js';
import {createHttpServer} from '../dist/src/http/server.js';
function png(){function chunk(type,data){const t=Buffer.from(type),n=Buffer.alloc(4),crc=Buffer.alloc(4);n.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([t,data])));return Buffer.concat([n,t,data,crc]);}const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(1,0);ihdr.writeUInt32BE(1,4);Buffer.from([8,6,0,0,0]).copy(ihdr,8);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(Buffer.from([0,255,0,0,255]))),chunk('IEND',Buffer.alloc(0))]);}
for(const viewport of [{width:1440,height:1000},{width:390,height:844}])test(`owner exact preview, PNG review, scope invalidation and explicit consent (${viewport.width}px)`,async t=>{
 const f=publicationFixture(),bytes=png(),privateBytes=Buffer.from('Private source canary: do not export');f.artifact({id:'private-artifact',version:1,title:'Synthetic red pixel',createdAt:f.clock.now(),approvedAt:f.clock.now(),sourceHash:sha256(privateBytes),bytes,contentType:'image/png',limitations:['Synthetic test pixel']},privateBytes);
 const runtime=new FakeRuntime(),company=new Company(f.store,f.dir,process.cwd(),'fake',undefined,undefined,{sources:[f.source],destinations:[f.destination],clock:f.clock}),dispatcher=new Dispatcher(company,runtime),http=createHttpServer(company,dispatcher,join(process.cwd(),'public'));await new Promise(r=>http.server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:process.env.BOTSQUAD_BROWSER_CHANNEL??'chrome',headless:true}),page=await browser.newPage({viewport,timezoneId:'UTC'}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();await http.close();await dispatcher.stop();assert.deepEqual(errors,[]);assert.equal(runtime.calls.length,0);f.cleanup();});
 await page.goto(`http://127.0.0.1:${http.server.address().port}/investment-publication`);await page.waitForFunction(()=>!document.querySelector('#preview-button').disabled);assert.equal(f.store.all('SELECT * FROM investment_public_jobs').length,0);
 for(const type of f.envelope.eventTypes)await page.locator(`input[name="eventTypes"][value="${type}"]`).check();await page.locator('input[name="contentTypes"][value="image/png"]').check();await page.locator('[name=expiresAt]').fill('2026-03-10T00:00');for(const field of ['maxAttempts','maxBytes','maxQueueBytes','maxAgeSeconds','writesPerMinute'])await page.locator(`[name=${field}]`).fill(String(f.envelope[field]));
 let enter,release;const entered=new Promise(r=>enter=r),released=new Promise(r=>release=r);await page.route('**/api/investment-publication/preview',async route=>{const response=await route.fetch();enter();await released;await route.fulfill({response});},{times:1});await page.locator('#preview-button').click();await entered;await page.locator('[name=maxAttempts]').fill('98');release();await page.waitForResponse(r=>r.url().endsWith('/preview'));assert.equal(await page.locator('#preview-panel').isVisible(),false);assert.equal(await page.locator('#consent').isDisabled(),true);
 await page.locator('#preview-button').click();await page.locator('#preview-panel').waitFor({state:'visible'});assert.equal(f.store.all('SELECT * FROM investment_public_jobs').length,0);await page.locator('#preview-content summary').click();await page.waitForFunction(()=>document.querySelector('#preview-content img')?.naturalWidth===1);assert.equal((await page.locator('#preview-panel').textContent()).includes('Private source canary'),false);
 await page.locator('#consent-check').check();await page.locator('[name=maxAttempts]').fill('99');assert.equal(await page.locator('#preview-panel').isVisible(),false);assert.equal(await page.locator('#consent').isDisabled(),true);
 await page.locator('#preview-button').click();await page.locator('#preview-panel').waitFor({state:'visible'});await page.locator('#consent-check').check();await page.locator('#consent').click();await page.getByText('Exact consent saved; delivery is queued.',{exact:true}).waitFor();assert.ok(f.store.all('SELECT * FROM investment_public_jobs').length>0);assert.equal(f.store.all('SELECT * FROM investment_public_attempts').length,0);
 await page.getByRole('button',{name:'Pause publication',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#channels').textContent.includes('paused ·'));await page.getByRole('button',{name:'Revoke consent',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#channels').textContent.includes('revoked ·'));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));mkdirSync('/private/tmp/botsquad-inv07-browser',{recursive:true});await page.screenshot({path:`/private/tmp/botsquad-inv07-browser/owner-${viewport.width}.png`,fullPage:true});
});
