import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { rmSync } from 'node:fs';
import { Store } from '../src/persistence/store.js';
import { PublicationService } from '../src/control/publication/service.js';
for(const phase of ['before_stage_commit','before_receipt_commit'])test(`actual SIGKILL at ${phase} retains transactional publication fences`,async t=>{
 const fixture=new URL('./fixtures/publication/support.js',import.meta.url).href;
 const script=`import {publicationFixture} from ${JSON.stringify(fixture)};import {createHash} from 'node:crypto';const f=publicationFixture();const transport={send:async(d,m)=>{const b=JSON.parse(m.body);return {status:201,contentType:'application/json',bytes:Buffer.from(JSON.stringify({schemaVersion:'1.0',batchId:b.batchId,experimentId:b.experimentId,runId:b.runId,bodyDigest:createHash('sha256').update(m.body).digest('hex'),receiptId:'test-receipt',receivedAt:f.clock.now(),acceptedIds:b.events.map(e=>e.eventId),duplicateIds:[],receiverCursor:'test-cursor',watermark:{journalSequence:null,journalHash:null,sourceSequence:b.events.at(-1).sourceSequence,sourceGaps:false}}))};}};const s=f.configured(transport,{fault:point=>{if(point===process.argv[1]){process.stdout.write(JSON.stringify({path:f.path,dir:f.dir})+'\\n');process.kill(process.pid,'SIGKILL');}}});const p=s.preview(f.envelope),g=s.consent({previewId:p.id,digest:p.digest});await s.deliver({channelId:g.channelId});throw new Error('kill not reached');`;
 const child=spawn(process.execPath,['--input-type=module','-e',script,phase],{stdio:['ignore','pipe','pipe']});let output='',diagnostics='';child.stdout.on('data',data=>{output+=String(data);});child.stderr.on('data',data=>{diagnostics+=String(data);});const timer=setTimeout(()=>child.kill('SIGKILL'),5000);t.after(()=>clearTimeout(timer));
 const {code,signal}=await new Promise<{code:number|null;signal:string|null}>((resolve,reject)=>{child.once('error',reject);child.once('exit',(code,signal)=>resolve({code,signal}));});assert.equal(code,null,diagnostics);assert.equal(signal,'SIGKILL');assert.ok(output,diagnostics);const {path,dir}=JSON.parse(output) as {path:string;dir:string};t.after(()=>rmSync(dir,{recursive:true,force:true}));const store=new Store(path);try{
  assert.equal(store.get<{integrity_check:string}>('PRAGMA integrity_check')!.integrity_check,'ok');assert.deepEqual(store.all('PRAGMA foreign_key_check'),[]);
  if(phase==='before_stage_commit'){assert.equal(store.all('SELECT * FROM investment_public_grants').length,0);assert.equal(store.all('SELECT * FROM investment_public_jobs').length,0);}else{assert.equal(store.all('SELECT * FROM investment_public_attempts').length,1);assert.equal(store.all('SELECT * FROM investment_public_results').length,0);const channel=store.get<{id:string}>('SELECT id FROM investment_public_channels')!;const s=new PublicationService(store);await assert.rejects(s.deliver({channelId:channel.id}),/restore_reconciliation_required/);assert.equal(store.get<{n:number}>("SELECT count(*) n FROM investment_public_jobs WHERE state='sending' AND needs_receipt=1")!.n,1);}
 }finally{store.close();}
});
