import {tool,type ToolDefinition} from './adapter.js';
const string={type:'string'},list={type:'array',items:string,maxItems:20};
/** Paper tools are supplied only in an owner-bound investment discussion schema. */
export function paperTools():ToolDefinition[]{return [
 tool('paper_inspect','Inspect only this frozen paper run, exact proposal/review records and publication admission health. No prices or balances may be supplied.',{}),
 tool('paper_propose','Commit your own exact paper proposal revision with rationale, alternatives, risks and invalidation condition. HOLD is valid; one BUY or SELL order at most. Market observation IDs are trusted prices; contribution/evidence IDs are scoped research provenance and must have been read in full this execution. Never invent another employee approval.',{decisionId:string,revision:{type:'integer',minimum:1},action:{type:'string',enum:['HOLD','BUY','SELL']},marketObservationIds:list,order:{anyOf:[{type:'null'},{type:'object',additionalProperties:false,required:['instrumentId','side','quantity','priceGuard','targetSession'],properties:{instrumentId:string,side:{type:'string',enum:['BUY','SELL']},quantity:string,priceGuard:string,targetSession:string}}]},rationale:string,alternatives:{...list,minItems:1,maxItems:10},risks:{...list,minItems:1,maxItems:10},invalidationCondition:string,contributionIds:list,evidenceIds:list}),
 tool('paper_read_proposal','Read the complete immutable proposal and exact provenance in this scope. Required in the current execution before review or submission.',{proposalId:string}),
 tool('paper_review','Record your own independent approval or rejection of the complete unchanged proposal hash. The author must be a different employee whose producing turn settled. Supply substantive rationale and retained dissent. Generic discussion synthesis review is not paper approval.',{proposalId:string,proposalHash:string,disposition:{type:'string',enum:['approve','reject']},rationale:string,dissent:list,evidenceIds:list}),
 tool('paper_submit','Submit the exact latest independently reviewed paper proposal. Requires completed upstream executions, active run/grant and trusted admission. A BUY can wait for owner publication preview approval; no backdating, prices, fills or publication authority.',{proposalId:string,reviewId:string,proposalHash:string}),
];}
export const investmentInstructions=`This fresh conversation is an owner-scoped investment discussion. The paper_* tools are the only additional paper authority beyond ordinary discussion. They never grant real financial, publication, account, price-writing or external-action permission. Rely only on the supplied experiment responsibility and scoped evidence. Preserve genuine alternatives, uncertainty and dissent; HOLD is valid. Never invent other employees' speech or approval. The same proposal revision must be independently reviewed. A committed tool result is not proof that its producing runtime settled. Respect waiting for exact owner publication review; do not bypass it or retry blindly. End each discussion turn after its structured contribution as usual.`;
