import type {ToolDefinition} from './adapter.js';
const str={type:'string'},nullable={type:['string','null']},ids={type:'array',items:str,maxItems:16};
const tool=(name:string,description:string,properties:Record<string,unknown>):ToolDefinition=>({name,description,inputSchema:{type:'object',properties,required:Object.keys(properties),additionalProperties:false}});
export function mandateTools():ToolDefinition[]{return [
  tool('inspect_mandate','Inspect the current bounded mandate, cycle, evidence catalog, eligible workers and outstanding work. Catalogs/previews are not evidence-body delivery. No unrelated private history.',{}),
  tool('read_mandate_record','Read an original observation, decision, initiative, linked Task/artifact or completed group synthesis in this mandate. Begin offset 0 and follow next_offset to receive the entire record before citing it. Each execution must establish its own evidence delivery.',{record_id:str,offset:{type:'integer',minimum:0}}),
  tool('propose_initiative','Record one useful hypothesis, its mechanism, desired observable outcome and assumptions. This is interpretation, never a measured observation.',{title:str,mechanism:str,expected_outcome:str,assumptions:str}),
  tool('convene_working_group','Choose two to six eligible workers (including facilitator and synthesizer) to investigate a useful strategic question. Explicitly export selected fully read mandate observations to that audience. This is bounded deliberation, not a Task; current individual discussion research grants still apply. After creating work use wait_for_internal_work and end.',{topic:str,desired_output:str,constraints:str,participant_ids:ids,facilitator_id:str,synthesizer_id:str,observation_ids:ids,allow_research:{type:'boolean'}}),
  tool('record_strategic_decision','Append an attributable strategic decision. Compare real alternatives; cite fully delivered record IDs, contrary evidence and unknowns. If no evidence was available explicitly explain missing_evidence. A recommendation grants no external action. scale is only an internal strategic disposition.',{initiative_id:nullable,disposition:{type:'string',enum:['continue','iterate','pivot','stop','scale']},recommendation:str,rationale:str,alternatives:str,evidence_ids:ids,contrary_evidence:str,unknowns:str,missing_evidence:nullable}),
  tool('assign_internal_task','Separately assign one bounded analysis/research Task to your existing eligible direct-report researcher or product manager, explicitly linked to a decision in this cycle. Choose evidence_ids from fully read observations/results to export the exact source bodies (12000 characters total). The assignee cannot access your mandate history or infer missing evidence from an ID in prose. No source/repository/infrastructure/approval tools are added. Research requires the assignee’s own current Task grant. Wait for the result before closing.',{decision_id:str,worker_id:str,objective:str,acceptance_criteria:str,constraints:str,evidence_ids:ids}),
  tool('schedule_review','Persist a useful bounded review under the owner scheduling envelope. Use current clock_now to choose an absolute due_at, after expected internal work. For one-time set recurrence_kind=once and interval_seconds/local_time null. Daily uses HH:mm and the mandate IANA timezone. Count/end bound every recurrence. Existing schedule_id updates its future version; history stays immutable.',{schedule_id:nullable,purpose:str,initiative_id:nullable,due_at:str,recurrence_kind:{type:'string',enum:['once','interval','daily']},interval_seconds:{type:['integer','null']},local_time:nullable,occurrence_limit:{type:'integer'},end_at:str}),
  tool('wait_for_internal_work','Commit this coordinator turn and release its execution slot. Trusted completion events wake one continuation after the linked work settles. At least one unreviewed internal item is required. End immediately; do not poll.',{summary:str}),
  tool('complete_cycle','Commit a source-linked cycle summary after evaluating completed internal work and recording a decision. A future review must be persisted, or stop must explicitly end the mandate. Trusted code closes only after provider settlement. End immediately.',{summary:str,stop:{type:'boolean'}}),
];}
export const mandateInstructions=`You are the coordinator of a durable BotSquad strategic mandate. This is a company review, distinct from a Task, direct chat and working-group discussion.
Decide useful investigations, participants, hypotheses, alternatives and internal work from the supplied situation. Do not follow a predetermined strategy or invent other workers' speech. Your mandate objective is strategic direction, never a grant. Trusted envelope, capabilities, current grants and existing approval boundaries intersect.
Read relevant evidence bodies before reasoning or citing; catalogs/previews are not body delivery. Always include the integer offset in read_mandate_record: start at offset 0 and follow next_offset. When next_offset is null and fully_delivered is true, that record is complete: do not call it again in this execution. Correct a rejected call from its error; never repeat the same failed arguments. Preserve original evidence mode, source, observation period, recording time, missingness and limitations. SIMULATED_FIXTURE and SANITIZED_SNAPSHOT never imply actual production metrics or real business success. You may formulate hypotheses, but cannot create or edit observations. Initiatives and prior decisions are context, not measurements; they cannot alone establish factual support.
Research and deliberation use existing eligible workers and their current grants. Choose a useful team if deliberation will improve the decision. A group is not an assignment: separately create a decision-linked internal analysis/research Task if permitted and useful. You cannot hire, grant authority, approve, publish, spend, contact users, change external systems or use a browser/computer. Project/engineering proposals may be analysis artifacts only.
Record attributable choices with alternatives, evidence, dissent/contrary findings, unknowns and rationale. Review previous decisions and any intervening observations before deciding whether to continue, iterate, pivot, stop or scale. An unchanged strategy is valid when justified; a pivot is never required.
At most 20 tool calls, 48000 retrieved characters and one committed coordinator outcome per execution. Reserve calls for final commitment. A working group or Task runs after you release this slot: call wait_for_internal_work, then END; do not wait or poll. After results, read/evaluate them and record an appropriate next decision. Persist a useful future schedule within the envelope, then complete_cycle. On a later scheduled cycle evaluate the intervening evidence and original hypothesis explicitly. End if stop criteria or bounds require it. State real blockers honestly.
Use public-facing operational explanations, not hidden provider reasoning. Durable records remain authoritative across provider-context replacement.`;
