import {SimulatorProjectionSource,type PublicationDescription,type DecisionDerivative,type ProjectionEmit} from './simulator-source.js';
import type {Store} from '../../persistence/store.js';
import type {SimulationClock} from '../investment.js';
import type {Material,ProjectionContext,Origin} from '../../domain/publication/types.js';
import type {Decision,Review,Journal} from '../../domain/investment/types.js';
import type {TeamScope,TeamEnvelope,PaperProposal,PaperReview,PaperNarrative} from '../../domain/investment-team/types.js';
import type {WorkingGroup,GroupEvidence,GroupSynthesis} from '../../domain/discussions.js';
import type {Actor,RecordRef,Source} from '../../../contracts/investment/v1/types.js';
import {hash} from '../../domain/investment/identity.js';
import {ensure} from '../../domain/investment/arithmetic.js';
import {sha256} from '../../../scripts/investment-contracts/schema.js';
import {createHash} from 'node:crypto';
const textHash=(s:string)=>createHash('sha256').update(JSON.stringify(s)).digest('hex');
interface Contribution {message_id:string;body:string;worker_id:string|null;execution_id:string|null;created_at:string;revision:number;kind:string;evidence_ids:string;contribution_ids:string}
interface Provenance {kind:string;id:string;hash:string;at:string}
/** Explicit trusted publication selection. Missing rights never authorize copying research excerpts. */
export interface TeamPublicationSelection {
 groupId:string; runtimeEvidence:'recorded_employee'|'fake_runtime_fixture';
 evidenceRights:Record<string,'owner_authored'|'licensed_publication'>;
}
/** Reads committed records, never supplied substitute employee prose. All output still needs exact owner preview/consent. */
export class CommittedTeamPublicationSource extends SimulatorProjectionSource {
 constructor(id:string,title:string,db:Store,clock:SimulationClock,operator:string,runId:string,description:PublicationDescription,private readonly selection:TeamPublicationSelection){super(id,title,db,clock,operator,runId,description);ensure(description.artifacts.length===0,'team_source_uses_committed_artifacts');}
 private group(){const g=this.db.get<WorkingGroup>('SELECT * FROM working_groups WHERE group_id=?',this.selection.groupId);ensure(g,'publication_group_missing');return g;}
 private scope(){const s=this.db.get<TeamScope>('SELECT * FROM investment_team_scopes WHERE group_id=?',this.selection.groupId);if(s){const g=this.group();ensure(g.scope_version===s.group_scope&&hash(this.db.all<{worker_id:string}>('SELECT worker_id FROM conversation_participants WHERE conversation_id=? AND active=1 AND worker_id IS NOT NULL',g.conversation_id).map(p=>p.worker_id).sort())===hash(this.participants.sort()),'publication_team_sharing_withdrawn');const e=JSON.parse(s.envelope) as TeamEnvelope;ensure(e.audience==='public_candidate','private_pilot_publication_prohibited');ensure(s.run_id===this.privateRunId&&hash({envelope:e,configuration:s.configuration_hash,groupScope:s.group_scope,context:s.context_hash})===s.digest,'publication_team_scope_mismatch');ensure(hash(e.participants.map(p=>p.workerId).sort())===hash(this.participants.sort()),'publication_team_roster_mismatch');for(const p of e.participants){const w=this.description.workers[p.workerId];ensure(w&&w.name===p.name&&hash(w.responsibilities)===hash([p.responsibility]),'publication_team_identity_mismatch');}}return s;}
 private contributions(){return this.db.all<Contribution>("SELECT m.message_id,m.body,m.worker_id,m.execution_id,m.created_at,c.revision,c.kind,c.evidence_ids,c.contribution_ids FROM discussion_contributions c JOIN conversation_messages m USING(message_id) WHERE c.group_id=? ORDER BY c.revision",this.selection.groupId);}
 private evidence(){return this.db.all<GroupEvidence>('SELECT * FROM group_evidence WHERE group_id=? ORDER BY revision',this.selection.groupId);}
 private syntheses(){return this.db.all<GroupSynthesis>('SELECT * FROM group_syntheses WHERE group_id=? ORDER BY version',this.selection.groupId);}
 private settled(executionId:string){const e=this.db.get<{status:string;provenance_status:string;runtime_adapter:string}>('SELECT * FROM executions WHERE execution_id=?',executionId);ensure(e&&e.status==='completed'&&e.provenance_status==='recorded'&&!this.db.get('SELECT 1 FROM execution_runtime_attempts WHERE execution_id=? AND unresolved=1',executionId)&&!this.db.get('SELECT 1 FROM research_operations WHERE execution_id=? AND unresolved=1',executionId),'publication_employee_execution_unsettled');ensure(this.selection.runtimeEvidence==='fake_runtime_fixture'||!/(fake|fixture|mock)/i.test(e.runtime_adapter),'publication_fixture_employee_claim');}
 protected sourceLimitations(){return this.selection.runtimeEvidence==='fake_runtime_fixture'?['Synthetic market data and fake runtime records; no actual employee execution is claimed.']:['Synthetic market data. Employee attribution comes from settled recorded executions; no observed market price or live operation is claimed.'];}
 protected rosterKind(){return 'committed_team_scope';}
 protected validateRoster(){const g=this.group();ensure(hash(this.db.all<{worker_id:string}>('SELECT worker_id FROM conversation_participants WHERE conversation_id=? AND active=1 AND worker_id IS NOT NULL',g.conversation_id).map(p=>p.worker_id).sort())===hash(this.participants.sort()),'publication_team_roster_mismatch');this.scope();}
 protected sourceEvidence(){return {scope:this.scope()??null,group:this.group(),selection:this.selection,contributions:this.contributions(),evidence:this.evidence(),syntheses:this.syntheses(),executions:this.db.all('SELECT e.execution_id,e.status,e.provenance_status,e.runtime_adapter FROM executions e JOIN investment_team_executions t USING(execution_id) JOIN investment_team_scopes s USING(scope_id) WHERE s.group_id=?',this.selection.groupId),proposals:this.db.all('SELECT p.* FROM investment_team_proposals p JOIN investment_team_scopes s USING(scope_id) WHERE s.group_id=?',this.selection.groupId),reviews:this.db.all('SELECT r.* FROM investment_team_reviews r JOIN investment_team_scopes s USING(scope_id) WHERE s.group_id=?',this.selection.groupId)};}
 private synthesisRef(s:GroupSynthesis,ctx:ProjectionContext):RecordRef {const version=this.syntheses().filter(p=>p.worker_id===s.worker_id&&p.version<=s.version).length;return {kind:'artifact',id:ctx.identity('artifact',`synthesis:${s.group_id}:${s.worker_id}`),version,relation:'supports'};}
 private contributionRef(c:Contribution,ctx:ProjectionContext):RecordRef {const synthesis=this.syntheses().find(s=>s.execution_id===c.execution_id);if(synthesis)return this.synthesisRef(synthesis,ctx);if(c.kind==='charter')return {kind:'discussion',id:ctx.identity('discussion',this.group().group_id),version:1,relation:'supports'};return {kind:c.worker_id?'contribution':'artifact',id:ctx.identity(c.worker_id?'contribution':'artifact',c.message_id),version:1,relation:'supports'};}
 private refs(rows:Provenance[],ctx:ProjectionContext):RecordRef[]{return rows.map(p=>{if(p.kind==='contribution'){const c=this.contributions().find(c=>c.message_id===p.id);ensure(c&&hash(c.body)===p.hash,'publication_contribution_source_mismatch');if(c.execution_id)this.settled(c.execution_id);return this.contributionRef(c,ctx);}const e=this.evidence().find(e=>e.evidence_id===p.id);ensure(e&&hash(e.content)===p.hash&&this.selection.evidenceRights[e.evidence_id],'publication_evidence_rights_required');if(e.execution_id)this.settled(e.execution_id);return {kind:'artifact',id:ctx.identity('artifact',p.id),version:1,relation:'supports'};});}
 private references(contributions:string[],evidence:string[],ctx:ProjectionContext){return this.refs([...contributions.map(id=>{const c=this.contributions().find(c=>c.message_id===id);ensure(c,'publication_contribution_missing');return {kind:'contribution',id,hash:hash(c.body),at:c.created_at};}),...evidence.map(id=>{const e=this.evidence().find(e=>e.evidence_id===id);ensure(e,'publication_evidence_missing');return {kind:'evidence',id,hash:hash(e.content),at:e.created_at};})],ctx);}
 protected decisionDerivative(decision:Decision,r:Review,j:Journal,ctx:ProjectionContext):DecisionDerivative {
  const s=this.scope();ensure(s,'publication_team_scope_required');const p=this.db.get<PaperProposal>('SELECT * FROM investment_team_proposals WHERE scope_id=? AND decision_id=? AND revision=?',s.scope_id,decision.decisionId,decision.revision),review=this.db.get<PaperReview>('SELECT * FROM investment_team_reviews WHERE scope_id=? AND review_id=?',s.scope_id,r.id);
  ensure(p&&review&&p.simulator_hash===decision.hash&&review.simulator_hash===hash(r)&&review.proposal_id===p.proposal_id&&review.proposal_hash===p.proposal_hash&&p.worker_id===decision.author&&review.worker_id===r.reviewer&&p.worker_id!==review.worker_id,'publication_exact_employee_review_required');this.settled(p.execution_id);this.settled(review.execution_id);
  const narrative=JSON.parse(p.narrative) as PaperNarrative,provenance=JSON.parse(p.provenance) as Provenance[];ensure(hash({scope:s.digest,executionId:p.execution_id,proposal:JSON.parse(p.command),narrative,provenance})===p.proposal_hash,'publication_proposal_integrity');
  // Canonical v1 has no standalone price-observation record; refuse an absent evidence mapping.
  ensure(decision.evidence.length===0,'publication_standalone_price_evidence_unsupported_v1');
  return {...narrative,reviewRationale:review.rationale,dissent:JSON.parse(review.dissent),evidence:this.refs(provenance,ctx),reviewEvidence:this.refs(JSON.parse(review.evidence),ctx),sources:[],origin:{kind:'committed_paper_review',id:review.review_id,version:String(p.revision),hash:hash({proposal:p,review,journal:j.hash})}};
 }
 protected contentRights(material:Material){this.scope();for(const c of material.contents){let original:string;if(c.origin.kind==='team_evidence'){const e=this.evidence().find(e=>e.evidence_id===c.origin.id);ensure(e&&this.selection.evidenceRights[e.evidence_id]&&textHash(e.content)===e.sha256,'publication_evidence_rights_required');if(e.execution_id)this.settled(e.execution_id);original=e.content;}else if(c.origin.kind==='team_note'){const note=this.contributions().find(n=>n.message_id===c.origin.id);ensure(note&&!note.worker_id,'publication_owner_note_source');original=note.body;}else{const s=this.syntheses().find(s=>s.synthesis_id===c.origin.id);ensure(s&&textHash(s.content)===s.sha256,'publication_synthesis_source_mismatch');this.settled(s.execution_id);original=s.content;}ensure(c.origin.hash===hash({original:hash(original),derivative:sha256(c.bytes)}),'publication_artifact_source_mismatch');}}
 protected extra(ctx:ProjectionContext,material:Material,emit:ProjectionEmit){const g=this.group(),s=this.scope();if(!s)return;const pub=ctx.identity;const discussionId=pub('discussion',g.group_id),origin:Origin={kind:'team_discussion',id:g.group_id,version:String(s.group_scope),hash:hash({topic:g.topic,desiredOutput:g.desired_output,constraints:g.constraints,scope:s.digest})};
  emit('discussion.opened',{discussionId,topic:g.topic,charter:`${g.desired_output}\n${g.constraints}`,audiencePolicyVersion:ctx.policyVersion,participants:this.participants.map(p=>pub('worker',p))},`discussion:${g.group_id}`,g.created_at,origin);
  const artifact=(key:string,version:number,title:string,original:string,bytes:Buffer,at:string,actor:Actor,kind:string,rights:'owner_authored'|'licensed_publication',relationships:RecordRef[]=[],sources:Source[]=[],publicKey=key)=>{const artifactId=pub('artifact',publicKey),o={kind,id:key,version:String(version),hash:hash({original:hash(original),derivative:sha256(bytes)})};material.contents.push({origin:o,contentType:'text/markdown',bytes});if(version===1)emit('artifact.registered',{artifactId,title,author:actor,status:'awaiting_publication',reason:null,relationships},`team-artifact:${key}`,at,o,actor);emit('artifact.published',{artifactId,version,title,author:actor,createdAt:at,publishedAt:at,contentType:'text/markdown',sizeBytes:bytes.length,sha256:sha256(bytes),relationships,sources,rights,limitations:this.sourceLimitations(),supersedes:version>1?{kind:'artifact',id:artifactId,version:version-1,relation:'supersedes'}:null,derivative:true},`team-artifact:${key}:1`,at,o,actor);};
  for(const e of this.evidence()){const rights=this.selection.evidenceRights[e.evidence_id],worker=e.execution_id?this.db.get<{worker_id:string}>('SELECT worker_id FROM executions WHERE execution_id=?',e.execution_id)?.worker_id:null,actor:Actor=worker?{kind:'worker',workerId:pub('worker',worker)}:{kind:'owner'};if(!rights){emit('artifact.registered',{artifactId:pub('withheld_artifact',e.evidence_id),title:'Withheld shared research record',author:actor,status:'withheld',reason:'No explicit permission to publish this retained excerpt.',relationships:[]},`withheld:${e.evidence_id}`,e.created_at,{kind:'withheld_evidence',id:e.evidence_id,version:'1',hash:e.sha256},actor);continue;}ensure(textHash(e.content)===e.sha256,'publication_evidence_source_mismatch');if(e.execution_id)this.settled(e.execution_id);const m=JSON.parse(e.metadata) as {url?:string;retrieved_at?:string;published_at?:string;observed_at?:string},sources:Source[]=e.kind==='public_source'&&m.url?[{sourceId:pub('source',e.source_id??e.evidence_id),url:m.url,title:e.title,publisher:new URL(m.url).hostname,publishedAt:m.published_at??null,eventAt:m.observed_at??null,retrievedAt:m.retrieved_at??e.created_at,summary:'Original research link. Excerpt publication requires the separately recorded permission.',limitations:['The link alone grants no republication rights.'],rights:'public_link'}]:[];artifact(e.evidence_id,1,e.title,e.content,Buffer.from(e.content),e.created_at,actor,'team_evidence',rights,[],sources);}
  let ordinal=0;const published=new Set<string>();
  for(const c of this.contributions()){
   if(c.kind==='charter'){published.add(c.message_id);continue;}
   if(!c.worker_id){artifact(c.message_id,1,'Owner discussion note',c.body,Buffer.from(c.body),c.created_at,{kind:'owner'},'team_note','owner_authored');published.add(c.message_id);continue;}
   ensure(c.execution_id,'publication_contribution_owner');this.settled(c.execution_id);ensure(this.participants.includes(c.worker_id),'publication_contribution_participant');
   const replies=JSON.parse(c.contribution_ids) as string[];ensure(replies.every(id=>published.has(id)),'publication_reply_source_required');
   const relationships=this.references(replies,JSON.parse(c.evidence_ids),ctx),synthesis=this.syntheses().find(s=>s.execution_id===c.execution_id);
   if(synthesis){const v=JSON.parse(synthesis.content) as Record<string,unknown>,keys=['recommendation','alternatives','supporting_findings','challenges_addressed','dissent_and_risks','missing_evidence_and_confidence','next_actions_and_approvals'],bytes=Buffer.from(keys.map(k=>`## ${k.replaceAll('_',' ')}\n${String(v[k]??'')}`).join('\n\n')),ref=this.synthesisRef(synthesis,ctx),previous=this.syntheses().find(s=>s.version===synthesis.version-1);if(previous&&previous.worker_id!==synthesis.worker_id)relationships.push({...this.synthesisRef(previous,ctx),relation:'supersedes'});
    artifact(synthesis.synthesis_id,ref.version,`${g.topic} — ${synthesis.state} recommendation ${synthesis.version}`,synthesis.content,bytes,synthesis.created_at,{kind:'worker',workerId:pub('worker',synthesis.worker_id)},'team_synthesis','owner_authored',relationships,[],`synthesis:${g.group_id}:${synthesis.worker_id}`);
    if(synthesis.state==='final')emit('discussion.closed',{discussionId,outcome:String(v.recommendation),dissent:[String(v.dissent_and_risks)],unresolved:[String(v.missing_evidence_and_confidence)],synthesis:{...ref,kind:'artifact'}},`discussion-close:${synthesis.synthesis_id}`,synthesis.created_at,{kind:'committed_synthesis',id:synthesis.synthesis_id,version:String(synthesis.version),hash:synthesis.sha256});
   }else{const reply=relationships.find(r=>r.kind==='contribution');emit('discussion.contribution',{contributionId:pub('contribution',c.message_id),discussionId,ordinal:String(++ordinal),body:c.body,replyTo:reply?.id??null,evidence:relationships.filter(r=>r!==reply)},`contribution:${c.message_id}`,c.created_at,{kind:'committed_contribution',id:c.message_id,version:'1',hash:hash(c)},{kind:'worker',workerId:pub('worker',c.worker_id)});}
   published.add(c.message_id);
  }
 }
}
