// Operator-only isolated acceptance. No scripted employee replies or selected strategy.
// Both product datasets below are explicitly SIMULATED; no private product account is read.
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
const base=process.env.BOT_MANDATES_URL??'http://127.0.0.1:4314';assert.match(base,/^http:\/\/127\.0\.0\.1:431[4-9]$/);
const dir=resolve(process.env.BOT_MANDATES_EVIDENCE??'.validation/prompt09/real');mkdirSync(dir,{recursive:true});
const fixture=JSON.parse(readFileSync(join(dir,'fixture.json'),'utf8'));assert.equal(fixture.roster_fixture,true);assert.match(fixture.data_root,/^\/var\/lib\/botsquad\/validation\/mandates-p09-/);
const phase=process.argv[2],journal=join(dir,'acceptance.json'),record=existsSync(journal)?JSON.parse(readFileSync(journal,'utf8')):{started:new Date().toISOString(),phases:{},ids:{},attempts:[]};
const save=()=>writeFileSync(journal,JSON.stringify(record,null,2));
const get=async p=>{const r=await fetch(`${base}/api/${p}`);assert.ok(r.ok,`${p}: ${r.status}`);return r.json();};
const session=await get('session');const post=async(p,body)=>{const r=await fetch(`${base}/api/${p}`,{method:'POST',headers:{'Content-Type':'application/json','X-BotSquad-Token':session.csrfToken},body:JSON.stringify(body)});assert.ok(r.ok,`${p}: ${await r.clone().text()}`);return r.json();};
const state=await get('state');assert.ok(state.workers.every(w=>w.workspace_path.startsWith(fixture.data_root+'/workspaces/')));assert.equal(state.workers.find(w=>w.worker_id===fixture.atlas)?.display_name,'Atlas');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function observe(id,predicate,label,timeout=1800000){const until=Date.now()+timeout;while(Date.now()<until){const d=await get(`mandates/${id}`);writeFileSync(join(dir,`${phase}-latest.json`),JSON.stringify(d,null,2));if(predicate(d))return d;const bad=d.cycles.find(c=>c.state==='blocked');if(bad)throw Error(`${label}: cycle blocked: ${bad.error}`);await wait(1500);}throw Error(`Timeout: ${label}`);}
async function admit(m,body,extra={}){return post('mandates/observations',{mandate_id:m.mandate_id,cycle_id:null,initiative_id:null,mode:'simulated_fixture',name:'SIMULATED acceptance baseline',value:null,unit:null,observed_at:new Date(Date.now()-3600000).toISOString(),period:'SIMULATED previous four-week period',source:'fixture://prompt09/strategic-acceptance',provenance:'Trusted validation harness authored synthetic values; not production analytics',limitations:'SIMULATED fixture only. No actual Asymmetri Motion feature, adoption, quality, revenue or customer behavior is established.',missingness:'Actual costs, customer demand, attribution and live product outcomes are unknown.',body,...extra});}
async function create(specific){const m=await post('mandates/create',{title:specific?'Asymmetri Motion — SIMULATED strategic acceptance':'Fictitious product — SIMULATED broad mandate',objective:specific?'Manage and market Asymmetri Motion; improve product quality, adoption and sustainable revenue within the approved constraints.':'Improve the sustainable success of this small software product within the supplied resources and constraints. Decide what investigation, internal work and strategy are useful.',success_criteria:'Choose a useful evidence-backed initiative, compare alternatives, select useful workers, conduct permitted investigation/deliberation, separately assign at least one bounded internal analysis Task and assess its result. Record reasoning and a useful follow-up. Subsequent reviews must evaluate intervening labelled evidence.',stop_criteria:'Stop if authority, evidence or bounded resources are insufficient. At most two strategic cycles; after the second review explicitly stop this acceptance mandate.',constraints:'Internal strategic test only. All product facts and metrics in the packet are SIMULATED. No publication, repository changes, outreach, spending, accounts, private analytics or external-system actions. Meaningful strategy and participant choices belong to the company. For this elapsed-time scheduler test, schedule the first follow-up 90–120 seconds after the internal work has completed; refresh inspect_mandate for current clock_now immediately before scheduling. The owner harness will add a labelled outcome before it is due. Do not require a pivot.',resources:'Bounded real model usage: at most 40 reserved employee executions, one group, three internal Tasks, 12 research operations per cycle. Existing eligible workers and explicitly granted public research only.',coordinator_id:fixture.atlas,envelope:{internal_tasks:true,working_groups:true,public_research:true,worker_schedules:true,max_executions:40,max_tasks:3,max_groups:1,max_research_operations:12,max_pending_work:2,max_cycle_minutes:45,max_cycles:2,min_interval_seconds:30,max_horizon_days:1,max_occurrences:2,max_active_schedules:1,timezone:'America/Vancouver',evidence_modes:['simulated_fixture','public_source','owner_provided']}});
record.ids[specific?'asymmetri':'broad']=m.mandate_id;record.attempts.push({phase,mandate_id:m.mandate_id,at:new Date().toISOString()});save();return m;}
try{
  assert.ok(!record.phases[phase],`Phase ${phase} already passed; retain evidence rather than replay`);
  if(phase==='prepare'){
    for(const worker of [fixture.scout,fixture.maya]){const current=await get(`research/workers/${worker}`);if(!current.grants.some(g=>g.status==='active'&&g.capability==='public_research'))await post('research/grant',{worker_id:worker,preset:'public_research',expires_at:null,document_paths:[],allow_discussions:true});}
    record.phases.prepare={individual_grants:[fixture.scout,fixture.maya],production_grants_unchanged:true};
  }else if(phase==='broad'||phase==='asymmetri'){
    const specific=phase==='asymmetri',m=await create(specific);
    const baseline=await admit(m,specific?'SIMULATED Asymmetri Motion reference profile, not a claim about the real product: a hypothetical motion-analysis software app serving independent creators. SIMULATED baseline: 400 trial starts; 36 percent reach a first successful analysis; 20 percent return in week two; 30 percent of the 20 synthetic feedback entries mention confusing setup, 25 percent mention slow processing, and 15 percent request clearer export guidance. SIMULATED subscription planning example: 24 paying accounts at 12 currency-units/month; this is not actual revenue. SIMULATED engineering capacity: one small internal proposal this week. Real product features, acquisition economics and production analytics are unknown. Quality, onboarding, export clarity and positioning are plausible competing strategies; do not prescribe a required choice.':'SIMULATED fictitious software product profile: an offline planning application for small teams. SIMULATED baseline: 200 trial workspaces; 45 percent create a first plan; 28 percent return in week two. Of 24 synthetic feedback entries, 8 mention collaboration clarity, 6 mention slow setup, 4 mention reliability, and 6 are inconclusive. SIMULATED pricing example: 18 paid workspaces at 10 currency-units/month; real costs and margin are unknown. Capacity is limited to one small internal analysis this week. Retention, reliability, positioning and setup improvements are plausible alternatives. Choose the most useful investigation and work; no strategy is prescribed.');record.ids[`${phase}_baseline`]=baseline.observation_id;save();
    await post('mandates/control',{mandate_id:m.mandate_id,action:'activate'});if((await get('state')).paused)await post('pause',{paused:false});
    const first=await observe(m.mandate_id,d=>d.cycles.some(c=>c.number===1&&c.state==='closed'),'first actual cycle');assert.ok(first.decisions.length);assert.ok(first.initiatives.length);assert.ok(first.work.some(w=>w.task_id));assert.ok(first.schedules.length);writeFileSync(join(dir,`${phase}-cycle1.json`),JSON.stringify(first,null,2));
    if(!specific){await post('mandates/control',{mandate_id:m.mandate_id,action:'pause'});record.phases.broad={mandate_id:m.mandate_id,cycle:first.cycles.find(c=>c.number===1),decisions:first.decisions.map(d=>d.decision_id),internal_work:first.work,schedules:first.schedules,evidence_mode:'simulated_fixture',paused_after_first_cycle:true};}
    else{
      const cycle=first.cycles.find(c=>c.number===1),initiative=first.initiatives.find(i=>first.decisions.some(d=>d.initiative_id===i.initiative_id))??first.initiatives[0];
      const observation=await admit(m,'SIMULATED intervening acceptance outcome, generated independently of the chosen strategy: the selected internal proposal was examined against 12 synthetic case descriptions. Seven descriptions were consistent with its intended mechanism, three were inconclusive and two exposed an accessibility or edge-case concern. No implementation or customer experiment occurred. No reliable change in conversion, adoption, revenue, cost or retention can be inferred. Evidence supports examining the mechanism further but is weak, small-sample and cannot establish causal product/business improvement. Decide whether to continue, iterate, pivot, stop or scale within the internal envelope; a particular disposition is not prescribed.',{name:'SIMULATED review of the chosen internal initiative',cycle_id:cycle.cycle_id,initiative_id:initiative.initiative_id,value:'7 consistent / 3 inconclusive / 2 concerns',unit:'synthetic case descriptions',period:'SIMULATED interval between strategic cycles',observed_at:new Date().toISOString(),source:'fixture://prompt09/intervening-independent-cases',provenance:'Trusted harness supplied a fixed neutral synthetic outcome for the team-selected initiative. No external action occurred.'});record.ids.asymmetri_outcome=observation.observation_id;save();
      const executionsBefore=(await get('state')).executions.length;const second=await observe(m.mandate_id,d=>d.cycles.some(c=>c.number===2&&c.state==='closed'),'scheduled second actual cycle');const c2=second.cycles.find(c=>c.number===2);assert.equal(c2.trigger,'durable_schedule');assert.ok(c2.occurrence_id);assert.equal(second.occurrences.find(o=>o.occurrence_id===c2.occurrence_id).state,'completed');assert.ok(second.decisions.some(d=>d.cycle_id===c2.cycle_id&&JSON.parse(d.evidence_ids).includes(observation.observation_id)),'Second cycle must actually cite delivered intervening evidence');writeFileSync(join(dir,'asymmetri-two-cycles.json'),JSON.stringify(second,null,2));record.phases.asymmetri={mandate_id:m.mandate_id,baseline_mode:'simulated_fixture',outcome_mode:'simulated_fixture',observation_id:observation.observation_id,cycles:second.cycles,decisions:second.decisions,occurrences:second.occurrences,executions_before_scheduled_review:executionsBefore};
    }
  }else if(phase==='idle'){
    const before=await get('state');assert.ok(!before.executions.some(e=>e.status==='running'));await wait(30000);const after=await get('state');assert.equal(after.executions.length,before.executions.length);record.phases.idle={elapsed_seconds:30,executions_before:before.executions.length,executions_after:after.executions.length,no_idle_model_work:true};
  }else throw Error('Unknown acceptance phase');
  save();console.log(JSON.stringify({phase,passed:true,evidence:journal}));
}catch(error){record.attempts.push({phase,failed_at:new Date().toISOString(),error:String(error)});save();throw error;}
