import {randomUUID} from 'node:crypto';
import type {Company,ExecutionContext} from '../company.js';
import {requireThat,strictObject,textField,type Worker} from '../../domain/model.js';
import type {ReplyRequest} from '../../domain/conversations.js';
import type {RuntimeAdapter} from '../../runtime/adapter.js';
import {paperTools} from '../../runtime/investment-team.js';
import {INVESTMENT_SCHEMA,PAPER_TOOLS,type TeamEnvelope,type TeamScope,type PaperProposal,type PaperReview,type PaperNarrative,type PaperInput} from '../../domain/investment-team/types.js';
import {FixtureSimulator} from '../investment.js';
import {MarketFixtureSimulator} from '../market/admission.js';
import {MarketStore} from '../market/store.js';
import {hash,time,integer} from '../../domain/investment/identity.js';
import type {Proposal,Review} from '../../domain/investment/types.js';
import type {GroupEvidence} from '../../domain/discussions.js';
import type {Channel} from '../../domain/publication/types.js';
const id=()=>randomUUID();
const bound=(v:unknown,min:number,max:number)=>{requireThat(typeof v==='number','Numeric finite investment limit required');integer(v,min,max);};
const list=(v:unknown,max=20):string[]=>{requireThat(Array.isArray(v)&&v.length<=max&&v.every(x=>typeof x==='string'&&x.length>0&&x.length<=100)&&new Set(v).size===v.length,'Invalid investment identifier list');return v as string[];};
const proseList=(v:unknown,required=false):string[]=>{requireThat(Array.isArray(v)&&v.length<=(required?10:20)&&(!required||v.length>0)&&v.every(x=>typeof x==='string'&&x.trim().length>0&&x.length<=1500),'Invalid bounded explanation list');return v as string[];};
export class InvestmentTeam {
 runtime?:RuntimeAdapter;
 fault?:()=>void;
 constructor(readonly company:Company){}
 private get db(){return this.company.store;}
 now(){return new Date(this.company.mandates.clock.now()).toISOString();}
 private human(){this.company.conversations.human();}
 forGroup(groupId:string){return this.db.get<TeamScope>('SELECT * FROM investment_team_scopes WHERE group_id=?',groupId);}
 forConversation(conversationId:string){const g=this.company.discussions.forConversation(conversationId);return g?this.forGroup(g.group_id):undefined;}
 scope(scopeId:string){const s=this.db.get<TeamScope>('SELECT * FROM investment_team_scopes WHERE scope_id=?',scopeId);requireThat(s,'Investment scope missing');return s;}
 envelope(s:TeamScope){requireThat(hash({envelope:JSON.parse(s.envelope),configuration:s.configuration_hash,groupScope:s.group_scope,context:s.context_hash})===s.digest,'Investment scope integrity failed');return JSON.parse(s.envelope) as TeamEnvelope;}
 private sim(runId:string){const row=this.db.get<{configuration:string}>('SELECT configuration FROM investment_runs WHERE run_id=?',runId);requireThat(row,'Selected synthetic run missing');const c=JSON.parse(row.configuration) as {authorization:{fixtureOperator:string}};return new FixtureSimulator(this.db,{now:()=>this.now()},c.authorization.fixtureOperator);}
 configuration(s:TeamScope){const c=this.sim(s.run_id).configuration(s.run_id);requireThat(hash(c)===s.configuration_hash,'Frozen configuration changed');return c;}
 private members(s:TeamScope){const e=this.envelope(s),g=this.company.discussions.group(s.group_id);requireThat(g.scope_version===s.group_scope,'Investment group scope changed');requireThat(hash(this.company.discussions.members(g).map(w=>w.worker_id).sort())===hash(e.participants.map(p=>p.workerId).sort()),'Investment membership changed');for(const p of e.participants){const w=this.company.discussions.eligible().find(w=>w.worker_id===p.workerId);requireThat(w,'Investment participant is unavailable');}return e;}
 private current(s:TeamScope){const e=this.members(s);requireThat(s.state==='active','Investment capability is inactive');requireThat(time(this.now())<time(e.expiresAt),'Investment capability expired');requireThat(this.sim(s.run_id).inspect(s.run_id).lifecycle==='active','Investment run is paused or ended');this.configuration(s);this.company.investmentLoop.requireScope(s.scope_id);return e;}
 private contextHash(groupId:string){const g=this.company.discussions.group(groupId);return hash({topic:g.topic,desiredOutput:g.desired_output,constraints:g.constraints,revision:g.revision,evidenceRevision:g.evidence_revision,evidence:this.db.all('SELECT evidence_id,sha256 FROM group_evidence WHERE group_id=? ORDER BY revision',groupId)});}
 preview(input:unknown){this.human();return this.db.transaction(()=>this.previewWithin(input));}
 private previewWithin(input:unknown){const a=strictObject(input,['runId','groupId','audience','participants','proposers','reviewers','submitters','expiresAt','maxExecutions','maxResearch','maxProposals','maxOrders','turnLimits','publicationChannelId']);
  requireThat(a.audience==='public_candidate','Explicit public-candidate context is required');const runId=textField(a,'runId',100),groupId=textField(a,'groupId',100),g=this.company.discussions.group(groupId);
  requireThat(g.state==='draft'&&g.initiating_operation==='owner_selected'&&!this.db.get('SELECT 1 FROM conversation_sessions WHERE conversation_id=?',g.conversation_id)&&!this.db.get('SELECT 1 FROM mandate_internal_work WHERE group_id=?',groupId),'Use a fresh owner-selected group with no provider history or mandate binding');
  const existing=this.forGroup(groupId);requireThat((!existing||existing.state==='draft'&&existing.run_id===runId)&&!this.db.get('SELECT 1 FROM investment_team_scopes WHERE run_id=? AND group_id!=?',runId,groupId),'This group or run already has an immutable investment scope');const c=this.sim(runId).configuration(runId);requireThat(c.evidenceMode==='synthetic_fixture','Observed investment gate is closed');
  requireThat(Array.isArray(a.participants)&&a.participants.length>=2&&a.participants.length<=6,'Choose two to six existing participants');
  const participants=a.participants.map(value=>{const p=strictObject(value,['workerId','name','responsibility']);const workerId=textField(p,'workerId',100);requireThat(this.company.discussions.members(g).some(w=>w.worker_id===workerId),'Participant must belong to selected group');return {workerId,name:textField(p,'name',100),responsibility:textField(p,'responsibility',1000)};});
  requireThat(new Set(participants.map(p=>p.workerId)).size===participants.length&&participants.length===this.company.discussions.members(g).length,'Review every exact group participant');
  const proposers=list(a.proposers,6),reviewers=list(a.reviewers,6),submitters=list(a.submitters,6);for(const role of [proposers,reviewers,submitters])requireThat(role.length>0&&role.every(w=>participants.some(p=>p.workerId===w)),'Capability roles must use selected participants');
  requireThat(proposers.every(w=>c.authorization.authors.includes(w))&&reviewers.every(w=>c.authorization.reviewers.includes(w))&&proposers.every(w=>reviewers.some(r=>r!==w)),'Frozen simulator author/reviewer roles do not match');
  const expiresAt=textField(a,'expiresAt',40);requireThat(time(expiresAt)>time(this.now())&&time(expiresAt)<=time(c.authorization.expiresAt)&&time(expiresAt)-time(this.now())<=31*86400000,'Choose a finite scope expiry within frozen run authority');
  bound(a.maxExecutions,1,40);bound(a.maxResearch,0,32);bound(a.maxProposals,1,100);bound(a.maxOrders,0,100);const limits=strictObject(a.turnLimits,['inputTokens','outputTokens','maxCostMicros']);bound(limits.inputTokens,1,100000);bound(limits.outputTokens,1,16000);bound(limits.maxCostMicros,0,10000000);
  const channel=this.db.get<Channel>('SELECT * FROM investment_public_channels WHERE id=?',textField(a,'publicationChannelId',100));requireThat(channel&&channel.source_run_id===runId,'Choose a publication channel bound to the same run');this.company.publication.requireTeamRoster(channel.id,participants.map(p=>p.workerId));
  const envelope:TeamEnvelope={runId,groupId,audience:'public_candidate',participants,proposers,reviewers,submitters,expiresAt,maxExecutions:Number(a.maxExecutions),maxResearch:Number(a.maxResearch),maxProposals:Number(a.maxProposals),maxOrders:Number(a.maxOrders),turnLimits:{inputTokens:Number(limits.inputTokens),outputTokens:Number(limits.outputTokens),maxCostMicros:Number(limits.maxCostMicros)},publicationChannelId:channel.id};
  const scopeId=existing?.scope_id??id(),configuration=hash(c),context=this.contextHash(groupId),digest=hash({envelope,configuration,groupScope:g.scope_version,context});if(existing)this.db.run("UPDATE investment_team_scopes SET context_hash=?,envelope=?,digest=? WHERE scope_id=?",context,JSON.stringify(envelope),digest,scopeId);else this.db.run("INSERT INTO investment_team_scopes VALUES (?,?,?,?,?,?,?,?,'draft',?)",scopeId,runId,groupId,configuration,g.scope_version,context,JSON.stringify(envelope),digest,this.now());this.db.run("INSERT INTO investment_team_previews VALUES (?,?,?,?,?)",id(),scopeId,digest,JSON.stringify({envelope,configuration:c,context}),this.now());return {scopeId,digest,envelope,configuration:c,group:{topic:g.topic,desiredOutput:g.desired_output,constraints:g.constraints,evidence:this.db.all('SELECT title,content,sha256 FROM group_evidence WHERE group_id=? ORDER BY revision',groupId)},notice:'Only this fresh context and reviewed experiment responsibilities. No private mission/history export. Separate exact publication consent is still required.'};
 }
 consent(input:unknown){this.human();const a=strictObject(input,['scopeId','digest']);return this.db.transaction(()=>{const s=this.scope(textField(a,'scopeId',100));requireThat(a.digest===s.digest,'Investment consent digest mismatch');this.envelope(s);const previous=this.db.get('SELECT 1 FROM investment_team_controls WHERE scope_id=? AND action=\'consent\'',s.scope_id);if(previous)return {scopeId:s.scope_id,state:s.state};requireThat(s.state==='draft'&&this.company.discussions.group(s.group_id).state==='draft','Investment draft changed');requireThat(this.contextHash(s.group_id)===s.context_hash,'Investment preview context changed');this.members(s);requireThat(time(this.now())<time(this.envelope(s).expiresAt),'Investment capability expired');this.db.run("UPDATE investment_team_scopes SET state='active' WHERE scope_id=?",s.scope_id);this.db.run('INSERT INTO investment_team_controls VALUES (?,?,?,?,?)',id(),s.scope_id,'consent',s.digest,this.now());return {scopeId:s.scope_id,state:'active'};});}
 control(input:unknown){this.human();const a=strictObject(input,['scopeId','action']);return this.db.transaction(()=>{const s=this.scope(textField(a,'scopeId',100));requireThat(['pause','revoke','resume'].includes(String(a.action)),'Unknown investment capability control');requireThat(s.state!=='draft'&&s.state!=='revoked','Investment capability cannot be changed');if(a.action==='resume'){requireThat(s.state==='paused','Only paused capability can resume');this.members(s);requireThat(time(this.now())<time(this.envelope(s).expiresAt),'Investment capability expired');}const state=a.action==='resume'?'active':a.action==='pause'?'paused':'revoked';this.db.run('UPDATE investment_team_scopes SET state=? WHERE scope_id=?',state,s.scope_id);this.db.run('INSERT INTO investment_team_controls VALUES (?,?,?,?,?)',id(),s.scope_id,String(a.action),s.digest,this.now());if(state!=='active')this.company.emit('investment_interrupt',s.scope_id);this.company.emit('changed');return {scopeId:s.scope_id,state,notice:'Future scoped work denied when inactive. Existing paper fills/history and provider uncertainty are retained.'};});}
 schema(conversationId:string){return this.forConversation(conversationId)?INVESTMENT_SCHEMA:undefined;}
 identity(conversationId:string,worker:Worker){const s=this.forConversation(conversationId);if(!s)return;const p=this.envelope(s).participants.find(p=>p.workerId===worker.worker_id);requireThat(p,'Worker outside investment roster');return {worker_id:worker.worker_id,display_name:p.name,role:'Investment participant',mission:p.responsibility};}
 authorize(r:ReplyRequest){const s=this.forConversation(r.conversation_id);if(!s)return;this.company.investmentLoop.authorize(s.scope_id,r);const e=this.current(s);requireThat(e.participants.some(p=>p.workerId===r.target_worker_id),'Worker outside investment scope');requireThat(this.runtime?.type===this.company.worker(r.target_worker_id).runtime_type&&this.runtime.runBoundedInvestment,'Bounded investment runtime unavailable; no ordinary runtime fallback');if(r.status==='queued')requireThat(this.db.get<{n:number}>('SELECT count(*) n FROM investment_team_executions WHERE scope_id=?',s.scope_id)!.n<e.maxExecutions,'Investment execution budget exhausted');}
 reserve(r:ReplyRequest,executionId:string){const s=this.forConversation(r.conversation_id);if(!s)return;const e=this.current(s);requireThat(this.db.get<{n:number}>('SELECT count(*) n FROM investment_team_executions WHERE scope_id=?',s.scope_id)!.n<e.maxExecutions,'Investment execution budget exhausted');this.db.run('INSERT INTO investment_team_executions VALUES (?,?,?,?,?,?)',executionId,s.scope_id,e.turnLimits.inputTokens,e.turnLimits.outputTokens,e.turnLimits.maxCostMicros,this.now());this.company.investmentLoop.reserve(s.scope_id,r,executionId);}
 limits(executionId:string){const row=this.db.get<{input_limit:number;output_limit:number;cost_limit:number}>('SELECT * FROM investment_team_executions WHERE execution_id=?',executionId);return row?{inputTokens:row.input_limit,outputTokens:row.output_limit,maxCostMicros:row.cost_limit}:undefined;}
 tools(r:ReplyRequest){return this.forConversation(r.conversation_id)?paperTools():[];}
 isTool(name:string){return (PAPER_TOOLS as readonly string[]).includes(name);}
 private verify(context:ExecutionContext){const v=this.company.conversations.verify(context),s=this.forConversation(v.request.conversation_id);requireThat(s,'No investment execution scope');const e=this.current(s);requireThat(this.db.get('SELECT 1 FROM investment_team_executions WHERE execution_id=? AND scope_id=?',context.executionId,s.scope_id),'Investment execution reservation missing');const g=this.company.discussions.group(s.group_id),turn=this.company.discussions.turn(v.request.request_id)!;requireThat(g.state==='active'&&!turn.output,'Investment turn already completed or group inactive');return {s,e,g,turn,...v};}
 context(conversationId:string){const s=this.forConversation(conversationId);if(!s)return;const e=this.envelope(s);return {scopeId:s.scope_id,runId:s.run_id,configuration:this.configuration(s),envelope:e,proposals:this.db.all('SELECT proposal_id,decision_id,revision,worker_id,proposal_hash FROM investment_team_proposals WHERE scope_id=? ORDER BY rowid DESC LIMIT 20',s.scope_id),publicationHealth:this.company.publication.health(e.publicationChannelId),operatingLoop:this.company.investmentLoop.context(s.scope_id),limitsNotice:'Public-candidate context only. No private missions or other histories. Model work needs bounded runtime support; broker search additionally requires its own enforceable budget.'};}
 private settled(executionId:string,current:ExecutionContext){const x=this.company.execution(executionId),active=this.company.execution(current.executionId);requireThat(x.status==='completed'&&!this.db.get('SELECT 1 FROM execution_runtime_attempts a JOIN executions e USING(execution_id) WHERE e.worker_id=? AND unresolved=1 AND e.execution_id!=?',x.worker_id,current.executionId)&&!this.db.get('SELECT 1 FROM conversation_sessions WHERE worker_id=? AND unresolved=1 AND session_id!=?',x.worker_id,active.origin==='conversation'?active.session_id:'')&&!this.db.get('SELECT 1 FROM research_operations WHERE worker_id=? AND unresolved=1',x.worker_id)&&!this.company.computers.unknown(x.worker_id),'Producing execution is not settled; do not replay or use uncertain work');}
 private references(context:ExecutionContext,groupId:string,contributions:unknown,evidence:unknown){const cs=list(contributions),es=list(evidence);const g=this.company.discussions.group(groupId),x=this.company.execution(context.executionId);requireThat(x.origin==='conversation','Discussion required');const t=this.company.discussions.turn(x.request_id)!;requireThat(t.seen_revision===g.revision&&t.seen_evidence_revision===g.evidence_revision,'Refresh current discussion checkpoint first');const rows:{kind:string;id:string;hash:string;at:string}[]=[];
  for(const [kind,ids] of [['contribution',cs],['evidence',es]] as const)for(const recordId of ids){const r=kind==='evidence'?this.db.get<GroupEvidence>('SELECT * FROM group_evidence WHERE group_id=? AND evidence_id=?',groupId,recordId):this.db.get<{body:string;created_at:string;execution_id:string|null}>('SELECT m.body,m.created_at,m.execution_id FROM conversation_messages m JOIN discussion_contributions c USING(message_id) WHERE c.group_id=? AND m.message_id=?',groupId,recordId);requireThat(r,'Source outside investment group');requireThat(time(r.created_at)<=time(this.now()),'Source was not available by this decision checkpoint');const content='content' in r?r.content:r.body;
   const receipts=this.db.all<{result:string}>('SELECT result FROM tool_receipts WHERE execution_id=?',context.executionId).map(r=>JSON.parse(r.result) as {record_id?:string;evidence_id?:string;content?:string;next_offset?:number|null});const chunks=receipts.filter(p=>p.record_id===recordId&&typeof p.content==='string').map(p=>({text:p.content!,end:p.next_offset??content.length})).map(p=>({...p,start:p.end-p.text.length})).filter(p=>p.start>=0&&content.slice(p.start,p.end)===p.text).sort((a,b)=>a.start-b.start);let covered=0;for(const chunk of chunks)if(chunk.start<=covered)covered=Math.max(covered,chunk.end);requireThat(covered===content.length||receipts.some(p=>p.evidence_id===recordId&&p.content===content),'Read complete exact source content in this execution');if(r.execution_id)this.settled(r.execution_id,context);rows.push({kind,id:recordId,hash:hash(content),at:r.created_at});}
  return rows;
 }
 private proposal(scopeId:string,proposalId:string){const p=this.db.get<PaperProposal>('SELECT * FROM investment_team_proposals WHERE scope_id=? AND proposal_id=?',scopeId,proposalId);requireThat(p,'Proposal outside investment scope');return p;}
 private deliveredProposal(context:ExecutionContext,p:PaperProposal){requireThat(this.db.all<{result:string}>('SELECT result FROM tool_receipts WHERE execution_id=?',context.executionId).some(r=>{const v=JSON.parse(r.result) as {proposal?:PaperProposal};return v.proposal&&hash(v.proposal)===hash(p);}),'Read the full exact paper proposal in this execution');}
 private latest(p:PaperProposal){requireThat(!this.db.get('SELECT 1 FROM investment_team_proposals WHERE scope_id=? AND decision_id=? AND revision>?',p.scope_id,p.decision_id,p.revision),'Proposal revision is superseded');}
 market(s:TeamScope){const c=this.configuration(s);return new MarketFixtureSimulator(new MarketStore(this.db),{now:()=>this.now()},c.authorization.fixtureOperator,(runId,command)=>{requireThat(runId===s.run_id,'Wrong scoped run');const current=this.scope(s.scope_id),e=this.current(current),state=this.sim(runId).inspect(runId);this.company.investmentLoop.admitCommand(s.scope_id,command);const buy=command.type==='submit'?state.decisions[`${command.decisionId}:${command.revision}`]?.orders[command.orderIndex]?.side==='BUY':command.type==='fill'&&state.orders[command.orderId]?.side==='BUY';if(buy){const channel=this.db.get<Channel>('SELECT * FROM investment_public_channels WHERE id=?',e.publicationChannelId);requireThat(channel?.source_run_id===runId&&!this.company.publication.health(e.publicationChannelId).newRiskBlocked,'Publication health blocks new paper risk');this.company.publication.requireNewRisk(e.publicationChannelId);}});}
 research(context:ExecutionContext,tool:string){const x=this.company.execution(context.executionId);if(x.origin!=='conversation')return;const s=this.forConversation(this.company.conversations.request(x.request_id).conversation_id);if(!s)return;const e=this.current(s);requireThat(tool!=='research_search','Investment broker search requires a separately enforceable usage adapter; currently unavailable');requireThat(this.db.get<{n:number}>('SELECT count(*) n FROM research_operations WHERE origin=\'conversation\' AND scope_id=?',this.company.discussions.group(s.group_id).conversation_id)!.n<e.maxResearch,'Investment research budget exhausted');}
 call(context:ExecutionContext,name:string,input:unknown){const {s,e,g}=this.verify(context);requireThat(this.isTool(name),'Not a paper tool');const at=this.now();
  if(name==='paper_inspect'){strictObject(input,[]);return this.context(g.conversation_id);}
  if(name==='paper_read_proposal'){const a=strictObject(input,['proposalId']);return {proposal:this.proposal(s.scope_id,textField(a,'proposalId',100))};}
  if(name==='paper_propose'){
   requireThat(e.proposers.includes(context.workerId),'Worker cannot propose paper decisions');const a=strictObject(input,['decisionId','revision','action','marketObservationIds','order','rationale','alternatives','risks','invalidationCondition','contributionIds','evidenceIds']) as unknown as PaperInput;
   const decisionId=textField(a as unknown as Record<string,unknown>,'decisionId',100);integer(a.revision,1,100);requireThat(['BUY','SELL','HOLD'].includes(a.action),'Invalid paper direction');requireThat((a.action==='HOLD')===(a.order===null),'HOLD has no order; BUY/SELL need one order');
   const narrative:PaperNarrative={rationale:textField(a as unknown as Record<string,unknown>,'rationale',4000),alternatives:proseList(a.alternatives,true) as [string,...string[]],risks:proseList(a.risks,true) as [string,...string[]],invalidationCondition:textField(a as unknown as Record<string,unknown>,'invalidationCondition',1500),contributionIds:list(a.contributionIds),evidenceIds:list(a.evidenceIds)};
   const provenance=this.references(context,g.group_id,narrative.contributionIds,narrative.evidenceIds);requireThat(provenance.length>0,'Paper proposal requires actual scoped evidence or contributions');const state=this.sim(s.run_id).inspect(s.run_id),marketEvidence=list(a.marketObservationIds).map(id=>{const o=state.observations.find(o=>o.id===id);requireThat(o,'Unknown admitted market observation');return {id,availableAt:o.availableAt};});
   const old=this.db.get<PaperProposal>('SELECT * FROM investment_team_proposals WHERE scope_id=? AND decision_id=? AND revision=?',s.scope_id,decisionId,a.revision);const proposal:Proposal={decisionId,revision:a.revision,author:context.workerId,action:a.action,evidenceCutoff:old?.created_at??at,evidence:marketEvidence,rationale:narrative.rationale,orders:a.order?[a.order]:[]};const digest=hash({scope:s.digest,executionId:context.executionId,proposal,narrative,provenance});if(old){requireThat(old.proposal_hash===digest,'Paper proposal revision conflicts');return {proposal:old};}
   requireThat(this.db.get<{n:number}>('SELECT count(*) n FROM investment_team_proposals WHERE scope_id=?',s.scope_id)!.n<e.maxProposals,'Paper proposal budget exhausted');const j=this.market(s).execute(s.run_id,{type:'decision',proposal},`team_proposal_${digest}`);requireThat(j.outcome.status!=='rejected',`Paper proposal rejected: ${j.outcome.reason}`);
   const proposalId=id();this.db.run('INSERT INTO investment_team_proposals VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',proposalId,s.scope_id,decisionId,a.revision,context.workerId,context.executionId,digest,hash(proposal),JSON.stringify(proposal),JSON.stringify(narrative),JSON.stringify(provenance),at);this.fault?.();return {proposal:this.proposal(s.scope_id,proposalId)};
  }
  if(name==='paper_review'){
   const a=strictObject(input,['proposalId','proposalHash','disposition','rationale','dissent','evidenceIds']),p=this.proposal(s.scope_id,textField(a,'proposalId',100));requireThat(e.reviewers.includes(context.workerId)&&p.worker_id!==context.workerId,'Independent eligible paper reviewer required');this.latest(p);this.settled(p.execution_id,context);this.deliveredProposal(context,p);const original=JSON.parse(p.narrative) as PaperNarrative;this.references(context,g.group_id,original.contributionIds,original.evidenceIds);requireThat(a.proposalHash===p.proposal_hash,'Exact full proposal hash required');requireThat(a.disposition==='approve'||a.disposition==='reject','Invalid review disposition');const evidence=this.references(context,g.group_id,[],a.evidenceIds),rationale=textField(a,'rationale',4000),dissent=proseList(a.dissent);requireThat(!this.db.get('SELECT 1 FROM investment_team_reviews WHERE proposal_id=?',p.proposal_id),'One authoritative immutable review per revision; revise the proposal for another review');
   const review:Review={id:id(),decisionId:p.decision_id,revision:p.revision,proposalHash:p.simulator_hash,reviewer:context.workerId,disposition:a.disposition,reviewedAt:at};const j=this.market(s).execute(s.run_id,{type:'review',review},`team_review_${review.id}`);requireThat(j.outcome.status!=='rejected',`Paper review rejected: ${j.outcome.reason}`);this.db.run('INSERT INTO investment_team_reviews VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',review.id,s.scope_id,p.proposal_id,context.workerId,context.executionId,p.proposal_hash,hash(review),a.disposition,rationale,JSON.stringify(dissent),JSON.stringify(evidence),at);return {review:this.db.get<PaperReview>('SELECT * FROM investment_team_reviews WHERE review_id=?',review.id)};
  }
  const a=strictObject(input,['proposalId','reviewId','proposalHash']),p=this.proposal(s.scope_id,textField(a,'proposalId',100)),r=this.db.get<PaperReview>('SELECT * FROM investment_team_reviews WHERE scope_id=? AND review_id=?',s.scope_id,textField(a,'reviewId',100));requireThat(e.submitters.includes(context.workerId),'Worker cannot submit paper decisions');requireThat(r&&r.proposal_id===p.proposal_id&&r.proposal_hash===p.proposal_hash&&a.proposalHash===p.proposal_hash&&r.disposition==='approve','Exact approved paper review required');this.latest(p);this.settled(p.execution_id,context);this.settled(r.execution_id,context);this.deliveredProposal(context,p);
  const old=this.db.get<{result:string}>('SELECT result FROM investment_team_submissions WHERE proposal_id=?',p.proposal_id);if(old)return JSON.parse(old.result);const proposal=JSON.parse(p.command) as Proposal;requireThat(this.db.get<{n:number}>("SELECT count(*) n FROM investment_team_submissions s JOIN investment_team_proposals p USING(proposal_id) WHERE s.scope_id=? AND json_extract(p.command,'$.action')!='HOLD'",s.scope_id)!.n<e.maxOrders||proposal.action==='HOLD','Paper order budget exhausted');const state=this.sim(s.run_id).inspect(s.run_id);const j=proposal.action==='HOLD'?null:this.market(s).execute(s.run_id,{type:'submit',decisionId:p.decision_id,revision:p.revision,orderIndex:0,expectedVersion:state.ledgerVersion,reviewId:r.review_id},`team_submit_${p.proposal_id}`);const result={proposalId:p.proposal_id,reviewId:r.review_id,outcome:j?.outcome??{status:'hold'},journalVersion:j?.version??state.version};this.db.run('INSERT INTO investment_team_submissions VALUES (?,?,?,?,?,?,?,?,?)',id(),s.scope_id,p.proposal_id,r.review_id,context.workerId,context.executionId,result.journalVersion,JSON.stringify(result),at);return result;
 }
 inspect(){this.human();return {runs:this.db.all<{run_id:string;configuration:string}>('SELECT run_id,configuration FROM investment_runs').map(r=>({id:r.run_id,configuration:JSON.parse(r.configuration)})),groups:this.company.discussions.list().items.filter(g=>g.state==='draft'&&(!this.forGroup(g.group_id)||this.forGroup(g.group_id)?.state==='draft')).map(g=>({id:g.group_id,topic:g.topic,participants:this.company.discussions.members(g).map(w=>({workerId:w.worker_id,name:w.display_name}))})),channels:this.db.all('SELECT id,source_run_id FROM investment_public_channels'),scopes:this.db.all<TeamScope>('SELECT * FROM investment_team_scopes ORDER BY rowid DESC LIMIT 100').map(s=>({...s,envelope:this.envelope(s),executions:this.db.get<{n:number}>('SELECT count(*) n FROM investment_team_executions WHERE scope_id=?',s.scope_id)!.n,proposals:this.db.all('SELECT * FROM investment_team_proposals WHERE scope_id=?',s.scope_id),reviews:this.db.all('SELECT * FROM investment_team_reviews WHERE scope_id=?',s.scope_id)})),boundedRuntimeAvailable:!!this.runtime?.runBoundedInvestment,notice:'No normal-runtime fallback. Existing Codex adapter lacks enforceable investment token/cost limits; genuine employee execution remains held.'};}
}
