import {mkdtempSync,mkdirSync,writeFileSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {Company} from '../../src/control/company.js';
import {Store} from '../../src/persistence/store.js';
import {FixtureSimulator} from '../../src/control/investment.js';
import {configuration} from '../../test/fixtures/investment/support.js';
import {requireThat,assertCapabilities,CAPABILITIES,type Worker} from '../../src/domain/model.js';
import {ACTIVITY_MAX,type CreditPilotPolicy} from '../../src/domain/usage/policy.js';
export type PilotWorker=Pick<Worker,'worker_id'|'principal_id'|'display_name'|'title'|'role'|'manager_worker_id'|'lifecycle'|'runtime_type'|'enabled'|'capability_profile'|'delegatable_capabilities'> & {principal_enabled:number};
export function preparePilot(roster:PilotWorker[],model:string,repoRoot:string,runtimeType='codex-app-server'){
 requireThat(roster.length===2&&new Set(roster.map(w=>w.worker_id)).size===2,'Two existing distinct workers required');
 for(const w of roster){requireThat(/^[a-zA-Z0-9_-]{1,100}$/.test(w.worker_id)&&/^[a-zA-Z0-9_-]{1,100}$/.test(w.principal_id)&&w.enabled===1&&w.principal_enabled===1&&w.runtime_type===runtimeType,'Invalid or disabled observed worker');requireThat(!w.manager_worker_id||roster.some(p=>p.worker_id===w.manager_worker_id),'Selected roster must preserve its observed hierarchy');assertCapabilities(w.capability_profile,CAPABILITIES);assertCapabilities(w.delegatable_capabilities,CAPABILITIES);}
 const root=realpathSync(mkdtempSync(join(tmpdir(),'botsquad-credit-pilot-'))),pilotId=randomUUID();
 writeFileSync(join(root,'private-credit-pilot.json'),JSON.stringify({pilotId,purpose:'disposable-private-synthetic'}),{mode:0o600});
 const store=new Store(join(root,'company.sqlite')),company=new Company(store,root,repoRoot,runtimeType);
 store.transaction(()=>{for(const w of roster){const workspace=join(root,'workspaces',w.worker_id);mkdirSync(workspace,{mode:0o700});const now=new Date().toISOString();store.run('INSERT INTO principals VALUES (?,?,?,1,?)',w.principal_id,'bot',w.display_name,now);store.run(`INSERT INTO workers (worker_id,principal_id,display_name,title,role,mission,manager_worker_id,runtime_type,workspace_path,lifecycle,status,capability_profile,delegatable_capabilities,enabled,created_by_worker_id,created_at,updated_at,ai_model,reasoning_effort) VALUES (?,?,?,?,?,?,?,?,?,?,'idle',?,?,1,?,?,?,?,?)`,w.worker_id,w.principal_id,w.display_name,w.title,w.role,'Private mission excluded from disposable synthetic pilot',null,runtimeType,workspace,w.lifecycle,JSON.stringify(w.capability_profile),JSON.stringify(w.delegatable_capabilities),null,now,now,model,'low');}for(const w of roster)store.run('UPDATE workers SET manager_worker_id=?,created_by_worker_id=? WHERE worker_id=?',w.manager_worker_id,w.manager_worker_id,w.worker_id);});
 const [first,second]=roster as [PilotWorker,PilotWorker],now=new Date().toISOString(),expiresAt=new Date(Date.now()+3600000).toISOString();
 const config=configuration({runId:'private-'+pilotId,startsAt:now,authorization:{fixtureOperator:'disposable-pilot-owner',authors:[first.worker_id],reviewers:[second.worker_id],expiresAt,maxOrders:1}});new FixtureSimulator(store,{now:()=>now},'disposable-pilot-owner').create(config);
 const group=company.discussions.create({topic:'Fictitious ACME: assess evidence before a paper investment',desired_output:'Analyze the supplied synthetic evidence; subsequent speakers must read and respond to earlier reasoning. Compare HOLD with a hypothetical small position. Record an objection or revised view if warranted. A partial discussion is acceptable; no forced agreement or complete cycle is required.',constraints:'PRIVATE SYNTHETIC PILOT. All company observations and prices are invented. At most four supervised turns for the entire pilot; stop between turns for inspection. No source fetching, delegation, orders, publication, real trading or claims of observed market facts.',participant_ids:roster.map(w=>w.worker_id),facilitator_id:first.worker_id,synthesizer_id:first.worker_id,organize_with_atlas:false,allow_incomplete:true,allow_research:false,receipt_key:randomUUID()});
 const evidence=company.discussions.share({group_id:group.group_id,kind:'owner_material',title:'Entirely fictitious ACME evidence packet',content:'SYNTHETIC — not a real company, market quote or investment recommendation. ACME invented price: $50/share, 10 million shares. Last-year revenue $100m, this-year $120m; gross margin fell from 50% to 42%. Cash $35m, debt $10m; annual free cash flow moved from +$6m to -$4m. One customer represents 40% of sales and renews in six months. Management claims a new product will restore margin to 48%, but no independent order evidence is supplied. Alternative BETA has flat revenue, $8m positive cash flow and lower customer concentration; its invented valuation is $250m. Scenario portfolio is all cash. Assess which facts support or undermine a small hypothetical ACME position versus HOLD. Identify missing evidence, a falsifiable condition that would change your view, and respond to prior contributors using their actual record IDs. All numbers are invented for this discussion only.',source_id:null,document_path:null,receipt_key:randomUUID(),audience_confirmed:true,audience_scope_version:group.scope_version,audience_worker_ids:roster.map(w=>w.worker_id)});
 const policy:CreditPilotPolicy={...ACTIVITY_MAX,mode:'credit_approved_private_pilot',pilotId,maxPilot:4,maxDurationMs:300000,existingCreditsApproved:true,providerRetriesAccepted:true};
 const envelope={runId:config.runId,groupId:group.group_id,audience:'private_synthetic',participants:roster.map((w,i)=>({workerId:w.worker_id,name:w.display_name,responsibility:i===0?'Assess the synthetic business case and tradeoffs':'Independently challenge assumptions, concentration risk and the prior analysis'})),proposers:[first.worker_id],reviewers:[second.worker_id],submitters:[first.worker_id],expiresAt,maxExecutions:4,maxResearch:0,maxProposals:0,maxOrders:0,turnLimits:null,publicationChannelId:'',executionPolicy:policy};
 const preview=company.investmentTeam.preview(envelope);company.investmentTeam.consent({scopeId:preview.scopeId,digest:preview.digest});
 const manifest={pilotId,root,model,scopeId:preview.scopeId,groupId:group.group_id,runId:config.runId,evidenceId:evidence.evidence_id,rosterHash:createHash('sha256').update(JSON.stringify(roster)).digest('hex'),createdAt:now};
 writeFileSync(join(root,'manifest.json'),JSON.stringify(manifest,null,2),{mode:0o600});
 return {root,store,company,policy,envelope,manifest,group,roster,close:()=>store.close()};
}
