// Isolated real-runtime acceptance. The provider and product facts are SIMULATED.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
const base=process.env.BOT_BUSINESS_URL??'http://127.0.0.1:4315';assert.match(base,/^http:\/\/127\.0\.0\.1:431[4-9]$/);
const dir=resolve(process.env.BOT_BUSINESS_EVIDENCE??'');assert.match(dir,/^\/var\/lib\/botsquad\/validation\/business-p11-/);
const fixture=JSON.parse(readFileSync(join(dir,'fixture.json'),'utf8'));assert.equal(fixture.mode,'simulated_fixture');assert.equal(fixture.data_root,dir);
const journal=join(dir,'acceptance.json'),record=existsSync(journal)?JSON.parse(readFileSync(journal,'utf8')):{mode:'simulated_fixture',real_runtime:true,started_at:new Date().toISOString(),attempts:[],phases:{}},phase=process.argv[2];
const save=()=>writeFileSync(journal,JSON.stringify(record,null,2),{mode:0o600});
const get=async path=>{const r=await fetch(`${base}/api/${path}`);assert.ok(r.ok,`${path}: ${r.status}`);return r.json();};const session=await get('session');
const post=async(path,body)=>{const r=await fetch(`${base}/api/${path}`,{method:'POST',headers:{'Content-Type':'application/json','X-BotSquad-Token':session.csrfToken},body:JSON.stringify(body)});assert.ok(r.ok,`${path}: ${await r.clone().text()}`);return r.json();};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function observe(predicate,label){const until=Date.now()+1800000;while(Date.now()<until){const d=await get(`mandates/${record.mandate_id}`);writeFileSync(join(dir,`${phase}-latest.json`),JSON.stringify(d,null,2),{mode:0o600});if(predicate(d))return d;const blocked=d.cycles.find(c=>c.state==='blocked');if(blocked)throw Error(`${label}: ${blocked.error}`);await sleep(1500);}throw Error(`${label}: timeout`);}
try{
  assert.ok(!record.phases[phase],'Passed phases are never silently replayed');
  if(phase==='prepare'){
    const m=await post('mandates/create',{title:'Fieldnote operations — SIMULATED external provider acceptance',objective:'Improve the usefulness and clarity of the approved operating document. Decide which evidence, participants, alternatives and correction are worth pursuing.',success_criteria:'Investigate the supplied source, compare reasonable alternatives, record an attributable initiative and decision. Propose at most one useful exact document correction if justified, wait for separate owner approval, inspect its receipt and observed state, schedule and complete a second evidence-driven review.',stop_criteria:'Stop after the second scheduled review, or if no useful safe correction can be justified. Never invent business impact.',constraints:'All product/provider data is SIMULATED. No actual repository, website, customer, money, account or release is accessible. Only the exact fixture document grant exists. Internal analysis or a working group is optional where useful. The company chooses the conclusion and literal edit. After a confirmed fixture action, retrieve an operational observation and persist a follow-up 90–120 seconds after the first cycle closes; use current clock_now. Cycle 2 must read prior decision, exact receipt and new observation, assess costs/limitations and decide continue/iterate/pivot/stop. Stop this two-cycle test after the review; a stop decision is an acceptance resource bound, not a required favorable business conclusion.',resources:'At most 40 reserved model executions per cycle; one group and two internal analysis Tasks. No public research grant or spending. Model token usage is retained when available; monetary cost is unknown.',coordinator_id:fixture.atlas,envelope:{internal_tasks:true,working_groups:true,public_research:false,worker_schedules:true,max_executions:40,max_tasks:2,max_groups:1,max_pending_work:2,max_cycle_minutes:45,max_cycles:2,min_interval_seconds:30,max_horizon_days:1,max_occurrences:2,max_active_schedules:1,timezone:'America/Vancouver',evidence_modes:['simulated_fixture','owner_provided']}});
    record.mandate_id=m.mandate_id;save();const grant=await post('business/grant',{mandate_id:m.mandate_id,target:fixture.target,credential_ref:'SIMULATED',expires_at:new Date(Date.now()+86400000-10000).toISOString(),max_actions:3,mode:'simulated_fixture'});record.grant_id=grant.grant_id;
    const baseline=await post('business/observe',{grant_id:grant.grant_id,action_id:null,baseline:{outcome:'Clarity and consistency of the approved operating document',measurement_source:'SIMULATED document blob; no customer analytics',window:'Point-in-time baseline before any proposed action',unit:'document',denominator:null,freshness:'Retrieved now from isolated fixture',missing_fields:'Reader benefit, adoption, revenue and monetary model costs unknown',privacy:'Synthetic document only; no private business/customer data',expected_lag:'Immediate fixture state; business outcome unmeasured',attribution_limitations:'A document correction can establish text presence, not customer or revenue impact'}});record.baseline_id=baseline.evidence_id;
    record.phases.prepare={passive:true,baseline_id:baseline.evidence_id,mode:baseline.mode};
  }else if(phase==='propose'){
    await post('mandates/control',{mandate_id:record.mandate_id,action:'activate'});if((await get('state')).paused)await post('pause',{paused:false});
    const d=await observe(d=>d.business.actions.some(a=>a.status==='awaiting_approval')&&!d.executions.some(e=>e.status==='running'),'company-selected proposal');const a=d.business.actions.find(a=>a.status==='awaiting_approval');
    assert.equal(JSON.parse(a.target).repository_id,fixture.target.repository_id);assert.ok(d.decisions.some(x=>x.decision_id===a.decision_id&&JSON.parse(x.evidence_ids).length));assert.equal(d.business.receipts.length,0);
    record.action_id=a.action_id;record.intent_hash=a.intent_hash;record.phases.propose={action_id:a.action_id,intent_hash:a.intent_hash,no_effect:true,slot_released:true};writeFileSync(join(dir,'exact-fixture-review.json'),JSON.stringify(d,null,2),{mode:0o600});
  }else if(phase==='approve'){
    const d=await get(`mandates/${record.mandate_id}`),a=d.business.actions.find(a=>a.action_id===record.action_id);assert.equal(a.status,'awaiting_approval');assert.equal(a.intent_hash,record.intent_hash);assert.equal(a.adapter,'fixture-markdown-v1');assert.equal(JSON.stringify(JSON.parse(a.target)),JSON.stringify(fixture.target));
    // Explicit trusted fixture approval only. This harness refuses the real adapter.
    const approval=await post('business/decide',{action_id:a.action_id,intent_hash:a.intent_hash,decision:'approved'});const first=await observe(d=>d.cycles.some(c=>c.number===1&&c.state==='closed'),'first cycle closed');
    assert.ok(first.business.receipts.some(r=>r.action_id===a.action_id&&r.mode==='simulated_fixture'));assert.ok(first.business.evidence.some(e=>e.action_id===a.action_id&&e.category==='operational'));assert.ok(first.schedules.length);
    record.phases.approve={approval_id:approval.approval_id,cycle:first.cycles.find(c=>c.number===1),schedules:first.schedules};writeFileSync(join(dir,'cycle1.json'),JSON.stringify(first,null,2),{mode:0o600});
  }else if(phase==='review'){
    const d=await observe(d=>d.cycles.some(c=>c.number===2&&c.state==='closed'),'scheduled second cycle');const cycle=d.cycles.find(c=>c.number===2);assert.equal(cycle.trigger,'durable_schedule');assert.ok(cycle.occurrence_id);assert.equal(d.occurrences.find(o=>o.occurrence_id===cycle.occurrence_id).state,'completed');
    const decisions=d.decisions.filter(x=>x.cycle_id===cycle.cycle_id),cited=decisions.flatMap(x=>JSON.parse(x.evidence_ids));assert.ok(cited.some(id=>d.business.receipts.some(r=>r.receipt_id===id)));assert.ok(cited.some(id=>d.business.evidence.some(e=>e.evidence_id===id&&e.category==='operational')));
    const provider=JSON.parse(readFileSync(join(dir,'SIMULATED-provider-state.json'),'utf8'));assert.equal(provider.effects,1);record.phases.review={cycle,decision_ids:decisions.map(d=>d.decision_id),provider_effects:provider.effects,mode:'simulated_fixture',live_business_gate:false};writeFileSync(join(dir,'two-cycles.json'),JSON.stringify(d,null,2),{mode:0o600});
  }else if(phase==='idle'){
    const before=await get('state');assert.ok(!before.executions.some(e=>e.status==='running'));await sleep(30000);const after=await get('state');assert.equal(after.executions.length,before.executions.length);record.phases.idle={seconds:30,executions:after.executions.length,no_idle_model_work:true};
  }else throw Error('Unknown phase');save();console.log(JSON.stringify({phase,passed:true,mode:'simulated_fixture',evidence:journal}));
}catch(error){record.attempts.push({phase,error:String(error),at:new Date().toISOString()});save();throw error;}
