// Owner-browser acceptance against only the isolated Ubuntu Prompt 08 HQ.
// Employee replies/research are real. Setup and deliberate faults have separate receipts.
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {chromium} from 'playwright';
const base=process.env.BOT_DISCUSSIONS_URL,prompt09=process.env.BOT_DISCUSSIONS_PROMPT09==='1';assert.ok(prompt09?/^http:\/\/127\.0\.0\.1:431[89]$/.test(base):['http://127.0.0.1:4311','http://127.0.0.1:4312','http://127.0.0.1:4313'].includes(base));
const dir=resolve(process.env.BOT_DISCUSSIONS_EVIDENCE??'.validation/prompt08/real');mkdirSync(dir,{recursive:true});
const fixture=JSON.parse(readFileSync(join(dir,'fixture.json'),'utf8'));assert.equal(fixture.roster_fixture,true);if(prompt09)assert.match(fixture.data_root,/^\/var\/lib\/botsquad\/validation\/mandates-p09-[a-z0-9-]+$/);else assert.equal(fixture.data_root,base.endsWith(':4313')?'/var/lib/botsquad/validation/discussions-20261001-p08-research-confirmation':base.endsWith(':4312')?'/var/lib/botsquad/validation/discussions-20261001-p08-confirmation':'/var/lib/botsquad/validation/discussions-20261001-p08');
const phase=process.argv[2],recordPath=join(dir,'acceptance.json');
const record=existsSync(recordPath)?JSON.parse(readFileSync(recordPath,'utf8')):{started:new Date().toISOString(),phases:{},ids:{},attempts:[]};
assert.ok(!record.phases[phase],`Phase ${phase} already accepted; inspect evidence before retrying`);
const save=()=>writeFileSync(recordPath,JSON.stringify(record,null,2));
const raw=async p=>{const r=await fetch(`${base}/api/${p}`);assert.ok(r.ok,`${p}: ${r.status}`);return r.json();};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function observe(get,predicate,label,timeout=900000){const end=Date.now()+timeout;while(Date.now()<end){const value=await get();if(predicate(value))return value;await sleep(750);}throw Error(`Timed out: ${label}`);}
async function verify(){const s=await raw('state');assert.equal(s.workers.find(w=>w.worker_id===fixture.atlas)?.display_name,'Atlas');assert.equal(s.workers.find(w=>w.worker_id===fixture.grace)?.display_name,'Grace');assert.ok(s.workers.every(w=>w.workspace_path.startsWith(fixture.data_root+'/workspaces/')));const h=await raw('devices');assert.ok(h.hq_id);if(record.hq_id)assert.equal(h.hq_id,record.hq_id);else record.hq_id=h.hq_id;save();return s;}
const firstState=await verify();if(record.initial_tasks===undefined){assert.deepEqual(firstState.tasks.map(t=>t.task_id).sort(),[...fixture.setup_task_ids].sort());record.initial_tasks=fixture.setup_task_ids.length;save();}
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
async function ready(){await verify();await page.goto(base);await page.getByText('Connected to headquarters',{exact:true}).waitFor();await page.locator('[data-tab=groups]').click();}
async function shot(name){await sleep(300);await page.screenshot({path:join(dir,`${phase}-${name}.png`),fullPage:!(await page.locator('#inspect').evaluate(e=>e.open))});}
async function selected(id){await page.locator(`[data-group="${id}"]`).click();await page.locator(`[data-selected-group="${id}"]`).waitFor();}
async function mutation(path,action){const result=page.waitForResponse(r=>r.url()===`${base}/api/${path}`&&r.request().method()==='POST');await action();const response=await result;assert.ok(response.ok(),await response.text());return response.json();}
async function create(key,atlas,topic,constraints,research=false,members=[fixture.maya,fixture.turing,fixture.linus,fixture.grace]){
  await verify();await page.locator('#new-group').click();await page.locator('[name=topic]').fill(topic);await page.locator('[name=desired_output]').fill('A practical recommendation, alternatives and trade-offs, explicit supporting contribution/source IDs, responses to material challenges, unresolved concerns and evidence limits. Discuss only; no implementation.');await page.locator('[name=constraints]').fill(constraints);
  if(atlas)await page.locator('[name=atlas]').check();else{for(const id of members)await page.locator(`[name=participant][value="${id}"]`).check();await page.locator('[name=facilitator]').selectOption(members[0]);await page.locator('[name=synthesizer]').selectOption(members[0]);}
  if(research)await page.locator('[name=research]').check();await page.locator('[name=incomplete]').check();
  const g=await mutation('groups/create',()=>page.getByRole('button',{name:'Create draft',exact:true}).click());record.ids[key]=g.group_id;record.attempts.push({phase,group_id:g.group_id,at:new Date().toISOString()});save();await page.locator(`[data-selected-group="${g.group_id}"]`).waitFor();return g;
}
async function share(title,content){await page.locator('#share-group-material').click();await page.locator('[name=title]').fill(title);await page.locator('[name=content]').fill(content);await page.locator('[name=audience]').check();return mutation('groups/share',()=>page.getByRole('button',{name:'Share selected excerpt',exact:true}).click());}
async function note(body,kind='constraint'){await page.locator('#group-note').fill(body);await page.locator('#group-note-kind').selectOption(kind);return mutation('groups/note',()=>page.getByRole('button',{name:'Save interjection',exact:true}).click());}
async function control(action){return mutation('groups/control',()=>page.locator(`[data-group-action=${action}]`).click());}
async function resumeHQ(){const s=await verify();if(s.paused)await page.getByRole('button',{name:'Resume dispatch',exact:true}).click();}
async function detail(id,label){const d=await raw(`groups/${id}`);writeFileSync(join(dir,`${label}.json`),JSON.stringify(d,null,2));return d;}
async function direct(workerId,key,body){
  await page.locator(`[data-worker="${workerId}"]`).first().click();await page.getByRole('button',{name:'Open conversations',exact:true}).click();const c=await mutation('conversations/open',()=>page.locator('#new-conversation').click());record.ids[key]=c.conversation_id;save();await page.locator(`#chat-compose[data-conversation-id="${c.conversation_id}"]`).waitFor();await page.locator('#chat-body').fill(body);const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());record.ids[`${key}_request`]=sent.request.request_id;save();await resumeHQ();
  const d=await observe(()=>raw(`conversations/${c.conversation_id}`),d=>{const r=d.requests.find(r=>r.request_id===sent.request.request_id);return r&&['completed','failed','blocked','interrupted'].includes(r.status)&&!d.executions.some(e=>e.status==='running');},'direct conversation settlement');writeFileSync(join(dir,`${key}.json`),JSON.stringify(d,null,2));assert.equal(d.requests.find(r=>r.request_id===sent.request.request_id).status,'completed');return d;
}
async function done(id){const d=await observe(()=>raw(`groups/${id}`),d=>['completed','blocked','stopped'].includes(d.group.state)&&!d.executions.some(e=>e.status==='running'),'bounded group completion');await detail(id,`${phase}-group`);assert.equal(d.group.state,'completed',d.group.error??'Not complete');assert.ok(d.syntheses.some(s=>s.state==='final'));return d;}
try{
  await ready();record.revisions??={};record.revisions[phase]=(await raw('health')).commit;save();
  if(phase==='manual-start'){
    const state=await verify();assert.ok(state.paused);assert.equal(state.tasks.length,fixture.setup_task_ids.length);record.initial_tasks=state.tasks.length;
    const g=await create('manual',false,'Hypothetical video-analysis app: compare guided setup, an interactive example, and contextual help for first-use onboarding. Which practical first version fits?', 'Hypothetical product. One engineer-week. Never upload user videos; local/offline operation preferred. Keyboard and screen-reader accessibility matter. Compare meaningful trade-offs and identify an important open question for the team. Do not implement, assign Tasks, publish, spend or claim user testing occurred. Public research is unavailable; use supplied material.');
    await share('Hypothetical product brief','The hypothetical app analyzes short videos locally. New users currently see an empty workspace and do not know the first action. Three candidate approaches are guided setup, an interactive example using bundled synthetic media, and contextual help. The team has one engineer-week, no usage analytics, no research interviews, and no confirmed accessibility evaluation. This is supplied hypothetical information, not observed production evidence.');await shot('charter');
    assert.equal((await raw(`groups/${g.group_id}`)).executions.length,0);await control('start');await resumeHQ();
    const d=await observe(()=>raw(`groups/${g.group_id}`),d=>d.paused&&!d.executions.some(e=>e.status==='running')&&d.contributions.filter(c=>c.kind==='opening').length>=2,'operator pause after actual initial contributions');
    const interjection=await note('New owner constraint: the first useful action must remain available with a keyboard only, with no network and without importing a personal video. Compare the smallest accessible path against the one engineer-week limit. State what accessibility validation is still missing.');record.ids.interjection=interjection.message_id;save();await shot('interjection');await detail(g.group_id,'manual-before-restart');record.phases[phase]={safe_boundary:true,completed_openings:d.contributions.filter(c=>c.kind==='opening').length,queued:d.turns.filter(t=>t.status==='queued').length};
  }else if(phase==='manual-continue'){
    const id=record.ids.manual;assert.ok(id);await selected(id);await shot('restart-continuation');await resumeHQ();const d=await done(id);assert.ok(new Set(d.history.items.filter(m=>m.worker_id).map(m=>m.worker_id)).size>=4);assert.ok(d.turns.some(t=>t.kind==='response'&&t.status==='completed'),'Actual response turn required');assert.ok(d.contributions.some(c=>c.kind==='response'&&JSON.parse(c.contribution_ids).length));assert.equal((await verify()).tasks.length,record.initial_tasks);assert.ok(d.sessions.some(s=>s.generation>1&&s.previous_session_id));const final=d.syntheses.find(s=>s.state==='final');record.ids.manual_synthesis=final.synthesis_id;assert.match(final.content,/keyboard|screen.reader/i);assert.match(final.content,/risk|missing|unverified|untested/i);await shot('exchange');await page.locator(`[data-synthesis="${final.synthesis_id}"]`).click();await shot('synthesis');record.phases[phase]={group_id:id,synthesis_id:final.synthesis_id,turns:d.group.turns_used,participants:new Set(d.executions.map(e=>e.worker_id)).size};
  }else if(phase==='research'||phase==='research-grounded'){
    const s=await verify();const expectedTasks=record.initial_tasks+(record.ids.assignment?1:0);assert.equal(s.tasks.length,expectedTasks);await page.locator(`[data-worker="${fixture.atlas}"]`).first().click();await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();await page.locator('#grant-discussions').check();await mutation('research/grant',()=>page.locator('#grant-public').click());await shot('explicit-grant');await page.keyboard.press('Escape');
    await direct(fixture.atlas,'private_research','PRIVATE_GROUP_EXCLUSION_SENTINEL_P08. This is a private direct conversation, not a group export. Investigate one public documentation question about keyboard focus indicators using your own public query and research tools. Retrieve a relevant public page, give a concise sourced answer with limitations, and retain its source in this private work scope. Do not share private queries/history into other conversations or future working groups.');await shot('private-research-regression');await page.locator('[data-tab=groups]').click();
    const g=await create('research',true,'Use public software onboarding/documentation patterns to recommend a practical first-use approach for a small offline-capable tool. Compare evidence and trade-offs.', 'Atlas: choose an appropriate team from existing eligible workers. Only Atlas has an explicit public research grant. Investigate a material public question using your own bounded search queries; retrieve and share relevant evidence from at least two distinct public sources with the managed reader when available. Distinguish retrieved page content from search snippets. Other participants should inspect the shared exports and evaluate their relevance and limits. Discuss specific earlier contributions when clarification is worthwhile. Hypothetical product, one engineer-week, privacy and accessibility constraints. No implementation, publication, hiring or implied approvals.',true);
    const ownerBrief=await share('Authorized hypothetical charter material','Only this selected hypothetical brief is shared. The product is a local video-analysis prototype, has no usage analytics, and needs a first useful action that works without uploading personal media. Candidate approaches are examples, guided setup and contextual help. Public analogies do not prove causal impact or accessibility.');await shot('charter');await control('start');await resumeHQ();const d=await done(g.group_id);assert.ok(d.participants.length>=2);assert.ok(d.evidence.filter(e=>e.kind==='public_source').length>=2);assert.ok(new Set(d.evidence.filter(e=>e.kind==='public_source').map(e=>JSON.parse(e.metadata).url)).size>=2);assert.ok(d.turns.some(t=>t.kind==='organize'&&t.status==='completed'));assert.ok(d.contributions.some(c=>d.history.items.find(m=>m.message_id===c.message_id)?.worker_id!==fixture.atlas&&JSON.parse(c.evidence_ids).length),'Nonresearcher must cite shared evidence');const final=d.syntheses.find(s=>s.state==='final');assert.ok(JSON.parse(final.content).evidence_ids.length>=2);if(phase==='research-grounded')assert.ok(JSON.parse(final.content).evidence_ids.includes(ownerBrief.evidence_id),'Final must ground the supplied owner brief');assert.equal((await verify()).tasks.length,expectedTasks);await shot('exchange');await page.locator('[data-group-evidence]').last().click();await shot('shared-source');await page.keyboard.press('Escape');await page.locator(`[data-synthesis="${final.synthesis_id}"]`).click();await shot('synthesis');record.phases[phase]={group_id:g.group_id,synthesis_id:final.synthesis_id,evidence:d.evidence.map(e=>({evidence_id:e.evidence_id,source_id:e.source_id,kind:e.kind,sha256:e.sha256,metadata:JSON.parse(e.metadata)})),turns:d.group.turns_used};
  }else if(phase==='research-finish'||phase==='research-grounded-finish'){
    const id=record.ids.research;assert.ok(id);await selected(id);const blocked=await detail(id,'before-explicit-finish');assert.equal(blocked.group.state,'blocked');assert.ok(blocked.participants.find(w=>w.worker_id===fixture.atlas).provider_unresolved);assert.equal(blocked.syntheses.length,0);assert.ok(blocked.group.allow_incomplete);
    await page.locator('#group-final-synth').selectOption(fixture.maya);await shot('owner-selection');await control('finish');await resumeHQ();const d=await done(id);assert.ok(d.participants.find(w=>w.worker_id===fixture.atlas).provider_unresolved,'Original unknown fence must remain');assert.ok(d.turns.some(t=>t.kind==='organize'&&t.status==='completed'));assert.ok(d.participants.length>=2);assert.ok(d.evidence.filter(e=>e.kind==='public_source').length>=2);assert.ok(new Set(d.evidence.filter(e=>e.kind==='public_source').map(e=>JSON.parse(e.metadata).url)).size>=2);assert.ok(d.contributions.some(c=>d.history.items.find(m=>m.message_id===c.message_id)?.worker_id!==fixture.atlas&&JSON.parse(c.evidence_ids).length),'Nonresearcher must cite shared evidence');const final=d.syntheses.find(s=>s.state==='final');assert.equal(final.worker_id,fixture.maya);assert.ok(JSON.parse(final.content).evidence_ids.length>=2);assert.ok(JSON.parse(final.content).failed_participation.length);if(phase==='research-grounded-finish')assert.ok(JSON.parse(final.content).evidence_ids.includes(d.evidence.find(e=>e.kind==='owner_material').evidence_id),'Owner brief must be grounded in the new final');assert.equal((await verify()).tasks.length,record.initial_tasks+(record.ids.assignment?1:0));await shot('exchange');await page.locator('[data-group-evidence]').last().click();await shot('shared-source');await page.keyboard.press('Escape');await page.locator(`[data-synthesis="${final.synthesis_id}"]`).click();await shot('incomplete-synthesis');record.ids.research_synthesis=final.synthesis_id;record.phases[phase]={group_id:id,synthesis_id:final.synthesis_id,explicit_incomplete_finish:true,original_synthesizer_fence_retained:true,evidence:d.evidence.map(e=>({evidence_id:e.evidence_id,source_id:e.source_id,kind:e.kind,sha256:e.sha256,metadata:JSON.parse(e.metadata)})),turns:d.group.turns_used};
  }else if(phase==='permission-revocation'||phase==='permission-revocation-finish'){
    if(phase==='permission-revocation'){
    await page.locator(`[data-worker="${fixture.linus}"]`).first().click();await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();assert.equal(await page.locator('#grant-public').isDisabled(),true);await shot('engineer-denial');await page.keyboard.press('Escape');
    await page.locator(`[data-worker="${fixture.scout}"]`).first().click();await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();assert.equal(await page.locator('#grant-discussions').isChecked(),false);await mutation('research/grant',()=>page.locator('#grant-public').click());await page.keyboard.press('Escape');
    const d=await direct(fixture.scout,'revocation_research','Validate a bounded public documentation answer: use research_search for one official public page explaining keyboard focus visibility, then research_open for a selected public URL and give a short sourced answer with the source kind and evidence limitations. This is private direct research, not group sharing. Do not hire, assign, publish or perform external actions.');assert.ok(d.history.items.some(m=>m.worker_id===fixture.scout));
    }else{assert.ok(record.ids.revocation_research);await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${record.ids.revocation_research}"]`).click();await page.locator('#chat-body').waitFor();}
    const before=await raw(`research/workers/${fixture.scout}`);assert.ok(before.activity.some(a=>a.tool==='research_search'&&a.state==='completed'));assert.ok(before.activity.some(a=>a.tool==='research_open'&&a.state==='completed'));const grant=before.grants.find(g=>g.capability==='public_research'&&g.status==='active');assert.ok(grant);assert.ok(!grant.modes.includes('discussion'));await shot('live-private-research');
    await page.locator(`[data-worker="${fixture.scout}"]`).first().click();await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();await mutation('research/revoke',()=>page.getByRole('button',{name:'Revoke Public Research',exact:true}).click());await shot('revoked');await page.keyboard.press('Escape');
    await page.locator('#chat-body').fill('Owner permission-boundary validation: attempt research_search once for official keyboard focus documentation with the now-revoked grant. If trusted code denies it, report that denial honestly and stop; do not retry or invent new research. No other action is authorized.');const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());const after=await observe(()=>raw(`conversations/${record.ids.revocation_research}`),d=>d.requests.find(r=>r.request_id===sent.request.request_id)?.status==='completed'&&!d.executions.some(e=>e.status==='running'),'revoked research reply');const permissions=await raw(`research/workers/${fixture.scout}`);assert.equal(permissions.activity.length,before.activity.length,'Revoked lookup must not reserve/invoke I/O');assert.ok(permissions.grants.some(g=>g.grant_id===grant.grant_id&&g.status==='revoked'));writeFileSync(join(dir,'permission-revocation-private.json'),JSON.stringify({before,after,permissions},null,2));await shot('denial-reply');record.phases[phase]={worker_id:fixture.scout,grant_id:grant.grant_id,lookup_operations_before:before.activity.length,lookup_operations_after:permissions.activity.length,discussion_mode_not_granted:true,engineer_grant_disabled:true,revoked:true};
  }else if(phase==='direct-peer'){
    await direct(fixture.linus,'direct_peer','DIRECT_PRIVATE_SENTINEL_P08. In this private conversation, compare a discussion recommendation with an implementation assignment. Ask Grace one bounded peer question about a concrete failure mode if these are confused, using ask_peer; do not invent her answer. After the bounded peer response, explain the practical distinction and uncertainty. No Tasks, source edits or external actions.');
    const details=await observe(async()=>{const list=await raw('conversations');return Promise.all(list.items.map(c=>raw(`conversations/${c.conversation_id}`)));},rows=>rows.some(d=>d.requests.some(r=>r.kind==='continuation'&&r.status==='completed'))&&rows.every(d=>!d.executions.some(e=>e.status==='running')&&!d.requests.some(r=>['queued','replying','waiting'].includes(r.status))),'peer exchange settlement');writeFileSync(join(dir,'direct-peer-all.json'),JSON.stringify(details,null,2));assert.ok(details.some(d=>d.requests.some(r=>r.kind==='peer')),'Actual peer request required');assert.ok(details.some(d=>d.requests.some(r=>r.kind==='continuation'&&r.status==='completed')),'Actual peer continuation required');await shot('peer');record.phases[phase]={conversations:details.map(d=>({id:d.conversation.conversation_id,requests:d.requests.map(r=>({kind:r.kind,status:r.status}))}))};
  }else if(phase==='direct-rollover'||phase==='direct-rollover-neutral'){
    assert.ok(prompt09);const id=record.ids.direct_peer;assert.ok(id);await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${id}"]`).click();await page.locator('#chat-body').waitFor();const before=await raw(`conversations/${id}`);const state=await verify();
    await page.locator('#chat-body').fill('Passive owner correction: diagnostic retention is 53 hours. The unresolved policy question is whether deletion leaves an audit tombstone.');await mutation('conversations/send',()=>page.getByRole('button',{name:'Send passive message',exact:true}).click());await sleep(1500);assert.equal((await verify()).executions.length,state.executions.length);
    await page.getByRole('button',{name:'Replace Linus’s context',exact:true}).click();await page.locator('#chat-body').fill('After context replacement, recover the newest passive owner correction about diagnostic retention and its unresolved policy question. State the exact duration and issue. Explain how a group recommendation differs from an implementation assignment; no Task or code changes.');const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());const after=await observe(()=>raw(`conversations/${id}`),d=>d.requests.find(r=>r.request_id===sent.request.request_id)?.status==='completed'&&!d.executions.some(e=>e.status==='running'),'direct rollover');assert.ok(Math.max(...after.sessions.map(s=>s.generation))>Math.max(...before.sessions.map(s=>s.generation)));const reply=after.history.items.find(m=>m.response_to===sent.request.request_id);assert.match(reply.body,/53/);assert.match(reply.body,/tombstone/i);assert.equal((await verify()).tasks.length,state.tasks.length);writeFileSync(join(dir,`${phase}.json`),JSON.stringify({before,after},null,2));await shot('retained-context');record.phases[phase]={passive_no_execution:true,no_task_creation:true,conversation_id:id,request_id:sent.request.request_id};
  }else if(phase==='source-rollover'||phase==='source-failure'){
    assert.ok(prompt09);const id=record.ids.private_research;assert.ok(id);await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${id}"]`).click();await page.locator('#chat-body').waitFor();const before=await raw(`conversations/${id}`);const researchBefore=await raw(`research/workers/${fixture.atlas}`);
    if(phase==='source-rollover')await page.getByRole('button',{name:'Replace Atlas’s context',exact:true}).click();await page.locator('#chat-body').fill(phase==='source-rollover'?'After context replacement, inspect your retained research sources in this private conversation and use research_read to retrieve one original source. Give one supported fact, its original retrieval time and limitations. Do not search or open fresh web pages; do not share private history into a group.':'Bounded known-source-failure validation: attempt research_open once for https://example.com/botsquad-validation-missing-document . If unavailable, report the actual tool failure and stop, without inventing page content or retrying. No search or other actions.');const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());const after=await observe(()=>raw(`conversations/${id}`),d=>d.requests.find(r=>r.request_id===sent.request.request_id)?.status==='completed'&&!d.executions.some(e=>e.status==='running'),'source regression');const researchAfter=await raw(`research/workers/${fixture.atlas}`),execution=after.executions.find(e=>e.request_id===sent.request.request_id),ops=researchAfter.activity.filter(o=>o.execution_id===execution.execution_id);
    if(phase==='source-rollover'){assert.ok(Math.max(...after.sessions.map(s=>s.generation))>Math.max(...before.sessions.map(s=>s.generation)));assert.ok(ops.some(o=>o.tool==='research_read'&&o.state==='completed'));assert.ok(!ops.some(o=>['research_search','research_open'].includes(o.tool)));}else{assert.equal(ops.length,1);assert.equal(ops[0].tool,'research_open');assert.equal(ops[0].state,'failed');assert.equal(ops[0].unresolved,0);}const inspected=await Promise.all(ops.map(o=>raw(`research/operations/${o.operation_id}`)));if(phase==='source-rollover'){for(const r of inspected.filter(o=>o.tool==='research_read')){assert.ok(r.result?.source_id);const original=await raw(`research/operations/${r.result.operation_id}`),source=original.sources.find(s=>s.source_id===r.result.source_id);assert.ok(source);for(const k of ['source_id','retrieved_at','observed_at','published_at','freshness','sha256','url','kind'])assert.equal(r.result[k],source[k]);assert.ok(source.content.includes(r.result.content));assert.ok(Date.parse(source.retrieved_at)<Date.parse(execution.started_at));r.original_source=source;}}writeFileSync(join(dir,`${phase}.json`),JSON.stringify({before,after,researchBefore,researchAfter,inspected},null,2));await shot('source-evidence');record.phases[phase]={conversation_id:id,request_id:sent.request.request_id,operations:ops};
  }else if(phase==='assignment-group'){
    assert.equal(base,'http://127.0.0.1:4312');assert.equal((await raw('groups')).items.length,0);record.initial_tasks=(await verify()).tasks.length;
    const g=await create('manual',false,'Choose a bounded first-use experience for a hypothetical offline video-analysis tool. Compare a bundled synthetic example with contextual help.','Hypothetical evidence only; one engineer-week; keyboard-only access; no network or personal-video requirement. Recommend an option with trade-offs and unresolved evidence/accessibility questions. Discuss only. No research, implementation, external actions or assignments.',false,[fixture.maya,fixture.grace]);await share('Explicit hypothetical material','There are no user interviews or usage metrics. A bundled synthetic example may show immediate value; contextual help may cost less but still leave an empty workspace. Accessibility has not been tested.');await control('start');await resumeHQ();const d=await done(g.group_id);assert.ok(new Set(d.executions.map(e=>e.worker_id)).size>=2);const final=d.syntheses.find(s=>s.state==='final');assert.ok(final);record.ids.manual_synthesis=final.synthesis_id;assert.equal((await verify()).tasks.length,record.initial_tasks);await shot('completed');record.phases[phase]={group_id:g.group_id,synthesis_id:final.synthesis_id,fresh_validation_company:true,reason:'Original validation Atlas remains fenced after recorded provider timeout; fresh isolated acceptance does not repair or alter it.'};
  }else if(phase==='idle-assignment'){
    const id=record.ids.manual;await selected(id);const before=await detail(id,'idle-before'),state=await verify();assert.equal(state.tasks.length,record.initial_tasks);assert.ok(!state.executions.some(e=>e.status==='running'));await sleep(30000);const after=await detail(id,'idle-after'),later=await verify();assert.equal(later.executions.length,state.executions.length);assert.equal(after.turns.length,before.turns.length);assert.equal(after.research_activity.length,before.research_activity.length);assert.equal(after.syntheses.length,before.syntheses.length);
    await page.locator(`[data-prepare-assignment="${record.ids.manual_synthesis}"]`).click();await page.locator('[name=objective]').fill('Write a short internal follow-up report assessing the selected working-group recommendation and its unresolved accessibility and evidence limitations. Save the report with submit_artifact. Handle it yourself as Atlas; do not hire, assign child Tasks, implement, access repositories, publish or contact anyone.');await page.locator('[name=acceptance_criteria]').fill('One internal report, attributed to Atlas, using only this selected synthesis and the explicit owner fields. State a possible next decision, without approving or executing it.');await page.locator('[name=constraints]').fill('Internal analysis only. No new permissions, research, child assignments, implementation, external actions or implied approvals. Do not read private conversation histories.');await shot('assignment-preview');const task=await mutation('groups/assignment',()=>page.getByRole('button',{name:'Submit assignment to Atlas',exact:true}).click());record.ids.assignment=task.task_id;save();assert.equal(task.requester,'human');assert.equal(task.assignee_worker_id,fixture.atlas);assert.equal((await verify()).tasks.length,record.initial_tasks+1);
    const final=await observe(()=>raw('state'),s=>['completed','failed','cancelled'].includes(s.tasks.find(t=>t.task_id===task.task_id)?.status),'internal owner-authorized Task settlement');writeFileSync(join(dir,'assignment-state.json'),JSON.stringify(final,null,2));assert.equal(final.tasks.find(t=>t.task_id===task.task_id).status,'completed');assert.equal(final.tasks.length,record.initial_tasks+1);record.phases[phase]={idle_seconds:30,zero_new_work:true,task_id:task.task_id};
  }else if(phase==='direct-interrupt'){
    assert.ok(prompt09);const id=record.ids.direct_peer;await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${id}"]`).click();await page.locator('#chat-body').waitFor();const before=await verify();await page.locator('#chat-body').fill('Explain six distinct failure windows for context replacement, with concrete evidence requirements and recovery tradeoffs. This bounded validation turn may be interrupted by the owner; no Tasks, tools or external actions.');const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());record.ids.direct_interruption=sent.request.request_id;save();await observe(()=>raw('state'),s=>s.audit.some(e=>e.type==='conversation_runtime_turn_started'&&s.executions.some(x=>x.execution_id===e.execution_id&&x.request_id===sent.request.request_id)),'actual direct turn started',60000);await page.getByRole('button',{name:'Interrupt reply',exact:true}).click();const after=await observe(()=>raw(`conversations/${id}`),d=>d.requests.find(r=>r.request_id===sent.request.request_id)?.status==='interrupted'&&!d.executions.some(e=>e.status==='running'),'confirmed direct interruption',60000);assert.equal((await verify()).tasks.length,before.tasks.length);writeFileSync(join(dir,'direct-interruption.json'),JSON.stringify(after,null,2));await shot('confirmed');record.phases[phase]={conversation_id:id,request_id:sent.request.request_id,provider_confirmed:true,no_task_creation:true};
  }else if(phase==='interrupt'){
    const g=await create('interrupt',false,'Bounded lifecycle validation: compare two hypothetical offline onboarding approaches.','Discuss only; compare trade-offs and unresolved questions. No research, implementation or external actions.',false,[fixture.linus,fixture.scout]);await control('start');await resumeHQ();await observe(()=>raw(`groups/${g.group_id}`),d=>d.executions.some(e=>e.status==='running'&&e.runtime_reference),'actual active provider turn');await shot('active');await mutation('groups/interrupt',()=>page.locator('#interrupt-group').click());const d=await observe(()=>raw(`groups/${g.group_id}`),d=>!d.executions.some(e=>e.status==='running'),'interrupt settlement');await detail(g.group_id,'interrupt-settled');assert.ok(d.executions.some(e=>['interrupted','failed'].includes(e.status)));await control('stop');await shot('stopped');record.phases[phase]={group_id:g.group_id,executions:d.executions.map(e=>({execution_id:e.execution_id,status:e.status,error:e.error,interruption_reason:e.interruption_reason})),syntheses:d.syntheses.length};assert.equal(d.syntheses.length,0);
  }else if(phase==='direct-fault-prepare'){
    assert.ok(prompt09);assert.ok(!(await verify()).executions.some(e=>e.status==='running'));await page.locator(`[data-worker="${fixture.maya}"]`).first().click();await page.getByRole('button',{name:'Open conversations',exact:true}).click();const c=await mutation('conversations/open',()=>page.locator('#new-conversation').click());record.ids.direct_fault=c.conversation_id;save();await page.locator('#chat-body').fill('Passive recovery fixture: retain the internal-only constraint. This isolated conversation will exercise an operator-injected service failure; never replay an ambiguous provider turn.');await mutation('conversations/send',()=>page.getByRole('button',{name:'Send passive message',exact:true}).click());record.phases[phase]={conversation_id:c.conversation_id,passive_only:true};
  }else if(phase==='direct-fault-start'){
    assert.ok(prompt09);const id=record.ids.direct_fault;await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${id}"]`).click();await page.locator('#chat-body').fill('Explain the retained internal-only constraint and how uncertainty should be reported. This is the explicitly authorized controlled service-failure validation. No Tasks, external actions or research.');const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());record.ids.direct_fault_request=sent.request.request_id;record.phases[phase]={conversation_id:id,request_id:sent.request.request_id};save();
  }else if(phase==='direct-fault-inspect'){
    assert.ok(prompt09);const id=record.ids.direct_fault;await page.locator('[data-tab=direct]').click();await page.locator(`[data-conversation="${id}"]`).click();const before=await raw(`conversations/${id}`);assert.equal(before.requests.find(r=>r.request_id===record.ids.direct_fault_request).status,'blocked');assert.ok(before.sessions.some(s=>s.state==='blocked'));const count=(await verify()).executions.length;await sleep(30000);const after=await raw(`conversations/${id}`);assert.equal((await verify()).executions.length,count);assert.equal(after.history.items.filter(m=>m.worker_id).length,0);writeFileSync(join(dir,'direct-uncertainty-after-restart.json'),JSON.stringify({before,after},null,2));await shot('blocked-no-replay');record.phases[phase]={conversation_id:id,request_id:record.ids.direct_fault_request,unknown_fence_retained:true,idle_seconds:30,no_automatic_replay:true};
  }else if(phase==='fault-prepare'){
    const s=await verify();assert.ok(!s.executions.some(e=>e.status==='running'));const g=await create('fault',false,'Controlled crash recovery validation for a bounded hypothetical design discussion.','Compare a local example and contextual help, retaining an unresolved question. This isolated run will exercise operator-injected service failure. No research, implementation or external action.',false,[fixture.turing,fixture.grace]);record.ids.fault_conversation=g.conversation_id;await share('Recovery fixture material','Hypothetical charter: keep personal media local. This material must survive a controlled restart.');await note('Recovery constraint: no network dependency and no automatic replay of ambiguous turns.');await shot('draft');record.phases[phase]={group_id:g.group_id,conversation_id:g.conversation_id,draft_only:true};
  }else if(phase==='fault-start'){
    await selected(record.ids.fault);await control('start');record.phases[phase]={started:true,group_id:record.ids.fault};save();await resumeHQ();
  }else if(phase==='fault-inspect'){
    await selected(record.ids.fault);const d=await detail(record.ids.fault,'fault-after-restart');assert.equal(d.group.state,'blocked');assert.ok(d.executions.some(e=>e.status!=='running'));assert.ok(d.sessions.some(s=>s.state==='blocked'));assert.equal(d.history.items.filter(m=>m.worker_id).length,0);assert.equal(d.syntheses.length,0);await shot('blocked');const before=(await verify()).executions.length;await sleep(30000);assert.equal((await verify()).executions.length,before);await control('stop');await shot('stopped-no-replay');record.phases[phase]={group_id:d.group.group_id,blocked_reason:d.group.error,no_duplicate_contributions:true,observed_idle_seconds:30};
  }else throw Error('Unknown phase');
  assert.deepEqual(errors,[]);save();console.log(JSON.stringify({phase,accepted:true,result:record.phases[phase]}));
}catch(error){record.failures??=[];record.failures.push({phase,at:new Date().toISOString(),error:String(error),browser_errors:errors});save();await shot('failure').catch(()=>{});throw error;}finally{await browser.close();}
