// Owner-browser acceptance against only the isolated Ubuntu Prompt 08 HQ.
// Employee replies/research are real. Setup and deliberate faults have separate receipts.
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {chromium} from 'playwright';
const base=process.env.BOT_DISCUSSIONS_URL;assert.equal(base,'http://127.0.0.1:4311');
const dir=resolve(process.env.BOT_DISCUSSIONS_EVIDENCE??'.validation/prompt08/real');mkdirSync(dir,{recursive:true});
const fixture=JSON.parse(readFileSync(join(dir,'fixture.json'),'utf8'));assert.equal(fixture.roster_fixture,true);assert.equal(fixture.data_root,'/var/lib/botsquad/validation/discussions-20261001-p08');
const phase=process.argv[2],recordPath=join(dir,'acceptance.json');
const record=existsSync(recordPath)?JSON.parse(readFileSync(recordPath,'utf8')):{started:new Date().toISOString(),phases:{},ids:{},attempts:[]};
assert.ok(!record.phases[phase],`Phase ${phase} already accepted; inspect evidence before retrying`);
const save=()=>writeFileSync(recordPath,JSON.stringify(record,null,2));
const raw=async p=>{const r=await fetch(`${base}/api/${p}`);assert.ok(r.ok,`${p}: ${r.status}`);return r.json();};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function observe(get,predicate,label,timeout=900000){const end=Date.now()+timeout;while(Date.now()<end){const value=await get();if(predicate(value))return value;await sleep(750);}throw Error(`Timed out: ${label}`);}
async function verify(){const s=await raw('state');assert.equal(s.workers.find(w=>w.worker_id===fixture.atlas)?.display_name,'Atlas');assert.equal(s.workers.find(w=>w.worker_id===fixture.grace)?.display_name,'Grace');assert.ok(s.workers.every(w=>w.workspace_path.startsWith(fixture.data_root+'/workspaces/')));const h=await raw('devices');assert.ok(h.hq_id);if(record.hq_id)assert.equal(h.hq_id,record.hq_id);else record.hq_id=h.hq_id;save();return s;}
await verify();
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
async function ready(){await verify();await page.goto(base);await page.getByText('Connected to headquarters',{exact:true}).waitFor();await page.locator('[data-tab=groups]').click();}
async function shot(name){await sleep(300);await page.screenshot({path:join(dir,`${phase}-${name}.png`),fullPage:true});}
async function selected(id){await page.locator(`[data-group="${id}"]`).click();await page.locator(`[data-selected-group="${id}"]`).waitFor();}
async function mutation(path,action){const result=page.waitForResponse(r=>r.url()===`${base}/api/${path}`&&r.request().method()==='POST');await action();const response=await result;assert.ok(response.ok(),await response.text());return response.json();}
async function create(key,atlas,topic,constraints,research=false){
  await verify();await page.locator('#new-group').click();await page.locator('[name=topic]').fill(topic);await page.locator('[name=desired_output]').fill('A practical recommendation, alternatives and trade-offs, explicit supporting contribution/source IDs, responses to material challenges, unresolved concerns and evidence limits. Discuss only; no implementation.');await page.locator('[name=constraints]').fill(constraints);
  if(atlas)await page.locator('[name=atlas]').check();else{for(const id of [fixture.maya,fixture.turing,fixture.linus,fixture.grace])await page.locator(`[name=participant][value="${id}"]`).check();await page.locator('[name=facilitator]').selectOption(fixture.maya);await page.locator('[name=synthesizer]').selectOption(fixture.maya);}
  if(research)await page.locator('[name=research]').check();await page.locator('[name=incomplete]').check();
  const g=await mutation('groups/create',()=>page.getByRole('button',{name:'Create draft',exact:true}).click());record.ids[key]=g.group_id;record.attempts.push({phase,group_id:g.group_id,at:new Date().toISOString()});save();await page.locator(`[data-selected-group="${g.group_id}"]`).waitFor();return g;
}
async function share(title,content){await page.locator('#share-group-material').click();await page.locator('[name=title]').fill(title);await page.locator('[name=content]').fill(content);await page.locator('[name=audience]').check();return mutation('groups/share',()=>page.getByRole('button',{name:'Share selected excerpt',exact:true}).click());}
async function note(body,kind='constraint'){await page.locator('#group-note').fill(body);await page.locator('#group-note-kind').selectOption(kind);return mutation('groups/note',()=>page.getByRole('button',{name:'Save interjection',exact:true}).click());}
async function control(action){return mutation('groups/control',()=>page.locator(`[data-group-action=${action}]`).click());}
async function resumeHQ(){const s=await verify();if(s.paused)await page.getByRole('button',{name:'Resume dispatch',exact:true}).click();}
async function detail(id,label){const d=await raw(`groups/${id}`);writeFileSync(join(dir,`${label}.json`),JSON.stringify(d,null,2));return d;}
async function direct(workerId,key,body){
  await page.locator(`[data-worker="${workerId}"]`).first().click();await page.getByRole('button',{name:'Open conversations',exact:true}).click();const c=await mutation('conversations/open',()=>page.locator('#new-conversation').click());record.ids[key]=c.conversation_id;save();await page.locator(`#chat-compose[data-conversation-id="${c.conversation_id}"]`).waitFor();await page.locator('#chat-body').fill(body);const sent=await mutation('conversations/send',()=>page.getByRole('button',{name:'Send & request reply',exact:true}).click());record.ids[`${key}_request`]=sent.request.request_id;save();await resumeHQ();
  const d=await observe(()=>raw(`conversations/${c.conversation_id}`),d=>{const r=d.requests.find(r=>r.request_id===sent.request.request_id);return r&&['completed','failed','blocked','interrupted'].includes(r.status)&&!d.executions.some(e=>e.status==='running');},'direct conversation settlement');writeFileSync(join(dir,`${key}.json`),JSON.stringify(d,null,2));assert.equal(d.requests.find(r=>r.request_id===sent.request.request_id).status,'completed');return d;
}
async function done(id){const d=await observe(()=>raw(`groups/${id}`),d=>['completed','blocked','stopped'].includes(d.group.state)&&!d.executions.some(e=>e.status==='running'),'bounded group completion');await detail(id,`${phase}-group`);assert.equal(d.group.state,'completed',d.group.error??'Not complete');assert.ok(d.syntheses.some(s=>s.state==='final'));return d;}
try{
  await ready();record.revisions??={};record.revisions[phase]=(await raw('health')).commit;save();
  if(phase==='manual-start'){
    const state=await verify();assert.ok(state.paused);assert.equal(state.tasks.length,fixture.setup_task_ids.length);record.initial_tasks=state.tasks.length;
    const g=await create('manual',false,'Hypothetical video-analysis app: compare guided setup, an interactive example, and contextual help for first-use onboarding. Which practical first version fits?', 'Hypothetical product. One engineer-week. Never upload user videos; local/offline operation preferred. Keyboard and screen-reader accessibility matter. Compare meaningful trade-offs and identify an important open question for the team. Do not implement, assign Tasks, publish, spend or claim user testing occurred. Public research is unavailable; use supplied material.');
    await share('Hypothetical product brief','The hypothetical app analyzes short videos locally. New users currently see an empty workspace and do not know the first action. Three candidate approaches are guided setup, an interactive example using bundled synthetic media, and contextual help. The team has one engineer-week, no usage analytics, no research interviews, and no confirmed accessibility evaluation. This is supplied hypothetical information, not observed production evidence.');await shot('charter');
    assert.equal((await raw(`groups/${g.group_id}`)).executions.length,0);await control('start');await resumeHQ();
    const d=await observe(()=>raw(`groups/${g.group_id}`),d=>d.paused&&!d.executions.some(e=>e.status==='running')&&d.contributions.filter(c=>c.kind==='opening').length>=2,'operator pause after actual initial contributions');
    const interjection=await note('New owner constraint: the first useful action must remain available with a keyboard only, with no network and without importing a personal video. Compare the smallest accessible path against the one engineer-week limit. State what accessibility validation is still missing.');record.ids.interjection=interjection.message_id;save();await shot('interjection');await detail(g.group_id,'manual-before-restart');record.phases[phase]={safe_boundary:true,completed_openings:d.contributions.filter(c=>c.kind==='opening').length,queued:d.turns.filter(t=>t.status==='queued').length};
  }else if(phase==='manual-continue'){
    const id=record.ids.manual;assert.ok(id);await selected(id);await shot('restart-continuation');await resumeHQ();const d=await done(id);assert.ok(new Set(d.history.items.filter(m=>m.worker_id).map(m=>m.worker_id)).size>=4);assert.ok(d.turns.some(t=>t.kind==='response'&&t.status==='completed'),'Actual response turn required');assert.ok(d.contributions.some(c=>c.kind==='response'&&JSON.parse(c.contribution_ids).length));assert.equal((await verify()).tasks.length,record.initial_tasks);assert.ok(d.sessions.some(s=>s.generation>1&&s.previous_session_id));const final=d.syntheses.find(s=>s.state==='final');record.ids.manual_synthesis=final.synthesis_id;assert.match(final.content,/keyboard|screen.reader/i);assert.match(final.content,/risk|missing|unverified|untested/i);await shot('exchange');await page.locator(`[data-synthesis="${final.synthesis_id}"]`).click();await shot('synthesis');record.phases[phase]={group_id:id,synthesis_id:final.synthesis_id,turns:d.group.turns_used,participants:new Set(d.executions.map(e=>e.worker_id)).size};
  }else if(phase==='research'){
    const s=await verify();assert.equal(s.tasks.length,record.initial_tasks);await page.locator(`[data-worker="${fixture.atlas}"]`).first().click();await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();await page.locator('#grant-discussions').check();await mutation('research/grant',()=>page.locator('#grant-public').click());await shot('explicit-grant');await page.keyboard.press('Escape');
    await direct(fixture.atlas,'private_research','PRIVATE_GROUP_EXCLUSION_SENTINEL_P08. This is a private direct conversation, not a group export. Investigate one public documentation question about keyboard focus indicators using your own public query and research tools. Retrieve a relevant public page, give a concise sourced answer with limitations, and retain its source in this private work scope. Do not share private queries/history into other conversations or future working groups.');await shot('private-research-regression');await page.locator('[data-tab=groups]').click();
    const g=await create('research',true,'Use public software onboarding/documentation patterns to recommend a practical first-use approach for a small offline-capable tool. Compare evidence and trade-offs.', 'Atlas: choose an appropriate team from existing eligible workers. Only Atlas has an explicit public research grant. Investigate a material public question using your own bounded search queries; retrieve and share relevant evidence from at least two distinct public sources with the managed reader when available. Distinguish retrieved page content from search snippets. Other participants should inspect the shared exports and evaluate their relevance and limits. Discuss specific earlier contributions when clarification is worthwhile. Hypothetical product, one engineer-week, privacy and accessibility constraints. No implementation, publication, hiring or implied approvals.',true);
    await share('Authorized hypothetical charter material','Only this selected hypothetical brief is shared. The product is a local video-analysis prototype, has no usage analytics, and needs a first useful action that works without uploading personal media. Candidate approaches are examples, guided setup and contextual help. Public analogies do not prove causal impact or accessibility.');await shot('charter');await control('start');await resumeHQ();const d=await done(g.group_id);assert.ok(d.participants.length>=2);assert.ok(d.evidence.filter(e=>e.kind==='public_source').length>=2);assert.ok(new Set(d.evidence.filter(e=>e.kind==='public_source').map(e=>JSON.parse(e.metadata).url)).size>=2);assert.ok(d.turns.some(t=>t.kind==='organize'&&t.status==='completed'));assert.ok(d.contributions.some(c=>d.history.items.find(m=>m.message_id===c.message_id)?.worker_id!==fixture.atlas&&JSON.parse(c.evidence_ids).length),'Nonresearcher must cite shared evidence');const final=d.syntheses.find(s=>s.state==='final');assert.ok(JSON.parse(final.content).evidence_ids.length>=2);assert.equal((await verify()).tasks.length,record.initial_tasks);await shot('exchange');await page.locator('[data-group-evidence]').last().click();await shot('shared-source');await page.keyboard.press('Escape');await page.locator(`[data-synthesis="${final.synthesis_id}"]`).click();await shot('synthesis');record.phases[phase]={group_id:g.group_id,synthesis_id:final.synthesis_id,evidence:d.evidence.map(e=>({evidence_id:e.evidence_id,source_id:e.source_id,kind:e.kind,sha256:e.sha256,metadata:JSON.parse(e.metadata)})),turns:d.group.turns_used};
  }else if(phase==='direct-peer'){
    await direct(fixture.linus,'direct_peer','DIRECT_PRIVATE_SENTINEL_P08. In this private conversation, compare a discussion recommendation with an implementation assignment. Ask Grace one bounded peer question about a concrete failure mode if these are confused, using ask_peer; do not invent her answer. After the bounded peer response, explain the practical distinction and uncertainty. No Tasks, source edits or external actions.');
    await observe(()=>raw('state'),s=>!s.executions.some(e=>e.status==='running')&&!s.workers.some(w=>w.status==='working'),'peer exchange settlement');
    const conversations=await raw('conversations');const details=[];for(const c of conversations.items)details.push(await raw(`conversations/${c.conversation_id}`));writeFileSync(join(dir,'direct-peer-all.json'),JSON.stringify(details,null,2));assert.ok(details.some(d=>d.requests.some(r=>r.kind==='peer')),'Actual peer request required');assert.ok(details.some(d=>d.requests.some(r=>r.kind==='continuation'&&r.status==='completed')),'Actual peer continuation required');await shot('peer');record.phases[phase]={conversations:details.map(d=>({id:d.conversation.conversation_id,requests:d.requests.map(r=>({kind:r.kind,status:r.status}))}))};
  }else if(phase==='idle-assignment'){
    const id=record.ids.manual;await selected(id);const before=await detail(id,'idle-before'),state=await verify();assert.equal(state.tasks.length,record.initial_tasks);assert.ok(!state.executions.some(e=>e.status==='running'));await sleep(30000);const after=await detail(id,'idle-after'),later=await verify();assert.equal(later.executions.length,state.executions.length);assert.equal(after.turns.length,before.turns.length);assert.equal(after.research_activity.length,before.research_activity.length);assert.equal(after.syntheses.length,before.syntheses.length);
    await page.locator(`[data-prepare-assignment="${record.ids.manual_synthesis}"]`).click();await page.locator('[name=objective]').fill('Write a short internal follow-up report assessing the selected working-group recommendation and its unresolved accessibility and evidence limitations. Save the report with submit_artifact. Handle it yourself as Atlas; do not hire, assign child Tasks, implement, access repositories, publish or contact anyone.');await page.locator('[name=acceptance_criteria]').fill('One internal report, attributed to Atlas, using only this selected synthesis and the explicit owner fields. State a possible next decision, without approving or executing it.');await page.locator('[name=constraints]').fill('Internal analysis only. No new permissions, research, child assignments, implementation, external actions or implied approvals. Do not read private conversation histories.');await shot('assignment-preview');const task=await mutation('groups/assignment',()=>page.getByRole('button',{name:'Submit assignment to Atlas',exact:true}).click());record.ids.assignment=task.task_id;save();assert.equal(task.requester,'human');assert.equal(task.assignee_worker_id,fixture.atlas);assert.equal((await verify()).tasks.length,record.initial_tasks+1);
    const final=await observe(()=>raw('state'),s=>['completed','failed','cancelled'].includes(s.tasks.find(t=>t.task_id===task.task_id)?.status),'internal owner-authorized Task settlement');writeFileSync(join(dir,'assignment-state.json'),JSON.stringify(final,null,2));assert.equal(final.tasks.find(t=>t.task_id===task.task_id).status,'completed');assert.equal(final.tasks.length,record.initial_tasks+1);record.phases[phase]={idle_seconds:30,zero_new_work:true,task_id:task.task_id};
  }else throw Error('Unknown phase');
  assert.deepEqual(errors,[]);save();console.log(JSON.stringify({phase,accepted:true,result:record.phases[phase]}));
}catch(error){record.failures??=[];record.failures.push({phase,at:new Date().toISOString(),error:String(error),browser_errors:errors});save();await shot('failure').catch(()=>{});throw error;}finally{await browser.close();}
