// Actual Chrome owner controls and actual BotSquad model work on a fresh Ubuntu HQ.
// Fixtures establish identities and optional outages; answers/findings are never scripted.
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {chromium} from 'playwright';
const base=process.env.BOT_RESEARCH_URL;assert.equal(base,'http://127.0.0.1:4311');
const dir=resolve(process.env.BOT_RESEARCH_EVIDENCE??'.validation/we01-real');mkdirSync(dir,{recursive:true});
const fixture=JSON.parse(readFileSync(join(dir,'fixture.json'),'utf8'));assert.equal(fixture.roster_fixture,true);
const phase=process.argv[2]??'baseline';const path=join(dir,'browser-evidence.json');
const record=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):{started:new Date().toISOString(),phases:{},ids:{},attempts:[]};
assert.ok(!record.phases[phase],`Phase ${phase} already accepted; inspect retained evidence before another attempt`);
const save=()=>writeFileSync(path,JSON.stringify(record,null,2));
const raw=async p=>{const r=await fetch(`${base}/api/${p}`);assert.ok(r.ok,`${p}: ${r.status}`);return r.json();};
async function verify(){const s=await raw('state');assert.equal(s.workers.find(w=>w.worker_id===fixture.atlas)?.display_name,'Atlas');assert.equal(s.workers.find(w=>w.worker_id===fixture.scout)?.display_name,'Scout');assert.ok(s.workers.every(w=>w.workspace_path.startsWith(fixture.data_root+'/workspaces/')));const h=await raw('devices');assert.ok(h.hq_id);assert.notEqual(h.hq_id,'hq_1cfe3e8d-dcca-47a4-8090-b79c3470b9f9');if(record.hq_id)assert.equal(h.hq_id,record.hq_id);else record.hq_id=h.hq_id;save();return s;}
await verify();
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function observe(get,predicate,label,timeout=360000){const end=Date.now()+timeout;while(Date.now()<end){const value=await get();if(predicate(value))return value;await sleep(750);}throw new Error(`Timed out: ${label}`);}
async function shot(name){await sleep(300);await page.screenshot({path:join(dir,`${phase}-${name}.png`),fullPage:true});}
async function ready(){await verify();await page.goto(base);await page.getByText('Connected to headquarters',{exact:true}).waitFor();}
async function worker(id){if(await page.locator('#inspect').evaluate(e=>e.open))await page.keyboard.press('Escape');await page.locator(`[data-worker="${id}"]`).first().click();}
async function capabilities(id){await worker(id);await page.getByRole('button',{name:'Capabilities & research',exact:true}).click();await page.locator('#grant-public,[data-revoke-research]').first().waitFor();}
async function select(c,id){await worker(id);await page.getByRole('button',{name:'Open conversations',exact:true}).click();await page.locator(`[data-conversation="${c}"]`).click();await page.locator(`#chat-compose[data-conversation-id="${c}"]`).waitFor();}
async function open(id,key){await worker(id);await page.getByRole('button',{name:'Open conversations',exact:true}).click();const response=page.waitForResponse(r=>r.url()===base+'/api/conversations/open'&&r.request().method()==='POST');await page.locator('#new-conversation').click();const r=await response;assert.ok(r.ok());const c=(await r.json()).conversation_id;record.ids[key]=c;save();await page.locator(`#chat-compose[data-conversation-id="${c}"]`).waitFor();return c;}
async function send(c,body,reply=true){await verify();await page.locator(`#chat-compose[data-conversation-id="${c}"]`).waitFor();await page.locator('#chat-body').fill(body);const response=page.waitForResponse(r=>r.url()===base+'/api/conversations/send'&&r.request().method()==='POST');await page.getByRole('button',{name:reply?'Send & request reply':'Send passive message',exact:true}).click();const r=await response;assert.ok(r.ok(),await r.text());const result=await r.json();record.attempts.push({phase,at:new Date().toISOString(),conversation_id:c,request_id:result.request?.request_id??null});save();return result;}
async function settled(c,id){const d=await observe(()=>raw(`conversations/${c}`),d=>{const r=d.requests.find(r=>r.request_id===id);return r&&!['queued','replying'].includes(r.status)&&!d.executions.some(e=>e.request_id===id&&e.status==='running');},'conversation settlement');writeFileSync(join(dir,`${id}.json`),JSON.stringify(d,null,2));assert.equal(d.requests.find(r=>r.request_id===id).status,'completed');const answer=d.history.items.find(m=>m.response_to===id);assert.ok(answer?.body.length>50);record.replies??={};record.replies[id]=answer.body;save();return d;}
async function objective(body,key){if(await page.locator('#inspect').evaluate(e=>e.open))await page.keyboard.press('Escape');await page.locator('[data-tab="conversation"]').click();await page.locator('#objective').fill(body);const response=page.waitForResponse(r=>r.url()===base+'/api/objectives'&&r.request().method()==='POST');await page.getByRole('button',{name:'Assign objective',exact:true}).click();const r=await response;assert.ok(r.ok());const task=await r.json();record.ids[key]=task.task_id;save();return task.task_id;}
async function taskDone(id){const s=await observe(()=>raw('state'),s=>s.tasks.find(t=>t.task_id===id)?.status==='completed'||s.tasks.some(t=>(t.task_id===id||t.parent_task_id===id)&&['failed','cancelled'].includes(t.status)),'delegated Task completion',600000);writeFileSync(join(dir,`${id}-state.json`),JSON.stringify(s,null,2));assert.equal(s.tasks.find(t=>t.task_id===id).status,'completed');return s;}
async function publicGrant(id){await capabilities(id);await page.locator('#grant-public').click();await page.getByRole('button',{name:'Revoke Public Research',exact:true}).waitFor();await shot(`grant-${id===fixture.atlas?'atlas':'scout'}`);}
async function captureResearch(id){const status=await raw(`research/workers/${id}`);const ops=[];for(const a of status.activity){const op=await raw(`research/operations/${a.operation_id}`);ops.push({...op,sources:op.sources.map(({content,...s})=>({...s,retained_chars:content.length,excerpt:content.slice(0,350)}))});}writeFileSync(join(dir,`${phase}-${id===fixture.atlas?'atlas':'scout'}-research.json`),JSON.stringify({status,operations:ops},null,2));return ops;}
try{
  await ready();record.revisions??={};record.revisions[phase]=(await raw('health')).commit;save();
  if(phase==='baseline'){
    const s=await verify();assert.equal(s.tasks.length,1);assert.ok(s.paused);
    const c=await open(fixture.atlas,'atlas_conversation');await send(c,'WE-01 private validation context. This passive note asks for no model work.',false);assert.equal((await verify()).executions.length,s.executions.length);
    const r=await send(c,'Briefly explain what you can do in this direct conversation and whether you have a standing Public Research permission yet. Do not create or assign a Task.');record.ids.baseline_reply=r.request.request_id;save();await page.locator('#pause').click();await settled(c,r.request.request_id);assert.equal((await verify()).tasks.length,1);await shot('existing-conversation');
    const task=await objective('Delegate to the existing Scout a short internal-document analysis: read the approved README and identify two practical coordination lessons for a small software team. Ask Scout to save a concise report; evaluate it for me. Use existing approved document tools only, with no web research. This establishes prior Task continuity before any new permission.','baseline_task');
    const after=await taskDone(task);record.legacy_bindings=after.bindings;assert.ok(after.bindings.some(b=>b.worker_id===fixture.scout));assert.ok(after.bindings.some(b=>b.worker_id===fixture.atlas));
    assert.equal((await raw(`research/workers/${fixture.atlas}`)).grants.length,0);
  }else if(phase==='weather'){
    const before=await verify();const c=record.ids.atlas_conversation;assert.ok(c);const prior=await raw(`conversations/${c}`);record.weather_before_sessions=prior.sessions;
    await publicGrant(fixture.atlas);await publicGrant(fixture.scout);
    await capabilities(fixture.atlas);await page.locator('#grant-knowledge input[value="README.md"]').check();await page.getByRole('button',{name:'Confirm selected document access',exact:true}).click();await page.getByRole('button',{name:'Revoke Company Knowledge',exact:true}).waitFor();await shot('separate-knowledge');
    await select(c,fixture.atlas);const r=await send(c,"What's the current weather in Vancouver, British Columbia? Tell me when the information was observed and show the source.");record.ids.weather_reply=r.request.request_id;save();const d=await settled(c,r.request.request_id);assert.equal((await verify()).tasks.length,before.tasks.length);
    const ops=await captureResearch(fixture.atlas);assert.ok(ops.some(o=>o.tool==='research_search'&&o.state==='completed'&&o.provider==='codex-live-web'&&o.sources.length));assert.ok(d.sessions.length>prior.sessions.length);record.weather_after_sessions=d.sessions;await shot('current-weather-reply');
    await capabilities(fixture.atlas);await page.locator('[data-research-operation]').first().click();await page.locator('.research-source').first().waitFor();await shot('source-inspection');
  }else if(phase==='task'){
    const task=await objective('Research the public onboarding, documentation and support approaches of three software products you consider relevant to a small software team. Delegate bounded research to the existing Scout, whose Public Research standing permission is active. Have Scout read multiple actual public sources and save a supported report. Identify practical lessons, cite the actual sources, distinguish facts from recommendations, and note what could not be verified. Choose the products, sources and conclusions yourselves. Do not contact anyone, sign up, publish, spend money, change repositories, or transmit company documents. Evaluate the returned report for me.','public_task');
    const s=await taskDone(task);const children=s.tasks.filter(t=>t.parent_task_id===task);assert.ok(children.some(t=>t.assignee_worker_id===fixture.scout));const artifacts=s.artifacts.filter(a=>children.some(t=>t.task_id===a.related_task_id||t.task_id===a.task_id));assert.ok(artifacts.length);
    for(const a of artifacts){const r=await fetch(base+`/api/artifacts/${a.artifact_id}`);assert.ok(r.ok);writeFileSync(join(dir,`${a.artifact_id}.md`),await r.text());}
    const ops=await captureResearch(fixture.scout);const successful=ops.filter(o=>o.scope_id===task&&o.state==='completed');assert.ok(successful.filter(o=>o.tool==='research_open').length>=2,'Researcher must open actual sources');assert.ok(new Set(successful.flatMap(o=>o.sources.map(s=>new URL(s.url).hostname))).size>=2);
    for(const old of record.legacy_bindings)assert.deepEqual(s.bindings.find(b=>b.worker_id===old.worker_id),old);await shot('delegated-report');await captureResearch(fixture.atlas);
  }else if(phase==='rollover'){
    const c=record.ids.atlas_conversation;await select(c,fixture.atlas);const before=await raw(`conversations/${c}`);await page.getByRole('button',{name:'Replace Atlas’s context',exact:true}).click();
    const r=await send(c,'After context replacement, inspect your retained research source list and read one original stored source. Summarize the weather observation you previously reported, with its original observation time and source. Explain why it is an earlier observation, not a fresh current lookup. Do not refresh the public web for this request. Also read README.md through the separate Company Knowledge tool and give one relevant short takeaway; do not send document content to any external service.');record.ids.rollover_reply=r.request.request_id;save();const d=await settled(c,r.request.request_id);assert.ok(Math.max(...d.sessions.map(s=>s.generation))>Math.max(...before.sessions.map(s=>s.generation)));const ops=await captureResearch(fixture.atlas);const e=d.executions.find(e=>e.request_id===r.request.request_id);const scoped=ops.filter(o=>o.execution_id===e.execution_id);assert.ok(scoped.some(o=>o.tool==='research_read'));assert.ok(scoped.some(o=>o.tool==='read_company_document'));assert.equal(scoped.some(o=>o.tool==='research_search'||o.tool==='research_open'),false);await shot('retained-source-after-rollover');
  }else if(phase==='outage'){
    const c=await open(fixture.scout,'outage_conversation');const r=await send(c,'This is an explicitly isolated outage test, not normal source evidence. Attempt one public search for current Python documentation and one public read of https://docs.python.org/3/tutorial/. If the fixture reports unavailable, explain the limitation and do not invent retrieved facts or keep retrying.');record.ids.outage_reply=r.request.request_id;save();const d=await settled(c,r.request.request_id);const ops=await captureResearch(fixture.scout);const e=d.executions.find(e=>e.request_id===r.request.request_id);assert.ok(ops.filter(o=>o.execution_id===e.execution_id&&o.state==='failed').length>=2);assert.equal(ops.some(o=>o.unresolved),false);await shot('honest-outage');
  }else if(phase==='revoke'){
    await capabilities(fixture.atlas);await page.getByRole('button',{name:'Revoke Public Research',exact:true}).click();await page.locator('#grant-public').waitFor();await shot('revoked-standing-permission');
    const c=record.ids.atlas_conversation;await select(c,fixture.atlas);const r=await send(c,'The owner has revoked Public Research. As a bounded permission test, attempt research_search once for Vancouver current weather, report the tool denial accurately, then stop. Do not invent weather or try another route.');record.ids.revoked_reply=r.request.request_id;save();await settled(c,r.request.request_id);const status=await raw(`research/workers/${fixture.atlas}`);assert.ok(status.grants.some(g=>g.capability==='public_research'&&g.status==='revoked'));await shot('denial-after-revocation');await captureResearch(fixture.atlas);
  }else if(phase==='restart'){
    const before=await verify();const status=await raw(`research/workers/${fixture.atlas}`);assert.ok(status.grants.some(g=>g.capability==='public_research'&&g.status==='revoked'));assert.ok(status.grants.some(g=>g.capability==='company_knowledge'&&g.status==='active'));assert.ok(status.activity.length);
    const c=record.ids.atlas_conversation;await select(c,fixture.atlas);const r=await send(c,'After the HQ restart, read README.md through your standing Company Knowledge grant and explain one brief takeaway. Public Research remains revoked; do not look up the web. Mention that an old weather observation is not a new current observation.');record.ids.restart_reply=r.request.request_id;save();await settled(c,r.request.request_id);assert.equal((await verify()).tasks.length,before.tasks.length);await capabilities(fixture.atlas);await page.locator('[data-research-operation]').filter({hasText:'research search'}).first().click();await page.locator('.research-source').first().waitFor();await shot('evidence-after-restart');await captureResearch(fixture.atlas);
  }else if(phase==='idle'){
    const c=record.ids.atlas_conversation;await select(c,fixture.atlas);const before=await verify();assert.ok(before.tasks.every(t=>['completed','cancelled'].includes(t.status)));assert.ok(before.executions.every(e=>e.status!=='running'));const a=await raw(`research/workers/${fixture.atlas}`),b=await raw(`research/workers/${fixture.scout}`);
    await send(c,'Passive note for WE-01 idle evidence. Do not request a reply.',false);await sleep(30000);const after=await verify();assert.equal(after.executions.length,before.executions.length);assert.equal(after.tasks.length,before.tasks.length);assert.deepEqual((await raw(`research/workers/${fixture.atlas}`)).activity,a.activity);assert.deepEqual((await raw(`research/workers/${fixture.scout}`)).activity,b.activity);record.idle={milliseconds:30000,model_executions:0,research_operations:0,passive_no_dispatch:true};await shot('idle-no-work');
  }else throw new Error('Unknown phase');
  assert.deepEqual(errors,[]);record.phases[phase]={passed:true,finished:new Date().toISOString()};save();console.log(JSON.stringify({phase,passed:true,ids:record.ids}));
}catch(error){record.attempts.push({phase,failed_at:new Date().toISOString(),error:error.message});save();await page.screenshot({path:join(dir,`${phase}-failure-${Date.now()}.png`),fullPage:true}).catch(()=>{});throw error;}finally{await browser.close();}
