// Scripted real-browser fault probes. These are deliberately injected, not provider outages.
import assert from 'node:assert/strict';
import {mkdirSync,existsSync,writeFileSync,readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {Store} from '../../src/persistence/store.js';
import {Company} from '../../src/control/company.js';
import {BrowserClient} from '../../src/computer/client.js';
import {requireThat} from '../../src/domain/model.js';
import type {ComputerIntent} from '../../src/domain/computer.js';
const data=resolve(process.env.BOT_DATA_DIR??'');requireThat(process.env.BOT_VALIDATION_COMPUTER==='1'&&/^\/var\/lib\/botsquad\/validation\/computer-20261005-fault[0-9]+$/.test(data),'Explicit fresh isolated fault root required');
mkdirSync(data,{recursive:true,mode:0o700});requireThat(!existsSync(join(data,'company.sqlite')),'Retain previous fault data');
const store=new Store(join(data,'company.sqlite')),company=new Company(store,data,fileURLToPath(new URL('../../../',import.meta.url))),worker=company.initializeComputerOperator({display_name:'Fault Verifier'}),origin='http://127.0.0.1:43991';
const records:unknown[]=[];const record=(name:string,detail?:unknown)=>{records.push({name,detail,at:new Date().toISOString()});writeFileSync(join(data,'fault-results.json'),JSON.stringify(records,null,2),{mode:0o600});console.log('PASS '+name);};
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const idle=async()=>{for(let i=0;i<15;i++){if(await new BrowserClient().confirmIdle()){await delay(50);return;}await delay(500);}throw Error('Browser cleanup not confirmed');};
const start=(extra:Record<string,unknown>={})=>{const s=company.computers.request({worker_id:worker.worker_id,objective:'Labelled real-browser fault test',acceptance_criteria:'No replay or unapproved effect',constraints:'No model invocation; disposable fixture only',policy:{origins:[origin],fixtureOrigins:[origin],mutationPaths:['/save'],expiresAt:new Date(Date.now()+900000).toISOString(),...extra}});company.computers.authorize({session_id:s.session_id,policy_hash:s.policy_hash,decision:'approve'});const claim=company.claimNext();assert.ok(claim);company.computers.prepare(claim.context);return {s,...claim};};
type Run=ReturnType<typeof start>;
const call=(r:Run,name:string,args:Record<string,unknown>={})=>company.computers.callTool(r.context,randomUUID(),'computer_'+name,{session_id:r.s.session_id,...args},new AbortController().signal) as Promise<any>;
const okay=async(r:Run,name:string,args:Record<string,unknown>={})=>{const result=await call(r,name,args);assert.notEqual(result.ok,false,JSON.stringify(result));return result;};
const finish=async(r:Run)=>{await company.computers.stop(r.s.session_id,'interrupted','Fault probe complete');company.finish(r.execution.execution_id,{status:'interrupted',settled:true,error:'Labelled deterministic fixture'});await idle();};
const effects=()=>{const p='/var/lib/botsquad/validation/computer-20261005-records/effects.jsonl';return existsSync(p)?readFileSync(p,'utf8').trim().split('\n').length:0;};
try{
 await idle();const ceo=company.workers().find(w=>w.role==='ceo')!;assert.throws(()=>company.computers.request({worker_id:ceo.worker_id,objective:'Forged',acceptance_criteria:'Never launch',constraints:'No authority',policy:{}}),/authority/);await idle();record('ordinary worker denied before browser creation');
 // Client connection cancellation before launch request must not admit a late browser.
 const client=new BrowserClient();const connecting=client.launch('computer_'+randomUUID(),20,async()=>null,()=>{});const rejected=assert.rejects(connecting);const closed=await client.close();await rejected;assert.equal(closed,true);await idle();record('close during connection establishment has no late browser');
 let r=start();const navigate=call(r,'navigate',{url:origin+'/a'});await delay(60);const stopped=await company.computers.control({session_id:r.s.session_id,action:'revoke'});await navigate;await idle();assert.equal(stopped.shutdown_confirmed,1);company.finish(r.execution.execution_id,{status:'interrupted',settled:true,error:'Owner interrupted provisioning'});record('revocation during actual Chromium provisioning confirms termination');
 const lost=new BrowserClient();const launch=lost.launch('computer_'+randomUUID(),20,async()=>null,()=>{}).then(()=>true,()=>false);await delay(100);await lost.close();await launch;await idle();record('IPC closure during launch retains singleton until cleanup');
 const abrupt=new BrowserClient();const interruptedLaunch=abrupt.launch('computer_'+randomUUID(),20,async()=>null,()=>{}).then(()=>true,()=>false);await delay(50);assert.ok((abrupt as any).rpc);(abrupt as any).rpc.socket.destroy();await interruptedLaunch;await idle();record('abrupt IPC socket loss during pending Chromium launch leaves no orphan');
 r=start({maxRuntimeSeconds:10,idleSeconds:300});await okay(r,'navigate',{url:origin+'/a'});await delay(10500);assert.equal(company.computers.session(r.s.session_id).state,'expired');await finish(r);record('wall-clock deadline closes real browser');
 r=start({maxScreenshots:1});await okay(r,'navigate',{url:origin+'/a'});await okay(r,'snapshot');assert.equal((await call(r,'snapshot')).ok,false);assert.equal(company.computers.session(r.s.session_id).state,'expired');await finish(r);record('screenshot count bound closes real browser');
 r=start({maxNavigations:1});await okay(r,'navigate',{url:origin+'/a'});await call(r,'navigate',{url:origin+'/b'});assert.equal(company.computers.session(r.s.session_id).state,'expired');await finish(r);record('actual document navigation count closes browser');
 const prepare=async(path:string)=>{const r=start();const view=await okay(r,'navigate',{url:origin+path});const button=view.snapshot.elements.find((e:any)=>e.name==='Save disposable setting');assert.ok(button);await okay(r,'click',{ref:button.ref});const i=store.get<ComputerIntent>('SELECT * FROM computer_intents WHERE session_id=?',r.s.session_id)!;assert.ok(i);await okay(r,'request_protected_action',{intent_id:i.intent_id,reason:'Explicit adversarial fixture'});company.finish(r.execution.execution_id,{status:'completed',summary:'Awaiting exact owner'});company.computers.decide({intent_id:i.intent_id,request_hash:i.request_hash,page_hash:i.page_hash,decision:'approve'});const next=company.claimNext()!;assert.ok(next);company.computers.prepare(next.context);return {r:{...r,...next},i};};
 let before=effects();let w=await prepare('/d-fabricated');const result=await okay(w.r,'execute_approved',{intent_id:w.i.intent_id});assert.equal(result.mutation.source,'trusted_http_receipt');assert.match(result.mutation.body,/saved/);assert.doesNotMatch(result.mutation.body,/FABRICATED/);assert.equal(effects(),before+1);await finish(w.r);record('overridden page fetch cannot fabricate the trusted mutation receipt');
 before=effects();w=await prepare('/d-stale');await delay(1800);const stale=await call(w.r,'execute_approved',{intent_id:w.i.intent_id});assert.equal(stale.ok,false);assert.equal(effects(),before);assert.equal(company.computers.intent(w.i.intent_id).state,'cancelled');await finish(w.r);record('changed page and exact POST timer cannot redeem stale approval');
 r=start();let view=await okay(r,'navigate',{url:origin+'/input-casing'});for(const name of ['Upper password','Mixed file']){const element=view.snapshot.elements.find((e:any)=>e.name===name);assert.ok(element);const denied=await call(r,name==='Upper password'?'type':'click',{ref:element.ref,...(name==='Upper password'?{text:'disposable denied text'}:{})});assert.equal(denied.ok,false);assert.match(denied.error,/credential controls/);}await finish(r);record('uppercase and mixed-case password/file controls denied');
 r=start({maxRequests:1});await call(r,'navigate',{url:origin+'/a'});await call(r,'navigate',{url:origin+'/b'}).catch(()=>{});assert.equal(company.computers.session(r.s.session_id).state,'expired');await finish(r);record('real request-attempt exhaustion closes environment');
 r=start({maxNetworkBytes:2097152});await okay(r,'navigate',{url:origin+'/a'});await call(r,'navigate',{url:origin+'/b'});assert.equal(company.computers.session(r.s.session_id).state,'expired');await finish(r);record('real aggregate-byte reservation exhaustion closes environment');
 r=start();await call(r,'navigate',{url:origin+'/oversize'});assert.ok(store.get("SELECT 1 FROM computer_network_events WHERE session_id=? AND detail LIKE '%two MiB%'",r.s.session_id));await finish(r);record('real streamed response overflow denied at two MiB');
 r=start({origins:[origin,'https://example.com']});await call(r,'navigate',{url:origin+'/redirect-control'});assert.ok(store.get("SELECT 1 FROM computer_network_events WHERE session_id=? AND detail LIKE '%Redirect origin denied%'",r.s.session_id));await finish(r);record('real credential/control redirect blocked before destination request');
 r=start();view=await okay(r,'navigate',{url:origin+'/burst'});const burst=view.snapshot.elements.find((e:any)=>e.name==='Burst bounded requests');assert.ok(burst);await okay(r,'click',{ref:burst.ref});const requests=store.all<{disposition:string;url:string}>('SELECT disposition,url FROM computer_network_events WHERE session_id=? AND url=?',r.s.session_id,origin+'/slow');assert.equal(requests.filter(x=>x.disposition==='forwarded').length,4);assert.equal(requests.filter(x=>x.disposition==='blocked').length,4);await finish(r);record('real eight-request burst forwards four and denies four concurrent requests');
 assert.equal(store.get<{integrity_check:string}>('PRAGMA integrity_check')?.integrity_check,'ok');assert.deepEqual(store.all('PRAGMA foreign_key_check'),[]);record('fault evidence integrity');
}finally{await company.computers.shutdown();store.close();}
