// Operator-only C10-1 restart assertions; process termination is external and labelled.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const root='/var/lib/botsquad/validation/computer-20261005-worker2',base='http://127.0.0.1:4314',phase=process.argv[2];
assert.equal(process.env.BOT_VALIDATION_COMPUTER,'1');assert.equal(JSON.parse(readFileSync(root+'/fixture.json','utf8')).data_root,root);
const f=JSON.parse(readFileSync(root+'/fixture.json','utf8')),a=JSON.parse(readFileSync(root+'/acceptance.json','utf8'));
const get=async p=>{const v=await fetch(base+'/api/'+p);assert.ok(v.ok);return v.json();},token=(await get('session')).csrfToken;
const post=async(p,b,expected=200)=>{const v=await fetch(base+'/api/'+p,{method:'POST',headers:{'content-type':'application/json','x-botsquad-token':token},body:JSON.stringify(b)});const s=await v.text();assert.equal(v.status,expected,s);return JSON.parse(s);};
const effects=()=>readFileSync('/var/lib/botsquad/validation/computer-20261005-records/effects.jsonl','utf8').trim().split('\n').length;
const file=root+'/restart-evidence.json';
if(phase==='prepare'){
 assert.ok(!existsSync(file));await post('pause',{paused:true});
 const pending=await get('computers/'+a.phases['pending-restart'].session_id);assert.equal(pending.session.state,'awaiting_approval');assert.ok(pending.intents.some(i=>i.state==='pending'));
 const idle=await post('computers/request',{worker_id:f.operator,objective:'Explicit ready-before-launch restart fixture',acceptance_criteria:'Retain exact authority and no browser/model launch while paused',constraints:'Do not dispatch; operator will revoke after restart',policy:{origins:['http://127.0.0.1:43991'],fixtureOrigins:['http://127.0.0.1:43991'],expiresAt:new Date(Date.now()+900000).toISOString()}},201);
 await post('computers/authorize',{session_id:idle.session_id,policy_hash:idle.policy_hash,decision:'approve'});
 writeFileSync(file,JSON.stringify({label:'Deliberate HQ main-process SIGKILL with a settled pending approval and a ready unstarted session',before:{pending,idle:await get('computers/'+idle.session_id),effects:effects(),executions:(await get('state')).executions.length}},null,2),{flag:'wx',mode:0o600});console.log('Prepared exact pending + unstarted authorized sessions; dispatch paused');
}else if(phase==='inspect'){
 const r=JSON.parse(readFileSync(file,'utf8')),pending=await get('computers/'+r.before.pending.session.session_id),idle=await get('computers/'+r.before.idle.session.session_id);assert.equal(pending.session.state,'failed');assert.equal(pending.session.shutdown_confirmed,1);assert.equal(pending.intents.find(i=>i.intent_id===r.before.pending.intents[0].intent_id).state,'cancelled');assert.deepEqual(pending.evidence,r.before.pending.evidence);assert.equal(pending.session.policy_hash,r.before.pending.session.policy_hash);assert.equal(effects(),r.before.effects);assert.equal(idle.session.state,'ready');assert.deepEqual(idle.grant,r.before.idle.grant);assert.equal(idle.session.actions,0);assert.equal(idle.session.active_execution_id,null);assert.equal((await get('state')).executions.length,r.before.executions);assert.equal((await get('state')).paused,true);
 r.after={pending,idle,effects:effects(),executions:(await get('state')).executions.length,no_replay:true};writeFileSync(file,JSON.stringify(r,null,2),{mode:0o600});await post('computers/control',{session_id:idle.session.session_id,action:'revoke'});await post('pause',{paused:false});console.log('PASS actual restart cancels pending intent with zero effect; exact unstarted policy retained without dispatch');
}else if(phase==='unknown'){
 const key=a.phases.unknown;assert.ok(key);const d=await get('computers/'+key.session_id);assert.equal(d.session.state,'unknown');assert.equal(d.session.shutdown_confirmed,1);assert.equal(d.intents.find(i=>i.intent_id===key.intent_id).state,'unknown');assert.equal(effects(),key.effects_before+1);assert.notEqual((await get('state')).tasks.find(t=>t.task_id===key.task_id).status,'completed');
 const denied=await post('computers/request',{worker_id:f.operator,objective:'Cannot bypass unknown effect',acceptance_criteria:'Trusted denial',constraints:'No dispatch',policy:{}},400);assert.match(denied.error,/uncertain/i);const before=(await get('state')).executions.length;await new Promise(r=>setTimeout(r,30000));assert.equal((await get('state')).executions.length,before);assert.equal(effects(),key.effects_before+1);writeFileSync(root+'/unknown-recovery.json',JSON.stringify({label:'Deliberate exit after real transmission/response and before local receipt commit',session:d,effects_before:key.effects_before,effects_after:effects(),new_session_denial:denied,no_replay_seconds:30,executions:before},null,2),{mode:0o600,flag:'wx'});console.log('PASS unknown effect fenced with one observed effect and zero replay for 30 seconds');
}else throw Error('Unknown phase');
