// Fresh isolated regression with actual employees; all mutations use normal owner APIs.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const root='/var/lib/botsquad/validation/mandates-p09-prompt10',base='http://127.0.0.1:4318';
assert.equal(process.env.BOT_VALIDATION_COMPUTER,'1');
const f=JSON.parse(readFileSync(root+'/fixture.json','utf8'));assert.equal(f.data_root,root);
const phase=process.argv[2],path=root+'/computer-regression.json',r=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):{phases:{},attempts:[],ids:{}};
assert.ok(!r.phases[phase]);
const save=()=>writeFileSync(path,JSON.stringify(r,null,2),{mode:0o600});
const get=async p=>{const v=await fetch(base+'/api/'+p);assert.ok(v.ok,p);return v.json();};
const token=(await get('session')).csrfToken;
const post=async(p,body)=>{const v=await fetch(base+'/api/'+p,{method:'POST',headers:{'content-type':'application/json','x-botsquad-token':token},body:JSON.stringify(body)});const text=await v.text();assert.ok(v.ok,p+': '+text);return JSON.parse(text);};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async(fn,predicate,label)=>{const end=Date.now()+900000;while(Date.now()<end){const v=await fn();if(predicate(v))return v;await delay(1000);}throw Error('Timeout '+label);};
const send=(c,body,reply=true)=>post('conversations/send',{conversation_id:c,body,request_reply:reply,receipt_key:randomUUID()});
const answer=async(c,body)=>{const q=await send(c,body);const d=await wait(()=>get('conversations/'+c),d=>d.requests.some(x=>x.request_id===q.request.request_id&&['completed','failed','blocked','interrupted'].includes(x.status))&&!d.executions.some(x=>x.status==='running'),'answer');assert.equal(d.requests.find(x=>x.request_id===q.request.request_id).status,'completed');return d;};
const direct=async(worker,purpose,body)=>{const c=await post('conversations/open',{worker_id:worker,purpose});r.ids[phase]=c.conversation_id;save();return answer(c.conversation_id,body);};
const state=await get('state');assert.ok(state.workers.every(w=>w.workspace_path.startsWith(root+'/workspaces/')));
r.attempts.push({phase,at:new Date().toISOString()});save();await post('pause',{paused:false});
try {
 if(phase==='direct'){
  await direct(f.linus,'Prompt 10 retained-mode peer regression','Compare a group recommendation with an implementation assignment. Ask Grace one bounded peer question about a concrete failure if they are confused, using ask_peer. After her reply, explain the distinction and uncertainty. No Tasks, repository changes or external actions.');
  const ds=await wait(async()=>Promise.all((await get('conversations')).items.map(c=>get('conversations/'+c.conversation_id))),ds=>ds.some(d=>d.requests.some(q=>q.kind==='continuation'&&q.status==='completed'))&&ds.every(d=>!d.requests.some(q=>['queued','replying','waiting'].includes(q.status))),'peer continuation');
  assert.ok(ds.some(d=>d.requests.some(q=>q.kind==='peer'&&q.status==='completed')));assert.equal((await get('state')).tasks.length,state.tasks.length);r.phases[phase]={conversations:ds};
 } else if(phase==='rollover'){
  const c=r.ids.direct,before=await get('conversations/'+c);await send(c,'Passive correction: diagnostic retention is 47 hours. The unresolved question is whether deletion retains an audit tombstone.',false);await delay(1500);assert.equal((await get('state')).executions.length,state.executions.length);
  await post('conversations/rollover',{conversation_id:c,worker_id:f.linus});const after=await answer(c,'After context replacement, retrieve the newest passive correction about diagnostic retention and its unresolved question. State both without inventing missing policy. No Task or code change.');assert.ok(Math.max(...after.sessions.map(s=>s.generation))>Math.max(...before.sessions.map(s=>s.generation)));const replies=after.history.items.filter(m=>m.worker_id===f.linus).map(m=>m.body).join('\n');assert.match(replies,/47/);assert.match(replies,/tombstone/i);r.phases[phase]={before,after,passive_no_execution:true};
 } else if(phase==='research'){
  const grant=await post('research/grant',{worker_id:f.scout,preset:'public_research',expires_at:null,document_paths:[],allow_discussions:false});r.ids.grant=grant.grant_id;save();
  const d=await direct(f.scout,'Prompt 10 research regression','Use research_search once to find official Playwright browser documentation, then research_open one official result. Explain one supported browser isolation fact with the source URL and uncertainty. Do not browse private systems, assign work or share this private conversation.');const p=await get('research/workers/'+f.scout);assert.ok(p.activity.some(o=>o.tool==='research_search'&&o.state==='completed'));assert.ok(p.activity.some(o=>o.tool==='research_open'&&o.state==='completed'));r.phases[phase]={conversation:d,permissions:p};
 } else if(phase==='revocation'){
  const before=await get('research/workers/'+f.scout);await post('research/revoke',{grant_id:r.ids.grant});const after=await answer(r.ids.research,'Owner negative test: attempt research_search once for official browser documentation after your grant was revoked. Report the trusted denial and stop. Do not retry or invent sources.');const permissions=await get('research/workers/'+f.scout);assert.equal(permissions.activity.length,before.activity.length);r.phases[phase]={before,after,permissions};
 } else if(phase==='group'){
  const g=await post('groups/create',{topic:'Choose a first-use experience for a hypothetical offline video-analysis app',desired_output:'A recommendation with alternatives, trade-offs, cited shared evidence and uncertainty. No implementation.',constraints:'One engineer-week; keyboard-only access; no personal video or network required. No observed user metrics. No research, Tasks or external actions.',participant_ids:[f.maya,f.grace],facilitator_id:f.maya,synthesizer_id:f.maya,organize_with_atlas:false,allow_incomplete:true,allow_research:false,receipt_key:randomUUID()});r.ids.group=g.group_id;save();
  const e=await post('groups/share',{group_id:g.group_id,kind:'owner_material',title:'Hypothetical product brief',content:'Hypothetical supplied facts: an empty workspace gives no obvious first action. A bundled synthetic example may demonstrate value; contextual help may cost less. There are no user interviews, usage metrics or accessibility results. One engineer-week is available.',source_id:null,document_path:null,receipt_key:randomUUID(),audience_confirmed:true,audience_scope_version:g.scope_version,audience_worker_ids:[f.maya,f.grace]});await post('groups/control',{group_id:g.group_id,action:'start',receipt_key:randomUUID()});
  const d=await wait(()=>get('groups/'+g.group_id),d=>['completed','blocked','stopped'].includes(d.group.state)&&!d.executions.some(e=>e.status==='running'),'group');assert.equal(d.group.state,'completed',d.group.error);assert.ok(new Set(d.executions.map(e=>e.worker_id)).size>=2);const s=d.syntheses.find(s=>s.state==='final');assert.ok(s);assert.ok(JSON.parse(s.content).evidence_ids.includes(e.evidence_id));assert.equal((await get('state')).tasks.length,state.tasks.length);r.ids.synthesis=s.synthesis_id;r.phases[phase]=d;
 } else if(phase==='assignment'){
  const t=await post('groups/assignment',{synthesis_id:r.ids.synthesis,objective:'Write a short internal report assessing the selected group recommendation and its unresolved accessibility/evidence limits. Handle it yourself as Atlas and submit_artifact. Do not delegate, hire, research, change repositories or act externally.',acceptance_criteria:'One attributed internal report grounded in selected synthesis, retaining uncertainty.',constraints:'Internal analysis only. No additional authority or private-history access.',receipt_key:randomUUID()});const after=await wait(()=>get('state'),s=>s.tasks.some(x=>x.task_id===t.task_id&&['completed','failed','blocked'].includes(x.status)),'assignment');assert.equal(after.tasks.find(x=>x.task_id===t.task_id).status,'completed');assert.equal(after.tasks.length,state.tasks.length+1);assert.ok(after.artifacts.some(a=>a.task_id===t.task_id));r.phases[phase]={task:t,artifacts:after.artifacts.filter(a=>a.task_id===t.task_id)};
 } else if(phase==='mandate'){
  const m=await post('mandates/create',{title:'Prompt 10 bounded scheduler regression',objective:'Review the supplied hypothetical onboarding concern and decide what evidence is missing. This tests two bounded internal reviews.',success_criteria:'Make an evidence-grounded strategic decision and close each cycle. No work assignment is necessary.',stop_criteria:'After the second cycle, explicitly stop.',constraints:'Hypothetical fixture only. First cycle: record a useful decision and schedule a follow-up 45–90 seconds ahead, using inspect_mandate current clock. Give the one-time schedule an end_at at least five minutes AFTER its due_at so the finite dispatch window is usable. Second cycle: review the prior decision then explicitly stop. No Tasks, groups, research, code or external actions.',resources:'At most 8 executions each cycle and two cycles.',coordinator_id:f.atlas,envelope:{internal_tasks:false,working_groups:false,public_research:false,worker_schedules:true,max_executions:8,max_tasks:1,max_groups:1,max_research_operations:1,max_pending_work:1,max_cycle_minutes:10,max_cycles:2,min_interval_seconds:30,max_horizon_days:1,max_occurrences:1,max_active_schedules:1,timezone:'America/Vancouver',evidence_modes:['owner_provided']}});r.ids.mandate=m.mandate_id;save();
  await post('mandates/observations',{mandate_id:m.mandate_id,cycle_id:null,initiative_id:null,mode:'owner_provided',name:'Hypothetical concern',value:null,unit:null,observed_at:new Date().toISOString(),period:'No measurement period',source:'fixture://prompt10/regression',provenance:'Owner-authored hypothetical test input',limitations:'No actual customer outcome',missingness:'No interviews or usage data',body:'A hypothetical offline app opens to an empty workspace. There is no measured abandonment rate. Compare a small evidence-gathering step before implementation.'});await post('mandates/control',{mandate_id:m.mandate_id,action:'activate'});
  const d=await wait(()=>get('mandates/'+m.mandate_id),d=>d.cycles.some(c=>c.number===2&&c.state==='closed')||d.cycles.some(c=>c.state==='blocked')||d.occurrences.some(o=>o.state==='cancelled'),'two cycles');assert.ok(d.cycles.some(c=>c.number===2&&c.state==='closed'),JSON.stringify(d.cycles));assert.ok(d.occurrences.some(o=>o.state==='completed'));assert.ok(d.cycles.some(c=>c.trigger==='durable_schedule'));assert.ok(d.decisions.length>=2);r.phases[phase]=d;
 } else if(phase==='idle'){
  assert.ok(!state.executions.some(e=>e.status==='running'));await delay(30000);const after=await get('state');assert.equal(after.executions.length,state.executions.length);assert.equal(after.tasks.length,state.tasks.length);r.phases[phase]={elapsed_seconds:30,executions:after.executions.length,tasks:after.tasks.length};
 } else throw Error('Unknown phase');
 save();console.log('PASS '+phase);
} catch(e){r.attempts.push({phase,error:String(e),at:new Date().toISOString()});save();throw e;}
